### PR TITLE
Fix tech docs missing #1750

### LINKED ISSUE #1750: TechDocs: Docs Not Found
Currenlty, this is what the [TechDocs Not Found](https://github.com/spotify/backstage/blob/master/plugins/techdocs/src/reader/components/TechDocsNotFound.tsx) page looks like. 
Screen Shot 2020-07-27 at 9 34 11 AM

To be consistent throughout Backstage we would like to use the [ErrorPage](https://github.com/spotify/backstage/blob/master/packages/core/src/layout/ErrorPage/ErrorPage.tsx) component
image

* Render the ErrorPage component in TechDocsNotFound
* Make the ErrorPage component customizable so that for example:
          - "Error 404: Page not found" is "Error 404: Documentation not found" 
          -  The path that the user visited is visible as something like "Path: /docs/..." 

Feel free to suggest any other improvements!

### PR DESCRIPTION
**Pull request by DavidJSykes**
## Hey, I just made a Pull Request!

Fixes #1750
TechDocs NotFound page has been updated to use the existing ErrorPage format. 
ErrorPage now has an optional parameter for docPath to display the path that the user was trying to visit if it is passed in.
TechDocsNotFound test has been changed to reflect those changes.

I initially was developing in a Windows environment and the test suite was not working correctly, however individual file tests did work fine.

Tech docs not found

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [X] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [X] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

File: packages/core/src/layout/ErrorPage/ErrorPage.tsx [hunk 1]
```diff
@@ -48,6 +53,8 @@ export const ErrorPage = ({ status, statusMessage }: IErrorPageProps) => {
       <Grid item xs={12} sm={4}>
         <Typography variant="body1" className={classes.subtitle}>
           ERROR {status}: {statusMessage}
+          <br />
```
Comment (freben) [inline packages/core/src/layout/ErrorPage/ErrorPage.tsx:56]: Typically you'd use several `<Typography paragraph>` instead, which makes sure that spacing etc is correct

File: packages/core/src/layout/ErrorPage/ErrorPage.tsx [hunk 2]
```diff
@@ -24,6 +24,7 @@ import { useNavigate } from 'react-router';
 interface IErrorPageProps {
   status: string;
   statusMessage: string;
+  docPath?: string;
```
Comment (hooloovooo) [inline packages/core/src/layout/ErrorPage/ErrorPage.tsx:27]: Maybe this should be renamed to something like `resourcePath` or `path` to not make it specific to docs if anybody else wants to use it.

Comment (DavidJSykes) [reply packages/core/src/layout/ErrorPage/ErrorPage.tsx:27]: @hooloovooo I did think about calling it something more generic since it will just take any string and work with it. I liked `additionalInfo`.

Comment (hooloovooo) [reply packages/core/src/layout/ErrorPage/ErrorPage.tsx:27]: Yea that might also be an option. Not sure if we want it to be too generic though since that could easily make it inconsistent. Anything is probably fine for now and we can change it at a later point if we feel that it's too generic. If you change it to `additionalInfo` i'll approve and merge. :)

Comment (DavidJSykes) [reply packages/core/src/layout/ErrorPage/ErrorPage.tsx]: @hooloovooo thank you for the assistance on this. Hopefully, it does the job for now!

**Review by hooloovooo — APPROVED** [review]
Thanks. Nice work! 👍

**Comment by emmaindal** [comment]
Woho @DavidJSykes Thank you so much 😄
