### PR TITLE
fix(locationAnalyzer): don't add github slug annotation when SCM system cannot be determined

### LINKED ISSUE #3541: Catalog import open PR doesn't support GitHub Enterprise yet
## Expected Behavior

When submitting the URL of a GitHub Enterprise repo to the register component screen, the pull request is opened on the GHE instance.

## Current Behavior

GitHub.com is hardcoded and so won't open PRs on GHE. User always receives HTTP 401 unauthorized.

Octokit library defaults to GitHub.com when not otherwise specified:

https://github.com/backstage/backstage/blob/257619c1ee9c49454fc32b6d7d2b07283ea8d738/plugins/catalog-import/src/api/CatalogImportClient.ts#L101-L103

Also hardcoded here:

https://github.com/backstage/backstage/blob/257619c1ee9c49454fc32b6d7d2b07283ea8d738/plugins/catalog-import/src/api/CatalogImportClient.ts#L180-L183

## Possible Solution

The OAuth provider objects don't seem to maintain the enterprise URL separately today, so I think if we query the config and get `enterpriseInstanceUrl` it could be used when instantiating the Octokit object.

Roughly this code:

https://github.com/backstage/backstage/blob/257619c1ee9c49454fc32b6d7d2b07283ea8d738/plugins/catalog-import/src/api/CatalogImportClient.ts#L90-L103

Would maybe need something along these lines though I wasn't able to get the plumbing from this component to the config working properly:

```
    const token = await this.githubAuthApi.getAccessToken(['repo']); 
    const configApi = useApi(configApiRef);
    const enterpriseInstanceUrl = configApi.getOptionalString('auth.providers.github.enterpriseInstanceUrl'); 
    const octo = new Octokit({
      auth: token,
      baseUrl: enterpriseInstanceUrl,
    });
```

The Octokit object just takes the `baseUrl` as a param.

## Steps to Reproduce

1. Register a component manually (e.g., http://localhost:3000/catalog-import )
2. Enter a GHE instance URL (even a fake one) in the form `https://ghe.mycompany.com/org/repo`, click Next
3. The review step CORRECTLY shows the target URL, though note the annotation is incorrect - it uses only the last part of the host and .com, in this example will only show "mycompany.com" when it should likely be hardcoded to github.com per the slug
    image
4. Click Next, receive HTTP 401 from GitHub.com
    image

## Your Environment

- NodeJS Version (v12): v12.16.2
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909 WSL2 Ubuntu 18.04
- Browser Information: Microsoft Edge (Chrome engine 87)

### PR DESCRIPTION
**Pull request by kuangp**
Signed-off-by: Phil Kuang <pkuang@factset.com>

## Hey, I just made a Pull Request!

This was adding incorrect annotations when used with GHE hosted under custom urls (and I think if you use GitLab also) so removing adding it unless we know we're hitting github.com. I don't believe this is a breaking change since the previous behavior was already broken. 

Closes #3541 
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts [hunk 1]
```diff
@@ -37,12 +37,16 @@ export class RepoLocationAnalyzer implements LocationAnalyzer {
...
         name: name,
-        // Probably won't handle properly self-hosted git providers with custom url
-        annotations: { [`${source}/project-slug`]: `${owner}/${name}` },
       },
       spec: { type: 'other', lifecycle: 'unknown' },
     };
 
+    if (source === 'github.com') {
+      entity.metadata.annotations = {
+        [`github.com/project-slug`]: `${owner}/${name}`,
```
Comment (OrkoHunter) [inline plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts:46]: Let's also add other public Git host providers i.e. `gitlab.com`, `bitbucket.org` here, since those will be missed by this change.

Comment (kuangp) [reply plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts:46]: @OrkoHunter I wasn't aware those were valid annotations? They're not currently mentioned in the [docs](https://backstage.io/docs/features/software-catalog/well-known-annotations). Is there plugins that use those annotations?

Looking at the `AnnotateScmSlugEntityProcessor`, it seems to also only support `github.com/project-slug`:
https://github.com/backstage/backstage/blob/cbfa75bf69da90961daae517f28a106327ceb5d0/plugins/catalog-backend/src/ingestion/processors/AnnotateScmSlugEntityProcessor.ts#L26

Comment (OrkoHunter) [reply plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts:47]: @kuangp Hmm. I noticed that the existing code was setting these annotations anyway, which will now be removed by this change.

```ts
        annotations: { [`${source}/project-slug`]: `${owner}/${name}` },
```

This `source` here can totally be `gitlab.com` and `bitbucket.org`. Hence, my suggestion would be to not disable setting these annotations here.

But I agree they might not be in use yet.

Comment (andrewthauer) [reply plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts:47]: Wouldn't it make more sense to just rely on the AnnotateScmSlugEntityProcessor entirely rather then handle GitHub specially here?

Comment (kuangp) [reply plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts:47]: `AnnotateScmSlugEntityProcessor` is an optional processor and not added by default so I kept this to preserve existing behavior. I'm fine also with removing this annotation here, the bug in #3541 was preventing us from using the catalog file PR feature since it was adding an invalid annotation for us.

Comment (kuangp) [reply plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts]: @OrkoHunter updated my change to also whitelist `gitlab.com` and `bitbucket.org` to preserve current behavior for these SCMs.

**Review by Rugvip — COMMENTED** [review]
Tbh I don't think we should skip adding the slug for the self hosted integrations, but instead figure out which slug to actually add through the integrations API.

For example, if you have GHE hosted at `github.my-company.net`, I'd expect an entity at the location `https://github.my-company.com/my-org/my-repo` to get the annotation `github.com/project-slug: 'myorg/my-repo'`. It should be possible to do that reverse lookup pretty easily using `byHost` from the integrations API, and then if that fails we could skip the annotation.

**Comment by kuangp** [comment]
Thanks @Rugvip , updated my change based on your suggestion

File: plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts [hunk 2]
```diff
@@ -24,25 +26,51 @@ import {
...
-        // Probably won't handle properly self-hosted git providers with custom url
-        annotations: { [`${source}/project-slug`]: `${owner}/${name}` },
       },
       spec: { type: 'other', lifecycle: 'unknown' },
     };
 
+    const integration = this.scmIntegrations.byUrl(request.location.target);
+
+    let annotationPrefix;
+    switch (integration?.type) {
```
Comment (andrewthauer) [inline plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts:51]: I feel like resolving integration types to annotation prefixes, could most likely be something common. Would adding this to the `integration` package make sense?

Comment (kuangp) [reply plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts]: Good idea!

**Comment by kuangp** [comment]
@andrewthauer updated based on your suggestion, thanks!

**Comment by kuangp** [comment]
@andrewthauer @Rugvip do you have any further comments? I'm hoping to have this in for this weeks release

File: packages/integration/api-report.md [hunk 3]
```diff
@@ -10,6 +10,8 @@ import { Config } from '@backstage/config';
 export class AzureIntegration implements ScmIntegration {
     constructor(integrationConfig: AzureIntegrationConfig);
     // (undocumented)
+    get annotationPrefix(): string;
+    // (undocumented)
```
Comment (adamdmharvey) [inline packages/integration/api-report.md:14]: For all these `// (undocumented)`, I'd recommend either adding TODO so our IDEs or even the `@backstage/plugin-todo` picks them up, OR just adding them to the documentation via this PR :)  But the easiest may just be doing:

```
// TODO: Azure slug is not yet documented https://backstage.io/docs/features/software-catalog/well-known-annotations
```

Just may help elevate the fact that there is tech debt there, and I'm sure one of us can pick that up!

**Review by adamdmharvey — COMMENTED** [review]
Really nice!  One nit about the TODOs but a nice, clean change.

File: packages/integration/api-report.md (hunk 3 above)
Comment (kuangp) [reply packages/integration/api-report.md:14]: what is the correct way to add this documentation? this file was auto-generated from the build. Is this created from jsdoc annotations in the code?

Comment (freben) [reply packages/integration/api-report.md:14]: Yep.

File: .changeset/gold-boats-wash.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/integration': patch
+---
+
+Expose an `annotationPrefix` property for SCM integrations
```
Comment (freben) [inline .changeset/gold-boats-wash.md:5]: I'm personally a bit unsure about this one - what the use cases will be, whether their values really will line up anyway, etc. There may be fairly little value in having it, and risk for confusion, where one slug is actually slightly different from another one etc, for example where azure might have that tricky third field etc. Thoughts @andrewthauer ?

File: plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts [hunk 5]
```diff
@@ -24,25 +26,32 @@ import {
 
 export class RepoLocationAnalyzer implements LocationAnalyzer {
   private readonly logger: Logger;
+  private readonly scmIntegrations: ScmIntegrations;
 
-  constructor(logger: Logger) {
+  constructor(logger: Logger, scmIntegrations: ScmIntegrations) {
```
Comment (freben) [inline plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts:31]: the type is `ScmIntegrationsRegistry`, should use that here and above.

File: .changeset/gold-boats-wash.md (hunk 4 above)
Comment (andrewthauer) [reply .changeset/gold-boats-wash.md:5]: > where one slug is actually slightly different from another one etc, for example where azure might have that tricky third field etc.

@freben - I'm not sure what exactly what you mean here. My thinking is these would be the well known annotation for each SCM provider (e.g. `[scm-provider]/project-slug`). Rather then having the annotation key as a constant that is possibly in a plugin, it feels more naturely they live on the ScmIntegration itself?

File: plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts (hunk 5 above)
Comment (kuangp) [reply plugins/catalog-backend/src/ingestion/LocationAnalyzer.ts]: thanks! updated

File: .changeset/gold-boats-wash.md (hunk 4 above)
Comment (kuangp) [reply .changeset/gold-boats-wash.md:5]: @freben further thoughts? or suggestions on a better direction for this change?

**Comment by kuangp** [comment]
@freben @andrewthauer any additional thoughts here?

File: .changeset/gold-boats-wash.md (hunk 4 above)
Comment (andrewthauer) [reply .changeset/gold-boats-wash.md:5]: None specific here, but if this adding the prefixes to the integration package are a possible concern, then I guess it would be safer to put them back into the `catalog-import` package for the time being? It could always be refactored later on once the possible usage becomes more clear.

Comment (kuangp) [reply .changeset/gold-boats-wash.md]: @andrewthauer @freben reverted my changes to `@backstage/integration`. Let me know if there's any another concerns I should address

**Comment by kuangp** [comment]
@freben @andrewthauer sorry for the spam but wanted to bump this PR again to try to get this into this weeks release

**Comment by freben** [comment]
Yeap it's on my queue to look at now

**Review by freben — APPROVED** [review]
Cool, let's go!
