### PR TITLE
Don't crash if the entities response doesn't include the entities name and kind

### LINKED ISSUE #6215: "Failed to load entity types" after upgrade to release-2021-06-24
After upgrading from [release-2021-06-17.1](https://github.com/backstage/backstage/releases/tag/release-2021-06-17.1) to [release-2021-06-24](https://github.com/backstage/backstage/releases/tag/release-2021-06-24) an error occurs on catalog page (`/catalog`) and the entity type picker is not shown.

## Expected Behavior

Loading catalog page should work w/o errors.

## Current Behavior

An error occurs on catalog page (`/catalog`) and the entity type picker is not shown, after import entity of type `Location`.

In the console following message is shown:
```
Cannot update a component (`AlertDisplay`) while rendering a different component (`EntityTypePicker`). To locate the bad setState() call inside `EntityTypePicker`, follow the stack trace as described in https://fb.me/setstate-in-render
    in EntityTypePicker (created by CatalogPage)
    in div (created by CatalogPage)
    in EntityListProvider (created by CatalogPage)
    in div (created by CatalogPage)
    in article (created by Content)
    in Content (created by CatalogPage)
    in div (created by Page)
    in ThemeProvider (created by Page)
    in Page (created by CatalogLayout)
    in CatalogLayout (created by CatalogPage)
    in CatalogPage (created by RoutableExtension(CatalogPage))
    in RoutableExtension(CatalogPage) (created by Extension(Component))
    in PluginErrorBoundary (created by Extension(Component))
    in Suspense (created by Extension(Component))
    in Extension(Component) (at App.tsx:80)
    in Route (at App.tsx:80)
    in FlatRoutes (at App.tsx:78)
    in div (created by SidebarPage)
    in SidebarPage (at Root.tsx:74)
    in Root (at App.tsx:107)
    in Route (created by AppRouter)
    in Routes (created by AppRouter)
    in SignInPageWrapper (created by AppRouter)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by AppRouter)
    in AppRouter (at App.tsx:106)
    in RoutingProvider (created by Provider)
    in CssBaseline (created by WithStyles(CssBaseline))
    in WithStyles(CssBaseline) (created by AppThemeProvider)
    in ThemeProvider (created by AppThemeProvider)
    in AppThemeProvider (created by Provider)
    in AppContextProvider (created by Provider)
    in ApiProvider (created by Provider)
    in Provider (at App.tsx:103)
    in App (at src/index.tsx:6)
```

## Possible Solution

-

## Steps to Reproduce

1. Upgrade standalone app from `release-2021-06-17.1` to `release-2021-06-24`
2. Import entity of type `Location`
3. Navigate to `/catalog`

## Your Environment

- NodeJS Version (v12): 14.17.0
- Operating System and Version (e.g. Ubuntu 14.04): PopOS 20.10
- Browser Information: Opera v76.0.4017.123

### PR DESCRIPTION
**Pull request by dhenneke**
Resolves #6215

A quick fix until the sort is moved into the backend.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: packages/catalog-client/src/CatalogClient.ts [hunk 1]
```diff
@@ -92,6 +92,16 @@ export class CatalogClient implements CatalogApi {
     );
 
     const refCompare = (a: Entity, b: Entity) => {
+      // in case field filtering is used, these fields might not be part of the response
```
Comment (dhenneke) [inline packages/catalog-client/src/CatalogClient.ts:95]: Might not be the most elegant fix, but it works 😄

Comment (freben) [reply packages/catalog-client/src/CatalogClient.ts:95]: Wanna check `a.kind`, `a.metadata?.namespace` and `a.metadata?.name` right?

Comment (dhenneke) [reply packages/catalog-client/src/CatalogClient.ts:95]: At least `*.kind` and `*.metadata.name`. Isn't `namespace` an optional field in the catalog? But I'm not sure if it also optional at this place. At least the `stringifyEntityRef` function is able to handle it, but then the order might still be invalid if someone chose to request only the kind and the name.

Comment (freben) [reply packages/catalog-client/src/CatalogClient.ts:95]: Yeah indeed metadata is still optional (even if there's a default policy that sets it to default)

**Review by freben — APPROVED** [review]
