### PR TITLE
Fix Microsoft Auth Provider when Profile not requested

### LINKED ISSUE #23032: 🐛 Bug Report: Regression with Microsoft Auth Provider getting non Microsoft Graph tokens
### 📜 Description

If you use the Microsoft auth provider to get an access token for a scope other than Microsoft graph (e.g. Azure Devops #22644, Kubernetes), it blows up with an error.

This issue affects the new microsoft auth backend module since at least v1.21.0.  
Somewhere between v1.22.2 and v.1.23.0-next.2, this issue also started affecting the old backend, as well as the newer backend if configuring auth through `legacyPlugin`.  (next.1 and next.0 fail to install for me, so I haven't yet narrowed down the break more specifically.

### 👍 Expected behavior

Should be able to get access tokens for Azure Devops or Kubernetes

### 👎 Actual Behavior with Screenshots

image

### 👟 Reproduction steps

1. Configure Microsoft Auth Provider
3. Go to http://localhost:7007/api/auth/microsoft/start?scope=499b84ac-1321-427f-aa17-267ca6975798%2Fvso.build%20offline_access&origin=http%3A%2F%2Flocalhost:3000&flow=popup&env=development

New Backend, with the followign in index.ts
```
backend.add(import('@backstage/plugin-auth-backend'));
backend.add(myCompanyAuthModuleMicrosoftProvider);
```
Or from v.1.23.0-next.2
```
backend.add(legacyPlugin('auth', import('./plugins/auth')));
```

### 📃 Provide the context for the Bug.

The errors seem to be rooted in https://github.com/backstage/backstage/blob/7917cbe801df7a9489ae0796b18b8449e1fd5707/plugins/auth-backend/src/lib/passport/PassportStrategyHelper.ts#L31-L39 .  This makes sense to some degree as neither the Azure Devops nor Kubernetes integrations request the `profile` scope, so it's not surprising that `profile` is undefined.

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by afscrome**
## Hey, I just made a Pull Request!

This PR ensures that the Microsoft provider passes an empty profile object down if it hasn't received/requested one from the provider.  Fixes #23032.

The legacy Microsoft provider previously did something similar to replace a null profile with an empty object. https://github.com/backstage/backstage/blob/96c4f54bf6070db12676e9af0bf75d0d479c3d72/plugins/auth-backend/src/providers/microsoft/provider.ts#L266

I guess the only question is whether we want to fix this specifically for the Microsoft provider, or should we handle a null profiles deeper in the stack (i.e. `PassportOAuthAuthenticatorHelper.defaultProfileTransform` or in `PassportHelpers.transformProfile`)

Reason this didn't affect the legacy backend is that it was only recently the legacy backend Microsoft module was swapped over to use the path from the newer backend - #22208

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by Rugvip — APPROVED** [review]
Ah alright, thank you! 👍

File: plugins/auth-backend-module-microsoft-provider/src/authenticator.ts [hunk 1]
```diff
@@ -25,8 +26,16 @@ import { union } from 'lodash';
 
 /** @public */
 export const microsoftAuthenticator = createOAuthAuthenticator({
-  defaultProfileTransform:
-    PassportOAuthAuthenticatorHelper.defaultProfileTransform,
+  defaultProfileTransform: (
+    result: OAuthAuthenticatorResult<PassportProfile>,
+    context,
+  ) => {
+    result.fullProfile = result.fullProfile ?? {};
```
Comment (Rugvip) [inline plugins/auth-backend-module-microsoft-provider/src/authenticator.ts:33]: Yep I think it could be good to move this fix here, as you mentioned: plugins/auth-node/src/oauth/PassportOAuthAuthenticatorHelper.ts

Don't really see a reason to not apply this across the board, at least making sure that it doesn't crash and just passes through empty info instead

**Comment by afscrome** [comment]
Test failures on node 20.x look unrelated to this change - timeout in a database test: https://github.com/backstage/backstage/actions/runs/7961815832/job/21733936673?pr=23077#step:8:20958

File: .changeset/eight-oranges-wave.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/plugin-auth-backend-module-microsoft-provider': patch
```
Comment (Rugvip) [inline .changeset/eight-oranges-wave.md:2]: Gotta update this one now 😅

**Review by Rugvip — CHANGES_REQUESTED** [review]

File: .changeset/eight-oranges-wave.md (hunk 2 above)
Comment (afscrome) [reply .changeset/eight-oranges-wave.md]: 🤦 - I remembered to update the changeset text, but not the package name.

**Review by Rugvip — APPROVED** [review]
:shipit: :sunglasses:
