### PR TITLE
fix(core-components): fix deps graph scrolling

### LINKED ISSUE #31296: Catalog Entity Inspector Ancestry moves on its own
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
ancestry, catalog, ghost
```

### 🗃️ Project Area

Catalog

### 🔗 External Integration

N/A

### 📝 Description & Context

The "Ancestry" graph in the "Entity Inspector" scroll on its own.

Discovered locally with Backstage 1.43.3 (with and without NFS).

Also experienced on demo.backstage.io, with Chrome and Firefox.

https://github.com/user-attachments/assets/28220078-12fb-436c-8e93-66ceecb54589

### 👍 Expected Behavior

The UI elements should not try to escape from the user.

### 📦 Reproduction Repo

_No response_

### 🥾 Reproduction steps

1. Go to https://demo.backstage.io/catalog/default/component/backstage?inspect=ancestry
2. Watch the graph scroll on its own

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

fixes dependency graph scrolling down forever. also fixes the full screen mode to take all the space in the screen.

closes #31296

[petstore-Overview-Backstage-Example-App.webm](https://github.com/user-attachments/assets/d2415545-cb18-470e-b3df-d2f1c1a5bd8e)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by GabDug** [comment]
Thanks for the quick fix @drodil! I confirm that it seems to do the trick for https://github.com/backstage/backstage/issues/31296, which was a funny issue tbh!

File: packages/core-components/src/components/DependencyGraph/DependencyGraph.tsx [hunk 1]
```diff
@@ -282,7 +282,10 @@ export function DependencyGraph<NodeData, EdgeData>(
   const [_measureRef] = useMeasure();
   const measureRef = once(_measureRef);
 
-  const scalableHeight = fit === 'grow' ? maxHeight : containerHeight;
+  const scalableHeight = useMemo(
+    () => (fit === 'grow' && !fullScreenHandle.active ? maxHeight : '100%'),
+    [fit, maxHeight, fullScreenHandle],
+  );
```
Comment (vinzscam) [inline packages/core-components/src/components/DependencyGraph/DependencyGraph.tsx]:
```suggestion
  const scalableHeight = fit === 'grow' && !fullScreenHandle.active ? maxHeight : '100%';
```

**Comment by drodil** [comment]
@vinzscam any chance to get this for the `-next` release?
