### PR TITLE
catalog-backend: fix azure ingestion default branch browser url

### LINKED ISSUE #2254: Unable to ingest from Azure git repos
I tried ingesting a template from a private Azure git repo but got an error. After some investigation it seems that the generated URL doesn't correspond with what is in the Azure docs.

## Expected Behavior
As per [this](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/items/get?view=azure-devops-rest-6.0) documentation the URL should be in the following format:

`GET https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/items?path={path}&api-version=6.0`

## Current Behavior
The currently generated URL looks like the following:

`GET https://dev.azure.com/{organization}/{project}/_apis/sourceProviders/TfsGit/filecontents?repository={repositoryId}&commitOrBranch=undefined&path={path}&api-version=6.0-preview.1`

I have not tried with a Team Foundation Version Control (TFVC) repo so I'm not sure if that works and what would happen if the URL is changed.

## Possible Solution
Change AzureApiReaderProcessor.ts to the documented URL.

## Steps to Reproduce

1. Go to register an existing component
2. Supply a URL for a private Azure repo

## Your Environment

- NodeJS Version (v12): v12.18.3
- Operating System and Version (e.g. Ubuntu 14.04): VS Code Node.js devcontainer
- Browser Information: Chrome 85.0.4183.83

### PR DESCRIPTION
**Pull request by o-farooq**
## Hey, I just made a Pull Request!

fix azure ingestion default branch browser url

the default branch browser url does not contain branch name and is throwing error due to undefined branch being passed to API
e.g. `https://dev.azure.com/{organization}/{project}/_git/{reponame}?path={path}`

the full url with branch name works fine 
e.g. `https://dev.azure.com/{organization}/{project}/_git/reponame?path={path}&version=GBmaster`

changed from source provider api to git api as source provider api does not support optional branch name
git api returns the default branch contents when no branch name is specified

this fixes #2254 

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [x] Prettier run on changed files
- [x] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

**Comment by freben** [comment]
Cool! Am I right in understanding that this works for both git and tfs repos?

**Review by freben — APPROVED** [review]

File: plugins/catalog-backend/src/ingestion/processors/AzureApiReaderProcessor.ts [hunk 1]
```diff
@@ -119,17 +119,19 @@ export class AzureApiReaderProcessor implements LocationProcessor {
...
+        'items',
       ].join('/');
 
-      url.search = [
-        `repository=${repoName}`,
-        `commitOrBranch=${ref}`,
-        `path=${path}`,
-        'api-version=6.0-preview.1',
-      ].join('&');
+      const queryParams = [`path=${path}`];
```
Comment (freben) [inline plugins/catalog-backend/src/ingestion/processors/AzureApiReaderProcessor.ts:128]: Oh hey I just want to check. Since this is using raw string manipulation, does it handle url encoded characters correctly? Like if the path contains a file with spaces or similar.

**Comment by freben** [comment]
Merging - we can always tweak more later
