### PR TITLE
scaffolder-backend: remove support for deprecated publisher configuration

### LINKED ISSUE #4591: bug(scaffolder-backend): Incorrect deprecation warnings
## Expected Behavior

Deprecation warnings indicating a token has been defined against a scaffolder configuration, which are no longer needed, are valid and identifying a configuration which should be changed.

## Current Behavior

On a newly created template app, with only one integration for GitHub, a scaffold section, and no token defined for the scaffolder, you are warned about deprecated configs in Azure, GitHub, and GitLab.

image

## Possible Solution

Seems to be some sort of bug being exposed here, though it could be much further upstream:

https://github.com/backstage/backstage/blob/cf9a229a3e72db24e848f3e000c8a2850224e344/plugins/scaffolder-backend/src/scaffolder/stages/publish/publishers.ts#L66-L71

Even with no Azure settings at all, the array returns kick starting the for loop, and if the publisher is not valid, the deprecation warning is spit out.

## Steps to Reproduce

1. Scaffold a brand new app: `npx @backstage/create-app`
2. Review `app-config.yaml` and ensure no scaffolder tokens are defined
3. When you startup the Backend, you get three deprecation warnings, even for scaffolder or integration configs you have not defined:
  ```
  2021-02-19T04:03:47.637Z scaffolder warn 'Specifying credentials for Azure in the Scaffolder configuration is deprecated. This will cause errors in a future release. Please migrate to using integrations config and specifying tokens under hostnames' type=plugin
  2021-02-19T04:03:47.637Z scaffolder warn 'Specifying credentials for GitHub in the Scaffolder configuration is deprecated. This will cause errors in a future release. Please migrate to using integrations config and specifying tokens under hostnames' type=plugin
  2021-02-19T04:03:47.638Z scaffolder warn 'Specifying credentials for Gitlab in the Scaffolder configuration is deprecated. This will cause errors in a future release. Please migrate to using integrations config and specifying tokens under hostnames' type=plugin
  ```

## Your Environment

- NodeJS Version (v12): v12.16.2 
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909 WSL2 Ubuntu 18.04
- Browser Information: Microsoft Edge

### PR DESCRIPTION
**Pull request by Rugvip**
## Hey, I just made a Pull Request!

Fixes #4591 by getting rid of the deprecated path :grin:

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4724-xjqfxgcxf0t3jcb9dbq7wylzmjqmjg0c.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/603a55c665f81793cffc92ad

File: plugins/scaffolder-backend/src/scaffolder/stages/publish/publishers.ts [hunk 1]
```diff
@@ -51,32 +51,16 @@ export class Publishers implements PublisherBuilder {
...
 
-    const deprecationWarning = (name: string) => {
-      logger.warn(
-        `'Specifying credentials for ${name} in the Scaffolder configuration is deprecated. This will cause errors in a future release. Please migrate to using integrations config and specifying tokens under hostnames'`,
-      );
-    };
-
     for (const integration of scm.azure.list()) {
       const publisher = await AzurePublisher.fromConfig(integration.config);
       if (publisher) {
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/publish/publishers.ts:62]: Hm i was hoping that we would be able to remove the undefined return value as well

**Review by freben — APPROVED** [review]

File: plugins/scaffolder-backend/src/scaffolder/stages/publish/publishers.ts (hunk 1 above)
Comment (Rugvip) [reply plugins/scaffolder-backend/src/scaffolder/stages/publish/publishers.ts:62]: I'll let you take a stab at structuring that :grin:
