### PR TITLE
Fix ResponseError HTTP status

### LINKED ISSUE #22528: 🐛 Bug Report:  api/catalog/entities/by-name throws 500 error for 401 authentication error
### 📜 Description

catalog by-name api is returning error
```
Request failed with status 500 Request failed with 401 AuthenticationError
``` 

### 👍 Expected behavior

It should return 401 instead of 500

### 👎 Actual Behavior with Screenshots

Should this ResponseError allow passing error status like 401?
https://github.com/backstage/backstage/blob/9a8d556661dc97a00db1cf37f0190b5b83f059bb/packages/errors/src/errors/ResponseError.ts#L73
```
ResponseError: Request failed with 401 AuthenticationError
    at ResponseError.fromResponse (/usr/src/app/node_modules/@backstage/errors/dist/index.cjs.js:238:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PermissionClient.makeRequest (/usr/src/app/node_modules/@backstage/plugin-permission-common/dist/index.cjs.js:180:13)
    at async AuthorizedEntitiesCatalog.entities (/usr/src/app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-9cfeea71.cjs.js:5815:32)
    at async /usr/src/app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-9cfeea71.cjs.js:5255:28
```

### 👟 Reproduction steps

not sure how to reproduce

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

OS:   Darwin 23.3.0 - darwin/x64
node: v18.18.2
yarn: 1.22.18
cli:  0.23.1 (installed)
backstage:  1.19.6

Dependencies:
  @backstage/app-defaults                                          1.4.4
  @backstage/backend-app-api                                       0.5.7, 0.5.10
  @backstage/backend-common                                        0.19.8, 0.15.2, 0.20.1
  @backstage/backend-dev-utils                                     0.1.2, 0.1.3
  @backstage/backend-openapi-utils                                 0.0.5
  @backstage/backend-plugin-api                                    0.6.6, 0.6.9
  @backstage/backend-tasks                                         0.5.11, 0.5.14
  @backstage/catalog-client                                        1.4.5, 1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.1.5, 0.2.2
  @backstage/cli                                                   0.18.1, 0.23.1
  @backstage/config-loader                                         1.5.2, 1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.0
  @backstage/core-components                                       0.11.2, 0.13.7
  @backstage/core-plugin-api                                       1.7.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-app-api                                      0.2.0
  @backstage/frontend-plugin-api                                   0.2.0
  @backstage/integration-aws-node                                  0.1.7, 0.1.8
  @backstage/integration-react                                     1.1.20
  @backstage/integration                                           1.7.1, 1.8.0
  @backstage/plugin-api-docs                                       0.9.12
  @backstage/plugin-app-backend                                    0.3.54
  @backstage/plugin-app-node                                       0.1.6
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.3
  @backstage/plugin-auth-backend-module-google-provider            0.1.3
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.3
  @backstage/plugin-auth-backend                                   0.19.4
  @backstage/plugin-auth-node                                      0.4.0, 0.4.3
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.3
  @backstage/plugin-catalog-backend-module-ldap                    0.5.21
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.3
  @backstage/plugin-catalog-backend                                1.14.0
  @backstage/plugin-catalog-common                                 1.0.17, 1.0.20
  @backstage/plugin-catalog-graph                                  0.2.37
  @backstage/plugin-catalog-import                                 0.10.1
  @backstage/plugin-catalog-node                                   1.4.7, 1.6.1
  @backstage/plugin-catalog-react                                  1.8.5
  @backstage/plugin-catalog                                        1.14.0
  @backstage/plugin-events-node                                    0.2.15
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-explore-react                                  0.0.32
  @backstage/plugin-explore                                        0.4.11
  @backstage/plugin-graphiql                                       0.2.55
  @backstage/plugin-home-react                                     0.1.4
  @backstage/plugin-home                                           0.5.9
  @backstage/plugin-kubernetes-backend                             0.13.0
  @backstage/plugin-kubernetes-common                              0.7.0
  @backstage/plugin-kubernetes-node                                0.1.0
  @backstage/plugin-kubernetes-react                               0.1.0
  @backstage/plugin-kubernetes                                     0.11.0
  @backstage/plugin-org                                            0.6.15
  @backstage/plugin-pagerduty                                      0.6.6
  @backstage/plugin-permission-backend                             0.5.29
  @backstage/plugin-permission-common                              0.7.12, 0.7.9
  @backstage/plugin-permission-node                                0.7.17, 0.7.20
  @backstage/plugin-permission-react                               0.4.16
  @backstage/plugin-proxy-backend                                  0.4.4
  @backstage/plugin-scaffolder-backend                             1.18.1
  @backstage/plugin-scaffolder-common                              1.4.2
  @backstage/plugin-scaffolder-node                                0.2.7
  @backstage/plugin-scaffolder-react                               1.5.6
  @backstage/plugin-scaffolder                                     1.15.1
  @backstage/plugin-search-backend-module-catalog                  0.1.10
  @backstage/plugin-search-backend-module-pg                       0.5.15
  @backstage/plugin-search-backend-module-techdocs                 0.1.10
  @backstage/plugin-search-backend-node                            1.2.10
  @backstage/plugin-search-backend                                 1.4.6
  @backstage/plugin-search-common                                  1.2.10, 1.2.7
  @backstage/plugin-search-react                                   1.7.1
  @backstage/plugin-search                                         1.4.1
  @backstage/plugin-shortcuts                                      0.3.15
  @backstage/plugin-tech-radar                                     0.6.9
  @backstage/plugin-techdocs-backend                               1.8.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.1
  @backstage/plugin-techdocs-node                                  1.7.6, 1.9.0
  @backstage/plugin-techdocs-react                                 1.1.12
  @backstage/plugin-techdocs                                       1.8.0
  @backstage/plugin-user-settings                                  0.7.11
  @backstage/release-manifests                                     0.0.10, 0.0.5
  @backstage/test-utils                                            1.4.4
  @backstage/theme                                                 0.2.19, 0.3.0, 0.4.3
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.6
✨  Done in 1.91s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by vinzscam**
## Hey, I just made a Pull Request!

This PR fixes an issue that was causing  `ResponseError` not to report the HTTP status from the provided response.
The `statusCode` property in now set in `ResponseError` which makes `errorHandler` to report the correct HTTP status to the clients.
Without this fix, throwing a `ResponseError` will always return `500` as HTTP status.

Closes #22528

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by sennyeya — APPROVED** [review]

File: packages/errors/src/errors/ResponseError.ts [hunk 1]
```diff
@@ -65,29 +68,36 @@ export class ResponseError extends Error {
   ): Promise<ResponseError> {
     const data = await parseErrorResponseBody(response);
 
-    const status = data.response.statusCode || response.status;
-    const statusText = data.error.name || response.statusText;
```
Comment (freben) [inline packages/errors/src/errors/ResponseError.ts:69]: Curious about this one. It used to be that we wanted to actually propagate custom error names from the backend to the frontend. I could understand if we for example treated `'Error'` like undefined, but entirely removing this feature - is that the right move?

**Review by freben — APPROVED** [review]
