### PR TITLE
fix: 🐛 implemented a circular dependency check in the ServiceRegistry

### LINKED ISSUE #19264: 🐛 Bug Report: service factory circular dependencies silently fail
### 📜 Description

When creating a custom `rootConfig` service factory that depended on `rootLogger` the application would build successfully but the backend service would never start up and just silently hangs.

This is likely happening due to a circular dependency in service factories: `rootConfig -> rootLogger -> rootConfig`

### 👍 Expected behavior

Some kind of circular dependency warning similar to how angular webpack shows them:
image

Also would it ideally make sense for the `rootLogger` to have no direct dependencies as to me seems like an essential dependency that can be used by any dependency?

### 👎 Actual Behavior with Screenshots

Custom `rootConfig` service factory that depends on `rootLogger`:
image

`rootLogger` service factory that depends on `rootConfig`:
image

Console logs when running the backend. It builds successfully but the runtime doesn't seem to startup (it's hanging silently on something):
image

### 👟 Reproduction steps

Create a custom `rootConfig` service factory that depends on `rootLogger` to create a circular dependency in service factories: `rootConfig -> rootLogger -> rootConfig`

### 📃 Provide the context for the Bug.

I noticed that the `rootConfigServiceFactory` used `console.log` instead of the `LoggerService`. So for my custom config service factory I tried using the `rootLogger`.

image

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by marleypowell**
fix: :bug: implemented a circular dependency check in the `ServiceRegistry`

fixes #19264

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: packages/backend-app-api/src/wiring/ServiceRegistry.ts [hunk 1]
```diff
@@ -146,6 +146,43 @@ export class ServiceRegistry implements EnumerableServiceHolder {
...
+      head.service,
+    ];
+
+    let node = nodes.shift();
+
+    if (node) {
+      depChain.push(node);
+    }
+
+    while (!!node && node.id !== head.service.id) {
```
Comment (Rugvip) [inline packages/backend-app-api/src/wiring/ServiceRegistry.ts:164]: You'll want to keep track of visited nodes, or you might end up with an infinite loop in the case where the starting node is not part of the cycle, for example `A -> B -> C -> B`.

File: packages/backend-app-api/src/wiring/ServiceRegistry.ts [hunk 2]
```diff
@@ -146,6 +146,43 @@ export class ServiceRegistry implements EnumerableServiceHolder {
...
+      const nodeFactory = this.#providedFactories.get(node.id);
+      const nodeDeps = nodeFactory?.deps;
+      if (nodeDeps) {
+        nodes.unshift(...Object.values(nodeDeps));
+      }
+      node = nodes.shift();
+      if (node) {
+        depChain.push(node);
```
Comment (Rugvip) [inline packages/backend-app-api/src/wiring/ServiceRegistry.ts:172]: Always pushing a node here seems like it would result in incorrect chains in many cases. For example `A -> B,C` and `C -> A`. I think that'd tell you that the chain is `A -> B -> C -> A` right?

**Review by Rugvip — CHANGES_REQUESTED** [review]
Thank you for taking a look at this! 👍 

I actually ended up implementing a similar check for modules over in https://github.com/backstage/backstage/pull/19337/files#diff-b5085d072500931193f6d660a80ad32abac0056a02a7865c157dd87030a81f36, what do you think about integrating that once it's merged instead?

File: packages/backend-app-api/src/wiring/ServiceRegistry.ts (hunk 1 above)
Comment (marleypowell) [reply packages/backend-app-api/src/wiring/ServiceRegistry.ts]: Added a unit test to cover this scenario

File: packages/backend-app-api/src/wiring/ServiceRegistry.ts (hunk 2 above)
Comment (marleypowell) [reply packages/backend-app-api/src/wiring/ServiceRegistry.ts]: Added a unit test to cover this scenario

**Comment by marleypowell** [comment]
> Thank you for taking a look at this! 👍
> 
> I actually ended up implementing a similar check for modules over in https://github.com/backstage/backstage/pull/19337/files#diff-b5085d072500931193f6d660a80ad32abac0056a02a7865c157dd87030a81f36, what do you think about integrating that once it's merged instead?

As suggested I've updated `ServiceRegistry` to use `DependencyGraph` for circular dependency checks. Also as discussed I've fixed a small issue in `DependencyGraph` where the returned circular chain was in reverse order.

File: packages/backend-app-api/src/wiring/types.ts [hunk 3]
```diff
@@ -39,6 +39,7 @@ export interface CreateSpecializedBackendOptions {
 
 export interface ServiceHolder {
   get<T>(api: ServiceRef<T>, pluginId: string): Promise<T> | undefined;
+  checkForCircularDeps(): void;
```
Comment (Rugvip) [inline packages/backend-app-api/src/wiring/types.ts:42]: Hmm, this doesn't quite make sense to add to any of these interfaces. Given that, I'm feeling it makes the most sense to keep `checkForCircularDeps` private and instead add a static `ServiceRegistry.create()` factory that instantiates the registry and checks for circular deps, removing the call from `BackendInitialized.start`

File: .changeset/tricky-melons-fold.md [hunk 4]
```diff
@@ -0,0 +1,6 @@
+---
+'@backstage/backend-app-api': patch
+---
+
+fix: :bug: implemented up front circular dependency check in the `BackendInitializer`
+fix: :bug: updated `detectCircularDependency` in `DependencyGraph` to return circular dependencies starting from the first node
```
Comment (Rugvip) [inline .changeset/tricky-melons-fold.md:6]: GitHub emoji shorthands might not show up everywhere the changelogs are rendered, so these would need to be emoji characters instead. Tbh I think it's best to skip here though, changelogs are very serious business 😁

**Review by Rugvip — CHANGES_REQUESTED** [review]
Sweet! 😁 

Just a few nits, and thank you for building out the test suite!

File: .changeset/tricky-melons-fold.md (hunk 4 above)
Comment (marleypowell) [reply .changeset/tricky-melons-fold.md:6]: Removed emoji references.

File: packages/backend-app-api/src/wiring/types.ts (hunk 3 above)
Comment (marleypowell) [reply packages/backend-app-api/src/wiring/types.ts:42]: Updated to have a static create method and private constructor. I've made the changeset a minor bump (IIRC that's fine for breaking changes pre v1.0.0)

**Review by Rugvip — CHANGES_REQUESTED** [review]
Thank you! 👍 

Just a changeset nit

File: .changeset/tricky-melons-fold.md [hunk 5]
```diff
@@ -0,0 +1,7 @@
+---
+'@backstage/backend-app-api': minor
+---
+
+refactor!: updated `ServiceRegistry` to have a static create method and private constructor.
+fix: updated `ServiceRegistry` to perform circular dependency check on creation.
+fix: updated `detectCircularDependency` in `DependencyGraph` to return circular dependencies starting from the first node
```
[the remark this answers is not in the document]
Comment (marleypowell) [reply .changeset/tricky-melons-fold.md]: thanks, applied suggestion.

**Review by Rugvip — APPROVED** [review]
