### PR TITLE
Allowed owners fix repourl picker

### LINKED ISSUE #13730: [Scaffolder] RepoUrlPicker allowedOwners selection changes automatically
## Expected Behavior

When multiple allowedOwners are in the template, the user selects the desired owner and the selection remains while filling out the rest of the template form.

## Actual Behavior

When multiple allowedOwners exist, the user has to select the desired owner twice to get the selection to "stick", and also the selection switches back to the first option when the "Repository" field is updated.

## Steps to Reproduce

1. Use a template with RepoUrlPicker containing multiple allowedOwners
    ```
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - some-github-owner-A
              - some-github-owner-B
              - some-github-owner-C
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
    ```
2. Select an owner (B) other than the first (A), it should remain on the first (A)
3. Select owner (B) again, it should now remain selected (B)
4. Start typing in the Repository field, the owner should switch back to the first (A)

## Context

We're trying to limit the owners available to the user by presenting a list of GitHub organizations to choose from.

This results in difficulty for the user to select their owner, they have to select the owner multiple times to get it to "stick" when filling out the template forms, or they don't see the owner switch on them and end up creating the repository in the wrong organization.

## Your Environment

This behaviour happens in Safari and Firefox, though I mainly work in Safari.

- Browser Information: Safari Version 15.6.1 (17613.3.9.1.16)

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.6.0 - darwin/arm64
node: v18.7.0
yarn: 3.2.1
cli:  0.18.1 (installed)
backstage:  1.4.0

Dependencies:
  @backstage/app-defaults                          1.0.5
  @backstage/backend-common                        0.14.1, 0.15.0
  @backstage/backend-plugin-api                    0.1.1
  @backstage/backend-tasks                         0.3.4
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.1
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.5
  @backstage/core-components                       0.10.0, 0.11.0
  @backstage/core-plugin-api                       1.0.5
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.3
  @backstage/integration                           1.3.0
  @backstage/plugin-api-docs                       0.8.8
  @backstage/plugin-auth-backend                   0.15.1
  @backstage/plugin-auth-node                      0.2.4
  @backstage/plugin-catalog-backend-module-github  0.1.6
  @backstage/plugin-catalog-backend                1.3.1
  @backstage/plugin-catalog-common                 1.0.5
  @backstage/plugin-catalog-graph                  0.2.20
  @backstage/plugin-catalog-import                 0.8.11
  @backstage/plugin-catalog-node                   1.0.1
  @backstage/plugin-catalog-react                  1.1.3
  @backstage/plugin-catalog                        1.5.0
  @backstage/plugin-github-actions                 0.5.8
  @backstage/plugin-github-pull-requests-board     0.1.2
  @backstage/plugin-home                           0.4.24
  @backstage/plugin-org                            0.5.8
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.4
  @backstage/plugin-permission-react               0.4.4
  @backstage/plugin-proxy-backend                  0.2.29
  @backstage/plugin-scaffolder-backend             1.5.1
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.5.0
  @backstage/plugin-search-backend-module-pg       0.3.6
  @backstage/plugin-search-backend-node            1.0.1
  @backstage/plugin-search-backend                 1.0.1
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.1
  @backstage/plugin-search                         1.0.1
  @backstage/plugin-sonarqube                      0.3.7
  @backstage/plugin-stack-overflow                 0.1.4
  @backstage/plugin-tech-radar                     0.5.15
  @backstage/plugin-techdocs-backend               1.2.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.3
  @backstage/plugin-techdocs-node                  1.3.0
  @backstage/plugin-techdocs-react                 1.0.3
  @backstage/plugin-techdocs                       1.3.1
  @backstage/plugin-user-settings                  0.4.7
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
```

### PR DESCRIPTION
**Pull request by Parsifal-M**
## Hey, I just made a Pull Request!

This should fix #13730, the allowedOwners does not "stick" or reset when you make a selection or type in the box below it.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Parsifal-M** [comment]
Hmmm I can see some failures in the CI so I will check on these, although all my changes seem to work fine locally on a `yarn dev` I will come back to this.

**Comment by freben** [comment]
You can put technical identifiers and similar in backticks ``` `allowedOwners` ``` to get the spell checker to ignore it

File: plugins/scaffolder/src/components/fields/RepoUrlPicker/RepoUrlPicker.tsx [hunk 1]
```diff
@@ -160,9 +160,9 @@ export const RepoUrlPicker = (
       {hostType === 'github' && (
         <GithubRepoPicker
           allowedOwners={allowedOwners}
+          onChange={prevState => ({ ...prevState, allowedOwners })}
           rawErrors={rawErrors}
           state={state}
-          onChange={updateLocalState}
```
Comment (benjdlambert) [inline plugins/scaffolder/src/components/fields/RepoUrlPicker/RepoUrlPicker.tsx:165]: I wonder if there's something inside this handler that's causing the issue, because I thought under the hood it basically does something like `onChange={prevState => ({ ...prevState, allowedOwners })}`

Comment (Parsifal-M) [reply plugins/scaffolder/src/components/fields/RepoUrlPicker/RepoUrlPicker.tsx:165]: Hey, yeah thats what I am looking at indeed now, my initial approach I realize now was not the best. :sweat_smile:

Comment (Parsifal-M) [reply plugins/scaffolder/src/components/fields/RepoUrlPicker/RepoUrlPicker.tsx:165]: Hey @benjdlambert this seems to work:

```  
const updateLocalState = useCallback(
    (owner: RepoUrlPickerState) => {
      setState(prevState => ({ ...prevState, ...owner }));
    },
    [setState],
  );
```

But then the tests fail with this which I am not 100% sure why:

```
  ● RepoUrlPicker › happy path rendering › should render the repo url picker with minimal props

    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    Expected: ObjectContaining {"formData": "github.com?owner=backstage&repo=repo123"}, Anything

    Number of calls: 0

      81 |       fireEvent.click(submitButton);
      82 |
    > 83 |       expect(onSubmit).toHaveBeenCalledWith(
         |                        ^
      84 |         expect.objectContaining({
      85 |           formData: 'github.com?owner=backstage&repo=repo123',
      86 |         }),

      at Object.toHaveBeenCalledWith (components/fields/RepoUrlPicker/RepoUrlPicker.test.tsx:83:24)

  ● RepoUrlPicker › requestUserCredentials › should call the scmAuthApi with the correct params

    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    Expected: {"additionalScope": {"customScopes": {"github": ["workflow"]}, "repoWrite": true}, "url": "https://github.com/backstage/repo123"}

    Number of calls: 0

      160 |       });
      161 |
    > 162 |       expect(mockScmAuthApi.getCredentials).toHaveBeenCalledWith({
          |                                             ^
      163 |         url: 'https://github.com/backstage/repo123',
      164 |         additionalScope: {
      165 |           repoWrite: true,
```

Would you have any idea why? Not sure if after making the change the tests should just work or need to change the test themselves. But in `yarn dev` this change seems to work.

Comment (Parsifal-M) [reply plugins/scaffolder/src/components/fields/RepoUrlPicker/RepoUrlPicker.tsx:165]: Found the issue, a strange one indeed.

Doing this change basically disables the `Owner` input on the second step of creating one of the example templates it won't accept any input :thinking: 

Will continue to debug this.

**Comment by Parsifal-M** [comment]
Hey @benjdlambert, @freben! 👋


What do you think of the approach I took? I think this is a much cleaner way to handle it. 

Let me know what you think! 

Thank you,

**Comment by benjdlambert** [comment]
@Parsifal-M do we still not need to set the default owner as the one that's first in the list to get it to set the default value?

**Comment by Parsifal-M** [comment]
> @Parsifal-M do we still not need to set the default owner as the one that's first in the list to get it to set the default value?

Hey! :wave: 

So I have played around with this and my results are as follows:

```
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - some-github-owner-First
              - some-github-owner-Second
              - some-github-owner-Third
 ```

And in the UI I see:

image

I have noticed another bug actually in relation to this for `Bitbucket` namely here below, the issue is exactly the same and I think for the same reason essentially with the `useEffect` hook.

```
  useEffect(() => {
    if (host === 'bitbucket.org' && allowedOwners.length) {
      onChange({ workspace: allowedOwners[0] });
    }
  }, [allowedOwners, host, onChange]);
```
In this file -> https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/RepoUrlPicker/BitbucketRepoPicker.tsx#L36

I don't think we need this because its inherited from the `RepoUrlPicker.tsx`

Apologies for going slightly off topic, hope this more or less answers your question, if not let me know :smile:

**Comment by benjdlambert** [comment]
Hmm so I actually think that this is the wrong fix here. What's actually happening is that we're not setting an owner value at all, and I wonder if we're overriding the set value.

Can you try and change the `useEffect` to this:


```ts
  useEffect(() => {
    if (allowedOwners.length > 0 && !state.owner) {
      setState(prevState => ({
        ...prevState,
        owner: allowedOwners[0],
      }));
    }
  }, [setState, allowedOwners, state.owner]);
  ```

 And see if this works for you? If it does it's likely we will need to change them for the rest of the state members too.

**Comment by Parsifal-M** [comment]
> Hmm so I actually think that this is the wrong fix here. What's actually happening is that we're not setting an owner value at all, and I wonder if we're overriding the set value.
> 
> Can you try and change the `useEffect` to this:
> 
> ```ts
>   useEffect(() => {
>     if (allowedOwners.length > 0 && !state.owner) {
>       setState(prevState => ({
>         ...prevState,
>         owner: allowedOwners[0],
>       }));
>     }
>   }, [setState, allowedOwners, state.owner]);
> ```
> 
> And see if this works for you? If it does it's likely we will need to change them for the rest of the state members too.

Hey @benjdlambert will try this and do some testing and report back, from an initial quick test it looks good!

**Comment by Parsifal-M** [comment]
Hey @benjdlambert :wave:

From a `yarn test` and some manual testing in the UI it all looks good, however the issue I run into now is that we get this message when trying to make a commit:

```
  103:6  error  React Hook useEffect has a missing dependency: 'state.organization'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
  112:6  error  React Hook useEffect has a missing dependency: 'state.owner'. Either include it or remove the dependency array         react-hooks/exhaustive-deps
  118:6  error  React Hook useEffect has a missing dependency: 'state.repoName'. Either include it or remove the dependency array      react-hooks/exhaustive-deps
```

Which is odd, because they are added to the deps as you advised above, I'll have to do a bit of research on this and will come back.

**Comment by benjdlambert** [comment]
Hmm can you commit and push what you've done so far so we can see the build logs here and I can try to advise what's going on

**Comment by Parsifal-M** [comment]
Hey @benjdlambert,

Done, I had to add the below so I could commit and push but its there:

```
// eslint-disable-next-line react-hooks/exhaustive-deps
```
in order to make the commit and push it :sweat_smile:

**Comment by benjdlambert** [comment]
Hmm ok, I think this could actually be a bug in the `eslint` rule. 

Can you try doing this:

```ts

const { owner, repoName, organizations } = state;

```

and then replace all calls to `state.owner` etc with the destructured var instead.

You should be able to remove the comment excluding the rule then 🤞

**Comment by Parsifal-M** [comment]
> Hmm ok, I think this could actually be a bug in the `eslint` rule.
> 
> Can you try doing this:
> 
> ```ts
> const { owner, repoName, organizations } = state;
> ```
> 
> and then replace all calls to `state.owner` etc with the destructured var instead.
> 
> You should be able to remove the comment excluding the rule then crossed_fingers

Hey @benjdlambert,

The good news is that error no longer appears but the bad news is it causes issues further down:

```
  140:20  error  'owner' is already declared in the upper scope on line 91 column 11     @typescript-eslint/no-shadow
  140:27  error  'repoName' is already declared in the upper scope on line 91 column 18  @typescript-eslint/no-shadow
  219:19  error  'repoName' is already declared in the upper scope on line 91 column 18  @typescript-eslint/no-shadow
```

Which is caused by the `useDebounce` found here: https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/RepoUrlPicker/RepoUrlPicker.tsx#L138 

My not-so-educated guess on this is that you could rename those:

```
      const [hosts, owners, repoNames] = [
        state.host,
        state.owner,
        state.repoName,
      ].map(encodeURIComponent);

      // user has requested that we use the users credentials
      // so lets grab them using the scmAuthApi and pass through
      // any additional scopes from the ui:options
      const { token } = await scmAuthApi.getCredentials({
        url: `https://${hosts}/${owners}/${repoNames}`,
        additionalScope: {
          repoWrite: true,
          customScopes: requestUserCredentials.additionalScopes,
        },
      });
```

But I'm not sure that's a great idea... :thinking:

**Comment by Parsifal-M** [comment]
Maybe this :thinking: 

```
      const [hostUri, ownerUri, repoNamesUri] = [
        state.host,
        state.owner,
        state.repoName,
      ].map(encodeURIComponent);

      // user has requested that we use the users credentials
      // so lets grab them using the scmAuthApi and pass through
      // any additional scopes from the ui:options
      const { token } = await scmAuthApi.getCredentials({
        url: `https://${hostUri}/${ownerUri}/${repoNamesUri}`,
        additionalScope: {
          repoWrite: true,
          customScopes: requestUserCredentials.additionalScopes,
        },
      });
```

**Comment by benjdlambert** [comment]
I think this is probably fine.

```ts
      const [encodedHost, encodedOwner, encodedRepoName] = [
        state.host,
        state.owner,
        state.repoName,
      ].map(encodeURIComponent);
```

**Comment by Parsifal-M** [comment]
> I think this is probably fine.
> 
> ```ts
>       const [encodedHost, encodedOwner, encodedRepoName] = [
>         state.host,
>         state.owner,
>         state.repoName,
>       ].map(encodeURIComponent);
> ```

Hey! Thanks for all the help on this @benjdlambert I have definitely learned a few things :smile: 

You'll see from my latest push the current status of this, I had to revert `repoName` because unfortunately in addition to it being an issue here (before the change)

```
      const [encodedHost, encodedOwner, encodedRepoName] = [
        state.host,
        state.owner,
        state.repoName,
      ].map(encodeURIComponent);
```

It was also an issue here:

```
      <RepoUrlPickerRepoName
        repoName={state.repoName}
        allowedRepos={allowedRepos}
        onChange={repoName =>
          setState(prevState => ({ ...prevState, repoName }))
        }
        rawErrors={rawErrors}
```

Here: https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/RepoUrlPicker/RepoUrlPicker.tsx#L217

I did try a few things but couldn't get a working solution for now :disappointed: as its quite late here I will continue tomorrow on this to see if there is an easy way of doing it. 

I did notice however that it does not really make much of an impact in terms of functionality having it this way.

Thanks again!

**Comment by benjdlambert** [comment]
I went ahead and fixed this up to support the `repoName` too, think  that we should probably adjust the changeset wording to something else though, as it's not just the `allowedOwners` field that's been fixed.

Maybe something like:

`Fixed a bug where the `allowed*` values for the `RepoUrlPicker` would be reset on render`

**Review by benjdlambert — APPROVED** [review]
Thanks for this! :tada:

**Comment by suuus** [comment]
Thank you for contributing during Hacktoberfest 🍂! You can claim the Backstage Hacktoberfest Holopin at https://bck.st/hacktoberfest-holopin 🙌🏻
