### PR TITLE
fix(#26139): handle duplicate end key parts in ReviewState table

### LINKED ISSUE #26139: 🐛 Bug Report: `ui:backstage.review.explode` doesn't handle duplicated last key parts
### 📜 Description

Using the new default `ui:backstage.review.explode` option in the `ReviewState`, if the template contains duplicated final keys, only the last key (and its value) is kept in the summary table.

For example, a schema which contains both `one.foo: value1` and `two.foo: value2` will only display `foo: value2` in the summary table.

(Verified that this is just a UI bug, and the full data is sent to the Template action as expected.)

### 👍 Expected behavior

The full path of the key in the schema should be displayed in the summary table to ensure that all keys are unique, and therefore retained.

### 👎 Actual Behavior with Screenshots

Only the final key is retained.

### Toy example

First username/password:
image

Second username/password:
image

Review stage, only showing the second username/password:
image

### 👟 Reproduction steps

Create a Template with the following parameters:

```yaml
  parameters:
  - properties:
      spec:
        properties:
          one:
            properties:
              foo:
                description: Foo
                title: One.Foo
                type: string
            required:
            - foo
            title: One
            type: object
        title: ""
        type: object
    title: One
  - properties:
      spec:
        properties:
          two:
            properties:
              foo:
                description: Foo
                title: Two.Foo
                type: string
            required:
            - foo
            title: Two
            type: object
        title: ""
        type: object
    title: Two
```

When creating an instance from the Template, only the value of `two.foo` will be displayed in the `ReviewState` summary table.

### 📃 Provide the context for the Bug.

We noticed the new table layout, and wondered how it would handle this scenario. Tested locally and verified the behaviour described above.

It's likely that for our use-case this would be hit in the real world, but it hasn't been yet (and we'll choose the old, non-explode table display option for now!).

### 🖥️ Your Environment

```
 > yarn backstage-cli info
yarn run v1.22.21
$ /Users/richbartoncooper/Projects/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 23.5.0 - darwin/arm64
node: v18.19.0
yarn: 1.22.21
cli:  0.27.0 (installed)
backstage:  1.30.0

Dependencies:
  @backstage/app-defaults                                          1.5.10
  @backstage/backend-app-api                                       0.9.0
  @backstage/backend-common                                        0.24.0
  @backstage/backend-defaults                                      0.4.2
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.16
  @backstage/backend-plugin-api                                    0.8.0
  @backstage/backend-tasks                                         0.6.0
  @backstage/catalog-client                                        1.6.6
  @backstage/catalog-model                                         1.6.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.27.0
  @backstage/config-loader                                         1.9.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.2
  @backstage/core-compat-api                                       0.2.8
  @backstage/core-components                                       0.14.10
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.37
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.7, 0.7.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.30
  @backstage/integration                                           1.14.0
  @backstage/plugin-api-docs                                       0.11.8
  @backstage/plugin-app-backend                                    0.3.72
  @backstage/plugin-app-node                                       0.1.23
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.4
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.15
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.6
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.6
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.2.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.18
  @backstage/plugin-auth-backend-module-github-provider            0.1.20
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.20
  @backstage/plugin-auth-backend-module-google-provider            0.1.20
  @backstage/plugin-auth-backend-module-guest-provider             0.1.9
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.18
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.4
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.16
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.4
  @backstage/plugin-auth-backend-module-okta-provider              0.0.16
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.4
  @backstage/plugin-auth-backend                                   0.22.10
  @backstage/plugin-auth-node                                      0.5.0
  @backstage/plugin-auth-react                                     0.1.5
  @backstage/plugin-bitbucket-cloud-common                         0.2.22
  @backstage/plugin-catalog-backend-module-aws                     0.4.0
  @backstage/plugin-catalog-backend-module-logs                    0.0.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.21
  @backstage/plugin-catalog-backend                                1.25.0
  @backstage/plugin-catalog-common                                 1.0.26
  @backstage/plugin-catalog-graph                                  0.4.8
  @backstage/plugin-catalog-import                                 0.12.2
  @backstage/plugin-catalog-node                                   1.12.5
  @backstage/plugin-catalog-react                                  1.12.3
  @backstage/plugin-catalog                                        1.22.0
  @backstage/plugin-events-node                                    0.3.9
  @backstage/plugin-kubernetes-common                              0.8.2
  @backstage/plugin-org                                            0.6.28
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.20
  @backstage/plugin-permission-backend                             0.5.47
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.1
  @backstage/plugin-permission-react                               0.4.25
  @backstage/plugin-proxy-backend                                  0.5.4
  @backstage/plugin-scaffolder-backend-module-azure                0.1.15
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.13
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.15
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.13
  @backstage/plugin-scaffolder-backend-module-github               0.4.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.5
  @backstage/plugin-scaffolder-backend                             1.24.0
  @backstage/plugin-scaffolder-common                              1.5.5
  @backstage/plugin-scaffolder-node                                0.4.9
  @backstage/plugin-scaffolder-react                               1.11.0
  @backstage/plugin-scaffolder                                     1.24.0
  @backstage/plugin-search-backend-module-catalog                  0.2.0
  @backstage/plugin-search-backend-module-pg                       0.5.33
  @backstage/plugin-search-backend-module-techdocs                 0.2.0
  @backstage/plugin-search-backend-node                            1.3.0
  @backstage/plugin-search-backend                                 1.5.15
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.7.14
  @backstage/plugin-search                                         1.4.15
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.10
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.13
  @backstage/plugin-techdocs-node                                  1.12.9
  @backstage/plugin-techdocs-react                                 1.2.7
  @backstage/plugin-techdocs                                       1.10.8
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.11
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.10
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
✨  Done in 1.55s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by richcooper95**
### Issue

Following the changes introduced in https://github.com/backstage/backstage/pull/25346 to only display the final key part in the table display name in the `ReviewState`, multiple keys having the same final key part aren't all displayed in the final table.

See issue #26139 for a full description of the issue.

### Example

A schema which contains both `one.foo: value1` and `two.foo: value2` will only display `foo: value2` in the summary table.

### Solution

Instead of taking the final key part as the table name entry, we can construct the full schema path, separated by `>`.

In the example above, we'd see both entries displayed as:

| Name  | Value |
| ------------- | ------------- |
| One > Foo | value1  |
| Two > Foo | value2 |

(I considered `.` instead, and could go either way!)

#### Toy example

image

### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] ~Added or updated documentation~
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

fixes #26139

### CODE REVIEW

File: plugins/scaffolder-react/src/next/components/ReviewState/util.ts [hunk 1]
```diff
@@ -20,8 +20,11 @@ export function isJsonObject(value?: JsonValue): value is JsonObject {
...
 
-// Helper function to get the last part of the key
-export function getLastKey(key: string): string {
+// Helper function to format a key into a human-readable string
+export function formatKey(key: string): string {
   const parts = key.split('/');
-  return parts[parts.length - 1];
+  return parts
+    .filter(Boolean)
+    .map(part => part.charAt(0).toLocaleUpperCase('en-US') + part.slice(1))
```
Comment (stephenglass) [inline plugins/scaffolder-react/src/next/components/ReviewState/util.ts:28]: Using `lodash/startCase` may work better here (it's used in other parts of scaffolder UI for similar formatting)

**Review by stephenglass — COMMENTED** [review]
Appreciate your work on this 🙏

File: plugins/scaffolder-react/src/next/components/ReviewState/util.ts (hunk 1 above)
Comment (richcooper95) [reply plugins/scaffolder-react/src/next/components/ReviewState/util.ts:28]: `startCase` is a bit more opinionated (e.g. removes special characters), and YAML accepting special chars in quoted keys means I think we should still support this - so to retain the [current behaviour](https://github.com/backstage/backstage/pull/26140/files#diff-9d5518eed3fe4ace9a53f765ca0f2865d485c7f2c6a76bd8bb0220ae9abe3337R77) I went for this manual capitalisation instead!

Assuming we'd want to display the full key (including special chars) in the output table, I think this might be necessary 🤔

Comment (stephenglass) [reply plugins/scaffolder-react/src/next/components/ReviewState/util.ts:28]: Understood. `startCase` currently is the default title format for the review page. [See current code here](https://github.com/backstage/backstage/blob/f54d3a5385659eebb7e629c7f2ab8e763c67a111/packages/core-components/src/components/StructuredMetadataTable/StructuredMetadataTable.tsx#L179). Imo it would make sense  to keep using that formatting for consistency and remove test case for special chars if needed but I'll let the maintainers weigh in on this.

Comment (benjdlambert) [reply plugins/scaffolder-react/src/next/components/ReviewState/util.ts:28]: @richcooper95, yeah, kinda leaning towards using the existing formatting solution that we use indirectly already.

Think that the special start character one is a little bit of an edge case, and think we can take that separately if needed.

**Review by benjdlambert — CHANGES_REQUESTED** [review]
Nice! Think that this is looking good, just a thing about the `startCase` method, let's use that instead to keep it consistent.

File: plugins/scaffolder-react/src/next/components/ReviewState/util.ts (hunk 1 above)
Comment (richcooper95) [reply plugins/scaffolder-react/src/next/components/ReviewState/util.ts]: Cool, sounds good! Just changed in https://github.com/backstage/backstage/pull/26140/commits/23ac83be20198321087170177cdf2b064936efb0 👍

**Review by benjdlambert — APPROVED** [review]
Nice! thanks for this @richcooper95 :tada:
