### PR TITLE
Bug fix concerning the issue #20971

### LINKED ISSUE #20971: 🐛 Bug Report: Broken Table filters for invalid Initial States
### 📜 Description

Broken filters occur if there is an invalid initialState that doesn't match some of the data coming in
https://codesandbox.io/s/sleepy-field-nmypkz?file=/src/App.tsx

### 👍 Expected behavior

It should remove the invalid state

### 👎 Actual Behavior with Screenshots

A broken UI appears 
image

### 👟 Reproduction steps

See CodeSandbox for repro https://codesandbox.io/s/sleepy-field-nmypkz?file=/src/App.tsx 

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

CodeSandbox

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by iwarra**
Signed-off-by: Ivona Josipovic

## Hey, I just made a Pull Request!

Added a conditional that checks if the initial state is valid. It prevents the broken UI pictured below from being rendered. 
Closes #20971 

Before:
Broken UI

After: 
fix

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: packages/core-components/src/components/Select/Select.tsx [hunk 1]
```diff
@@ -218,15 +218,21 @@ export function SelectComponent(props: SelectProps) {
...
+                        items.find(el => el.value === selectedValue)?.label
+                      }
+                      clickable
+                      onDelete={handleDelete(selectedValue)}
+                      className={classes.chip}
+                    />
+                  ) : (
+                    false
+                  ),
+                )}
```
Comment (tudi2d) [inline packages/core-components/src/components/Select/Select.tsx:235]: Makes senes! Not caused by you, but as this code is already touched, would you be up for simplifying this by running `.find` only once instead of 3 times? :)

File: .changeset/many-lemons-arrive.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/core-components': patch
+---
+
+Fixed bug in Select component where a broken filter was showing when an invalid initialState was passed.
```
Comment (tudi2d) [inline .changeset/many-lemons-arrive.md:5]: spelling issue to fix - you can also highlight that Select is the component name by formating it as code. suggestion would be:

```suggestion
Fixed `Select` component default filter state.
```

**Review by tudi2d — CHANGES_REQUESTED** [review]
Tja @iwarra & welcome to the Backstage community 🎉 Congrats on your first PR - looks great & basically ready to go. Just two, small comments.

File: .changeset/many-lemons-arrive.md (hunk 2 above)
Comment (iwarra) [reply .changeset/many-lemons-arrive.md:5]: Tjoo, thanks for the warm welcome and your feedback. 🤩
I'll give it a shot, new PR coming tomorrow morning.

**Comment by tudi2d** [comment]
> [...] There will still be a `Filter(1)` and `no records to display` leading to inconsistency in the UI. What do you think about filtering out invalid filters from `selectedFilters` right from `Table` before passing them all the way down to `Select`? That way, the UI remains consistent.

Good catch, @Olunusib - thanks for highlighting - I missed that. @iwarra can you adjust the PR to this? :)

**Comment by vinzscam** [comment]
> > [...] There will still be a `Filter(1)` and `no records to display` leading to inconsistency in the UI. What do you think about filtering out invalid filters from `selectedFilters` right from `Table` before passing them all the way down to `Select`? That way, the UI remains consistent.
> 
> Good catch, @Olunusib - thanks for highlighting - I missed that. @iwarra can you adjust the PR to the feedback? :)

but you still need the fix for the `<Select />` component since it is independent from `<Table />`. Shouldn't this be addressed separately as the issue was only related to the `<Select />` component?

File: .changeset/many-lemons-arrive.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/core-components': patch
+---
+
+Fixed `Select` component default filter state.
```
Comment (vinzscam) [inline .changeset/many-lemons-arrive.md:5]:
```suggestion
Fixed an issue causing the `Select` component to show empty chips when some of the selected values did not match any item
```

**Review by Rugvip — APPROVED** [review]
Nice, thank you! 👍
