### PR TITLE
app-backend: replace all instances when injecting config

### LINKED ISSUE #22621: 🐛 Bug Report: backend-app config injection is not working in new frontend system
### 📜 Description

The system for injecting additional configuration to the frontend at runtime is not working correctly in the new backend system.

### 👍 Expected behavior

It should be possible to supply additional config via for example `APP_CONFIG`-prefixed environment variables, and have it apply in both the frontend and backend as it does in legacy apps.

### 👎 Actual Behavior with Screenshots

When running the backend with a built app, the config applies in the frontend but not in the backend. Config injection works correctly when running via `yarn dev`.

### 👟 Reproduction steps

In a repo using the new frontend system:
1. Build the app
2. Run `yarn start-backend` with some config overridden 
3. Note that that config does not apply in the frontend (though it does appear in the module-backstage bundle)

### 📃 Provide the context for the Bug.

I believe this problem occurs because there are two copies of the [`defaultConfigLoader`](https://github.com/backstage/backstage/blob/33daed5469339e9367fd9ce3c4cb6893d66f39f9/packages/core-app-api/src/app/defaultConfigLoader.ts) function being included in the module-backstage bundle. This means there are two instances of `__APP_INJECTED_RUNTIME_CONFIG__`, and the app-backend [only replaces one instance](https://github.com/backstage/backstage/blob/master/plugins/app-backend/src/lib/config.ts#L52).

I suspect this function might be appearing twice due to [the cross-package import of `defaultConfigLoader` in frontend-app-api](https://github.com/backstage/backstage/blob/33daed5469339e9367fd9ce3c4cb6893d66f39f9/packages/frontend-app-api/src/wiring/createApp.tsx#L63).

Happy to discuss - it seems likely there's a reason that we're stuck with this cross-package import in the short term, so perhaps a reasonable mitigation might be to start with updating the app-backend to replace multiple instances of `__APP_INJECTED_RUNTIME_CONFIG__`. Happy to send up a PR for that if helpful.

### 🖥️ Your Environment

OS:   Darwin 23.3.0 - darwin/arm64
node: v18.12.1
yarn: 3.2.3
cli:  0.25.2-next.1 (local)
backstage: N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by mtlewis**
## Hey, I just made a Pull Request!

Fixes #22621.

Switches the injection and replacement of config in app-backend to replace all instances, rather than just one. This also required making the quantifier lazy in the replacement regex, otherwise we can end up matching the first start marker, the last end marker, and every start and end marker in between them (!).

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/app-backend/src/lib/config.ts [hunk 1]
```diff
@@ -58,8 +58,8 @@ export async function injectConfig(
     } else if (content.includes('__APP_INJECTED_CONFIG_MARKER__')) {
       logger.info(`Replacing injected env config in ${jsFile}`);
 
-      const newContent = content.replace(
-        /\/\*__APP_INJECTED_CONFIG_MARKER__\*\/.*\/\*__INJECTED_END__\*\//,
+      const newContent = content.replaceAll(
+        /\/\*__APP_INJECTED_CONFIG_MARKER__\*\/.*?\/\*__INJECTED_END__\*\//g,
```
Comment (Rugvip) [inline plugins/app-backend/src/lib/config.ts:62]: yep that'd be important 😁

**Review by Rugvip — APPROVED** [review]
Sweet, thank you! 👍
