### PR TITLE
[CLI] Fix flaky end-to-end tests

### LINKED ISSUE #708: [CLI] Flaky E2E Test
## Expected Behavior

CLI E2E tests should not sometimes fail and have to be retriggered.

## Current Behavior

CLI E2E test sometimes fail to find the expected text on the page being loaded, even though there's nothing wrong with the PR. The test then has to be retriggered to pass.

## Possible Solution

Allow for 3 attempts to [`visit()`](https://github.com/spotify/backstage/blob/3b2aeae05a508f6253808ec118dafd2421362449/packages/cli/e2e-test/helpers.js#L104) and [check for content](https://github.com/spotify/backstage/blob/3b2aeae05a508f6253808ec118dafd2421362449/packages/cli/e2e-test/helpers.js#L121) on the page.

## Steps to Reproduce

`-`

## Context

Failed run: https://github.com/spotify/backstage/runs/619867498?check_suite_focus=true

## Your Environment

GitHub Actions

### PR DESCRIPTION
**Pull request by OrkoHunter**
Closes #708

The page may not be fully loaded on the first go. Hence, we wait for some time and then retry.

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

File: packages/cli/e2e-test/helpers.js [hunk 1]
```diff
@@ -117,12 +117,29 @@ async function waitForPageWithText(
     }
   }
 
+  // The page may not be fully loaded and hence we need to retry.
+  const maxAttemptsToSearchText = 3;
```
Comment (Rugvip) [inline packages/cli/e2e-test/helpers.js:121]: Think these could be `loadAttempts` and `findTextAttempts` to keep it short :p

File: packages/cli/e2e-test/helpers.js [hunk 2]
```diff
@@ -117,12 +117,29 @@ async function waitForPageWithText(
...
+        `Array.from(document.querySelectorAll("*")).some(el => el.textContent === "${escapedText}")`,
+        true,
+        `expected to find text ${text}`,
+      );
+      break;
+    } catch (error) {
+      if (error instanceof browser.assert.AssertionError) {
+        attemptsToSearchText++;
+        if (attemptsToSearchText <= maxAttemptsToSearchText) {
+          await new Promise(resolve => setTimeout(resolve, intervalMs));
```
Comment (Rugvip) [inline packages/cli/e2e-test/helpers.js:136]: I'm thinking we might want to do another `visit()` here before we wait

File: packages/cli/e2e-test/helpers.js [hunk 3]
```diff
@@ -117,12 +117,29 @@ async function waitForPageWithText(
...
+  for (;;) {
+    try {
+      browser.assert.evaluate(
+        `Array.from(document.querySelectorAll("*")).some(el => el.textContent === "${escapedText}")`,
+        true,
+        `expected to find text ${text}`,
+      );
+      break;
+    } catch (error) {
+      if (error instanceof browser.assert.AssertionError) {
```
Comment (Rugvip) [inline packages/cli/e2e-test/helpers.js:133]: Can prolly do this for any error? Less code :grin:

**Review by Rugvip — COMMENTED** [review]
Thanks! Couple of minor comments

File: packages/cli/e2e-test/helpers.js (hunk 1 above)
Comment (OrkoHunter) [reply packages/cli/e2e-test/helpers.js]: Yep, reads better :)

File: packages/cli/e2e-test/helpers.js (hunk 2 above)
Comment (OrkoHunter) [reply packages/cli/e2e-test/helpers.js]: Added. Not 100% sure about the reason. But again, headless browsers are mysterious, so it's better to be conservative. :P

File: packages/cli/e2e-test/helpers.js (hunk 3 above)
Comment (OrkoHunter) [reply packages/cli/e2e-test/helpers.js]: Yeah, done!

File: packages/cli/e2e-test/helpers.js [hunk 4]
```diff
@@ -95,18 +95,18 @@ async function waitForPageWithText(
...
     try {
       await new Promise(resolve => setTimeout(resolve, intervalMs));
       await browser.visit(path);
       break;
     } catch (error) {
       if (error.message.match(EXPECTED_LOAD_ERRORS)) {
-        attempts++;
-        if (attempts > maxAttempts) {
+        loadAttempts++;
+        if (loadAttempts > maxLoadAttempts) {
```
Comment (freben) [inline packages/cli/e2e-test/helpers.js:109]: should technically be `>=` :P

File: packages/cli/e2e-test/helpers.js [hunk 5]
```diff
@@ -117,12 +117,29 @@ async function waitForPageWithText(
     }
   }
 
+  // The page may not be fully loaded and hence we need to retry.
+  const maxFindTextAttempts = 3;
```
Comment (freben) [inline packages/cli/e2e-test/helpers.js:121]: this should be put along with `maxLoadAttempts = 240` as a parameter at the top, right?

File: packages/cli/e2e-test/helpers.js [hunk 6]
```diff
@@ -95,18 +95,18 @@ async function waitForPageWithText(
   browser,
   path,
   text,
-  { intervalMs = 1000, maxAttempts = 240 } = {},
+  { intervalMs = 1000, maxLoadAttempts = 240 } = {},
 ) {
-  let attempts = 0;
+  let loadAttempts = 0;
   for (;;) {
```
Comment (freben) [inline packages/cli/e2e-test/helpers.js:101]: (not a real change request, just noting because loops are hard to make pretty sometimes)

now if this in the future were broken apart into waitForPage and waitForText, we could make beautiful regular for loops an not care about the loop variable and use return instead of break to exit etc etc :)

```js
async function waitForPage(browser, path, {...}) {
  for (const i = 0; i < maxLoadAttempts; ++i) {
    try {
      await browser.visit(path);
      return;
    } catch (error) {
      if (!error.message.match(EXPECTED_LOAD_ERRORS)) {
        throw error;
      }
      await new Promise(resolve => setTimeout(resolve, intervalMs));
    }

    throw new Error('Max attempts ...');
  }
}
```

File: packages/cli/e2e-test/helpers.js (hunk 4 above)
Comment (OrkoHunter) [reply packages/cli/e2e-test/helpers.js:109]: Yes, I'll update. :D

File: packages/cli/e2e-test/helpers.js (hunk 5 above)
Comment (OrkoHunter) [reply packages/cli/e2e-test/helpers.js:121]: Thanks @freben ! I think so too.

File: packages/cli/e2e-test/helpers.js (hunk 6 above)
Comment (OrkoHunter) [reply packages/cli/e2e-test/helpers.js:101]: Right. This looks better. It should be a for loop instead of the current "while" loop.

**Comment by OrkoHunter** [comment]
@freben Addressed your comments. Couldn't make the for loop prettier in this PR :)

**Review by freben — APPROVED** [review]
Thanks for doing this!
