### PR TITLE
Do not send last_activity_after timestamp to gitlab api when the cache is empty 

### LINKED ISSUE #10399: gitlab-discovery processor looks for projects last changed in the present or future
## Expected Behavior
I'm expecting gitlab-discovery to fetch all projects in the group I point it at.

## Actual Behavior
When processing a gitlab-discovery location, the timestamp used for `last_activity_after` is pretty much the current time, which means no projects show up when the API is queried. Maybe it's a good idea to give it some leeway? I'm thinking it should probably be set to some value in the past.

## Steps to Reproduce
Setup a gitlab-discovery location and wait for it to process a group.

## Context
I'm on a self-hosted instance of GitLab (14.8.2-ee) with the v4 API.

https://github.com/backstage/backstage/blob/1a1e711aced140635964d23794f11fc0d06ca172/plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts#L96-L100

https://github.com/backstage/backstage/blob/1a1e711aced140635964d23794f11fc0d06ca172/plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts#L146-L152

## Your Environment
Local environment.

```text
OS:   Darwin 21.3.0 - darwin/arm64
node: v16.14.0
yarn: 1.18.0
cli:  0.16.0 (installed)

Dependencies:
  @backstage/app-defaults                         1.0.0
  @backstage/backend-common                       0.13.1
  @backstage/backend-tasks                        0.2.1
  @backstage/catalog-client                       1.0.0
  @backstage/catalog-model                        1.0.0
  @backstage/cli-common                           0.1.8
  @backstage/cli                                  0.16.0
  @backstage/config-loader                        1.0.0
  @backstage/config                               1.0.0
  @backstage/core-app-api                         1.0.0
  @backstage/core-components                      0.9.2
  @backstage/core-plugin-api                      1.0.0
  @backstage/errors                               1.0.0
  @backstage/integration-react                    1.0.0
  @backstage/integration                          1.0.0
  @backstage/plugin-api-docs                      0.8.3
  @backstage/plugin-app-backend                   0.3.30
  @backstage/plugin-auth-backend                  0.12.3
  @backstage/plugin-auth-node                     0.1.6
  @backstage/plugin-catalog-backend-module-gitlab 0.1.1
  @backstage/plugin-catalog-backend               1.0.0
  @backstage/plugin-catalog-common                1.0.0
  @backstage/plugin-catalog-graph                 0.2.15
  @backstage/plugin-catalog-react                 1.0.0
  @backstage/plugin-catalog                       1.0.0
  @backstage/plugin-github-actions                0.5.3
  @backstage/plugin-kubernetes-backend            0.4.13
  @backstage/plugin-kubernetes-common             0.2.8
  @backstage/plugin-kubernetes                    0.6.3
  @backstage/plugin-org                           0.5.3
  @backstage/plugin-permission-common             0.5.3
  @backstage/plugin-permission-node               0.5.5
  @backstage/plugin-permission-react              0.3.4
  @backstage/plugin-proxy-backend                 0.2.24
  @backstage/plugin-scaffolder-common             1.0.0
  @backstage/plugin-search-backend-node           0.5.2
  @backstage/plugin-search-backend                0.4.8
  @backstage/plugin-search-common                 0.3.2
  @backstage/plugin-search                        0.7.4
  @backstage/plugin-techdocs-backend              1.0.0
  @backstage/plugin-techdocs-node                 1.0.0
  @backstage/plugin-techdocs                      1.0.0
  @backstage/plugin-user-settings                 0.4.2
  @backstage/release-manifests                    0.0.2
  @backstage/search-common                        0.3.2
  @backstage/test-utils                           1.0.0
  @backstage/theme                                0.2.15
  @backstage/types                                1.0.0
  @backstage/version-bridge                       1.0.0
```

### PR DESCRIPTION
**Pull request by zeeraw**
## Hey, I just made a Pull Request!
The `last_activity_after` timestamp was being sent as current time when the cache is empty. Now it should not be sent at all and as we assert in the test.

Fixes #10399

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts [hunk 1]
```diff
@@ -93,11 +93,21 @@ export class GitLabDiscoveryProcessor implements CatalogProcessor {
...
       page: 1,
-    });
+    } as {
+      group: string;
+      page: number;
+      last_activity_after: string | undefined;
+    };
+
+    const lastActivity = (await this.cache.get(this.getCacheKey())) as string;
+    if (lastActivity !== '') {
```
Comment (freben) [inline plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts:106]: Mmm should probably rather be `if (lastActivity) {` to cover for undefined/null etc too.

Comment (zeeraw) [reply plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts:106]: Won't it always be a string though, because of `as string;`?

Comment (freben) [reply plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts:106]: No. `as` is a typescript-level "theoretical" cast, it has absolutely no runtime effect (it's compiled away and in javascript there will be no trace of it left)

Comment (Rugvip) [reply plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts:106]: We can get away with a lot less refactoring here as well right? I'd hope that sending `last_activity_after` as `undefined` has the same effect as not sending it at all.

File: plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts [hunk 2]
```diff
@@ -135,6 +145,8 @@ export class GitLabDiscoveryProcessor implements CatalogProcessor {
       );
     }
 
+    await this.cache.set(this.getCacheKey(), new Date().toISOString());
```
Comment (Rugvip) [inline plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts:148]: Feels safer to grab this timestamp before making the request, so that we err on the side of requesting too much rather than too little.

That is:

```
lastActivity = cache.get(...)
now = new Date().toISOString()
// request
cache.set(..., lastActivity || now)
```

**Review by Rugvip — COMMENTED** [review]
Thank you! 👍

File: plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts (hunk 2 above)
Comment (zeeraw) [reply plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts:148]: I think there's a problem with this as the last activity will never change from its original value if we just set it to whatever existed in the cache.

File: plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts (hunk 1 above)
Comment (zeeraw) [reply plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts]: @freben made changes as per your recommendation. Tests still seem to pass.

File: plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts (hunk 2 above)
Comment (Rugvip) [reply plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts:148]: Yep it needs some adjustment, whatever works, but I'd like to avoid the race

Comment (zeeraw) [reply plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts:148]: @Rugvip I'm thinking either we make it so that it respects the last modified or we simply don't cache it at all. If we want to give it some leeway adjusting the time we cache by offsetting it by an arbitrary amount of time. I'm not sure what we'd achieve by setting it to a virtually static value.

**Comment by zeeraw** [comment]
Is it stale? Still awaiting a response.

File: plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts (hunk 2 above)
Comment (Rugvip) [reply plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts:148]: Let's say we execute a request at the arbitrary point in time `15`. The response takes a little time to be processed and returned, so it arrives at `19`. That's the point when we call `Date.now()` in our code, so we store `19` in the cache. The next request is then going to ask for any updates that happened after `19`.

Now let's say there was activity at `18`, which we won't be included in the initial request because our request reached GitLab before that. We'll also miss it in our next request though, since we're asking for updates that happened after `19`.

The fix I'm after is to grab the timestamp before the request rather than after, so that what we store in the cache in the above example is `15`, rather than `19`, meaning there's no gap in time where we would miss updates.

Comment (zeeraw) [reply plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts:148]: Ah, alright, I see! Can do.

Comment (zeeraw) [reply plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts]: I've made a fix and rebased @Rugvip, please check if it's in line with what you expected.

File: plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts [hunk 3]
```diff
@@ -97,14 +98,25 @@ export class GitLabDiscoveryProcessor implements CatalogProcessor {
...
+      page: number;
+      last_activity_after: string | undefined;
+    };
+
+    const lastActivity = (await this.cache.get(this.getCacheKey())) as string;
+    // We check for the existence of lastActivity and only set it if it's present to ensure
+    // that the options doesn't include the key so that the API doesn't receive an empty query parameter.
+    if (lastActivity) {
+      opts.last_activity_after = lastActivity;
+    }
```
Comment (Rugvip) [inline plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts:117]: Think it should be possible to do something like this instead:

```ts
const lastActivity = await this.cache.get(this.getCacheKey());

const opts = {
  group,
  page: 1,
  ...(lastActivity && { last_activity_after: lastActivity }),
}
```

**Review by Rugvip — COMMENTED** [review]
Nice, thanks! 👍 

Just an opportunity to clean things up a bit :grin:

File: plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts (hunk 3 above)
Comment (zeeraw) [reply plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts:110]: Fixed this.

**Review by freben — APPROVED** [review]
Looks good! Ran prettier on the file since CI was complaining about a missing semicolon; (<- oh look, there it is!) will merge tomorrow if it goes green

**Comment by zeeraw** [comment]
🎉 Wohooo, great! Looking forward to the release.

**Comment by suuus** [comment]
Congrats on your first PR merged @zeeraw! Happy to count you as a contributor.
