### PR TITLE
fix(techdocs): ExpandableNavigation addon does not work on Firefox

### LINKED ISSUE #30332: TechDocs sidebar won’t expand in Firefox
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
nav docs 
firefox nav 
firefox expand
nav expand
menu expand
menu collapse
```

### 🗃️ Project Area

TechDocs

### 🔗 External Integration

N/A

### 📝 Description & Context

On Backstage 1.40.1, the TechDocs navigation sidebar no longer expands or collapses when viewed in Firefox. This behavior did not occur in Backstage 1.39.1. While investigating this, I confirmed the issue on Firefox 139.0.4 against the official demo at:
https://demo.backstage.io/docs/default/component/backstage/overview/architecture-overview/

### 👍 Expected Behavior

Clicking a parent entry in the TechDocs sidebar toggles its child items (expand/collapse).

### 📦 Reproduction Repo

_No response_

### 🥾 Reproduction steps

1.	Open Firefox ~139.0.4.
2.	Navigate to the TechDocs demo page:
https://demo.backstage.io/docs/default/component/backstage/overview/architecture-overview/
3.	In the left-hand sidebar, click any parent section (e.g., Getting Started).
4.	Observe that no child entries appear

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

### PR DESCRIPTION
**Pull request by GabDug**
## Hey, I just made a Pull Request!

Fix #30332

After enabling the `ExpandableNavigation`, one of our users reported that he wasn't able to collapse/open individual navigation items: only the top level collapse/open button was working, which is a clear regression from the default Mkdocs/Techdocs experience.

The issue only appears on Firefox, with no error in the browser side. It works properly on Chrome and Safari.

This can currently be tested on the demo website: https://demo.backstage.io/docs/default/component/backstage-demo
image

The fix has been tested on Chrome, Firefox and Safari. Tests don't need to be updated.

Demo on Firefox:

https://github.com/user-attachments/assets/225ea7f8-2976-4b56-95f9-20f06a0fc63c

Keyboard usage from #29960 is still working on all browsers.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by GabDug** [comment]
Would fix #30332

**Comment by sqsp-rwatkins** [comment]
@Rugvip Can we get this reopened? We're getting reports of this and I can reproduce it on the latest version (141.0.3 (aarch64))

**Comment by mycodeself** [comment]
This is still happening with backstage 1.42.3 (latest) + firefox 142.0 (64-bit). We're still in version 1.39.0 which seems doesn't have this issue.

File: plugins/techdocs-module-addons-contrib/src/ExpandableNavigation/ExpandableNavigation.tsx [hunk 1]
```diff
@@ -73,85 +73,59 @@ export const ExpandableNavigationAddon = () => {
...
+      const isExpanded = item.checked;
+      const shouldExpand = expanded?.expandAllNestedNavs;
+      if (shouldExpand && !isExpanded) {
+        return true;
+      }
+      if (!shouldExpand && isExpanded) {
+        return true;
+      }
+      return false;
+    }
```
Comment (webark) [inline plugins/techdocs-module-addons-contrib/src/ExpandableNavigation/ExpandableNavigation.tsx:96]:
```suggestion
    function shouldToggle(item: HTMLInputElement) {
      return expanded?.expandAllNestedNavs !== item.checked;;
    }
```

just a thought.

**Comment by webark** [comment]
anything to do to move this forward?

**Comment by awanlin** [comment]
Hi @GabDug, best I can tell this has always been a draft, when I review PRs I will filter these out as I have no way to know if they are ready or not. Especially in cases like TechDocs where I loop in the related maintainers. I know most of the Core Maintainers will also filter these out. It does also explain why it never got a review to the point of it closing due to stale.

With that said, is it ready for review? If it is I would rebase, make sure the CI is still green, and then flip this to be ready for us to review 👍

**Comment by GabDug** [comment]
Hi @awanlin,

Thanks for your comment and for bringing this up! The PR is still in draft and needs some more testing & cleanup, as highlighted by @webark’s suggestion. I didn’t prioritize it earlier because we temporarily removed the addon from our instance, but I understand that leaving it in draft means it won’t get reviewed.

I’d really appreciate your help with review and testing, especially since manual cross-browser E2E testing is needed and there are no automated tests. I want to make sure we don’t introduce regressions.

I’ll rebase, clean up the PR, and mark it as ready for review soon. Thanks for your patience and for keeping the conversation going!

**Comment by RobertMaaskant** [comment]
This is still happening with Backstage 1.43.3 and Firefox 143.0.1 (64-bit). Any chance we can get this approved and merged?

**Comment by GabDug** [comment]
Rebased the PR.

**Comment by GabDug** [comment]
Hi @awanlin @webark, CI is green & PR is rebased, let me know if there are other changes needed :)

Cheers!

**Review by johnphilip283 — APPROVED** [review]
Thanks for the fix!
