### PR TITLE
config-loader: add configuration schema support

### LINKED ISSUE #2854: [RFC] Static Configuration Schema
**Status:** Open for comments

## Need

Backstage's [static configuration](https://backstage.io/docs/conf/) is being used extensively throughout the project, by both the core packages and plugins. In many places there are examples of valid config, in some places the expected format is documented, but in most cases you need to go read the source code to understand what config you can use. That trajectory that we're on is obviously not scalable, and I think we need more guidelines and/or tooling in place to help make the configuration schema easier to document, discover, and validate.

A separate concern is the uncertainty in who reads each part of the configuration, as in what scope it has. For example, given a configuration value, is it needed by the frontend only? both frontend and backend? only backend? backend and it should be a secret? Given the lack of documentation of the configuration, there's also little clarity in the scope of each value and you again end up relying mostly on examples. In this case it doesn't even help to read the source code though, as that doesn't tell you whether the value is secret or not. Even with solid documentation of the scope of each value, it would be even better to know the scope of each value when loading the documentation. That way we can enforce some values to be treated as secrets and never be sent to the frontend, and we can also omit any backend-only config from the frontend.

### Schema

We add support for declaring static configuration schema through [JSONSchema](https://json-schema.org/). Each package provides it's own sub-schema, and the entire schema can then be stitched together into full view for each individual Backstage app.

Schema is directly or indirectly provided through a `package.json` `configSchema` field. The field can either contain inline JSONSchema, or be a reference to a `.json` or `.yaml` file that contains the schema.

Both the schema itself and the static configuration is validated whenever configuration is loaded, for example when starting up a backend, or building a frontend app. The schema is validated for conflicts, for example if one packages declares a `number` value where another package declares a `string`, an error is thrown. We also validate the configuration itself, for example if (`app-config.yaml`) declares a `string` value where the schema expects a `number`, an error will the thrown.

In addition to validation, we also use the stitched schema to generate documentation. Initially this likely takes the form of a basic CLI tool that prints configuration in the terminal, or whatever else is easiest to set up. Continued work would be to generate either Markdown or a documentation site, as well as bringing the schema into text editors.

### Configuration Value Scope

We also extend JSONSchema with a custom `scope` field. This field is used to indicate where the configuration is loadable from. Valid values are `app`, `default`, and `secret`, where `default` is the default 🙄 . The field applies to any value type, and when used for objects or arrays it applies to all children too, unless they declare a different scope.

Specifying a scope of `app` means that the value will also be sent to the frontend, while a `secret` scope means the value is secret and should never be sent to the frontend, and may have additional validation or tooling tied to it, such as being filtered from logs.

During schema stitching we may discover different declared scopes for the same value, in which case the most specific scope will apply. For example, if a value has both `app` and `default`, the resulting scope is `app`, likewise, `secret` and `default` will result in `secret`. The combination `app` and `secret` is forbidden however, and will cause the schema validation to fail.

## Alternatives

Skip the JSONSchema part and standardize on a way of writing documentation for configuration instead. We'd likely provide a Markdown template to paste into the README and fill in. This does not help solve the configuration scope at runtime, but could still be used to document the scope. A big downside of this approach is that there is no way to aggregate the documentation into a single big schema and document for a given project. When writing configuration you simply have to bounce around different READMEs to figure out the complete schema.

## Risks

Writing JSONSchema can be a bit tedious and it may make people more hesitant to makes things configurable in the first place, especially for more complex configuration. There's also a risk that there are bugs in the schema, as in the schema and the code reading the config don't match. For both of these I think adding tooling around generating either schema from TypeScript types or the other way around could be useful, but nothing to keep in scope before basic functionality is in place.

We may also want to avoid allowing configuration to be inlined in `package.json`, as it could have an impact on what tooling we're able to use.

### PR DESCRIPTION
**Pull request by Rugvip**
Adds configuration schema support!

This implements the `visibility` concept, where frontend configuration is selected using the schema rather than what config values are loaded in with `$env` etc. That means that you can now put secrets in plaintext, as well as load in frontend config using the `$` keys.

Fixes #2854

Also ended up implementing configuration schema definitions in TypeScript due to some happy hacking

### CODE REVIEW

**Comment by Fox32** [comment]
> Edit: That's not the draft button >_> w/e, not ready for merge yet but cba recreating 😁

You can turn it into a draft at the right (a bit hidden): 
image

Does this need a changeset?

**Comment by Rugvip** [comment]
@Fox32 ah, thanks x)

Yeah changesets definitely coming, along with docs, tests and whatnot, just wanted to get this up for feedback for now.

It's not really a breaking change but at the same time it is xP. The API hasn't changed except for the `app-backend` plugin, but since this switches to config schema being required for all frontend config, it might still break things.

File: packages/config-loader/src/lib/schema/compile.ts [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+    {
+      // JSONSchema is typically subtractive, as in it always reduces the set of allowed
+      // inputs through constraints. This changes the object property merging to be additive
+      // rather than subtractive.
+      ignoreAdditionalProperties: true,
+      resolvers: {
+        // This ensures that the visibilities across different schemas are sound, and
+        // selects the most specific visibility for each path.
+        visibility(values: string[], path: string[]) {
+          const hasApp = values.some(_ => _ === 'frontend');
```
Comment (freben) [inline packages/config-loader/src/lib/schema/compile.ts:78]: hasFrontend? :)

**Review by freben — COMMENTED** [review]
what i had time for today

File: packages/cli/src/commands/config/print.ts [hunk 2]
```diff
@@ -16,16 +16,41 @@
...
 import { loadCliConfig } from '../../lib/config';
+import cloneDeepWith from 'lodash/cloneDeepWith';
 
 export default async (cmd: Command) => {
-  const { config } = await loadCliConfig(cmd.config, cmd.withSecrets ?? false);
+  const { schema, appConfigs } = await loadCliConfig(cmd.config);
+  let data;
 
-  const flatConfig = config.get();
+  if (cmd.frontend) {
```
Comment (benjdlambert) [inline packages/cli/src/commands/config/print.ts:27]: I wonder if we could break this out into another function that just has `return` for the conditional rather than using `let` and reassigning. Might be a little cleaner?

File: packages/cli/src/commands/config/print.ts [hunk 3]
```diff
@@ -16,16 +16,41 @@
...
+    const frontendConfigs = schema.process(appConfigs, {
+      visibilities: ['frontend'],
```
[the remark this answers is not in the document]
Comment (Rugvip) [reply packages/cli/src/commands/config/print.ts:29]: Yeah switched to `visiblity` :p

File: packages/config-loader/src/lib/schema/collect.ts [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+    : __non_webpack_require__;
+
+/**
+ * This collects all known config schemas across all dependencies of the app.
+ */
+export async function collectConfigSchemas(
+  packageNames: string[],
+): Promise<ConfigSchemaPackageEntry[]> {
+  const visitedPackages = new Set<string>();
+  const schemas = Array<ConfigSchemaPackageEntry>();
```
[the remark this answers is not in the document]
Comment (Rugvip) [reply packages/config-loader/src/lib/schema/collect.ts:42]: Why tho

**Comment by Rugvip** [comment]
Now ready for more proper review :p

File: plugins/techdocs/package.json [hunk 5]
```diff
@@ -54,5 +54,21 @@
...
+    "title": "@backstage/techdocs",
+    "type": "object",
+    "properties": {
+      "techdocs": {
+        "type": "object",
+        "properties": {
+          "requestUrl": {
+            "type": "string",
+            "visibility": "frontend"
+          }
```
Comment (hooloovooo) [inline plugins/techdocs/package.json:69]:
```suggestion
          },
          "storageUrl": {
            "type": "string"
          }
        },
        required: [ "requestUrl" ]
```

**Review by timbonicus — APPROVED** [review]
Ooh la la, config types ❤️

File: packages/config-loader/src/lib/schema/collect.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (freben) [reply packages/config-loader/src/lib/schema/collect.ts:45]: Yeah just a personal thing where it feels odd to use what i conceive to be a type, as also a constructor. I know that it isn't really the case, but we use `new` to construct instances of EVERYTHING, so why not arrays and maps and sets as well :) You say `new Set` on the very line right above this! We should probably at least be consistent

File: packages/config-loader/src/lib/schema/collect.ts [hunk 6]
```diff
@@ -0,0 +1,180 @@
...
+          );
+        } else {
+          const path = resolvePath(dirname(pkgPath), pkg.configSchema);
+          const value = await fs.readJson(path);
+          schemas.push({
+            value,
+            path: relativePath(currentDir, path),
+          });
+        }
+      } else {
```
Comment (freben) [inline packages/config-loader/src/lib/schema/collect.ts:112]: I'm kinda wondering if we should instead always make this a path, and always make it `.d.ts`, and always generate one (but empty) with every plugin, always have it present in `files`. More opinionated, fewer choices, easier to get going, fewer steps to forget (like "oh i have to add it to the files section too? i didn't realise")

File: packages/config-loader/src/lib/schema/types.ts [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+ */
+
+import { AppConfig, JsonObject } from '@backstage/config';
+
+/**
+ * An sub-set of configuration schema.
+ */
+export type ConfigSchemaPackageEntry = {
+  /**
+   * The configuration schema itself, as JSONSchema draft-07
```
Comment (freben) [inline packages/config-loader/src/lib/schema/types.ts:24]: Wait but, this is not the meta-schema right? Either way, it's technically the superset of draft-07, could link to the actual schema here instead

File: packages/config-loader/src/lib/schema/types.ts [hunk 8]
```diff
@@ -0,0 +1,111 @@
...
+   */
+  value: JsonObject;
+  /**
+   * The path that the configuration schema was discovered at.
```
Comment (freben) [inline packages/config-loader/src/lib/schema/types.ts:28]: absolute?

File: packages/config-loader/src/lib/schema/types.ts [hunk 9]
```diff
@@ -0,0 +1,111 @@
...
+/**
+ * The result of validating configuration data using a schema.
+ */
+type ValidationResult = {
+  /**
+   * Errors that where emitted during validation, if any.
+   */
+  errors?: ValidationError[];
+  /**
+   * The configuration visibilities the where discovered during validation.
```
Comment (freben) [inline packages/config-loader/src/lib/schema/types.ts:62]:
```suggestion
   * The configuration visibilities that were discovered during validation.
```

File: packages/backend-common/config.d.ts [hunk 10]
```diff
@@ -0,0 +1,148 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+export interface Config {
+  app: {
+    baseUrl: string; // defined in core, but repeated here without doc
```
Comment (freben) [inline packages/backend-common/config.d.ts:19]: maybe we can standardise on `/** @see @backstage/core */`, but maybe we don't want jsdocs in these cases?

File: plugins/app-backend/src/lib/config.test.ts [hunk 11]
```diff
@@ -80,14 +95,19 @@ describe('injectEnvConfig', () => {
     expect(fsMock.writeFile).toHaveBeenCalledTimes(1);
     expect(fsMock.writeFile).toHaveBeenCalledWith(
       resolvePath(MOCK_DIR, 'main.js'),
-      '/*__APP_INJECTED_CONFIG_MARKER__*/"{\\"x\\":0}"/*__INJECTED_END__*/',
+      '/*__APP_INJECTED_CONFIG_MARKER__*/"[{\\"data\\":{\\"x\\":0},\\"context\\":\\"test\\"}]"/*__INJECTED_END__*/',
```
Comment (freben) [inline plugins/app-backend/src/lib/config.test.ts:98]: Just a thought - the frontend isn't technically interested in the context right? It's in a sense an information leakage of directory structures from backend concerns that one may not necessarily want to have sent over.

File: .changeset/app-backend-config.md [hunk 12]
```diff
@@ -0,0 +1,7 @@
+---
+'@backstage/plugin-app-backend': minor
+---
+
+Use new config schema support to automatically inject config with frontend visibility, in addition to the existing env schema injection.
+
+This removes the confusing behavior where configuration was only injected into the app att build time. Any runtime configuration (except for environment config) in the backend used to only apply to the backend itself, and not be injected into the frontend.
```
Comment (dhenneke) [inline .changeset/app-backend-config.md:7]:
```suggestion
This removes the confusing behavior where configuration was only injected into the app at build time. Any runtime configuration (except for environment config) in the backend used to only apply to the backend itself, and not be injected into the frontend.
```

File: plugins/app-backend/src/lib/config.test.ts (hunk 11 above)
Comment (Rugvip) [reply plugins/app-backend/src/lib/config.test.ts:98]: It is! It's for providing more informative error messages, and the paths are sanitized in that they're only relative paths from the repo root or just the filename itself

File: packages/backend-common/config.d.ts (hunk 10 above)
Comment (Rugvip) [reply packages/backend-common/config.d.ts:19]: Yeah in general this doesn't fully establish a pattern for how to deal with values that are defined in a different package but re-used. We do indeed want to avoid jsdoc here though, as that could potentially override the original docs, and something like `@see @backstage/core` would be merged in with the actual definition which would be confusing.

File: docs/conf/defining.md [hunk 13]
```diff
@@ -4,16 +4,109 @@ title: Defining Configuration for your Plugin
...
+The visibility only applies to the direct parent of where the keyword is placed
+in the schema. For example, if you set the visibility to `frontend` for a subset
+of the schema with `type: "object"`, but none of the descendants, only an empty
+object will be available in the frontend. The full ancestry does not need to
+have correctly defined visibilities however, so it is enough to only for example
+declare the visibility of a leaf node of `type: "string"`.
+
+## Validation
+
+Schema can be validated using the `backstage-cli config:validate` command. If
```
[the remark this answers is not in the document]
Comment (Rugvip) [reply docs/conf/defining.md:88]: Yep open to suggestions, I think `check` makes sense as we've used that in other places?

File: docs/conf/defining.md [hunk 14]
```diff
@@ -4,16 +4,109 @@ title: Defining Configuration for your Plugin
...
+## Guidelines
+
+> Limit static configuration. The first question to ask is whether a particular
+> option actually needs to be static configuration, or if it might just as well
+> be a TypeScript API. In general options that you want to be able to change for
+> different deployment environments should be static configuration, while it
+> should otherwise be avoided.
 
 When defining configuration for your plugin, keep keys camelCased and stick to
 existing casing conventions such as `baseUrl`.
```
[the remark this answers is not in the document]
Comment (Rugvip) [reply docs/conf/defining.md:105]: It's about `baseUrl` vs `baseURL`, clarified

File: packages/backend-common/config.d.ts [hunk 15]
```diff
@@ -0,0 +1,148 @@
...
+  backend: {
+    baseUrl: string; // defined in core, but repeated here without doc
+    /** Address that the backend should listen to. */
+
+    listen:
+      | string
+      | {
+          /** Address of the interface that the backend should bind to. */
+          address?: string;
+          /** Port that the backend should listen to. */
```
[the remark this answers is not in the document]
Comment (Rugvip) [reply packages/backend-common/config.d.ts:31]: Yep, I avoided going super deep in actually creating a complete schemas in this PR though, would rather follow up with that

File: packages/backend-common/config.d.ts [hunk 16]
```diff
@@ -0,0 +1,148 @@
...
+    /** Integration configuration for Azure */
+    azure?: {
+      /** The hostname of the given Azure instance */
+      host: string;
+      /**
+       * Token used to authenticate requests.
+       * @visibility secret
+       */
+      token?: string;
+    }[];
```
[the remark this answers is not in the document]
Comment (Rugvip) [reply packages/backend-common/config.d.ts:97]: Yep, this could totally be our rule for when to use which btw, `[]` is fine if it fits on the same line, otherwise use `Array<>`

File: packages/cli/package.json [hunk 17]
```diff
@@ -146,5 +147,31 @@
     "watch": "./src",
     "exec": "bin/backstage-cli",
     "ext": "ts"
+  },
+  "configSchema": {
```
[the remark this answers is not in the document]
Comment (Rugvip) [reply packages/cli/package.json:151]: Yep, just showing a bit of both. Tbh for a single value or 2 I kinda prefer inline schema though

File: .github/workflows/ci.yml [hunk 18]
```diff
@@ -72,6 +72,9 @@ jobs:
       - name: prettier
         run: yarn prettier:check
 
+      - name: validate config
```
[the remark this answers is not in the document]
Comment (Rugvip) [reply .github/workflows/ci.yml:75]: Yeah why not tbh, we don't for example run prettier or doc link verification either, but could

File: packages/config-loader/src/lib/schema/collect.ts (hunk 6 above)
Comment (Rugvip) [reply packages/config-loader/src/lib/schema/collect.ts:112]: Yeah if this ends up being something almost every plugin does then I think we could add that in the future. Still hoping that adding config isn't something that every plugin does or something we should encourage :p

File: packages/config-loader/src/lib/schema/types.ts (hunk 7 above)
Comment (Rugvip) [reply packages/config-loader/src/lib/schema/types.ts:24]: Type would actually be embedded in the json data rather than be defined here anyway. Got rid of the rest of the comment, was from when It was actually using a proper schema type from ajv.

File: packages/config-loader/src/lib/schema/collect.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (Rugvip) [reply packages/config-loader/src/lib/schema/collect.ts:45]: I think of it as omitting `new` for any native types, `String`, `Boolean`, `Array`, `Number`, `Object`

**Review by freben — APPROVED** [review]

**Review by OrkoHunter — APPROVED** [review]
