### PR TITLE
Fix for repo lint max-warnings options

### LINKED ISSUE #29298: 🐛 Bug Report: --max-warnings flag in backstage-cli lint is only respected for package
### 📜 Description

When adding the `--max-warnings` flag to `lint` subcommand in only works when using the `package` specifier, doesn't work for the `repo` one
```bash
$ backstage-cli repo lint --max-warnings 0
error: unknown option '--max-warnings'
```

### 👍 Expected behavior

Works also for `repo` specifier

### 👎 Actual Behavior with Screenshots

```bash
$ backstage-cli repo lint --max-warnings 0
error: unknown option '--max-warnings'
```

### 👟 Reproduction steps

1. Install backstage-cli 0.31.0
2. Run `backstage-cli repo lint --max-warnings 0`

### 📃 Provide the context for the Bug.

Release notes say to add the flag for keeping previous behaviour buy it doesn't work.

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by vinzscam**
## Hey, I just made a Pull Request!

It looks like we forgot to specify `--max-warnings` as a valid option of the `repo lint` command.
Fixes #29298

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by deejay1 — APPROVED** [review]

**Comment by deejay1** [comment]
@vinzscam update the the API reports `yarn build:api-reports`

File: packages/cli/src/modules/lint/alpha.ts [hunk 1]
```diff
@@ -76,6 +76,10 @@ export default createCliPlugin({
           '--since <ref>',
           'Only lint packages that changed since the specified ref',
         );
+        command.option(
+          '--max-warnings <number>',
+          'Fail if more than this number of warnings. -1 allows warnings. (default: 0)',
```
Comment (freben) [inline packages/cli/src/modules/lint/alpha.ts:81]: Wasn't the idea that the default should be -1 both here and in the other lint command?

Comment (vinzscam) [reply packages/cli/src/modules/lint/alpha.ts]: ooops, thx! I've updated all the descriptions

**Review by freben — APPROVED** [review]
