### PR TITLE
auth-backend: refuse to issue excessively large tokens

### LINKED ISSUE #20188: 🐛 Bug Report: 413 when too many entities are assigned
### 📜 Description

When a user is owner of too many entities (in my case groups) the corresponding JWT Token is growing too big and the browser is rejecting these Requests with a 413. 

### 👍 Expected behavior

TBH I'm not quite sure what I'm expecting. Maybe some Docs on how to increase the maximum header size because Backstage itself can't mitigate this.

### 👎 Actual Behavior with Screenshots

Chrome DevTools show that each request is rejected with a 413 (Request headers too large)  Will add screenshots after creating of the issue

### 👟 Reproduction steps

I had a custom gitlab instance and used the [gpt](https://gitlab.com/gitlab-org/quality/performance) from GitLab to create 1000 Groups. What I didn't think about was that my user is now owner of all of them and the [GitLab Discovery](https://backstage.io/docs/integrations/gitlab/discovery/) is creating Backstage groups for all of them. Probably someone don't need GitLab to reproduce this and could just create 1000 Group Entities via a `Groups.yaml`. 

### 📃 Provide the context for the Bug.

I wasn't able to use backstage anymore as any request was failing

### 🖥️ Your Environment

```
OS:   Darwin 22.6.0 - darwin/arm64
node: v18.18.0
yarn: 3.6.1
cli:  0.22.13 (installed)
backstage:  1.18.1

Dependencies:
  @backstage/app-defaults                                          1.4.3
  @backstage/backend-app-api                                       0.5.3
  @backstage/backend-common                                        0.19.5
  @backstage/backend-defaults                                      0.2.3
  @backstage/backend-dev-utils                                     0.1.1
  @backstage/backend-openapi-utils                                 0.0.4
  @backstage/backend-plugin-api                                    0.6.3
  @backstage/backend-tasks                                         0.5.8
  @backstage/catalog-client                                        1.4.4
  @backstage/catalog-model                                         1.4.2
  @backstage/cli-common                                            0.1.12
  @backstage/cli-node                                              0.1.4
  @backstage/cli                                                   0.22.13
  @backstage/config-loader                                         1.5.0
  @backstage/config                                                1.1.0
  @backstage/core-app-api                                          1.10.0
  @backstage/core-components                                       0.13.5
  @backstage/core-plugin-api                                       1.6.0
  @backstage/dev-utils                                             1.0.21
  @backstage/errors                                                1.2.2
  @backstage/eslint-plugin                                         0.1.3
  @backstage/integration-aws-node                                  0.1.6
  @backstage/integration-react                                     1.1.19
  @backstage/integration                                           1.7.0
  @backstage/plugin-api-docs                                       0.9.11
  @backstage/plugin-app-backend                                    0.3.51
  @backstage/plugin-app-node                                       0.1.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.1.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.0
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.0
  @backstage/plugin-auth-backend-module-google-provider            0.1.0
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.0
  @backstage/plugin-auth-backend                                   0.19.0
  @backstage/plugin-auth-node                                      0.3.0
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.0
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.0
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.0
  @backstage/plugin-catalog-backend                                1.13.0
  @backstage/plugin-catalog-common                                 1.0.16
  @backstage/plugin-catalog-graph                                  0.2.36
  @backstage/plugin-catalog-import                                 0.10.0
  @backstage/plugin-catalog-node                                   1.4.4
  @backstage/plugin-catalog-react                                  1.8.4
  @backstage/plugin-catalog                                        1.13.0
  @backstage/plugin-events-node                                    0.2.12
  @backstage/plugin-explore-common                                 0.0.2
  @backstage/plugin-github-actions                                 0.6.5
  @backstage/plugin-home-react                                     0.1.3
  @backstage/plugin-home                                           0.5.8
  @backstage/plugin-kubernetes-backend                             0.12.0
  @backstage/plugin-kubernetes-common                              0.6.6
  @backstage/plugin-kubernetes                                     0.10.3
  @backstage/plugin-org                                            0.6.14
  @backstage/plugin-permission-backend                             0.5.26
  @backstage/plugin-permission-common                              0.7.8
  @backstage/plugin-permission-node                                0.7.14
  @backstage/plugin-permission-react                               0.4.15
  @backstage/plugin-proxy-backend                                  0.4.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.6
  @backstage/plugin-scaffolder-backend                             1.17.0
  @backstage/plugin-scaffolder-common                              1.4.1
  @backstage/plugin-scaffolder-node                                0.2.3
  @backstage/plugin-scaffolder-react                               1.5.5
  @backstage/plugin-scaffolder                                     1.15.0
  @backstage/plugin-search-backend-module-catalog                  0.1.7
  @backstage/plugin-search-backend-module-explore                  0.1.7
  @backstage/plugin-search-backend-module-pg                       0.5.12
  @backstage/plugin-search-backend-module-techdocs                 0.1.7
  @backstage/plugin-search-backend-node                            1.2.7
  @backstage/plugin-search-backend                                 1.4.3
  @backstage/plugin-search-common                                  1.2.6
  @backstage/plugin-search-react                                   1.7.0
  @backstage/plugin-search                                         1.4.0
  @backstage/plugin-tech-radar                                     0.6.8
  @backstage/plugin-techdocs-backend                               1.7.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.0
  @backstage/plugin-techdocs-node                                  1.8.0
  @backstage/plugin-techdocs-react                                 1.1.11
  @backstage/plugin-techdocs                                       1.7.0
  @backstage/plugin-user-settings                                  0.7.10
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.3
  @backstage/theme                                                 0.4.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.5

``
`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by Rugvip**
## Hey, I just made a Pull Request!

Closes #20188

Adding a check to make sure that user tokens aren't ridiculously large. Tokens of this size would never be expected in practice and would basically always be a bug in the sign-in resolver implementation or data model.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/auth-backend/src/identity/TokenFactory.ts [hunk 1]
```diff
@@ -97,14 +98,25 @@ export class TokenFactory implements TokenIssuer {
...
       .setIssuer(iss)
       .setAudience(aud)
       .setSubject(sub)
       .setIssuedAt(iat)
       .setExpirationTime(exp)
       .sign(await importJWK(key));
+
+    if (token.length > MAX_TOKEN_LENGTH) {
+      throw new Error(
+        `Failed to issue a new user token. The resulting token is excessively large, with either too many ownership claims or too large custom claims. The following claims were requested: '${JSON.stringify(
```
Comment (tudi2d) [inline plugins/auth-backend/src/identity/TokenFactory.ts:113]: How could someone fix their headers then? Does it maybe make sense to link a doc or give a suggestion what to do instead?

**Review by tudi2d — APPROVED** [review]
looks good. could this break existing instances?

**Review by freben — APPROVED** [review]

File: plugins/auth-backend/src/identity/TokenFactory.ts [hunk 2]
```diff
@@ -23,6 +23,7 @@ import { LoggerService } from '@backstage/backend-plugin-api';
 import { AnyJWK, KeyStore, TokenIssuer, TokenParams } from './types';
 
 const MS_IN_S = 1000;
+const MAX_TOKEN_LENGTH = 32768; // At 64 bytes per entity ref this still leaves room for about 500 entities
```
Comment (Rugvip) [inline plugins/auth-backend/src/identity/TokenFactory.ts:26]: Bumped up to 32k, since people have been hitting 4k in production setups, so 8k seemed a bit low. The intention is for this to never be hit in production setups without bugs
