### PR TITLE
fix(scaffolder): open markdown links in new tab for template outputs

### LINKED ISSUE #32192: Following links in markdown should open in new tab
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
template
markdown
nunjucks
_blank
"new tab"
```

### 🗃️ Project Area

Software Templates

### 🔗 External Integration

N/A

### 📝 Description & Context

When the output of a software template has links rendered in the markdown of text content, if you follow the links they will open in the current tab, making it harder for users to stay on track with more involved processes that output multiple links and/or are just intermediate outputs of templates used in golden paths.

### 👍 Expected Behavior

Links from markdown output text are rendered with `target="_blank"` to open in new tabs by default, similar to other areas like output links, property descriptions.

### 📦 Reproduction Repo

_No response_

### 🥾 Reproduction steps

Add any link to the text output of a template.
```
  output:
    text:
      - title: Project Skeleton
        content: |
          Welcome to your new Skeleton XYZ Project. The following resources have been created for you.

          - **Repository**  
          [Repo](https://www.github.com)
          
          - **Dev deployment**  
          [Deploy](https://www.example.com)

          - **Documentation**  
          [Docs](https://www.google.com/)
```

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes, but I would like some more guidance

### PR DESCRIPTION
**Pull request by Vivek1819**
### What does this PR do?

This PR updates the markdown rendering behavior in **Scaffolder task outputs** so that links open in a new tab (`target="_blank"`).

Currently, links rendered from template output markdown replace the current Backstage tab. This can interrupt user workflows when navigating to external resources generated by a template (e.g., repositories, documentation, deployment links).

With this change, links open in a new tab by default, providing a smoother user experience.

---

### Implementation Details

The change passes `linkTarget="_blank"` to `MarkdownContent` within `DefaultTemplateOutputs`, ensuring that this behavior is scoped specifically to Scaffolder task outputs and does not affect other markdown usage across Backstage.

Verified locally in the Scaffolder example app.

Closes #32192

---

## ✅ Checklist

* [ ] A changeset describing the change and affected packages
  *(Let me know if a changeset is required for this UX-level fix and I can add one.)*
* [ ] Added or updated documentation
  *(No documentation updates required.)*
* [ ] Tests for new functionality and regression tests for bug fixes
  *(Behavior verified manually in the Scaffolder UI.)*
* [ ] Screenshots attached (for UI changes)
  *(Optional — can attach if preferred.)*
* [x] All commits include a `Signed-off-by` line.

### CODE REVIEW

File: plugins/scaffolder-react/src/next/components/TemplateOutputs/DefaultTemplateOutputs.tsx [hunk 1]
```diff
@@ -96,7 +96,10 @@ export const DefaultTemplateOutputs = (props: {
             titleTypographyProps={{ component: 'h2' }}
           >
             <Box padding={2} height="100%">
-              <MarkdownContent content={textOutput.content ?? ''} />
+              <MarkdownContent
```
Comment (freben) [inline plugins/scaffolder-react/src/next/components/TemplateOutputs/DefaultTemplateOutputs.tsx]: I would prefer if you changed [the `components` prop inside `MarkdownContent`](https://github.com/backstage/backstage/blob/c7d2bf99eed2d5a3725714b0a30cbd7cf2be6e80/packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx#L94) instead, with `a: Link` basically - where Link ideally is from backstage/core-components. It has the builtin behavior that for links that go outside the site it's in a new window/tab, otherwise it stays internal.

File: .changeset/common-shrimps-wink.md
Comment (freben) [inline .changeset/common-shrimps-wink.md:1]: Remove this file from the PR

File: packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx [hunk 2]
```diff
@@ -109,6 +110,15 @@ const components: Options['components'] = {
   h4: headingRenderer,
   h5: headingRenderer,
   h6: headingRenderer,
+
+  a: ({ href, children, ...props }) =>
+    href ? (
+      <Link {...(props as any)} to={href}>
```
Comment (freben) [inline packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx]: We generally strictly avoid `any`. Can this be done better?

Comment (Vivek1819) [reply packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx]: Updated the implementation to avoid any and limited the forwarded props to title, target, and rel, which are the relevant attributes for markdown links. This avoids the type conflicts with the Backstage Link component.

File: packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx [hunk 3]
```diff
@@ -109,6 +110,15 @@ const components: Options['components'] = {
   h4: headingRenderer,
   h5: headingRenderer,
   h6: headingRenderer,
+
+  a: ({ href, children, title, target, rel }) =>
+    href ? (
+      <Link to={href} title={title} target={target} rel={rel}>
```
Comment (freben) [inline packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx]:
```suggestion
      <Link to={href} title={title} ...(target ? { target } : {}) ...(rel ? { rel } : {})>
```

I think Copilot is right about target and rel here

**Comment by freben** [comment]
Let's see if it builds now

File: packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx [hunk 4]
```diff
@@ -109,6 +110,15 @@ const components: Options['components'] = {
   h4: headingRenderer,
   h5: headingRenderer,
   h6: headingRenderer,
+
+  a: ({ href, children, title, target, rel }) =>
+    href ? (
+      <Link to={href} title={title} ...(target ? { target } : {}) ...(rel ? { rel } : {})>
+        {children}
+      </Link>
+    ) : (
```
Comment (freben) [inline packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx:124]:
```suggestion
      <Link
        to={href}
        title={title}
        {...(target ? { target } : {})}
        {...(rel ? { rel } : {})}
      >
```

File: packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx [hunk 5]
```diff
@@ -109,6 +110,15 @@ const components: Options['components'] = {
   h4: headingRenderer,
   h5: headingRenderer,
   h6: headingRenderer,
+
+  a: ({ href, children, title, target, rel }) =>
+    href ? (
+      <Link to={href} title={title} ...(target ? { target } : {}) ...(rel ? { rel } : {})>
```
Comment (freben) [inline packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx]:
```suggestion
      <Link
        to={href}
        title={title}
        {...(target ? { target } : {})}
        {...(rel ? { rel } : {})}
      >
```
