### PR TITLE
fix(shortcuts): refactor client to observe storageApi and store updates

### LINKED ISSUE #16817: 🐛 Bug Report: `shortcuts` plugin with `storageApi` of `UserSettingsStorage` only allows for a single shortcut
### 📜 Description

The `shortcuts` plugin used in conjunction with the `UserSettingsStorage` `storageApi` for persistent user settings only allows for a single `ShortcutItem` at a time.

### 👍 Expected behavior

Multiple configured shortcuts should be allowed

### 👎 Actual Behavior with Screenshots

Adding a new Shortcut Item results overriding and replacing previously configured shortcuts 

https://user-images.githubusercontent.com/12898497/224427305-839e0559-04dd-470d-bb28-9ed93f630384.mov

### 👟 Reproduction steps

1. [Install and configure the shortcuts plugin](https://github.com/backstage/backstage/tree/v1.11.1/plugins/shortcuts#usage)
2. [Install and configure the `user-settings-backend`](https://github.com/backstage/backstage/tree/v1.11.1/plugins/user-settings-backend#setup-backend) and [update the `storageAp` to use `UserSettingsStorage`](https://github.com/backstage/backstage/tree/v1.11.1/plugins/user-settings-backend#setup-app)
3. start a local dev server
4. On any page, add a Shortcut Item for that page
5. Navigate to another different page, add a Shortcut Item for that page
6. See how the previously added ShortcutItem is replaced

### 📃 Provide the context for the Bug.

It looks like the [`LocalStoredShortcuts`](https://github.com/backstage/backstage/blob/v1.11.1/plugins/shortcuts/src/api/LocalStoredShortcuts.ts#L29) that is used by default makes use of the currently configured `storageApi`, but on [`add`](https://github.com/backstage/backstage/blob/v1.11.1/plugins/shortcuts/src/api/LocalStoredShortcuts.ts#L49-L52), it [attempts to get the current `snapshot` from the storageApi](https://github.com/backstage/backstage/blob/v1.11.1/plugins/shortcuts/src/api/LocalStoredShortcuts.ts#L44) 

This will always apparently return an empty snapshot for the `UserSettingStorage` client ([source](https://github.com/backstage/backstage/blob/v1.11.1/plugins/user-settings/src/apis/StorageApi/UserSettingsStorage.ts#L166-L168)) 

The [StarredEntitiesApi](https://github.com/backstage/backstage/blob/v1.11.1/plugins/catalog/src/apis/StarredEntitiesApi/DefaultStarredEntitiesApi.ts) seems to not have the same issues, so likely the default Shortcuts Api Client needs to be updated to match

### 🖥️ Your Environment

```
OS:   Darwin 22.3.0 - darwin/x64
node: v16.14.0
yarn: 1.22.17
cli:  0.22.3 (installed)
backstage:  1.11.0

Dependencies:
  @backstage/app-defaults                          1.2.0
  @backstage/backend-app-api                       0.4.0
  @backstage/backend-common                        0.18.2
  @backstage/backend-dev-utils                     0.1.0
  @backstage/backend-plugin-api                    0.4.0
  @backstage/backend-tasks                         0.4.3
  @backstage/catalog-client                        1.3.1
  @backstage/catalog-model                         1.2.0
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.3
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.5.0
  @backstage/core-components                       0.12.4
  @backstage/core-plugin-api                       1.4.0
  @backstage/errors                                1.1.4
  @backstage/eslint-plugin                         0.1.1
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.10
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.9.0
  @backstage/plugin-app-backend                    0.3.42
  @backstage/plugin-auth-backend                   0.18.0
  @backstage/plugin-auth-node                      0.2.11
  @backstage/plugin-catalog-backend                1.7.2
  @backstage/plugin-catalog-common                 1.0.11
  @backstage/plugin-catalog-graph                  0.2.27
  @backstage/plugin-catalog-import                 0.9.5
  @backstage/plugin-catalog-node                   1.3.3
  @backstage/plugin-catalog-react                  1.3.0
  @backstage/plugin-catalog                        1.8.0
  @backstage/plugin-github-actions                 0.5.15
  @backstage/plugin-org                            0.6.5
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.5
  @backstage/plugin-permission-react               0.4.10
  @backstage/plugin-proxy-backend                  0.2.36
  @backstage/plugin-scaffolder-backend             1.11.0
  @backstage/plugin-scaffolder-common              1.2.5
  @backstage/plugin-scaffolder-node                0.1.0
  @backstage/plugin-scaffolder-react               1.1.0
  @backstage/plugin-scaffolder                     1.11.0
  @backstage/plugin-search-backend-module-pg       0.5.3
  @backstage/plugin-search-backend-node            1.1.3
  @backstage/plugin-search-backend                 1.2.3
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.5.0
  @backstage/plugin-search                         1.1.0
  @backstage/plugin-shortcuts                      0.3.7
  @backstage/plugin-tech-radar                     0.6.1
  @backstage/plugin-techdocs-backend               1.5.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.10
  @backstage/plugin-techdocs-node                  1.5.0
  @backstage/plugin-techdocs-react                 1.1.3
  @backstage/plugin-techdocs                       1.5.0
  @backstage/plugin-user-settings-backend          0.1.6
  @backstage/plugin-user-settings                  0.7.0
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.5
  @backstage/theme                                 0.2.17
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
✨  Done in 1.45s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by alecjacobs5401**
## Hey, I just made a Pull Request!

Resolves #16817

Refactors the `LocalStoredShortcuts` client that already uses the `storageApi` to observe updates to `storageApi` and make updates to local shortcuts. 

Doing so ensures that `add` will properly append instead of doing a full replace

Heavily follows how the [DefaultStarredEntitiesApi](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/apis/StarredEntitiesApi/DefaultStarredEntitiesApi.ts) interfaces with the `storageApi`

The `api-report.md` changes should be non-breaking - I just changed it to `import type` for types/interfaces instead of the full thing. Happy to remove and change that back if that is preferred!

#### Using Local Storage as the storageApi

https://user-images.githubusercontent.com/12898497/224771552-ae93e612-67b5-4e60-bfa7-7c578fa0e316.mov

#### Using `UserSettingsStorage` from `user-settings` plugin as the storageApi (with the `user-settings-backend` configured locally)

https://user-images.githubusercontent.com/12898497/224771714-84eaf2a7-939a-43f8-9704-e82d062c5945.mov

## :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/shortcuts/src/api/LocalStoredShortcuts.ts [hunk 1]
```diff
@@ -16,38 +16,52 @@
...
 
-  shortcut$() {
-    return this.shortcuts;
+  shortcut$(): Observable<Shortcut[]> {
+    return this.observable;
   }
 
   get() {
-    return Array.from(
-      this.storageApi.snapshot<Shortcut[]>('items').value ?? [],
```
Comment (alecjacobs5401) [inline plugins/shortcuts/src/api/LocalStoredShortcuts.ts:44]: this was the source of the but in https://github.com/backstage/backstage/issues/16817

The `UserSettingsStorage` `storageApi` would always return a [static value of presence 'unknown'](https://github.com/backstage/backstage/blob/80698c1de81dc0774b87c466cb8951c11d4acea4/plugins/user-settings/src/apis/StorageApi/UserSettingsStorage.ts#L166-L168)

**Review by freben — APPROVED** [review]
Looks good!
