### PR TITLE
fix(github-actions): fix crash when viewing ongoing workflows

### LINKED ISSUE #2949: GithubActions JobList crashes
When navigating to `catalog/Component/backstage/ci-cd`, choosing a workflow that is "In Progress" and attempting to view the JobList the page crashes.
## Expected Behavior
Expected to either provide the list of jobs up to moment of retrieval or not allow expansion until completed. 

## Current Behavior
Currently the screen goes blank and several error are thrown in the console. 

## Steps to Reproduce

1. Navigate to BackStage component
2. Click on CI/CD
3. Choose a WorkFlow that is currently "In Progress"
4. Expand the Jobs Accordion element.

## Your Environment

- NodeJS Version (v12.16.1):
- Operating System and Version (macOS 10.15.6):
- Browser Information: Safari 14.0

### PR DESCRIPTION
**Pull request by freben**
Fixes #2949

### CODE REVIEW

File: plugins/github-actions/src/components/WorkflowRunDetails/WorkflowRunDetails.tsx [hunk 1]
```diff
@@ -108,7 +109,7 @@ const StepView = ({ step }: { step: Step }) => {
       <TableCell>
         <WorkflowRunStatus
           status={step.status.toUpperCase()}
-          conclusion={step.conclusion.toUpperCase()}
+          conclusion={step.conclusion?.toUpperCase()}
```
Comment (Rugvip) [inline plugins/github-actions/src/components/WorkflowRunDetails/WorkflowRunDetails.tsx:112]: Should update the type too right?

**Review by Rugvip — APPROVED** [review]

File: plugins/github-actions/src/components/WorkflowRunDetails/WorkflowRunDetails.tsx (hunk 1 above)
Comment (freben) [reply plugins/github-actions/src/components/WorkflowRunDetails/WorkflowRunDetails.tsx:112]: done! good idea
