### PR TITLE
fix: distributed actions visibility in scaffolder

### LINKED ISSUE #31187: Actions registry actions not visible in scaffolder
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
scaffolder actions registry
```

### 🗃️ Project Area

Software Templates

### 🔗 External Integration

N/A

### 📝 Description & Context

Actions registered to `actionsRegistryService` are not visible in available actions list in scaffolder (/create/actions list)

### 👍 Expected Behavior

Actions should be visible in the list

### 📦 Reproduction Repo

_No response_

### 🥾 Reproduction steps

1. Go to /create/actions
2. Search for get-entities action registered by the catalog backend

Reproducable also on demo site

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Undecided

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

depending on the plugin startup order, some distributed actions might not be available when the scaffolder backend starts. this was mentioned in the comment that is now removed. while this might change in the future, this would patch the current way the distributed actions are fetched.

related #31213 and #31207

closes #31187

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by drodil** [comment]
@benjdlambert another try! Thanks for the cleanup, much easier now :)

File: plugins/scaffolder-backend/src/scaffolder/actions/TemplateActionRegistry.ts [hunk 1]
```diff
@@ -16,13 +16,39 @@
...
+import { isPlainObject } from 'lodash';
+import { Schema } from 'jsonschema';
+import { JsonObject } from '@backstage/types';
+
+/**
+ * @internal
+ */
+export interface TemplateActionRegistry {
+  register(action: TemplateAction<any, any, any>): void;
+  get(actionId: string): Promise<TemplateAction<any, any, any>>;
```
Comment (benjdlambert) [inline plugins/scaffolder-backend/src/scaffolder/actions/TemplateActionRegistry.ts]: Thinking that `get` should also have `{ credentials }`. It's going to lead to some funky behavior possibly when permissions comes along.

That way I think we can cleanup the `await auth.getOwnServiceCredentials()` everywhere as they should all be request driven AFAIK.

Comment (drodil) [reply plugins/scaffolder-backend/src/scaffolder/actions/TemplateActionRegistry.ts]: Hm, maybe, but that's going to spread _a lot_ since the only usage for this function is in the `NunjucksWorkflowRunner` and it has no clue about the credentials when calling that. It would mean changing all the steps in between, meaning `TaskWorker`, `TaskContext`, and most importantly, `TaskBroker`, which again means public API changes. 

Wouldn't it be enough that the action is invoked as the calling user? It might have some funky behaviour indeed 🤔

Comment (benjdlambert) [reply plugins/scaffolder-backend/src/scaffolder/actions/TemplateActionRegistry.ts]: Hm the `NunjucksWorkflowRunner` already has access to this though.

`this.options.actionRegistry.get(step.action, { credentials: task.getInitiatorCredentials())` should do it.

Comment (drodil) [reply plugins/scaffolder-backend/src/scaffolder/actions/TemplateActionRegistry.ts]: Damn, missed that! I will use it

**Comment by drodil** [comment]
Not stale, needs another round
