### PR TITLE
TechDocs Backend: Replace hardcoded github api by configuration value

### LINKED ISSUE #2988: TechDocs Backend: Hardcoded Github URL
The TechDocs backend plugin does not use the configured `apiBaseUrl` instead, it is hardcoded to `api.github.com` which makes it impossible to fetch data from private GitHub (like Github Enterprise)

## Expected Behavior
Use `apiBaseUrl` from the configuration reader. https://github.com/spotify/backstage/blob/master/app-config.yaml#L77

## Current Behavior
It is hardcoded to `api.github.com` and builds a connection to the wrong GitHub. https://github.com/spotify/backstage/blob/master/plugins/techdocs-backend/src/default-branch.ts#L47

## Possible Solution
Pass `config` as an additional parameter and read the property form there.

## Steps to Reproduce

1. Add a private GitHub configuration on config.yaml
2. Try to fetch any sort of information from your private GitHub (like catalog-info.yaml)
3. Debug for hours to figure out the issue.

## Context
Trying to build the connection to our private GitHub to enable the Techdocs plugin to read documentations from our repositories.

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 18.04):
- Browser Information: Chrome

### PR DESCRIPTION
**Pull request by roflc0pter**
Fixes: https://github.com/spotify/backstage/issues/2988

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/spotify/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Review by emmaindal — APPROVED** [review]
LGTM, thanks 😄

File: plugins/techdocs-backend/src/default-branch.ts [hunk 1]
```diff
@@ -42,9 +42,11 @@ interface IGitlabBranch {
   };
 }
 
-function getGithubApiUrl(url: string): URL {
+function getGithubApiUrl(config: Config, url: string): URL {
   const { protocol, owner, name } = parseGitUrl(url);
-  const apiBaseUrl = 'api.github.com';
+  const apiBaseUrl =
+    config.getOptionalString('catalog.processors.github.apiBaseUrl') ||
```
Comment (freben) [inline plugins/techdocs-backend/src/default-branch.ts:48]: This is the old deprecated location. These are now under `integrations` (see the app-config in master for examples)

Comment (roflc0pter) [reply plugins/techdocs-backend/src/default-branch.ts]: Updated :)

**Review by hooloovooo — APPROVED** [review]
