### PR TITLE
fix(catalog-backend): unify github and github/api, and use git-url-parse

### LINKED ISSUE #2506: Register existing component fails when adding an internal repository via GitHub API
Screen Shot 2020-09-17 at 2 06 29 PM

## Expected Behavior

I would like to be able to add a project that's internal to an enterprise organization to Backstage via "Register existing component" 

## Current Behavior

I get the following error attempting to register the component.

```
InputError: Failed to read location github https://github.com/<enterprise_org>/pulse-documentation/blob/master/component-info.yaml, NotFoundError: https://github.com/resideo/pulse-documentation/blob/master/component-info.yaml could not be read as https://raw.githubusercontent.com/<enterprise_org>/pulse-documentation/master/component-info.yaml, 404 Not Found at HigherOrderOperations.addLocation (/Users/tarasmankovski/Projects/pulse/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:543:13) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async /Users/tarasmankovski/Projects/pulse/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:1472:22
```

## Possible Solution

I did some digging. It looks like the problem is caused by the wrong processor being used to handle submission to 
`/register-component`. 

The request includes the following payload: `{"type":"github","target":"https://github.com/resideo/pulse-documentation/blob/master/component-info.yaml"}` which specifies type as "github" instead of "github/api".

We should determine the type on the backend rather than the frontend.

## Steps to Reproduce

1. Try to add a component from an internal repository of a GitHub enterprise organization

## Context

*How has this issue affected you?*

I believe this problem affects both "register component" and scaffolder. When scaffolder is used to add to an enterprise organization the component is not added to list of components.

## Your Environment

- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu
- Browser Information: Chrome

### PR DESCRIPTION
**Pull request by freben**
This removes the separation between GithubApiReaderProcessor and GithubReaderProcessor, unifying them. It supports both API and raw reading, with and without tokens. The bump of git-url-parse is only because there's another PR in the pipe that just bumps that out of necessity, so, avoiding clashes :)

For backwards compatibility it tries to read both the old and new config keys, and supports both location types.

### CODE REVIEW

**Review by OrkoHunter — APPROVED** [review]

**Comment by benjdlambert** [comment]
Should we aim to deprecate one of the types in this next release too @freben? Maybe with a warning in the console when someone has a `github/api` location for instance?

File: plugins/catalog-backend/src/ingestion/processors/GithubReaderProcessor.ts [hunk 1]
```diff
@@ -15,50 +15,231 @@
...
+  const providers: ProviderConfig[] = [];
 
-    if (this.privateToken !== '') {
-      headers.Authorization = `token ${this.privateToken}`;
+  // In a previous version of the configuration, we only supported github,
+  // and the "privateToken" key held the token to use for it. The new
+  // configuration method is to use the "providers" key instead.
+  const providerConfigs =
+    config.getOptionalConfigArray('catalog.processors.github.providers') ??
+    config.getOptionalConfigArray('catalog.processors.githubApi.providers') ??
```
Comment (Rugvip) [inline plugins/catalog-backend/src/ingestion/processors/GithubReaderProcessor.ts:150]: Could we just throw an error explaining that it's been moved to `*.github.*` if `catalog.processors.githubApi.providers` exists? Makes it easier to remove in the future. Same with the ones below

Comment (freben) [reply plugins/catalog-backend/src/ingestion/processors/GithubReaderProcessor.ts:150]: Sure, because alpha? It's a bit jarring for those who already have it configured.

Comment (freben) [reply plugins/catalog-backend/src/ingestion/processors/GithubReaderProcessor.ts:150]: Warning as @blam says is a middle ground but I'm not sure who reads the log output carefully enough :)

Comment (Rugvip) [reply plugins/catalog-backend/src/ingestion/processors/GithubReaderProcessor.ts:150]: Yeah, I'd say the non-alpha thing to do would be a deprecation warning, which we could do, and then later move to an error.

It might be nicer in this case seeing as we're expecting people to be using the config that we're breaking. As long as we're providing a clear enough fix I don't think we'll waste anyone's time too much

**Comment by freben** [comment]
Put the deprecation warning in, and added changelog and relevant docs :) Do remember to pester me in reviews if I forget to do that again in the future!

**Review by benjdlambert — APPROVED** [review]
