### PR TITLE
user-settings: Always show Pin Sidebar and minor fixes

### LINKED ISSUE #4298: user-settings: Pin sidebar disappears on smaller screens
## Expected Behavior

In user settings, the _Pin sidebar_ configuration in the **Appearance** card should always be visible even if the screen width gets smaller.

## Current Behavior

On the user settings page, if you reduce the screen size so the two current cards - Profile and Appearance - stack one on top of the other, the "Pin sidebar" configuration element disappears.

**Full screen**
image

**Smaller screen** - where'd it go? 🔍 
image

## Possible Solution

Check and validate the Grid settings in the Appearance card.

## Steps to Reproduce

1. Visit settings page
2. See appearance card with Pin Sidebar
3. Reduce screen size until the profile and appearance cards stack on top of each other

## Context

All in all, a few elements on this pace seem to get partially hidden or move around a bit funny, so someone with a keen eye and knowledge of the MUI grid settings just might need to take a peek.

## Your Environment

- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909 WSL 2 Ubuntu 18.04
- Browser Information: Microsoft Edge (Chrome engine)

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

Closes #4298.

* Ensures the Pin sidebar button is always visible, even on smaller screens.
* Removes an extraneous `<Grid>` wrapper on the profile panel. (Seems it didn't even provide any additional white spacing or visual alignment.)
* Fixes typos in a hidden feature flag empty component I've never seen before. (since I always have feature flags, with cost-insights and welcome plugins!)

image

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

File: plugins/user-settings/src/components/General/Profile.tsx [hunk 1]
```diff
@@ -24,31 +24,27 @@ export const Profile = () => {
...
             </Grid>
           </Grid>
-        </InfoCard>
+          <Grid item>
+            <UserSettingsMenu />
+          </Grid>
+        </Grid>
       </Grid>
-    </Grid>
+    </InfoCard>
```
Comment (adamdmharvey) [inline plugins/user-settings/src/components/General/Profile.tsx:48]: this change is just the removal of the first two, and last two `<Grid>` elements, and then outdenting the rest of the code two places.

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
Nice!
