### PR TITLE
fix: todo-plugin ignores images and files that are bigger than/equal 200k

### LINKED ISSUE #5997: The TODO plugin cannot read most of our Gitlab repos
Hello, 
We installed the TODO plugins (both front-end and back-end plugins), but it only works well on a very small Gitlab project/repo. In most of our repos, it's loading forever with a loading spinner. 

I tried to debug this issue and inserted some logs in the source code. We found that the issue is from the GitlabUrlReader of the backend-common package. When calling the readTree method, the function is stuck when reading some image file or svg file. Sometimes it's also stuck on some other files.

Could anyone help on this? Thanks!

### PR DESCRIPTION
**Pull request by djamaile**
## Hey, I just made a Pull Request!

This fixes #5997 by ignoring images and files that are bigger than 200Kb

#### :heavy_check_mark: Checklist

- [x ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by djamaile** [comment]
Currently looking for feedback on this PR, especially the size check. Could also be that the size check might be out of scope for this issue. If so, let me know and I will remove it.

File: packages/backend-common/src/reading/tree/TarArchiveResponse.ts [hunk 1]
```diff
@@ -98,6 +98,11 @@ export class TarArchiveResponse implements ReadTreeResponse {
         }
       }
 
+      if (entry.size && entry.size >= 20000) {
```
Comment (Rugvip) [inline packages/backend-common/src/reading/tree/TarArchiveResponse.ts:101]: We can't do this for all readers, as it's used in places where you expect to get all files returned as well. We could pass the size in second `info` param in in the filter function though, allowing us to filter in the plugin.

File: plugins/todo-backend/src/lib/TodoReader/TodoScmReader.ts [hunk 2]
```diff
@@ -80,10 +81,25 @@ export class TodoScmReader implements TodoReader {
     { url }: ReadTodosOptions,
     etag?: string,
   ): Promise<CacheItem> {
+    const shouldNotInclude = [
```
Comment (Rugvip) [inline plugins/todo-backend/src/lib/TodoReader/TodoScmReader.ts:84]: Make this a constant at the top of the file instead, if you cba it would be nice to have this list configurable as part of the `TodoScmReader`, as a second `options` argument to `fromConfig`.

File: .changeset/mean-spiders-run.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/plugin-todo-backend': minor
```
Comment (Rugvip) [inline .changeset/mean-spiders-run.md:2]: Let's fit this into a non-breaking change, meaning a `patch` bump

**Review by Rugvip — COMMENTED** [review]
Thanks! The size check kinda makes sense but we need to move it out of the `backend-common` implementation as that's a shared facility.

**Comment by djamaile** [comment]
Hi, I can confirm that what @Jerry4013 is saying is working. Changing the gitlab reader from zip to tar would fix the issue. With that change I could read out the official gitlab repo in a minute or so. Do, you want me to include it in this MR? I was wondering if the extension skipper and size check are then still needed?

For the size check you want to move it out of the backend-common, where would you like define it then? For the excludedExtension constant you said you would like to have it part of the fromConfig function. Do you envision something like this:

```js
static fromConfig(config: Config, options: Omit<Options, 'integrations'>, skippedExtensions: Array<string>) {
    return new TodoScmReader({
      ...options,
      integrations: ScmIntegrations.fromConfig(config),
      skippedExtensions: ... // don't know yet from we should get the values
    });
  }
  
Let me know what you think.

**Comment by freben** [comment]
Hey @djamaile - there are a few comments remaining on refactoring this, but we are eager to get the contribution in. Will you have the time to make those changes?

**Comment by djamaile** [comment]
Hi @freben ! I have been a bit sick this week. I will be able to work on this at the end of the weekend. Feel free to merge @Jerry4013 PR, I can always rebase on top of it or we can close this if you feel it is needed anymore.

**Comment by freben** [comment]
Ah, hope you get better soon!

We'll probably want both - they help in different ways!

**Comment by freben** [comment]
Just a small ping - do you think you will have an opportunity to continue on this?

**Comment by Rugvip** [comment]
I took the liberty of refactoring this to try to get it across the line

File: packages/backend-common/src/reading/tree/TarArchiveResponse.ts [hunk 4]
```diff
@@ -43,7 +43,7 @@ export class TarArchiveResponse implements ReadTreeResponse {
     private readonly subPath: string,
     private readonly workDir: string,
     public readonly etag: string,
-    private readonly filter?: (path: string) => boolean,
+    private readonly filter?: (path: string, info: { size: number }) => boolean,
```
Comment (freben) [inline packages/backend-common/src/reading/tree/TarArchiveResponse.ts:46]:
```suggestion
    private readonly filter?: (path: string, info: { maxSize: number }) => boolean,
```

**Review by Rugvip — APPROVED** [review]
