### PR TITLE
TechDocs: Remove hardcoded backend URL from techdocs-backend

### LINKED ISSUE #3292: TechDocs has a hardcoded remoteUrl in LocalPublish
I'm not sure what problems this will cause, but I suspect nothing good can come out of hard coding the backend URL in https://github.com/backstage/backstage/blob/master/plugins/techdocs-backend/src/techdocs/stages/publish/local.ts#L67

## Expected Behavior

TechDocs should use `backend.baseUrl` instead of a hardcoded host.

## Current Behavior

It's hardcoded and I suspect would break when using anything other than `localhost:7000`

## Possible Solution

Use `backend.baseUrl`

## Steps to Reproduce

It's in the source code.

## Context

I just came across this by accident while implementing a workaround for #3290.

## Your Environment

- NodeJS Version (v12): 12
- Operating System and Version (e.g. Ubuntu 14.04): 18
- Browser Information: all

### PR DESCRIPTION
**Pull request by OrkoHunter**
Closes #3292

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

File: packages/backend/src/plugins/techdocs.ts [hunk 1]
```diff
@@ -50,7 +50,7 @@ export default async function createPlugin({
   const urlPreparer = new UrlPreparer(reader, logger);
   preparers.register('url', urlPreparer);
 
-  const publisher = new LocalPublish(logger);
+  const publisher = new LocalPublish(logger, config);
```
Comment (freben) [inline packages/backend/src/plugins/techdocs.ts:53]: You want to inject `discovery` here instead of config, and look up `"techdocs"` using that!

Comment (OrkoHunter) [reply packages/backend/src/plugins/techdocs.ts:53]: Ah! Thanks.

It does make sense to use `discovery.getBaseUrl("techdocs")` to get the baseUrl for TechDocs. :)

File: plugins/techdocs-backend/src/techdocs/stages/publish/local.test.ts [hunk 2]
```diff
@@ -37,7 +38,21 @@ const logger = getVoidLogger();
...
+        data: {
+          backend: {
+            baseUrl: 'http://localhost:7000',
+            listen: {
+              port: 7000,
+            },
+          },
+        },
+      },
+    ]);
```
Comment (OrkoHunter) [inline plugins/techdocs-backend/src/techdocs/stages/publish/local.test.ts:53]: Could this be part of `@backstage/test-utils` package i.e. to get a "default" config for testing purposes?
(Maybe there is, already)

**Review by hooloovooo — APPROVED** [review]
Don't know much about how to use the discovery api, but looks good to me!

File: plugins/techdocs-backend/package.json [hunk 3]
```diff
@@ -23,6 +23,7 @@
     "@backstage/backend-common": "^0.2.0",
     "@backstage/catalog-model": "^0.2.0",
     "@backstage/config": "^0.1.1",
+    "@backstage/core-api": "^0.2.1",
```
Comment (freben) [inline plugins/techdocs-backend/package.json:26]: i think this snuck in accidentally

File: plugins/techdocs-backend/src/techdocs/stages/publish/local.test.ts (hunk 2 above)
Comment (freben) [reply plugins/techdocs-backend/src/techdocs/stages/publish/local.test.ts:53]: No, I'd just make a mock `SingleHostDiscovery` instead.

File: plugins/techdocs-backend/src/techdocs/stages/publish/local.ts [hunk 4]
```diff
@@ -18,12 +18,15 @@ import { Logger } from 'winston';
 import { Entity } from '@backstage/catalog-model';
 import { PublisherBase } from './types';
 import { resolvePackagePath } from '@backstage/backend-common';
+import { DiscoveryApi } from '@backstage/core-api';
```
Comment (freben) [inline plugins/techdocs-backend/src/techdocs/stages/publish/local.ts:21]: yeah this should instead be the `SingleHostDiscovery`, it's a bit confusing but what you are importing here is a frontend corresponding thing, not the backend one, they happen to have the same signature

File: plugins/techdocs-backend/src/techdocs/stages/publish/local.ts [hunk 5]
```diff
@@ -63,8 +66,10 @@ export class LocalPublish implements PublisherBase {
           reject(err);
         }
 
-        resolve({
-          remoteUrl: `http://localhost:7000/api/techdocs/static/docs/${entity.metadata.name}`,
+        this.discoveryApi.getBaseUrl('techdocs').then(techdocsApiUrl => {
+          resolve({
+            remoteUrl: `${techdocsApiUrl}/static/docs/${entity.metadata.name}`,
+          });
```
Comment (freben) [inline plugins/techdocs-backend/src/techdocs/stages/publish/local.ts:72]: maybe a bit of a nit but what if the getBaseUrl fails :) you should probably have a reject then

File: yarn.lock [hunk 6]
```diff
@@ -1290,40 +1290,34 @@
     to-fast-properties "^2.0.0"
 
 "@backstage/core@^0.2.0":
-  version "0.3.0"
+  version "0.2.0"
```
Comment (freben) [inline yarn.lock:1293]: whoa this also probably was an accident

File: plugins/techdocs-backend/src/techdocs/stages/publish/local.test.ts (hunk 2 above)
Comment (OrkoHunter) [reply plugins/techdocs-backend/src/techdocs/stages/publish/local.test.ts:53]: @freben Do you mean something like this -

```
const mockDiscovery = new SingleHostDiscovery(mockInternalBaseUrl, mockInternalBaseUrl)
```

Looks like I can't create a mock `SingleHostDiscovery` like this since the constructor is private. And I have to rely on its static `fromConfig` method.

File: plugins/techdocs-backend/package.json (hunk 3 above)
Comment (OrkoHunter) [reply plugins/techdocs-backend/package.json:26]: I had to add `@backstage/core-api` for the `DisoveryApi` bit. But will revert this and `yarn.lock` changes :)

File: plugins/techdocs-backend/src/techdocs/stages/publish/local.test.ts (hunk 2 above)
Comment (freben) [reply plugins/techdocs-backend/src/techdocs/stages/publish/local.test.ts:53]: More like `const disc: jest.Mocked<SingleHostDiscovery> = { resolve: jest.fn() };` and then in your tests do `disc.resolve.mockReturnResolvedValueOnce('http://blah')` (all of this typed out without any testing so the names and stuff may be way off)

File: plugins/techdocs-backend/src/techdocs/stages/publish/local.ts (hunk 4 above)
Comment (OrkoHunter) [reply plugins/techdocs-backend/src/techdocs/stages/publish/local.ts]: Done! And thanks for letting me know about the two. :)

The `discovery` that `createPlugin` passes to techdocs-backend is of the type `PluginEndpointDiscovery` which is just an implementation of `SingleHostDiscovery`.

File: plugins/techdocs-backend/src/techdocs/stages/publish/local.test.ts (hunk 2 above)
Comment (OrkoHunter) [reply plugins/techdocs-backend/src/techdocs/stages/publish/local.test.ts]: aha! Yes, ofcourse. Thank you for this too.

**Review by freben — APPROVED** [review]
