### PR TITLE
scaffolder: Support conditional `if` on output links and text

### LINKED ISSUE #24805: 🐛 Bug Report: Scaffolder template - If statement in output spec no applied
### 📜 Description

In the `output` field of the template `spec`, `if` statement are not applied:
```
output:
    links:
      - if: ${{ parameters.CI === "Yes" }}
        title: Title
        url: URL
```

With the above spec, the link is always displayed even if CI is not equal to `Yes`

### 👍 Expected behavior

THe `if` statement should be matched and the `link` should only be applied/displayed if the condition matches

### 👎 Actual Behavior with Screenshots

The `link` is displayed no matter if the condition is matched.

### 👟 Reproduction steps

Create a template with the following or similar `output` spec:
```
output:
    links:
      - if: ${{ parameters.CI === "Yes" }}
        title: Title
        url: URL
```

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by gusevda**
## Hey, I just made a Pull Request!

Adds support for `if` conditions on scaffolder template output `links` and `text` items, matching the existing `if` behavior on steps. This allows template authors to conditionally show/hide output items based on parameters.

Resolves #24805

**Example usage:**
```yaml
output:
  links:
    - title: Always visible
      url: https://example.com
    - if: ${{ parameters.enableCI === "Yes" }}
      title: CI Dashboard
      url: https://ci.example.com
  text:
    - if: ${{ parameters.showDetails }}
      title: Details
      content: "Some details..."
```

**Changes:**
- Added `if` property to `ScaffolderOutputLink` and `ScaffolderOutputText` types (`@backstage/plugin-scaffolder-common`)
- Added `if` to the Template v1beta3 JSON schema for link and text items
- Added post-render filtering in `NunjucksWorkflowRunner` using the existing `isTruthy` helper (same semantics as step `if`)
- Strips the `if` field from output items before sending to the frontend
- Added tests covering all conditional scenarios
- Added a sample template demonstrating the feature

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/scaffolder-backend/src/scaffolder/tasks/helper.ts [hunk 1]
```diff
@@ -29,6 +34,28 @@ export function isTruthy(value: any): boolean {
...
+  return items
+    .filter(item => {
+      if (!isPlainObject(item)) return true;
+      return !('if' in item) || isTruthy(item.if);
+    })
+    .map(item => {
+      if (!isPlainObject(item)) return item;
+      const { if: _if, ...rest } = item;
+      return rest;
+    });
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/tasks/helper.ts]: you can replace this with a single `flatMap`, so we can skip some duplication

File: plugins/scaffolder-backend/src/scaffolder/tasks/helper.ts [hunk 2]
```diff
@@ -29,6 +34,28 @@ export function isTruthy(value: any): boolean {
...
+function isPlainObject(item: JsonValue): item is JsonObject {
+  return typeof item === 'object' && item !== null && !Array.isArray(item);
+}
+
+/**
+ * Filters an output array by evaluating the `if` condition on each item,
+ * and strips the `if` field from items that pass. Non-plain-object items
+ * are passed through unchanged.
+ */
+export function filterConditionalItems(items: JsonArray): JsonArray {
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/tasks/helper.ts]: does the input/output have to be `JsonArray`? Could make this `filterConditionalItems<T>(items: readonly T[]): T[]` which would let you skip the `as JsonArray` casts in the other file.

**Comment by gusevda** [comment]
Thanks for the review! @freben, I addressed both suggestions in 3a3d36131cbed9610dd7055499880e0fff4235ce

**Comment by gusevda** [comment]
@freben Just checking in - I addressed your two suggestions in https://github.com/backstage/backstage/commit/3a3d36131cbed9610dd7055499880e0fff4235ce. Could you take another look when you get a chance? Thanks!
