### PR TITLE
Link components to the location that created them

### LINKED ISSUE #771: catalog backend: implement refresh loops
Implement the logic of the backend service that keeps components refreshed from descriptor files in a version control system.

## Background

The corresponding service at Spotify stores the latest known good version of component files in a data store, and continuously attempts to refresh them with new data from our GitHub Enterprise, via polling. It also keeps track of the current status of this refresh loop per component, along with errors encountered. This status is part of the response when fetching components.

The first version of the catalog service will do the same. Push based or event triggered updates will come later.

## Some Questions

- As a location is registered, shall an initial refresh attempt be made, and the location registration fail if the refresh fails?
- How will later failed refreshes be handled? What metadata about the errors shall we store and how are they communicated to callers or component owners?
- What version control systems shall we support? Presumably at the very least github and gitlab. Shall this be pluggable?
- How shall we handle authentication for requesting data from the version control system? Can we initially use `/raw/` or similar browser endpoints, or should we for example require that the user supply a dev token to pass to API calls?
- How shall we handle rate limits and other exceptional states when doing refreshes?

### PR DESCRIPTION
**Pull request by freben**
#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

File: packages/backend/src/index.ts [hunk 1]
```diff
@@ -41,14 +41,16 @@ const DEFAULT_PORT = 7000;
...
-      useNullAsDefault: true,
-    }),
-  };
+  const logger = getRootLogger().child({ type: 'plugin', plugin });
+  const database = knex({
+    client: 'sqlite3',
+    connection: ':memory:',
+    useNullAsDefault: true,
+  });
+  database.client.pool.on('createSuccess', (_eventId: any, resource: any) => {
```
Comment (marcuseide) [inline packages/backend/src/index.ts:50]: Maybe it's worth breaking the database creation out into a seperate function? That could also be used in tests.

File: plugins/catalog-backend/src/catalog/DatabaseCatalog.ts [hunk 2]
```diff
@@ -44,15 +45,27 @@ export class DatabaseCatalog implements Catalog {
...
     await this.database.transaction(async (tx) => {
-      await tx('components')
-        .insert(component)
-        .catch(() =>
-          tx('components').where({ name: component.name }).update(component),
-        );
+      // TODO(freben): Currently, several locations can compete for the same component
+      const count = await tx('components')
+        .where({ name: component.name })
+        .update({ ...component, locationId });
```
Comment (marcuseide) [inline plugins/catalog-backend/src/catalog/DatabaseCatalog.ts:60]: I'm assuming the order, first `update` then `insert` doesn't really matter? Or is one more common then the other?

File: plugins/catalog-backend/src/migrations/20200511113813_init.ts [hunk 3]
```diff
@@ -27,7 +30,19 @@ export async function up(knex: Knex): Promise<any> {
         .comment('The actual target of the location');
     })
     .createTable('components', (table) => {
-      table.string('name').primary().comment('The name of the component');
+      table.comment('All components currently stored in the catalog');
+      table.uuid('id').primary().comment('Auto-generated ID of the component');
+      table
+        .uuid('locationId')
+        .references('id')
```
Comment (marcuseide) [inline plugins/catalog-backend/src/migrations/20200511113813_init.ts:37]: 👍

**Review by marcuseide — APPROVED** [review]

File: packages/backend/src/index.ts (hunk 1 above)
Comment (freben) [reply packages/backend/src/index.ts:50]: Maybe soon - this is not really production code anyway, it's here temporarily for the in memory database until we actually start talking to postgres.

File: plugins/catalog-backend/src/catalog/DatabaseCatalog.ts (hunk 2 above)
Comment (freben) [reply plugins/catalog-backend/src/catalog/DatabaseCatalog.ts:60]: Either could work, but since updates will be way more common than inserts, it's better to treat that as the default case.

Plus, if I do insert first, then it's an exception (key violation) that one handles, so it felt less violent to just try to update first and then insert if the first thing did nothing :)

File: packages/backend/src/index.ts (hunk 1 above)
Comment (Rugvip) [reply packages/backend/src/index.ts:50]: `backend-test-utils` inc

**Review by Rugvip — APPROVED** [review]
