### PR TITLE
fix(catalog-backend): limit search value lengths

### LINKED ISSUE #2835: Using PostgreSQL for development causes error
https://github.com/spotify/backstage/commit/28793b502cdeb048b12a28c96834da3fff940c31 was failing to start backend server in development. This might have been overlooked if you're using PostgreSQL in development.

## Expected Behavior

Should be able to use Backstage in development with PostgreSQL.

## Current Behavior

image

## Possible Solution

@Rugvip suggested that it might be "related to the recent DB schema changes". 

## Steps to Reproduce

1. Configure your local development instance to use PostgreSQL
2. Run `yarn start-backend` 
3. 💥 

## Context

I was using PostgreSQL for development but switched to sqlite for now.

### PR DESCRIPTION
**Pull request by freben**
Fixes #2835 

Note that I did NOT add a migration step that does SUBSTR on the value column, because at that point it would already be too late (the error happens in an earlier migration step). Unfortunately users will have to patch their value columns manually if they encounter this error.

### CODE REVIEW

File: plugins/catalog-backend/src/database/search.ts [hunk 1]
```diff
@@ -28,12 +28,19 @@ const SPECIAL_KEYS = [
...
+
+// Takes any value from an object and turns it into a value string for the
+// search table
 function toValue(current: any): string | null {
   if (current === undefined || current === null) {
     return null;
   }
 
-  return String(current).toLowerCase();
+  return String(current).toLowerCase().substr(0, MAX_VALUE_LENGTH);
```
Comment (Rugvip) [inline plugins/catalog-backend/src/database/search.ts:43]: Thoughts on just throwing away too large values instead of truncating?

Comment (freben) [reply plugins/catalog-backend/src/database/search.ts:43]: Yeah considered it. Thought maybe the data (if using wildcards) could be useful, buuut... Whatever we do I guess it's gonna be potentially surprising either way

Comment (Rugvip) [reply plugins/catalog-backend/src/database/search.ts:43]: Tbh I'm thinking we should not index any fields that could contain any large values, and then just make it a hard error causing the processing to fail

Comment (freben) [reply plugins/catalog-backend/src/database/search.ts:43]: I kinda agree. Won't introduce any knowledge of what fields to include / exclude though, I'll just make it skip above a certain length

Comment (freben) [reply plugins/catalog-backend/src/database/search.ts]: @Rugvip OK this turned into a bit of a refactor where the raw extraction is in one place, row forming (with lowercase and length limit logic) in one place, and the entity structure knowledge in a third place.

File: plugins/catalog-backend/src/database/search.ts [hunk 2]
```diff
@@ -28,16 +28,18 @@ const SPECIAL_KEYS = [
...
+// The maximum length allowed for search values. These columns are indexed, and
+// database engines do not like to index on massive values. For example,
+// postgres will balk after 8191 byte line sizes.
+const MAX_VALUE_LENGTH = 200;
 
-  return String(current).toLowerCase();
-}
+type Kv = {
+  key: string;
+  value: any;
```
Comment (Rugvip) [inline plugins/catalog-backend/src/database/search.ts:38]: `unknown` is better if it works

**Review by Rugvip — APPROVED** [review]

File: plugins/catalog-backend/src/database/search.ts (hunk 2 above)
Comment (freben) [reply plugins/catalog-backend/src/database/search.ts:38]: ah yeah totally, fixed

Comment (freben) [reply plugins/catalog-backend/src/database/search.ts:38]: wuuut i did a derpo, will have to put it in the next pr
