### PR TITLE
fix(plugins/tech-radar): list rerenders on hover

### LINKED ISSUE #13831: Tech Radar: Quadrant list of technologies scroll position resets on mouse move
## Expected Behavior

When there are enough technologies in a quadrant to introduce a scroll bar, you should be able to hover over entries "below the fold" (that you have to scroll down to see) and not have the scroll position reset.

## Actual Behavior

Any mouse movements that cause the entry in the radar itself to change focus resets the quadrant scroll position

## Steps to Reproduce

Example video: https://imgur.com/a/WoLlJKT

1. Create a Tech Radar
2. Add enough entries to a quadrant to introduce a scroll bar
3. Scroll down in the quadrant and move your mouse a little in any direction

## Context

This makes using the Tech Radar with many entries very difficult. The list of technologies is essentially unusable.

## Your Environment

N/A I'm using a hosted instance from Roadie

- Browser Information: Google Chrome Version 105.0.5195.102

- Output of yarn backstage-cli info: N/A I'm using a hosted instance from Roadie

### PR DESCRIPTION
**Pull request by marcofaggian**
Signed-off-by: marcofaggian <m@marcofaggian.com>

## Hey, I just made a Pull Request!

Fixes #13831

### Work done:

- Rework the Radar component and it's utils to an "immutable" data management (to avoid side effects)
- Refactor RadarLegend in its single components.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/tech-radar/src/components/Radar/Radar.tsx [hunk 1]
```diff
@@ -28,27 +28,53 @@ export type Props = {
...
   const [activeEntry, setActiveEntry] = useState<Entry>();
   const node = useRef<SVGSVGElement>(null);
 
-  // TODO(dflemstr): most of this can be heavily memoized if performance becomes a problem
-  adjustQuadrants(quadrants, radius, width, height);
-  adjustRings(rings, radius);
-  adjustEntries(entries, quadrants, rings, radius, activeEntry);
+  useEffect(() => {
+    setAdjustedQuadrants(adjustQuadrants(quadrants, radius, width, height));
+  }, [quadrants, radius, width, height]);
```
Comment (Rugvip) [inline plugins/tech-radar/src/components/Radar/Radar.tsx:51]: I think all of these can be refactored into `useMemo` instead. The combination of a plain `useEffect` + `useState` is usually something you want to avoid. Probably want to merge them all into a single one as well

File: plugins/tech-radar/src/components/Radar/utils.ts [hunk 2]
```diff
@@ -81,30 +81,33 @@ export const adjustQuadrants = (
     },
   ];
 
-  quadrants.forEach((quadrant, index) => {
+  return quadrants.slice().map((quadrant, index) => {
```
Comment (Rugvip) [inline plugins/tech-radar/src/components/Radar/utils.ts:84]: No need to slice here

File: plugins/tech-radar/src/components/Radar/utils.ts [hunk 3]
```diff
@@ -81,30 +81,33 @@ export const adjustQuadrants = (
...
+      legendY: legendParam.y,
+      legendWidth: legendParam.width,
+      legendHeight: legendParam.height,
+    };
   });
 };
 
 export const adjustEntries = (
-  entries: Entry[],
+  _entries: Entry[],
```
Comment (Rugvip) [inline plugins/tech-radar/src/components/Radar/utils.ts:103]: `_` is used to indicate an unused parameter. Stick to `entries` and use a different name for the internal var instead

File: plugins/tech-radar/src/components/Radar/utils.ts [hunk 4]
```diff
@@ -160,13 +167,14 @@ export const adjustEntries = (
...
-    ring.index = index;
-    ring.outerRadius = ((index + 2) / (rings.length + 1)) * radius;
-    ring.innerRadius =
-      ((index === 0 ? 0 : index + 1) / (rings.length + 1)) * radius;
-  });
+  return entries;
 };
+
+export const adjustRings = (rings: Ring[], radius: number) =>
+  rings.slice().map((ring, index) => ({
```
Comment (Rugvip) [inline plugins/tech-radar/src/components/Radar/utils.ts:175]: No need to slice here

**Review by Rugvip — CHANGES_REQUESTED** [review]
Thank you! 🎉 

Couple of extra tweaks, nice to get this refactor done 👍

**Review by Rugvip — APPROVED** [review]
Nice, thank you! 👍 🎉 

Gonna schedule this for merge after the next main-line release next Tuesday, as it's a fairly substantial change that I think could use some time to settle.

**Comment by suuus** [comment]
Thank you for contributing during Hacktoberfest 🍂! You can claim the Backstage Hacktoberfest Holopin at https://bck.st/hacktoberfest-holopin 🙌🏻
