### PR TITLE
More descriptive error messages when trying to create a component from invalid backstage.yaml config file

### LINKED ISSUE #2405: Unreadable error message when trying to create a component from invalid backstage.yaml config file
If in the default catalog file (backstage.yaml) exist any annotation that has value other than string, error occures during component creation. It's due to the architecture decision described here https://github.com/spotify/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md.

repro

## Expected Behavior

Instead of `Error: x: "y" is not valid at HigherOrderOperations.addLocation` there should be more descriptive error, for example "Error: values other than string are not valid for an annotation. To learn more about catalog file format visit https://github.com/spotify/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md"

## Current Behavior

The error message being displayed looks like that:

> InputError: Failed to read location github https://github.com/mcalus3/sample-service/blob/invalid-config-reproduction/backstage.yaml, Error: Processor EntityPolicyProcessor threw an error while processing entity at github https://github.com/mcalus3/sample-service/blob/invalid-config-reproduction/backstage.yaml, Error: annotations.cloud.google.com/function-ids "projects/backstage-test-project/locations/us-central1/functions/helloMarek,projects/backstage-test-project/locations/us-central1/functions/helloWorld,projects/backstage-test-project2/locations/us-central1/functions/helloMarek,projects/backstage-test-project2/locations/us-central1/functions/helloWorld" is not valid at HigherOrderOperations.addLocation (webpack-internal:///../../plugins/catalog-backend/src/ingestion/HigherOrderOperations.ts:89:13) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async eval (webpack-internal:///../../plugins/catalog-backend/src/service/router.ts:98:22)

## Steps to Reproduce

1. In Component Catalog click "create component" button
2. Click "register existing component" button
3. Paste component file url https://github.com/mcalus3/sample-service/blob/invalid-config-reproduction/backstage.yaml and click "submit" button

## Context

It does not block me because I can still insert a list of elements as a comma delimited strings, although making the possibility to make annotation a list would surely improve the readability. For future users it certainly would be more helpful to see the errors about invalid catalog file format.

## Your Environment

- [not relevant]

### PR DESCRIPTION
**Pull request by erictnilsson**
## Hey, I just made a Pull Request!
Resolves #2405 
If the component-info.yaml file isn't valid when registering a new component, the error message is now more descriptive by  stating what field is invalid and why, whilst also referring to the docs. Bits of the stack trace is cut in favour of readability but it is untouched in the logs for the sake of debugging. 

The error messages that are shown are taken from the [docs](https://github.com/spotify/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md) except for fields that need valid a prefix and/or suffix since I felt the rules are too long. Let me know if you disagree!

Screenshot of different scenarios: 
Screenshot 2020-10-22 at 10 54 05
Screenshot 2020-10-22 at 10 49 04
Screenshot 2020-10-22 at 10 37 06
Screenshot 2020-10-22 at 10 36 54
 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/spotify/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

File: packages/catalog-model/src/entity/policies/FieldFormatEntityPolicy.ts [hunk 1]
```diff
@@ -50,7 +50,43 @@ export class FieldFormatEntityPolicy implements EntityPolicy {
       }
 
       if (!isValid) {
-        throw new Error(`${field} "${value}" is not valid`);
+        let expectation;
+        switch (validator.name) {
```
Comment (freben) [inline packages/catalog-model/src/entity/policies/FieldFormatEntityPolicy.ts:54]: bit of a stretch perhaps but to make this typesafe, you could do 

```ts
        switch (
          validator.name as
            | keyof typeof KubernetesValidatorFunctions
            | keyof typeof CommonValidatorFunctions
        ) {
 ```

:)

**Review by freben — APPROVED** [review]
Cool, just nits. I think these are due for a rewrite such that each validator throws its own error message instead, but that's for a later time.

File: packages/catalog-model/src/entity/policies/FieldFormatEntityPolicy.ts (hunk 1 above)
Comment (erictnilsson) [reply packages/catalog-model/src/entity/policies/FieldFormatEntityPolicy.ts:54]: > Cool, just nits. I think these are due for a rewrite such that each validator throws its own error message instead, but that's for a later time.

Yes! That was my initial plan but since i'm still a greenhorn in the OSS community I didn't want to muck around too much :P played it safe!

Comment (erictnilsson) [reply packages/catalog-model/src/entity/policies/FieldFormatEntityPolicy.ts:54]: > bit of a stretch perhaps but to make this typesafe, you could do
> 
> ```ts
>         switch (
>           validator.name as
>             | keyof typeof KubernetesValidatorFunctions
>             | keyof typeof CommonValidatorFunctions
>         ) {
> ```
> 
> :)

good catch! I'll implement it. Also felt that my switch was a bit sloppy

**Review by benjdlambert — APPROVED** [review]
