### PR TITLE
fix: adds pagetheme colors

### LINKED ISSUE #5235: APIs always has same pageTheme as home
the apis pageTheme is hardcoded linked to the home pageTheme.

## Expected Behavior

apis has a different pageTheme as home.

## Current Behavior

apis has the same pageTheme as home.

## Possible Solution

https://github.com/backstage/backstage/blob/master/plugins/api-docs/dev/index.tsx#L67 > theme is hardcoded set to `home`. 

It needs to have its own theme; e.g. `apis`

https://github.com/backstage/backstage/blob/master/packages/theme/src/pageTheme.ts#L65

A new theme needs to be defined here

## Steps to Reproduce

- Navigate to the default route; observe the page theme.
- Navigate to APIs; observe the page theme is the same as home

This is in every backstage implementation.

## Context

When configuring theme overrides, it is impossible to override the theme so that the apis pageTheme is different from home.

## Your Environment

- NodeJS Version (v12): v14.15.1
- Operating System and Version (e.g. Ubuntu 14.04): macos
- Browser Information: n/a

### PR DESCRIPTION
**Pull request by rkristelijn**
closes #5235

Signed-off-by: Remi Kristelijn <remi.kristelijn@theapsgroup.com>

## Hey, I just made a Pull Request!

This will add undocumented pageThemes and makes it able to overwrite it. This is documented in both the docs and storybook

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info] (https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: packages/theme/src/pageTheme.ts [hunk 1]
```diff
@@ -63,4 +63,9 @@ export const pageTheme: Record<string, PageTheme> = {
   library: genPageTheme(colorVariants.rubyRed, shapes.wave),
   other: genPageTheme(colorVariants.darkGrey, shapes.wave),
   app: genPageTheme(colorVariants.toastyOrange, shapes.wave),
+  apis: genPageTheme(colorVariants.eveningSea, shapes.wave2),
+  grpc: genPageTheme(colorVariants.marineBlue, shapes.wave2),
```
Comment (Rugvip) [inline packages/theme/src/pageTheme.ts:67]: Let's skip the themes for the specific API types for now, sticking to just adding the `apis` theme.

File: .changeset/thirty-owls-lay.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+'@backstage/core': patch
+'storybook': patch
```
Comment (Rugvip) [inline .changeset/thirty-owls-lay.md:3]: No need to include storybook in the changeset

File: .changeset/thirty-owls-lay.md [hunk 3]
```diff
@@ -0,0 +1,6 @@
...
+---
+
+exposes undocumented PageTheme
```
Comment (Rugvip) [inline .changeset/thirty-owls-lay.md:6]: Make `PageTheme` an inline code block, that way it doesn't need to be added to vocab

**Review by Rugvip — COMMENTED** [review]
Thanks! 👍

File: packages/theme/src/pageTheme.ts (hunk 1 above)
Comment (rkristelijn) [reply packages/theme/src/pageTheme.ts:67]: done

File: .changeset/thirty-owls-lay.md (hunk 2 above)
Comment (rkristelijn) [reply .changeset/thirty-owls-lay.md]: done

File: .changeset/thirty-owls-lay.md (hunk 3 above)
Comment (rkristelijn) [reply .changeset/thirty-owls-lay.md]: done

File: docs/getting-started/app-custom-theme.md [hunk 4]
```diff
@@ -74,3 +74,64 @@ Note that your list of custom themes overrides the default themes. If you still
...
+  pageTheme: {
+    home: genPageTheme(['#123456','#123456'], shapes.wave),
+    documentation: genPageTheme(['#123456','#123456'], shapes.wave2),
+    tool: genPageTheme(['#123456','#123456'], shapes.round),
+    service: genPageTheme(['#123456','#123456'], shapes.wave),
+    website: genPageTheme(['#123456','#123456'], shapes.wave),
+    library: genPageTheme(['#123456','#123456'] shapes.wave),
+    other: genPageTheme(['#123456','#123456'], shapes.wave),
+    app: genPageTheme(['#123456','#123456'], shapes.wave),
+    apis: genPageTheme(['#123456','#123456'],
```
Comment (Rugvip) [inline docs/getting-started/app-custom-theme.md:134]: Oops, missing the end of this one

File: packages/theme/src/pageTheme.ts (hunk 1 above)
Comment (Rugvip) [reply packages/theme/src/pageTheme.ts:67]: Still seeing them here 😅

File: docs/getting-started/app-custom-theme.md (hunk 4 above)
Comment (rkristelijn) [reply docs/getting-started/app-custom-theme.md]: how sloppy, fixed now

**Comment by rkristelijn** [comment]
Just wondering, if you put a `console.log({themeId});` here https://github.com/backstage/backstage/blob/master/packages/core/src/layout/Page/Page.tsx#L37

you see a lot of different values that are not documented. What is the plan with that?

I know it is not directly related to #5235 but still

File: .changeset/thirty-owls-lay.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/core': patch
+---
+
+# exposes undocumented `PageTheme`
```
Comment (benjdlambert) [inline .changeset/thirty-owls-lay.md:5]: you can remove the `#` header here. Otherwise it could look strange in the release log :)

Comment (rkristelijn) [reply .changeset/thirty-owls-lay.md]: done

**Review by benjdlambert — APPROVED** [review]

File: packages/core/src/layout/Header/Header.stories.tsx [hunk 6]
```diff
@@ -45,6 +45,46 @@ export const HomeWithSubtitle = () => (
...
+);
+
+export const OpenApi = () => (
+  <Page themeId="openapi">
+    <Header title="OpenAPI catalogue" type="tool">
+      {labels}
+    </Header>
+  </Page>
+);
+
```
Comment (dhenneke) [inline packages/core/src/layout/Header/Header.stories.tsx:87]: These should've also been deleted? Since the `themeId`s don't exist, there shouldn't be stories for them.

File: packages/theme/src/pageTheme.ts [hunk 7]
```diff
@@ -63,4 +63,5 @@ export const pageTheme: Record<string, PageTheme> = {
   library: genPageTheme(colorVariants.rubyRed, shapes.wave),
   other: genPageTheme(colorVariants.darkGrey, shapes.wave),
   app: genPageTheme(colorVariants.toastyOrange, shapes.wave),
+  apis: genPageTheme(colorVariants.eveningSea, shapes.wave2),
```
Comment (Fox32) [inline packages/theme/src/pageTheme.ts:66]: Do we really want to go with that color? 
image

It's hard to read

Comment (benjdlambert) [reply packages/theme/src/pageTheme.ts:66]: Yep I think the variant needs updating. Need @katz95 input here.

Comment (Fox32) [reply packages/theme/src/pageTheme.ts:66]: @benjdlambert I created a PR to rollback the color #5320
