### PR TITLE
Auth: fix logout()

### LINKED ISSUE #1136: Auth: Fix logout
`logout()` does not seem to work at the moment.

### PR DESCRIPTION
**Pull request by marcuseide**
Small changes that uses `post` for `logout()` alongside with small changes in error handling.

Fixes #1136

### CODE REVIEW

**Review by stefanalund — APPROVED** [review]

**Review by soapraj — APPROVED** [review]

File: packages/core-api/src/lib/AuthConnector/DefaultAuthConnector.ts [hunk 1]
```diff
@@ -140,10 +140,14 @@ export class DefaultAuthConnector<AuthSession>
         'x-requested-with': 'XMLHttpRequest',
       },
       credentials: 'include',
+    }).catch(error => {
+      throw new Error(`Logout request failed, ${error}`);
     });
 
     if (!res.ok) {
-      throw new Error(`Logout request failed with status ${res.status}`);
+      const error: any = new Error(`Logout request failed, ${res.statusText}`);
```
Comment (freben) [inline packages/core-api/src/lib/AuthConnector/DefaultAuthConnector.ts:148]: was the `:any` necessary just to be able to set the status?
