### PR TITLE
Fix: added a check for invalid timezone

### LINKED ISSUE #4263: Incorrect homepage.clocks.timezone results in app blank page
If you configure homepage.clocks to include a non-existent timezone name then the UI presents a blank screen

## Expected Behavior

Throw an error somewhere. Anything but present a blank UI.

## Current Behavior

Silently displays a blank screen.

## Steps to Reproduce

1. edit `app-config.local.yaml` and add a misspelled timezone name e.g. `timezone: 'America/Los_Angelex'`
2. run backstage example app
3. gets a blank screen with this logged in the js console:

```
HomepageTimer.tsx?4f8e:47 Uncaught RangeError: Invalid time zone specified: America/Los_Angelex
    at Date.toLocaleTimeString (<anonymous>)
    at getTimes (HomepageTimer.tsx?4f8e:47)
    at eval (HomepageTimer.tsx?4f8e:64)
    at commitHookEffectListMount (react-dom.development.js?bc31:19765)
    at commitPassiveHookEffects (react-dom.development.js?bc31:19803)
    at HTMLUnknownElement.callCallback (react-dom.development.js?bc31:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?bc31:238)
    at invokeGuardedCallback (react-dom.development.js?bc31:293)
    at flushPassiveEffectsImpl (react-dom.development.js?bc31:22885)
    at unstable_runWithPriority (scheduler.development.js?ab43:653)
getTimes @ HomepageTimer.tsx?4f8e:47
eval @ HomepageTimer.tsx?4f8e:64
commitHookEffectListMount @ react-dom.development.js?bc31:19765
commitPassiveHookEffects @ react-dom.development.js?bc31:19803
callCallback @ react-dom.development.js?bc31:189
invokeGuardedCallbackDev @ react-dom.development.js?bc31:238
invokeGuardedCallback @ react-dom.development.js?bc31:293
flushPassiveEffectsImpl @ react-dom.development.js?bc31:22885
unstable_runWithPriority @ scheduler.development.js?ab43:653
runWithPriority$1 @ react-dom.development.js?bc31:11062
flushPassiveEffects @ react-dom.development.js?bc31:22852
performSyncWorkOnRoot @ react-dom.development.js?bc31:21769
eval @ react-dom.development.js?bc31:11112
unstable_runWithPriority @ scheduler.development.js?ab43:653
runWithPriority$1 @ react-dom.development.js?bc31:11062
flushSyncCallbackQueueImpl @ react-dom.development.js?bc31:11107
flushSyncCallbackQueue @ react-dom.development.js?bc31:11095
scheduleUpdateOnFiber @ react-dom.development.js?bc31:21231
dispatchAction @ react-dom.development.js?bc31:15683
eval @ providers.tsx?be31:89
eval @ providers.tsx?be31:133
Promise.then (async)
eval @ providers.tsx?be31:128
commitHookEffectListMount @ react-dom.development.js?bc31:19765
commitLifeCycles @ react-dom.development.js?bc31:19821
commitLayoutEffects @ react-dom.development.js?bc31:22835
callCallback @ react-dom.development.js?bc31:189
invokeGuardedCallbackDev @ react-dom.development.js?bc31:238
invokeGuardedCallback @ react-dom.development.js?bc31:293
commitRootImpl @ react-dom.development.js?bc31:22573
unstable_runWithPriority @ scheduler.development.js?ab43:653
runWithPriority$1 @ react-dom.development.js?bc31:11062
commitRoot @ react-dom.development.js?bc31:22413
finishSyncRender @ react-dom.development.js?bc31:21839
performSyncWorkOnRoot @ react-dom.development.js?bc31:21825
eval @ react-dom.development.js?bc31:11112
unstable_runWithPriority @ scheduler.development.js?ab43:653
runWithPriority$1 @ react-dom.development.js?bc31:11062
flushSyncCallbackQueueImpl @ react-dom.development.js?bc31:11107
flushSyncCallbackQueue @ react-dom.development.js?bc31:11095
scheduleUpdateOnFiber @ react-dom.development.js?bc31:21231
dispatchAction @ react-dom.development.js?bc31:15683
eval @ useAsyncFn.js?ffba:18
Promise.then (async)
eval @ useAsyncFn.js?ffba:17
eval @ useAsync.js?423a:9
commitHookEffectListMount @ react-dom.development.js?bc31:19765
commitPassiveHookEffects @ react-dom.development.js?bc31:19803
callCallback @ react-dom.development.js?bc31:189
invokeGuardedCallbackDev @ react-dom.development.js?bc31:238
invokeGuardedCallback @ react-dom.development.js?bc31:293
flushPassiveEffectsImpl @ react-dom.development.js?bc31:22885
unstable_runWithPriority @ scheduler.development.js?ab43:653
runWithPriority$1 @ react-dom.development.js?bc31:11062
flushPassiveEffects @ react-dom.development.js?bc31:22852
eval @ react-dom.development.js?bc31:22731
workLoop @ scheduler.development.js?ab43:597
flushWork @ scheduler.development.js?ab43:552
performWorkUntilDeadline @ scheduler.development.js?ab43:164
react-dom.development.js?bc31:19561 The above error occurred in the <HomepageTimer> component:
    in HomepageTimer (at CatalogLayout.tsx:46)
    in div (at Header.tsx:220)
    in header (at Header.tsx:205)
    in Header (at CatalogLayout.tsx:40)
    in div (at Page.tsx:45)
    in ThemeProvider (at Page.tsx:39)
    in Page (at CatalogLayout.tsx:39)
    in CatalogLayout (at CatalogPage.tsx:153)
    in CatalogPageContents (at CatalogPage.tsx:203)
    in EntityFilterGroupsProvider (at CatalogPage.tsx:202)
    in CatalogPage (at Router.tsx:78)
    in Route (at Router.tsx:78)
    in Routes (at Router.tsx:77)
    in Router (at App.tsx:78)
    in Route (at App.tsx:76)
    in FlatRoutes (at App.tsx:70)
    in div (at Page.tsx:71)
    in SidebarPage (at Root.tsx:76)
    in Root (at App.tsx:101)
    in Route (at App.tsx:352)
    in Routes (at App.tsx:351)
    in SignInPageWrapper (at App.tsx:350)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.tsx:349)
    in AppRouter (at App.tsx:100)
    in RoutingProvider (at App.tsx:278)
    in CssBaseline (created by WithStyles(CssBaseline))
    in WithStyles(CssBaseline) (at AppThemeProvider.tsx:94)
    in ThemeProvider (at AppThemeProvider.tsx:93)
    in AppThemeProvider (at App.tsx:277)
    in AppContextProvider (at App.tsx:276)
    in ApiProvider (at App.tsx:130)
    in Provider (at App.tsx:97)
    in App (created by HotExportedApp)
    in AppContainer (created by HotExportedApp)
    in HotExportedApp (at src/index.tsx:22)

```

## Context

I was trying to customize the timezone display for timezones relevant to me.

## Your Environment

- NodeJS Version (v12): v14.15.4
- Operating System and Version (e.g. Ubuntu 14.04): MacOS Catalina 10.15.7 (19H114)
- Browser Information: Chrome 88.0.4324.96 (Official Build) (x86_64)
- @backstage/core: 0.5.0 at a06a13c30d

### PR DESCRIPTION
**Pull request by nwright-nz**
## Hey, I just made a Pull Request!

Fixes #4263 - An invalid timezone will now emit a warning to the console, and default to Los Angeles time zone instead of a blank ui

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [X] Screenshots attached (for UI changes)
backstage_screenshot

### CODE REVIEW

File: packages/core/src/layout/HomepageTimer/HomepageTimer.tsx [hunk 1]
```diff
@@ -39,18 +39,28 @@ function getTimes(configApi: ConfigApi) {
...
+
       const options = {
         timeZone: clock.getString('timezone'),
         ...timeFormat,
       };
 
-      const time = d.toLocaleTimeString(lang, options);
-      const label = clock.getString('label');
+      try {
+        new Date().toLocaleString(lang, options);
```
Comment (OrkoHunter) [inline packages/core/src/layout/HomepageTimer/HomepageTimer.tsx:50]: Thanks! Could you also add/update tests to reflect this?

Comment (nwright-nz) [reply packages/core/src/layout/HomepageTimer/HomepageTimer.tsx:50]: Oops - yup will get on that

Comment (freben) [reply packages/core/src/layout/HomepageTimer/HomepageTimer.tsx:50]: Cool, let me know when you've added a test.

File: packages/core/src/layout/HomepageTimer/HomepageTimer.tsx [hunk 2]
```diff
@@ -39,18 +39,28 @@ function getTimes(configApi: ConfigApi) {
...
+      } catch (e) {
+        // eslint-disable-next-line no-console
+        console.warn(
+          `The timezone ${options.timeZone} is invalid. Defaulting to America/Los Angeles`,
+        );
+        options.timeZone = 'America/Los_Angeles';
+        label = 'Los Angeles';
```
Comment (adamdmharvey) [inline packages/core/src/layout/HomepageTimer/HomepageTimer.tsx:57]:
```suggestion
          `The timezone ${options.timeZone} is invalid. Defaulting to Greenwich Mean Time (GMT).`,
        );
        options.timeZone = 'GMT';
        label = 'GMT';
```

Thanks to @OrkoHunter we know [where in the world the project folks are](https://twitter.com/SpotifyEng/status/1341375405446598656), and there are few Los Angelinos.  Maybe this should just default to GMT so as not to infer any West Coast/East Coast US preference?  (says the guy from the US East Coast 😉 )

Possible suggestion?

Comment (OrkoHunter) [reply packages/core/src/layout/HomepageTimer/HomepageTimer.tsx:57]: +1 for GMT 😄

Comment (nwright-nz) [reply packages/core/src/layout/HomepageTimer/HomepageTimer.tsx]: GMT it is! I was toying with the idea of defaulting to New Zealand instead of LA, but this feels like a happy medium!

File: packages/core/src/layout/HomepageTimer/HomepageTimer.tsx (hunk 1 above)
Comment (nwright-nz) [reply packages/core/src/layout/HomepageTimer/HomepageTimer.tsx:50]: Added a test now - sorry for the delay, had to get my head around writing the test.

File: packages/core/src/layout/HomepageTimer/HomepageTimer.test.tsx [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+        {
+          label: 'New York',
+          timezone: 'America/New_Pork',
+        },
+      ],
+    },
+    context: 'test',
+  });
+
+  const rendered = await renderWithEffects(
```
Comment (freben) [inline packages/core/src/layout/HomepageTimer/HomepageTimer.test.tsx:44]: There is a renderInTestApp helper, but this is fine too!

**Review by freben — APPROVED** [review]
Thanks!
