### PR TITLE
bugfix: [3310] Favoriting a component resets interface to your owned components

### LINKED ISSUE #3310: Favoriting a component resets interface to your owned components
When you favorite/star a component, the table view actually refreshes to show you only those components you "own" regardless of what you did or did not star or what filter section you were in. Your updated starred count in left nav updates. However, neither the filtered list (all , starred, or owned) highlight in the left nav changes, nor does the header of the page itself.

## Expected Behavior

Favoriting a component should simply mark the star as favorite (filled in yellow) or no longer a favorite (outlined), and should update the favorite count in the left navigation under Personal / Favorite. However, which ever view or table list you were on should remain.

## Current Behavior

Using the Backstage sample out of the box on a fresh SqlLite database and all example components, you see this view:

image

If you click the star to favorite `playback-order`, everything seems to work. The yellow star is visible, the left nav updates to show 1:

image

However, if you then click all,
image

And on this screen, now click the yellow star to _unfavorite_ `playback-order`, you see:

image

You've been reset to show you the three components you own instead of the all list you were just on, which is not ideal.  Now, the good thing is your left navigation count for how many are starred has been properly updated, HOWEVER, you've been reset back to your "owned" components list (showing three), even though the header for the section still says "All" which is not correct.

## Steps to Reproduce

See above.

## Context

There are various permutations of this, but all resulting in a reset of the table list to show you only your owned components.  For example:

1. favorite one component
2. In left nav, select Starred.
3. Unfavorite it in this view.
4. You'll be reset again to show your three owned components, you'll have no favorites in left nav, but your header on the main page will still say "Starred".

image

## Your Environment

- NodeJS Version (v12): v12.16.2
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909 WSL 2
- Browser Information: Microsoft Edge (Chrome)

### PR DESCRIPTION
**Pull request by nhidtran**
…components

## Hey, I just made a Pull Request!

[Closes #3310](https://github.com/backstage/backstage/issues/3310)

**What:**
Favoriting a catalog entity would result in entites reloading with filter "owned" regardless of being on selectedfilter "Starred" or "All". The Sidebar filter would be correct, but not the list items and the items count (e.g. All(7) would display All(2) if the number of Owned Entities were "2")
**Why:**
When the `state` changes in the FilterGroups context provider, it causes `useEntityFilterGroup` to unregister. When it reregisters, it re-registered with the initiallySelected filter which was hardcoded to "owned"
**Fix:**
Pass the current selected filter up to Catalog Page and pass the selected filter as a prop
That way when state changes (entities are rebuilt), `useEntityFilterGroup` will use that value

Please let me know if there was a better way for a fix!

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

https://user-images.githubusercontent.com/43722865/107119223-3d4e1100-6854-11eb-9bfe-199dab3cbb8d.mov

### CODE REVIEW

**Review by adamdmharvey — APPROVED** [review]
Hooray - what a great first contrib, @nhidtran ! *And* a test for it, even. Well done. 👏

File: plugins/catalog/src/filter/useEntityFilterGroup.ts [hunk 1]
```diff
@@ -43,15 +43,19 @@ export const useEntityFilterGroup = (
     filterGroupStates,
   } = context;
 
-  // Intentionally consider initial set only at mount time
+  // on state changes unregisters and registers the filtergroup
+  // ensure that it re-registers with the correct filter as the prop changes and not the default
   // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (Rugvip) [inline plugins/catalog/src/filter/useEntityFilterGroup.ts:48]: Could remove this lint rule disable now 🎉

**Review by Rugvip — APPROVED** [review]
Thanks, good fix idd! :grin:

Damn is the starring slow though, but that's a separate issue 😅
