### PR TITLE
Handle missing commits in GitlabUrlReader.readTree

### LINKED ISSUE #8036: Unable to create component using template
## Expected Behavior

Component should be created in gitlab using template

## Current Behavior

Exception while creating the component in gitlab.

Exception trace as below: 
2021-11-12T20:24:36.000Z Beginning step Fetch Skeleton + Template
2021-11-12T20:24:36.000Z info: Fetching template content from remote URL {"timestamp":"2021-11-12T20:24:36.571Z"}
2021-11-12T20:24:37.000Z TypeError: Cannot read property 'id' of undefined
    at _GitlabUrlReader.readTree (C:\svb\setup\backstageapp\node_modules\@backstage\backend-common\dist\index.cjs.js:1753:63)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async UrlReaderPredicateMux.readTree (C:\svb\setup\backstageapp\node_modules\@backstage\backend-common\dist\index.cjs.js:1994:16)
    at async fetchContents (C:\svb\setup\backstageapp\node_modules\@backstage\plugin-scaffolder-backend\dist\index.cjs.js:271:17)
    at async Object.handler (C:\svb\setup\backstageapp\node_modules\@backstage\plugin-scaffolder-backend\dist\index.cjs.js:383:7)
    at async HandlebarsWorkflowRunner.execute (C:\svb\setup\backstageapp\node_modules\@backstage\plugin-scaffolder-backend\dist\index.cjs.js:2178:11)
    at async TaskWorker.runOneTask (C:\svb\setup\backstageapp\node_modules\@backstage\plugin-scaffolder-backend\dist\index.cjs.js:2433:143)
    at async C:\svb\setup\backstageapp\node_modules\@backstage\plugin-scaffolder-backend\dist\index.cjs.js:2427:9

## Possible Solution

Component should be created using template

## Steps to Reproduce

Step 1: Created a template for Springboot microservice targeting gitlab repository.
Step 2: Creating a component using #1 template
Step 3: Exception is generated as above

Template used: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/springboot-grpc-template/template.yaml

except it uses our gitlab host in allowedHosts section

## Context

I want to create templates specific to our needs and need to create components using these templates in gitlab

## Your Environment

- NodeJS Version (v14): node-v14.17.0-win-x64
- Operating System and Version (e.g. Ubuntu 14.04): windows
- Browser Information: chrome

Installed backstage in windows using the instructions in the backstage website.
app-config.yaml has integration section for my gitlab with token.
and a template is specified in this file under catalog.locations.

### PR DESCRIPTION
**Pull request by freben**
Fixes #8036

I considered whether it would make sense to explicitly detect the empty commits list and throwing a `NotFoundError` or so. But I wasn't sure that that would be entirely semantically correct, and expected the following archive read operation to be the one to emit better / more precise errors anyway if that somehow was needed.

### CODE REVIEW

**Comment by OrkoHunter** [comment]
Hmm, I guess in TechDocs' case of using readTree, it's better to have an empty directory/docs page vs an error that the repository doesn't exist.

File: packages/backend-common/src/reading/GitlabUrlReader.ts [hunk 1]
```diff
@@ -188,8 +188,7 @@ export class GitlabUrlReader implements UrlReader {
       throw new Error(message);
     }
 
-    const commitSha = (await commitsGitlabResponse.json())[0].id;
-
+    const commitSha = (await commitsGitlabResponse.json())[0]?.id ?? '';
```
Comment (Rugvip) [inline packages/backend-common/src/reading/GitlabUrlReader.ts:191]: Bit strange to have `{ etag: '' }` trigger a hit, perhaps keep this undefined and check for presence in the condition below?

**Review by Rugvip — APPROVED** [review]
Yep think this fix makes sense

Just a tiny nit on the etag logic

File: packages/backend-common/src/reading/GitlabUrlReader.ts (hunk 1 above)
Comment (freben) [reply packages/backend-common/src/reading/GitlabUrlReader.ts:191]: It's actually not so much about the condition; it's the fact that `treeResponseFactory.fromTarArchive` farther down has a non-optional `etag` argument. So in the current shape of things we have to pass in _something_ to it. Not sure that any other placeholder would make more sense than this either 🤔

Comment (Rugvip) [reply packages/backend-common/src/reading/GitlabUrlReader.ts:191]: Alright, let's :shipit:. Won't be hitting the check below anyway, just looks scary x)
