### PR TITLE
Export SignInConfig type

### LINKED ISSUE #5270: Cannot import SignInConfig in App.tsx from @backstage/core
After adding the GitLab authentication provider as per the [documentation](https://backstage.io/docs/auth/#adding-the-provider-to-the-sign-in-page), compilation with `yarn tsc` fails as it can't find SignInConfig from @backstage/core

## Expected Behavior

`yarn tsc` compiles the project without errors

## Current Behavior

```packages/app/src/App.tsx:27:28 - error TS2459: Module '"@backstage/core"' declares 'SignInConfig' locally, but it is not exported.

27 import { gitlabAuthApiRef, SignInConfig, SignInPage } from '@backstage/core';
                              ~~~~~~~~~~~~

  node_modules/@backstage/core/dist/index.d.ts:784:14
    784 declare type SignInConfig = {
                     ~~~~~~~~~~~~
    'SignInConfig' is declared here.
```

## Steps to Reproduce

1. Add code to import SignInConfig from @backstage/core in App.tsx as per the documentation
2. Run `yarn tsc`

## Context
Using a backstage app originally created using `npx @backstage/create-app` (@backstage/core 0.7.3)

## Your Environment

- NodeJS Version: 14.16.1
- Operating System and Version: Ubuntu 20.04.2 LTS

### PR DESCRIPTION
**Pull request by timbonicus**
Signed-off-by: Tim Hansen <timbonicus@gmail.com>

Fixes #5270.

I included `SignInConfig` in the docs to strongly-type what we expect users to pass in to `SignInPage` props. This is not exported.

Alternatively, I can amend the docs - but seems preferable to have these strongly typed so any later API changes are compile-time caught by implementors.

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: packages/core/src/layout/SignInPage/index.ts [hunk 1]
```diff
@@ -14,4 +14,5 @@
  * limitations under the License.
  */
 
+export type { SignInConfig } from './types';
```
Comment (Rugvip) [inline packages/core/src/layout/SignInPage/index.ts:17]: Thinking we want to rename this if we're gonna export it, something like `SignInPageProvider`? Or `SignInPageProviderConfig` / `SignInProviderConfig`, seeing as this is not the configuration for "sign-in".

**Review by Rugvip — COMMENTED** [review]
Generally when things aren't exported it's to either avoid bloat, but most commonly so that we don't have to go through figuring out what a good name for the thing is, so gotta do that now x)

Needs a changeset! :>

**Review by freben — APPROVED** [review]
noice
