### PR TITLE
fix(search): compile possible filter options from available entities

### LINKED ISSUE #3344: [Search] Dynamically load filter options
On the search page we do have two filter types at the moment. A selection of Kinds and checkboxes of lifecycles. The data for this is currently just hard coded in the [Filters component.](https://github.com/backstage/backstage/blob/master/plugins/search/src/components/Filters/Filters.tsx#L68)

The different kinds and lifecycles can look different depending on what entities that exist, therefore it would be nice to dynamically load all the filter options that exist for all your entities. 

For example, "The kind filter doesn't include User and Group, though they are in the table listing for me." and "e.g., if there are no APIs registered, than we shouldn't need to filter by them."

- [ ] Investigate if there is any existing api for this, maybe in the catalog client. 
- [ ] Replace the hard coded filters with dynamically loaded data.

### PR DESCRIPTION
**Pull request by magneticz**
## Hey, I just made a Pull Request!

This PR removes hardcoded filter values from Filter component in Search plugin and compiles list of available options from entities available.

fixes #3344 

State when filters cannot be taken from the results
Screenshot 2020-11-23 at 13 01 57

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

File: plugins/search/src/components/Filters/Filters.tsx [hunk 1]
```diff
@@ -79,54 +82,58 @@ export const Filters = ({
...
-        </List>
-      </CardContent>
+              >
+                {filter}
+              </MenuItem>
+            ))}
+          </Select>
+        </CardContent>
+      )}
+      {filterOptions.lifecycle.length > 0 && (
```
Comment (magneticz) [inline plugins/search/src/components/Filters/Filters.tsx:110]: @emmaindal Not sure what should be the behaviour here. I added this check, so that we don't have section, if there are no values. 

However, if both kind and lifecycle are not available, then filters pane will be empty

File: plugins/search/src/apis.ts [hunk 2]
```diff
@@ -39,8 +39,8 @@ class SearchApi {
       name: result.metadata.name,
       description: result.metadata.description,
       owner: result.spec.owner,
-      kind: result.kind,
-      lifecycle: result.spec.lifecycle,
+      kind: '',
```
Comment (emmaindal) [inline plugins/search/src/apis.ts:42]: We do want to set kind and lifecycle here to what is returned from the catalog api request, so back to how it was before I guess. Any reason to why it was replaced by empty strings?

File: plugins/search/src/components/SearchResult/SearchResult.tsx [hunk 3]
```diff
@@ -209,13 +209,30 @@ export const SearchResult = ({ searchQuery }: SearchResultProps) => {
...
+    },
+  );
+
   return (
     <>
       <Grid container>
         {showFilters && (
           <Grid item xs={3}>
             <Filters
               filters={filters}
```
Comment (emmaindal) [inline plugins/search/src/components/SearchResult/SearchResult.tsx:234]: Now when we have filterOptions as well, I think we can rename the `filters` state to `selectedFilters` or something more clear

File: plugins/search/src/components/Filters/Filters.tsx (hunk 1 above)
Comment (emmaindal) [reply plugins/search/src/components/Filters/Filters.tsx:110]: what about not render the button to open the filter options (+ the applied-filters-text) when length lifecycle and kind in filterOptions is 0?

File: plugins/search/src/apis.ts (hunk 2 above)
Comment (magneticz) [reply plugins/search/src/apis.ts:42]: Ops, that's my bad, I replaced it to empty strings to check, when there are no values and forgot to bring it back. Will update it

File: plugins/search/src/components/Filters/Filters.tsx (hunk 1 above)
Comment (magneticz) [reply plugins/search/src/components/Filters/Filters.tsx:110]: that is a possibility, my concern then would be that it might bring a confusion to end user, sometimes seeing the filters button and sometimes not seeing it. As an alternative, we could add some helper text in filter panel, something like "Filters cannot be applied to results" or something like that.

Comment (emmaindal) [reply plugins/search/src/components/Filters/Filters.tsx:110]: Good thinking! Go for that and we will take this in to account in the second iteration of the search result page!

Comment (magneticz) [reply plugins/search/src/components/Filters/Filters.tsx:117]: update the PR with the message in case there are no filters

File: plugins/search/src/components/SearchResult/SearchResult.tsx [hunk 4]
```diff
@@ -181,41 +181,58 @@ export const SearchResult = ({ searchQuery }: SearchResultProps) => {
...
+  );
+
   return (
     <>
       <Grid container>
         {showFilters && (
           <Grid item xs={3}>
             <Filters
-              filters={filters}
+              filters={selectedFilters}
```
Comment (emmaindal) [inline plugins/search/src/components/SearchResult/SearchResult.tsx:234]: filters can be replaced with selectedFilters as well and also in the Filters component (see my comment above)

File: plugins/search/src/components/Filters/Filters.tsx [hunk 5]
```diff
@@ -49,25 +49,28 @@ export type FiltersState = {
   checked: Array<string>;
 };
 
+export type FilterOptions = {
+  kind: Array<string>;
+  lifecycle: Array<string>;
+};
+
 type FiltersProps = {
   filters: FiltersState;
```
Comment (emmaindal) [inline plugins/search/src/components/Filters/Filters.tsx:58]: the filters property can now be selectedFilters

File: plugins/search/src/components/Filters/Filters.tsx [hunk 6]
```diff
@@ -49,25 +49,28 @@ export type FiltersState = {
...
+  filterOptions: FilterOptions;
   resetFilters: () => void;
   updateSelected: (filter: string) => void;
   updateChecked: (filter: string) => void;
 };
 
 export const Filters = ({
   filters,
```
Comment (emmaindal) [inline plugins/search/src/components/Filters/Filters.tsx:66]: the filters property can now be selectedFilters

File: plugins/search/src/components/SearchResult/SearchResult.tsx (hunk 4 above)
Comment (magneticz) [reply plugins/search/src/components/SearchResult/SearchResult.tsx:234]: My thinking was that `filters` in the Filters component will be considered as selected filters by default, since we are passing them to the Filters component. Do you think it might be confusing?

Comment (emmaindal) [reply plugins/search/src/components/SearchResult/SearchResult.tsx:234]: @magneticz now when we have filterOptions it could be, but I don't want to block this on that so lets leave it as it is for now! You might want to do a rebase on top of master though, we have merged some new stuff!

**Review by emmaindal — APPROVED** [review]
🎉  Thank you @magneticz!
