### PR TITLE
EntitySwitch render children when entity is not found

### LINKED ISSUE #19418: 🐛 Bug Report: PR 18919 prevents Warning: Entity Not Found from Appearing
### 📜 Description

In https://github.com/backstage/backstage/pull/18919, there was an implementation change where "If the entity is missing or there is an error, render nothing." The prior behavior, "If the entity is missing or there is an error, render the default page", was removed. The user is then served a blank page, instead of a a useful error experience.

### 👍 Expected behavior

Show a warning page "Warning: Entity not found" when loading an entity that does not exist.

image

### 👎 Actual Behavior with Screenshots

The page is completely blank.

image

### 👟 Reproduction steps

It is reproducible in the demo site. For example:
https://demo.backstage.io/catalog/default/user/idonotexist

### 📃 Provide the context for the Bug.

This PR seems directly related to the issue. https://github.com/backstage/backstage/pull/18919

### 🖥️ Your Environment

Reproducible in the demo backstage environment.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

### PR DESCRIPTION
**Pull request by vinzscam**
## Hey, I just made a Pull Request!

This PR closes #19418 by rendering the children in case an entity is not found.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/catalog/src/components/EntitySwitch/EntitySwitch.tsx [hunk 1]
```diff
@@ -77,14 +77,17 @@ export const EntitySwitch = (props: EntitySwitchProps) => {
         })
         .getElements()
         .flatMap<SwitchCaseResult>((element: ReactElement) => {
-          // If the entity is missing or there is an error, render nothing
-          if (!entity) {
```
Comment (freben) [inline plugins/catalog/src/components/EntitySwitch/EntitySwitch.tsx:81]: as per discussions elsewhere - i still think that maybe we need to do `if (loading && !entity) { return [] }` to make sure that during _initial_ load, the fallback isn't shown.

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
Oh sorry - needs a changeset too

**Review by freben — APPROVED** [review]
