### PR TITLE
Core: Make error boundary more helpful

### LINKED ISSUE #4292: jenkins: Improve error display on Jenkins latest build overview card
Improve error handling for the Jenkins overview card.

## Expected Behavior

If there is a misconfiguration of a Jenkins pipeline, I believe the expected behavior should be:

* the Jenkins card should still display, but inline to the card the card should display the error
* there should not be an errorApi alert popup for the user

## Current Behavior

In this case, the initial GitHub org path had a typo in it, so this component's Jenkins latest build card was broken. However, it's not so friendly to have a large red popup, and the sort of "can't display React" error for the card which infers there's a problem with Backstage (thus "go get the integrator to fix it"). The issue was in the entity config, itself.  Would be better to trap that error within the card and indicate it can't be displayed, and print the error.

image

## Steps to Reproduce

1. Install Jenkins plugin, placing the overview card on the entity overview page
2. Provide an invalid annotation in an entity for `jenkins.io/github-folder`
3. View the entity's overview page

## Context

Simply moving the error from alertApi popup/errorApi over to the card with maybe a `<WarningPanel>` would be great, but EVEN BETTER would be to trap this specific type of error, and provide some error context to the user such as can't find the job in Jenkins, which is different than can't CONNECT to Jenkins, and thus the inference may be an incorrect annotation. That might allow the entity owner to fix it themselves, rather than engaging the integrator team.

## Your Environment

- NodeJS Version (v12): v12
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909 WSL 2 Ubuntu 18.04
- Browser Information: Microsoft Edge (Chrome Engine)

### PR DESCRIPTION
**Pull request by TejasQ**
## Hey, I just made a Pull Request!
This PR possibly fixes #4292 by making the global card-contained error boundaries more explicit, allowing a user to expose a stack trace if they have the domain knowledge or are otherwise interested. It also exposes a _link_ to `#backstage` instead of just a non-interactive piece of text.

This may not be a complete solution for #4292, because the Jenkins plugin ideally should expose its own error boundary with more Jenkins specifics.

|Before|After|
|---|---|
||Kapture 2021-05-20 at 17 11 52|

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] ~Added or updated documentation~
- [ ] ~Tests for new functionality and regression tests for bug fixes~
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by adamdmharvey** [comment]
This does definitely look cool!  I wonder though if there isn't a good amount of overlap with the existing `<WarningPanel>`?  It too provides an unfoldable error, similar to how this works?

https://backstage.io/storybook/?path=/story/feedback-warning-panel--full-example

Is the value here a wrapper that automatically helps it, or does implementing this error boundary then need to be implemented in each card that might want to use it (just like they could add a `<WarningPanel>`?)

File: packages/core/src/layout/constants.ts [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+export const slackChannel = {
+  name: '#backstage',
+  href: 'https://spotify.slack.com/archives/C54P1J36Z',
```
Comment (Rugvip) [inline packages/core/src/layout/constants.ts:18]: Let's have something different here, perhaps if the url is not set we fall back to just the channel name? Or just make it `example.com` or smth

File: packages/core/src/layout/ErrorBoundary/ErrorBoundary.tsx [hunk 2]
```diff
@@ -28,15 +30,54 @@ type State = {
...
+            </code>
+          </pre>
+        )}
+        {slackChannel && (
+          <p>
+            Please contact{' '}
+            <a
+              href={slackChannel.href}
+              target="_blank"
+              rel="noopener noreferrer"
```
Comment (Rugvip) [inline packages/core/src/layout/ErrorBoundary/ErrorBoundary.tsx:73]: Why add these tbh? Could probably be useful information to have

**Review by Rugvip — COMMENTED** [review]
Thanks! Very much a step in the right direction regardless if it's complete solution. I'd say :shipit: and see how it fits in.

Just a couple of nits

**Comment by Rugvip** [comment]
Oh and 👍 to exploring whether it makes sense to use the `WarningPanel` as well, thanks @adamdmharvey

File: packages/core/src/layout/ErrorBoundary/ErrorBoundary.test.tsx [hunk 3]
```diff
@@ -56,7 +56,7 @@ describe('<ErrorBoundary/>', () => {
       );
 
       expect(getByRole('alert')).toBeInTheDocument();
-      expect(getByText(/something went wrong here/i)).toBeInTheDocument();
+      expect(getByText(/something went wrong/i)).toBeInTheDocument();
```
Comment (Rugvip) [inline packages/core/src/layout/ErrorBoundary/ErrorBoundary.test.tsx:59]: asd

File: packages/core/src/layout/ErrorBoundary/ErrorBoundary.tsx (hunk 2 above)
Comment (Rugvip) [reply packages/core/src/layout/ErrorBoundary/ErrorBoundary.tsx]: Chrome seems to have changed the default in 88 though, and seeing and the process security model is a Chrome thing to begin with it should be fine to skip now. Including the referrer I'm just thinking could be good for tracking internally within a company be able to make informed decisions.

Don't wanna block this, but also not thinking this is a pattern that we need to be using too much.

File: .changeset/rude-pumpkins-hang.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/core': patch
```
Comment (Rugvip) [inline .changeset/rude-pumpkins-hang.md:2]: This is currently a breaking change right? so `minor`. Perhaps it could be worth making it backwards compatible though, as in `slackChannel?: string | typeof defaultSlackChannel`.

**Review by Rugvip — COMMENTED** [review]
So this is a bit annoying, but since this was opened we've had the core package split, so this should now be applied to the `core-components` package instead 😅

File: packages/core/src/layout/ErrorBoundary/ErrorBoundary.tsx (hunk 2 above)
Comment (Rugvip) [reply packages/core/src/layout/ErrorBoundary/ErrorBoundary.tsx]: @freben figured that we where actually doing this internally too, so can easily settle the debate with that we could keep doing it at least for now. Speaking of which, could we use our own `Link` component here? That's where we'd want to collect these kind of things rather than having them spread out.

**Comment by freben** [comment]
Rebased on master and changed to using ErrorPanel.

**Comment by freben** [comment]
@TejasQ I hope you don't mind me helping push this across the line after the big core changes we made.

**Comment by freben** [comment]
Screenshot 2021-06-24 at 21 22 11
Screenshot 2021-06-24 at 21 27 26

**Review by benjdlambert — APPROVED** [review]
