### PR TITLE
fix presentation icon passing

### LINKED ISSUE #21529: Icons for custom kinds in new Catalog version
### 📜 Description

Hello!
I am facing issues with adding icons for the custom kind entities I have in my catalog. However, the icons are not getting used and it's showing a question mark icon instead. Refer to the image shared from the catalog table for the custom kind

image

### 👍 Expected behavior

It should ideally use the custom icons defined in the packages/app/api.ts file

### 👎 Actual Behavior with Screenshots

It is not using these apis and instead showing the question mark icon

### 👟 Reproduction steps

in packages/app/api.ts

  createApiFactory({
    api: entityPresentationApiRef,
    deps: {
      catalogApi: catalogApiRef,
    },
    factory({ catalogApi }) {
      return DefaultEntityPresentationApi.create({
        catalogApi,
        kindIcons: {
          jenkins: WorkIcon,
        },
      });
    },
  }),
  
 However this is not getting used.
 Packages being used:
 
 import { catalogApiRef, entityPresentationApiRef,
 } from '@backstage/plugin-catalog-react';
 import WorkIcon from '@material-ui/icons/Work';
  import { DefaultEntityPresentationApi } from '@backstage/plugin-catalog';
  
  versions:
      "@backstage/plugin-catalog-react": "^1.8.5",

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by freben**
Fixes #21529

I pondered this one for a bit back and forth. The original code had TWO icon picking functions: one in the renderer, and one fallback thing in the API implementation itself. The error was caused by the renderer insisting on always returning a fallback icon on unknown kinds, so the API fallback implementation never kicked in.

But having two seemed odd. So which one to pick?

- Make the default renderer always return no icon at all, and let the API handle fallbacks. This makes it a bit easier to implement custom renderers that don't care about icons, and is also the lightest change in terms of implementation code.
- Make the default renderer handle icons and remove the API fallback handling. Now you instead need to pass the kindIcons argument down through the layers from the API to the renderer, and those who make custom renderers may be tempted to call the default renderer (manually giving it the icons argument again!) and modifying its response. It also cements the API of the default renderer to have specifically kind based icon picking (eg excluding types as a possibility).

I chose to make the smallest possible change for this fix (the first option). But going forward it may be worth thinking about how to iterate on this further.

### CODE REVIEW

File: plugins/catalog/src/apis/EntityPresentationApi/DefaultEntityPresentationApi.ts [hunk 1]
```diff
@@ -194,11 +192,12 @@ export class DefaultEntityPresentationApi implements EntityPresentationApi {
     const renderer = options.renderer ?? createDefaultRenderer({ async: true });
 
     const kindIcons: Record<string, IconComponent> = {};
-    Object.entries(options.kindIcons ?? DEFAULT_ICONS).forEach(
-      ([kind, icon]) => {
-        kindIcons[kind.toLocaleLowerCase('en-US')] = icon;
-      },
-    );
+    Object.entries(DEFAULT_ICONS).forEach(([kind, icon]) => {
```
Comment (benjdlambert) [inline plugins/catalog/src/apis/EntityPresentationApi/DefaultEntityPresentationApi.ts:195]: not blocking but can't we just merge  these using `{...DEFAULT_ICONS, ...options.kindIcons }` and then do `Object.fromEntries(Object.entries().map(([kind, icon] => [kind.toLocaleLowerCase(), icon]))`?

Comment (freben) [reply plugins/catalog/src/apis/EntityPresentationApi/DefaultEntityPresentationApi.ts:195]: We could for sure! Or even better using mapKeys from lodash
