### PR TITLE
fix(ui): render html in gfm mode in MarkdownContent component

### LINKED ISSUE #30989: <br /> tags not handled properly by MarkdownContent
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
MarkdownContent, html, <br> <br /> </ br>
```

### 🗃️ Project Area

Design System

### 🔗 External Integration

N/A

### 📝 Description & Context

When using `import { MarkdownContent } from '@backstage/core-components'` it is displaying html tags in plain text instead of rendering them properly. Resulting in e.g. `<br />` tags in the markdown content to be shown as plain text.

### 👍 Expected Behavior

Since it should render according to Github flavoured Markdown `<br />` should show up as new lines in the Backstage theme.

### 📦 Reproduction Repo

_No response_

### 🥾 Reproduction steps

_No response_

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Undecided

### PR DESCRIPTION
**Pull request by theZMC**
## Fix HTML rendering in the `MarkdownContent` component when rendering github-flavored markdown

Fixes #30989

**This was created as a contribfest contribution from Kubecon 2025**

Previously, the `MarkdownContent` component did not parse HTML present within the provided markdown content even when GitHub-flavored markdown was specified. This is dissimilar to the rendering behavior of GitHub when rendering the same markdown. 

I have updated the component to render HTML when present in the content and have configured the component to invoke the `rehype-sanitize` plugin to keep unsafe/unwanted elements and attributes from being parsed and rendered.

### Example Content
```md
# GFM with HTML

This is a paragraph with <strong>bold text</strong> and <em>italic text</em>.

<br>

Here is a list:

<ul>
  <li>First item</li>
  <li>Second item with <a href="https://example.com">a link</a></li>
  <li>Third item</li>
</ul>

And a code block:

<pre><code class="language-js">
function greet() {
  console.log("Hello, world!");
}
</code></pre>
```

### Before
image

### After
image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by theZMC** [comment]
Putting back in draft while I investigate CI errors.

**Comment by theZMC** [comment]
~~I'm not sure what to do about the E2E tests as they seem to be failing on `master` in the same way they're failing in my fork, so I'm tempted to say they're unrelated to my changes, but it's possible there's an element I'm missing.~~


~~Please let me know how you'd like me to proceed.~~

Disregard. Seems the most recent run passed E2E just fine.

File: packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx [hunk 1]
```diff
@@ -108,6 +109,20 @@ const components: Options['components'] = {
   h6: headingRenderer,
 };
 
+// Disallowed in GFM rendering
+// Ref: https://github.github.com/gfm/#disallowed-raw-html-extension-
+const gfmDisallowedElements = [
```
Comment (aramissennyeydd) [inline packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx]: Should we use https://github.com/rehypejs/rehype-sanitize here instead? Seems that that's what's recommended by the library for HTML rendering, https://remarkjs.github.io/react-markdown/

File: packages/core-components/package.json [hunk 2]
```diff
@@ -77,6 +77,7 @@
     "linkify-react": "4.3.2",
     "linkifyjs": "4.3.2",
     "lodash": "^4.17.21",
+    "parse5": "^6.0.0",
```
Comment (aramissennyeydd) [inline packages/core-components/package.json:80]: Do we need this?

Comment (theZMC) [reply packages/core-components/package.json:80]: Yes, or maybe a `resolutions` entry, but I didn't see any such entries in the `core-components` package.json so wasn't sure what the project would prefer. I'll also gladly admit I'm not a nodejs dependency resolution afficionado, so I may be unaware of a more obvious solution. 

I can tell you the root cause is `rehype-raw` brings in `hast-util-raw` which relies on types that are no longer present in `parse5` 7+ which is what gets installed by default. This leads to a typescript type checking failure:
```sh
❯ yarn tsc:full
node_modules/hast-util-raw/lib/index.d.ts:19:43 - error TS2694: Namespace '"/home/zach/Sync/code/github.com/thezmc/backstage-backstage/node_modules/parse5/dist/index"' has no exported member 'Document'.

19 export type P5Document = import('parse5').Document
                                             ~~~~~~~~

node_modules/hast-util-raw/lib/index.d.ts:20:43 - error TS2694: Namespace '"/home/zach/Sync/code/github.com/thezmc/backstage-backstage/node_modules/parse5/dist/index"' has no exported member 'DocumentFragment'.

20 export type P5Fragment = import('parse5').DocumentFragment
                                             ~~~~~~~~~~~~~~~~

node_modules/hast-util-raw/lib/index.d.ts:21:47 - error TS2694: Namespace '"/home/zach/Sync/code/github.com/thezmc/backstage-backstage/node_modules/parse5/dist/index"' has no exported member 'Element'.

21 export type P5Element = Omit<import('parse5').Element, 'parentNode'>
                                                 ~~~~~~~

node_modules/hast-util-raw/lib/index.d.ts:22:44 - error TS2694: Namespace '"/home/zach/Sync/code/github.com/thezmc/backstage-backstage/node_modules/parse5/dist/index"' has no exported member 'Attribute'.

22 export type P5Attribute = import('parse5').Attribute
                                              ~~~~~~~~~

node_modules/hast-util-raw/lib/index.d.ts:24:20 - error TS2694: Namespace '"/home/zach/Sync/code/github.com/thezmc/backstage-backstage/node_modules/parse5/dist/index"' has no exported member 'Location'.

24   import('parse5').Location,
                      ~~~~~~~~

node_modules/hast-util-raw/lib/index.d.ts:30:31 - error TS2314: Generic type 'ParserOptions<T>' requires 1 type argument(s).

30 export type P5ParserOptions = import('parse5').ParserOptions
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 6 errors in the same file, starting at: node_modules/hast-util-raw/lib/index.d.ts:19
```

File: packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx (hunk 1 above)
Comment (theZMC) [reply packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx]: I was unaware of this, but I was trying to be mindful of how many dependencies I was adding, so I probably wouldn't have reached for this anyway. If the project is okay with an additional dependency, I can update this PR to use that package instead of my manual blocklist.

I can certainly see the benefit from a maintainability perspective of deferring this sanitization logic to another package.

Comment (theZMC) [reply packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx]: I dug further into this and it does seem like `rehype-sanitize` handles far more sanitization than just element allowlisting, so I went ahead and replaced my implementation with it. It also turns out I was mistaken and inline styles are not allowed in GFM, so I've updated the PR description to match the updated behavior.

File: packages/core-components/package.json (hunk 2 above)
Comment (aramissennyeydd) [reply packages/core-components/package.json:80]: Ah, yeah makes sense as to why it's v6 - @freben Is this going to cause issues? I know we try to keep versions consistent across the repo.

Comment (freben) [reply packages/core-components/package.json:80]: We don't explicitly use parse5 anywhere else. Since it's just a transitive dependency, I think what we have here is fine.

**Comment by aramissennyeydd** [comment]
@theZMC I think this just needs a rebase and we can get it in!

**Comment by theZMC** [comment]
@aramissennyeydd Nice. Thanks all!
