### PR TITLE
#4322  bitbucket own hosted v5.11.1 branchUrl fix and enabled error tracing…

### LINKED ISSUE #4322: [Techdocs] Own Hosted Bitbucket follow-up  #4233  (Issues during test)
## Expected Behavior

Reading branch from bitbucket server 

## Current Behavior

`Failed to retrieve default branch from https://<mybitbucket-host.com>/rest/api/1.0/projects/PRJ/repos/me-repo-1/default-branch, 404 Not Found`

## Possible Solution

https://github.com/backstage/backstage/blob/master/packages/integration/src/bitbucket/core.ts#L37

fixing 
```
  const branchUrl = isHosted
    ? `${config.apiBaseUrl}/repositories/${project}/${repoName}`
    : `${config.apiBaseUrl}/projects/${project}/repos/${repoName}/default-branch`;
```
to

```
  const branchUrl = isHosted
    ? `${config.apiBaseUrl}/repositories/${project}/${repoName}`
    : `${config.apiBaseUrl}/projects/${project}/repos/${repoName}/branches/default`;
``` 

## Steps to Reproduce

Same as in #4233

## Your Environment

 
**Atlassian Bitbucket v5.11.1**

### PR DESCRIPTION
**Pull request by kaparwan**
## Hey, I just made a Pull Request! for   #4322

Closes #4322

@OrkoHunter 

- Added branchUrl for  bitbucket own hosted v5.11.1 
- added error tracing for mkdocs stderr 

#### :heavy_check_mark: Checklist

 [ :heavy_check_mark: ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by freben** [comment]
Hi, you need to run prettier on the modified file.

File: packages/integration/src/bitbucket/core.ts [hunk 1]
```diff
@@ -32,10 +32,11 @@ export async function getBitbucketDefaultBranch(
 
   const isHosted = resource === 'bitbucket.org';
   // Bitbucket Server https://docs.atlassian.com/bitbucket-server/rest/7.9.0/bitbucket-rest.html#idp184
+  // Changed branchUrl to support Atlassian Bitbucket v5.11.1 , which has different branchUrl format
   const branchUrl = isHosted
     ? `${config.apiBaseUrl}/repositories/${project}/${repoName}`
-    : `${config.apiBaseUrl}/projects/${project}/repos/${repoName}/default-branch`;
-
+    : `${config.apiBaseUrl}/projects/${project}/repos/${repoName}/branches/default`;
+
```
Comment (freben) [inline packages/integration/src/bitbucket/core.ts:39]: This is not what we agreed upon - it'll have to be more involved than this. It should first try the new format, and then if it gets specifically a 404 it should try the old format.

File: packages/techdocs-common/src/stages/generate/helpers.ts [hunk 2]
```diff
@@ -133,6 +133,10 @@ export const runCommand = async ({
 
     process.stderr.on('data', stream => {
       logStream.write(stream);
+      // added below change to make OS ( child process) exception to the backend logs
+      const bufferbase64 = Buffer.from(stream, 'base64');
+      const textAscii = bufferbase64.toString('ascii');
+      console.log(' Process Stderror trace: ', textAscii);
```
Comment (freben) [inline packages/techdocs-common/src/stages/generate/helpers.ts:139]: I don't think this is what we want. Console.log is normally not allowed. Where logging is involved, we pass around the winston logger from the backend instead; see other parts of the codebase

File: packages/integration/src/bitbucket/core.ts (hunk 1 above)
Comment (kaparwan) [reply packages/integration/src/bitbucket/core.ts:38]: Thanks. done  and tested ok.  Please review .

File: packages/techdocs-common/src/stages/generate/helpers.ts (hunk 2 above)
Comment (kaparwan) [reply packages/techdocs-common/src/stages/generate/helpers.ts]: This was added to debug the local run and it helped to identify that "techdocs-core"  plugins  issue. This looks more of a process/documentation change rather than logger change.  Please advise.

File: packages/integration/src/bitbucket/core.ts (hunk 1 above)
Comment (OrkoHunter) [reply packages/integration/src/bitbucket/core.ts:38]: Thanks! Could you also update the tests (core.test.ts) to include both these endpoints? We should have a case where the endpoint above results in 404 and the endpoint below is used.

File: packages/integration/src/bitbucket/core.ts [hunk 3]
```diff
@@ -35,8 +35,16 @@ export async function getBitbucketDefaultBranch(
   const branchUrl = isHosted
     ? `${config.apiBaseUrl}/repositories/${project}/${repoName}`
     : `${config.apiBaseUrl}/projects/${project}/repos/${repoName}/default-branch`;
-
-  const response = await fetch(branchUrl, getBitbucketRequestOptions(config));
+    
+  var response = await fetch(branchUrl, getBitbucketRequestOptions(config));
+  
+  if (response.status === 404) {
```
Comment (OrkoHunter) [inline packages/integration/src/bitbucket/core.ts:41]:
```suggestion
  if (response.status === 404 && !isHosted) {
```

In case of `bitbucket.org` this block shouldn't be executed.

File: packages/techdocs-common/src/stages/generate/helpers.ts (hunk 2 above)
Comment (OrkoHunter) [reply packages/techdocs-common/src/stages/generate/helpers.ts]: Ideally you should something like `techdocs-cli` locally to preview docs when you are writing it. It should let you know about the mkdocs and its techdocs-core plugin issues.
https://backstage.io/docs/features/techdocs/troubleshooting#mkdocs-build-errors
https://github.com/backstage/techdocs-cli

**Review by OrkoHunter — COMMENTED** [review]
Please also add a changeset with a `patch` change for `@backstage/integration`. (Detail is in PR description.)

File: packages/integration/src/bitbucket/core.ts (hunk 3 above)
Comment (kaparwan) [reply packages/integration/src/bitbucket/core.ts]: @OrkoHunter . added above check and tested it successfully ( own hosted) .

File: packages/integration/src/bitbucket/core.ts (hunk 1 above)
Comment (kaparwan) [reply packages/integration/src/bitbucket/core.ts:38]: updated core.test.ts

**Comment by OrkoHunter** [comment]
Hey! You need to run prettier on those files to fix failing CI.

File: packages/integration/src/bitbucket/core.test.ts [hunk 4]
```diff
@@ -249,6 +251,42 @@ describe('bitbucket core', () => {
         config,
       );
       expect(defaultBranch).toEqual('main');
-    });
+      });
+
+      it('return default branch for Bitbucket Server for bitbucket version 5.11', async () => {
```
Comment (OrkoHunter) [inline packages/integration/src/bitbucket/core.test.ts:256]: Let's just say this?

```suggestion
      it('return default branch for Bitbucket Server for older bitbucket versions < 7.5', async () => {
```

Looking at the reference docs, I can see `default-branch` in 7.5 but not in earlier versions.
https://docs.atlassian.com/bitbucket-server/rest/7.5.0/bitbucket-rest.html#idp202
https://docs.atlassian.com/bitbucket-server/rest/7.4.0/bitbucket-rest.html

File: packages/integration/src/bitbucket/core.test.ts [hunk 5]
```diff
@@ -249,6 +251,42 @@ describe('bitbucket core', () => {
...
+          displayId: 'main',
+        };
+        worker.use(
+          rest.get(
+            'https://api.bitbucket.mycompany.net/rest/api/1.0/projects/backstage/repos/mock/default-branch',
+            (_, res, ctx) =>
+              res(
+                ctx.status(404),
+                ctx.set('Content-Type', 'application/json'),
+                ctx.json(defaultBranchResponse),
```
Comment (OrkoHunter) [inline packages/integration/src/bitbucket/core.test.ts:267]: Nit: If it's a 404, these are useless no :P
Just an empty response makes more sense.

File: packages/integration/src/bitbucket/core.ts [hunk 6]
```diff
@@ -35,8 +35,16 @@ export async function getBitbucketDefaultBranch(
...
     ? `${config.apiBaseUrl}/repositories/${project}/${repoName}`
     : `${config.apiBaseUrl}/projects/${project}/repos/${repoName}/default-branch`;
-
-  const response = await fetch(branchUrl, getBitbucketRequestOptions(config));
+    
+  var response = await fetch(branchUrl, getBitbucketRequestOptions(config));
+  
+  if (response.status === 404  && !isHosted) {
+    // First try the new format, and then if it gets specifically a 404 it should try the old format 
+    // (to support old  Atlassian Bitbucket v5.11.1 format )
```
Comment (OrkoHunter) [inline packages/integration/src/bitbucket/core.ts:43]:
```suggestion
    // (to support old  Atlassian Bitbucket versions < 7.5 ) 
```

**Review by OrkoHunter — APPROVED** [review]
Looks good to me!

**Comment by kaparwan** [comment]
> Please also add a changeset with a `patch` change for `@backstage/integration`. (Detail is in PR description.)

done. thanks

**Comment by OrkoHunter** [comment]
Sorry, prettier is still failing on CI for two files

Use `yarn run prettier --write <filepath>`

**Comment by kaparwan** [comment]
> Sorry, prettier is still failing on CI for two files
> 
> Use `yarn run prettier --write <filepath>`



> Sorry, prettier is still failing on CI for two files
> 
> Use `yarn run prettier --write <filepath>`

It is done. thanks.

File: packages/integration/src/bitbucket/core.ts [hunk 7]
```diff
@@ -36,7 +36,15 @@ export async function getBitbucketDefaultBranch(
     ? `${config.apiBaseUrl}/repositories/${project}/${repoName}`
     : `${config.apiBaseUrl}/projects/${project}/repos/${repoName}/default-branch`;
 
-  const response = await fetch(branchUrl, getBitbucketRequestOptions(config));
+  var response = await fetch(branchUrl, getBitbucketRequestOptions(config));
```
Comment (OrkoHunter) [inline packages/integration/src/bitbucket/core.ts:39]: Use `let` instead of `var`.

Comment (kaparwan) [reply packages/integration/src/bitbucket/core.ts]: fixed lint errors.

**Comment by kaparwan** [comment]
Hi @OrkoHunter 
except the  "documentation quality check " all other CI steps are  green now ;-) 
Would you like to fix this Doc quality check please ?  I was thinking this PR is for doc-for-code fix...  :-)

File: .changeset/wicked-boxes-taste.md [hunk 8]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/integration': major
+---
+
+#4322 bitbucket own hosted v5.11.1 branchUrl fix and enabled error tracing… #4347
```
Comment (OrkoHunter) [inline .changeset/wicked-boxes-taste.md:5]:
```suggestion
#4322 Bitbucket own hosted v5.11.1 branchUrl fix and enabled error tracing… #4347
```

**Comment by OrkoHunter** [comment]
We have a language linter so `bitbucket` just needed to be `Bitbucket`!

**Comment by kaparwan** [comment]
Doc Quality check now ok.  thanks
further Fossa/Build - is due to  "502 Bad Gateway" nginx proxy? etc. from build server ...

**Comment by OrkoHunter** [comment]
Yeah, ignore FOSSA. It's a known issue. #4240 

This LGTM!

**Review by freben — APPROVED** [review]
