### PR TITLE
tech-radar: add description dialog box

### LINKED ISSUE #4493: technology radar doesn't utilize description
When I follow the documentation for adding data to the technology radar it lists url and description in the data structure.  It would seem logical that this data would be shown to users somewhere within the interface.

## Expected Behavior

Description data is shown to the user in some fashion

## Current Behavior

nothing, data is not being utilized

## Possible Solution

Update the technology radar plugin to display the description when the user hovers over a blip or the name of the technology or both.

## Steps to Reproduce

if you just visit the default tech radar and click around you'll see it does not utilize the description field in any way.

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information: chrome

### PR DESCRIPTION
**Pull request by johnnyiller**
## Hey, I just made a Pull Request!

I added a dialog popup to the tech radar that will show up if you have a timeline entry and a description otherwise the functionality is  #unchanged.

Closes #4493 

handle_description

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4580-ajaldqmijihq1vuebaop5l6v9junflnd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/602e9a8765f817ecc7f3a73d

**Review by adamdmharvey — CHANGES_REQUESTED** [review]
Really nice incremental update!  Well done.  I like how the popup comes up.

I will say it's not clear to me as a user there IS more info to learn about if I click, i.e. I sort of have to click each of them to see which even have a description or a link, but that can likely be handled separately. The intent of this PR to suit your issue seems spot on.

Minor comment about the button itself

**Comment by adamdmharvey** [comment]
(and I'll add, having the Tugboat preview is great since I could use that to see how it works 👏 thanks @blam and team)

File: plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+      <DialogContent dividers>{description}</DialogContent>
+      {url && (
+        <DialogActions>
+          <Button
+            onClick={handleClick}
+            color="primary"
+            startIcon={<LinkIcon />}
+            variant="contained"
+          >
+            Visit URL
```
Comment (adamdmharvey) [inline plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx:54]: oops lost my comment!

Suggest this be "Learn More". To an end user, they aren't WANTING to "visit a url", they would want to click the button to find more out about this tech radar suggestion.

Trying to align to some good suggestions here https://material.io/components/buttons#text-button which I've recently been made aware the maintainers are intending to continue to align to (in alignment with the overall use of the Material-UI react library).

**Review by adamdmharvey — CHANGES_REQUESTED** [review]

File: plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx (hunk 1 above)
Comment (johnnyiller) [reply plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx:54]: makes more sense I'll update.

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4580-ajaldqmijihq1vuebaop5l6v9junflnd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/602e9a8765f817ecc7f3a73d

**Comment by johnnyiller** [comment]
@adamdmharvey it looks like the FOSSA check failed due to some error beyond my control.  Is there any way to retry that build step without pushing a new commit?

**Comment by freben** [comment]
Don't worry about fossa - it is flaky but non-essential. :)

File: plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+export type Props = {
+  open: boolean;
+  onClose: () => void;
+  title: string;
+  description: string;
+  url?: string;
+};
+
+const RadarDescription = (props: Props): JSX.Element => {
+  // const classes = useStyles(props);
```
Comment (freben) [inline plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx:32]: Remove?

File: plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+  };
+
+  return (
+    <Dialog data-testid="radar-description" open={open} onClose={onClose}>
+      <DialogTitle id="radar-description-dialog-title">{title}</DialogTitle>
+      <DialogContent dividers>{description}</DialogContent>
+      {url && (
+        <DialogActions>
+          <Button
+            onClick={handleClick}
```
Comment (freben) [inline plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx:49]: Just slap an `href` on the button which makes it act like a normal link, no need to close something that we'll immediately navigate away from

File: plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+  const handleClick = () => {
+    onClose();
+    if (url) {
+      window.location.href = url;
+    }
+  };
+
+  return (
+    <Dialog data-testid="radar-description" open={open} onClose={onClose}>
+      <DialogTitle id="radar-description-dialog-title">{title}</DialogTitle>
```
Comment (freben) [inline plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx:44]: Probably make this a test id instead

File: plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+          >
+            LEARN MORE
+          </Button>
+        </DialogActions>
+      )}
+    </Dialog>
+  );
+};
+
+export default RadarDescription;
```
Comment (freben) [inline plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx:61]: Avoid default exports :) https://backstage.io/docs/architecture-decisions/adrs-adr003

File: plugins/tech-radar/src/components/RadarEntry/RadarEntry.tsx [hunk 6]
```diff
@@ -82,9 +100,32 @@ const RadarEntry = (props: Props): JSX.Element => {
...
+            className={classes.link}
+            onClick={handleClickOpen}
+            href={url ? url : '#'}
+            role="button"
+            tabIndex={0}
+            onKeyPress={toggle}
+          >
+            {blip}
+          </a>
+          <RadarDescription
```
Comment (freben) [inline plugins/tech-radar/src/components/RadarEntry/RadarEntry.tsx:116]: Hm I'm concerned that we'd be rendering hundreds of (closed) dialogs, feels like the parent should hold a single dialog that gets toggled on click with some certain data in it instead :)

Like, having a useState that holds undefined or a radar entry, and then the dialog `open` prop is connected to whether the state is undefined or not...that kind of thing

Comment (johnnyiller) [reply plugins/tech-radar/src/components/RadarEntry/RadarEntry.tsx:116]: Thanks for the review, I think it only renders to the dom when actually in the open state from what I can tell but I catch your drift and can try to rework it.  I'm not really sure how to move the dialog into the parent, if there is some pattern that is usually followed I could give it a go.

File: plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx (hunk 5 above)
Comment (johnnyiller) [reply plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx:61]: okay will change

File: plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx (hunk 2 above)
Comment (johnnyiller) [reply plugins/tech-radar/src/components/RadarDescription/RadarDescription.tsx:32]: yes, sorry I missed it.

**Review by adamdmharvey — APPROVED** [review]
Good from my side; thx! Unlocking my change req.

File: plugins/tech-radar/src/components/RadarEntry/RadarEntry.tsx (hunk 6 above)
Comment (johnnyiller) [reply plugins/tech-radar/src/components/RadarEntry/RadarEntry.tsx]: I figured since I don't need the component unless open=true that I would just not render it unless open=true

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4580-ajaldqmijihq1vuebaop5l6v9junflnd.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/602e9a8765f817ecc7f3a73d

**Comment by johnnyiller** [comment]
@freben I have addressed all your concerns.  Please let me know if there are any other suggestions.

**Review by freben — APPROVED** [review]
