### PR TITLE
fix: better error around github teams not found

### LINKED ISSUE #10160: HttpError: Not Found when scaffolding with GitHub team that doesn't exist
1. Scaffold repo with GitHub provider
2. Inside of template have a parameter for a GitHub team to assign access to
3. Provide a GitHub team that doesn't exist

The repository gets created but publish fails
```
2022-03-11T20:40:21.973Z HttpError: Not Found
at /app/node_modules/@octokit/core/node_modules/@octokit/request/dist-node/index.js:86:21
```

_Originally posted by @peimanja in https://github.com/backstage/backstage/issues/8263#issuecomment-1065532112_

### PR DESCRIPTION
**Pull request by ballpointcarrot**
## Hey, I just made a Pull Request!

Adds a literate error around the
`createGithubRepoWithCollaboratorsAndTopics` function in order to provide that error in the scaffolder logs. Prior to this, the only thing returned was "Not Found," which didn't provide much information for someone trying to determine what failed in the background.

Fixes #10160

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by ballpointcarrot** [comment]
I may noodle around on this some more; I realize this is just providing more context, but doesn't really help out those that have a new repo with no access now.

Moving back into Draft.

**Comment by ballpointcarrot** [comment]
@Rugvip unsure of process/protocol here, but wanted to resurface since I've moved it back out of draft again. Apologies if bumps are impolite. :(

File: plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts [hunk 1]
```diff
@@ -351,3 +355,22 @@ function extractCollaboratorName(
   if ('user' in collaborator) return collaborator.user;
   return collaborator.team;
 }
+
+async function validateAccessTeam(client: Octokit, access: string) {
+  const [org, team_slug] = access.split('/');
+  try {
+    // Below rule disabled because of a 'getByName' check for a different library
+    // incorrectly triggers here.
```
Comment (Rugvip) [inline plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts:363]: Oh no 😅

File: plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts [hunk 2]
```diff
@@ -351,3 +355,22 @@ function extractCollaboratorName(
...
+    // eslint-disable-next-line testing-library/no-await-sync-query
+    await client.rest.teams.getByName({
+      org,
+      team_slug,
+    });
+  } catch (e) {
+    if (e.response.data.message === 'Not Found') {
+      const message = `Received 'Not Found' from the API; one of org:
+        ${org} or team: ${team_slug} was not found within GitHub.`;
+      throw new Error(message, { cause: e });
```
Comment (Rugvip) [inline plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts:373]: `ForwardedError` from `@backstage/errors` provides a pattern for this as well. In this case I actually think we may want to ignore the cause and create a new error though. In that case probably a `NotFoundError`.

File: plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts [hunk 3]
```diff
@@ -351,3 +355,22 @@ function extractCollaboratorName(
...
+async function validateAccessTeam(client: Octokit, access: string) {
+  const [org, team_slug] = access.split('/');
+  try {
+    // Below rule disabled because of a 'getByName' check for a different library
+    // incorrectly triggers here.
+    // eslint-disable-next-line testing-library/no-await-sync-query
+    await client.rest.teams.getByName({
+      org,
+      team_slug,
+    });
```
Comment (Rugvip) [inline plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts:368]: Just to see if we can be a bit more efficient here, is there no way to determine that this was the reason that the repo creation failed? If not, I think we could perhaps flip this around so that this request is only made in the event that repo creation fails to highlight the error. That way we avoid an extra request for the happy path.

**Review by Rugvip — CHANGES_REQUESTED** [review]
Thank you! 👍 

Just a few nits and thoughts

And yep sorry reviews have been a bit slow lately, been some busy weeks

File: plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts (hunk 3 above)
Comment (ballpointcarrot) [reply plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts:368]: Unfortunately, the problem is that the repo creation itself succeeds in the original implementation; the problem occurs when after the repo is created and the permissions fail to apply. An error kicks you out of the task, and you end up with a bare repo with no contents and no permissions applied. 

This ends up causing headache in scenarios where the person running the task doesn't have permissions to clean up GitHub; they created a bare repo, subsequent runs tell you the repo name is taken, and they need to contact someone else to perform cleanup.

File: plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts (hunk 2 above)
Comment (ballpointcarrot) [reply plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts]: Addressed in https://github.com/backstage/backstage/pull/16059/commits/23f21636358524615a23ed962cff33d296f7d82d

Comment (ballpointcarrot) [reply plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/helpers.ts]: ... and then removed cause in https://github.com/backstage/backstage/pull/16059/commits/67ed63552446b512d549e911e13cd7d36eb36186 😅

**Review by Rugvip — APPROVED** [review]
Thank you! 👍, let's :shipit:
