### PR TITLE
feat(scaffolder): cra add gha integration, fix imports

### LINKED ISSUE #2181: Make sure that example software templates match the example-app
Components that are created should include the correct annotations. Templates should include default annotations suitable for the templates purpose. 
The default annotations in the template should match whatever logic is in the create-app.

When creating a new app with create-app, templates and app logic is the same.

### PR DESCRIPTION
**Pull request by shmidt-i**
## Hey, I just made a Pull Request!
• Bumped @spotify/eslint-config to fix issue mentioned in https://github.com/facebook/react/issues/18819#issuecomment-690621414
• Adjusted CRA templater to include github-actions integration
• Fixed import in github-actions (non-backend-compatible code, needs to be dynamically loaded)
• Fixed bug which caused newly created component to be registered each second if user stays on a StatusModal after success.

Don't really like the import of @backstage/plugin-github-actions inside scaffolder per se, but since it's all a part of E2E flow, me and @benjdlambert  decided that it should be fine 🤷

### CODE REVIEW

**Comment by shmidt-i** [comment]
Fixes #2181

File: plugins/scaffolder-backend/src/scaffolder/stages/templater/cra/index.ts [hunk 1]
```diff
@@ -48,13 +50,33 @@ export class CreateReactAppTemplater implements TemplaterBase {
       },
     });
 
+    const extraAnnotations: Record<string, string> = {};
+    const finalDir = path.resolve(
+      resultDir,
+      options.values.component_id as string,
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/templater/cra/index.ts:56]: these things always scare me a bit, better hope the id didn't contain dots and slashes... we may want to check that the result is below resultDir or something

File: plugins/scaffolder/src/components/JobStatusModal/JobStatusModal.tsx [hunk 2]
```diff
@@ -43,10 +43,11 @@ export const JobStatusModal = ({
   entity,
 }: Props) => {
   const job = useJobPolling(jobId);
+  const jobStatus = job?.status ?? '';
 
   useEffect(() => {
-    if (job?.status === 'COMPLETED') onComplete(job);
-  }, [job, onComplete]);
+    if (jobStatus === 'COMPLETED') onComplete(job!);
+  }, [jobStatus, onComplete]); // eslint-disable-line react-hooks/exhaustive-deps
```
Comment (freben) [inline plugins/scaffolder/src/components/JobStatusModal/JobStatusModal.tsx:50]: hm so job isn't recreated on each return from useJobPolling? this missing dep does look like an actual risk since the effect function may be bound to an old version of the job

File: plugins/scaffolder/src/components/TemplatePage/TemplatePage.tsx [hunk 3]
```diff
@@ -108,27 +108,30 @@ export const TemplatePage = () => {
...
-    if (!componentYaml) {
-      errorApi.post(
-        new Error(
-          `Failed to find component-info.yaml file in ${job.metadata.remoteUrl}.`,
-        ),
+  const handleCreateComplete = useCallback(
+    async (job: Job) => {
+      const componentYaml = job.metadata.remoteUrl?.replace(
+        /\.git$/,
+        '/blob/master/component-info.yaml',
```
Comment (freben) [inline plugins/scaffolder/src/components/TemplatePage/TemplatePage.tsx:115]: hm ok, so this one is hardcoded to github semantics right now

**Review by freben — APPROVED** [review]

File: plugins/scaffolder-backend/src/scaffolder/stages/templater/cra/index.ts (hunk 1 above)
Comment (benjdlambert) [reply plugins/scaffolder-backend/src/scaffolder/stages/templater/cra/index.ts:56]: Good suggestion

**Comment by benjdlambert** [comment]
@shmidt-i do you think you'll get chance to fix this up today?

**Comment by stefanalund** [comment]
What is the status of this one @shmidt-i ?

**Comment by shmidt-i** [comment]
@stefanalund needs https://github.com/spotify/backstage/pull/2658 and that in turn needs my upcoming PR to the https://github.com/azz/eslint-plugin-monorepo/issues/10

**Comment by Rugvip** [comment]
@shmidt-i, we could bring this in as sprint work and finish it up, think that's a good way forward?

**Comment by shmidt-i** [comment]
I have it on me this sprint to finish it up, it's just gets updated (cli-wise) faster than I merge stuff :D

File: packages/app/src/index.tsx [hunk 4]
```diff
@@ -14,8 +14,7 @@
  * limitations under the License.
  */
 
-// eslint-disable-next-line monorepo/no-internal-import
-import '@backstage/cli/asset-types';
+import '@backstage/cli/asset-types/asset-types';
```
Comment (Rugvip) [inline packages/app/src/index.tsx]: Should be same path as before

**Review by Rugvip — APPROVED** [review]

**Comment by freben** [comment]
:shipit:
