### PR TITLE
[Permissions] Require at least one item in allOf/anyOf criteria

### LINKED ISSUE #9280: [Permissions] Ambiguous conditional decision behavior with empty `anyOf` criteria
Conditional policy decisions with empty `anyOf` criteria have ambiguous behavior depending on how they are evaluated (either applied to resources in memory or converted to a database query).

## Expected Behavior

The result should be the same regardless of how conditions are evaluated.

## Current Behavior

Actions are denied when applying these conditions to resources in memory.

Actions are allowed when converting these conditions to a query.

## Possible Solution

Add validation and possibly update static types to prevent empty `allOf` / `anyOf` criteria.

## Steps to Reproduce

1. Enable permissions for backstage
2. Create a policy with the following implementation:
```ts
class TestPolicy implements PermissionPolicy {
  async handle(
    request: PolicyAuthorizeQuery,
    user?: BackstageIdentityResponse,
  ): Promise<PolicyDecision> {
    if (request.permission.resourceType === 'catalog-entity') {
      return createCatalogPolicyDecision({
        anyOf: []
      });
    }
    return {
      result: AuthorizeResult.ALLOW,
    };
  }
}
```
3. Open the catalog page - note that all components are visible
4. Click into a component and open the context menu in the page header
5. The "Unregister entity" option is disabled

## Context

The permission framework allows rules to define
- how they are applied to resources in memory (`apply`)
- how they are converted to a query for use with some storage system (`toQuery`)

Rules can be joined together using `anyOf` and `allOf` within a `PermissionCriteria` object. When applying `PermissionCriteria` to resources in memory, the framework is responsible for evaluating these logical operators. When converting `PermissionCriteria` to a query, the plugin that owns the related resource type is responsible for evaluating these logical operators.

The framework will use `Array.prototype.every` to evaluate `allOf` and `Array.prototype.some` to evaluate `oneOf`. However, the behavior of these APIs is not obvious for empty arrays — `[].every(() => false) === true` while `[].some(() => false) === false`. Instead of requiring every plugin to align with this behavior, we should prevent policies from returning conditional decisions with empty criteria.

## Your Environment

- NodeJS Version (v14): v14.17.6
- Operating System and Version (e.g. Ubuntu 14.04): Darwin 20.6.0 - darwin/x64
- Browser Information: N/A

### PR DESCRIPTION
**Pull request by joeporpeglia**
Signed-off-by: Joe Porpeglia <josephp@spotify.com>

## Hey, I just made a Pull Request!

Closes #9280 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by vinzscam — APPROVED** [review]

File: plugins/permission-node/src/integration/createPermissionIntegrationRouter.ts [hunk 1]
```diff
@@ -38,8 +38,8 @@ const permissionCriteriaSchema: z.ZodSchema<
   PermissionCriteria<PermissionCondition>
 > = z.lazy(() =>
   z.union([
-    z.object({ anyOf: z.array(permissionCriteriaSchema) }),
-    z.object({ allOf: z.array(permissionCriteriaSchema) }),
+    z.object({ anyOf: z.array(permissionCriteriaSchema).nonempty() }),
```
Comment (vinzscam) [inline plugins/permission-node/src/integration/createPermissionIntegrationRouter.ts:41]: shall we add `strict` as well? Just to avoid passing down things like `{ allOf: [...], anyOf: [...] }`

Comment (joeporpeglia) [reply plugins/permission-node/src/integration/createPermissionIntegrationRouter.ts]: Done in 4448ba4!

File: plugins/permission-common/src/types/api.ts [hunk 2]
```diff
@@ -72,14 +72,44 @@ export type PermissionCondition<TParams extends unknown[] = unknown[]> = {
   params: TParams;
 };
 
+/**
+ * Utility type to represent an array with 1 or more elements.
+ * @internal
+ */
+export type NonEmptyArray<T> = [T, ...T[]];
```
Comment (joeporpeglia) [inline plugins/permission-common/src/types/api.ts:79]: The api-reports builder doesn't seem to like this type 🤔 . I'm getting this error while building locally:

```
# Generating package API reports
## Processing plugins/permission-common
Error: Internal Error: Unable to follow symbol for "NonEmptyArray"

You have encountered a software defect. Please consider reporting the issue to the maintainers of this application.
```

Comment (joeporpeglia) [reply plugins/permission-common/src/types/api.ts:79]: Looks like this is due to the `@internal` annotation. Marking as `@public` fixes the issue.

File: plugins/permission-node/src/integration/createConditionTransformer.ts [hunk 3]
```diff
@@ -25,17 +25,31 @@ import {
...
 
+const nonEmpty = <T>(list: T[]): [T, ...T[]] => {
+  if (list.length === 0) {
+    throw new Error(
+      'Invalid conditions provided. Expected at least one item for `allOf`/`anyOf` criteria but received none.',
+    );
+  }
+
+  return list as [T, ...T[]];
+};
```
Comment (mtlewis) [inline plugins/permission-node/src/integration/createConditionTransformer.ts:36]: Can this be expressed as a type assertion?

```suggestion
const nonEmpty = <T>(list: T[]): list is [T, ...T[]] => {
  if (list.length === 0) {
    throw new Error(
      'Invalid conditions provided. Expected at least one item for `allOf`/`anyOf` criteria but received none.',
    );
  }
};
```

Comment (mtlewis) [reply plugins/permission-node/src/integration/createConditionTransformer.ts:36]: Ah I see! That totally makes sense. It does leave me a bit confused about something tangentially related though - given that this code is validating part of an object of type `PermissionCriteria`, shouldn't the type already guarantee that the array won't be empty?

Comment (joeporpeglia) [reply plugins/permission-node/src/integration/createConditionTransformer.ts:36]: Yeah that's what I had hoped, but calling `map` on a `NonEmptyArray` doesn't preserve it's "non-emptiness"

Comment (joeporpeglia) [reply plugins/permission-node/src/integration/createConditionTransformer.ts]: Yup totally agree — it shouldn't be possible to reach that `throw` so casting feels more appropriate here anyway

File: plugins/permission-common/api-report.md [hunk 4]
```diff
@@ -65,6 +75,14 @@ export function isReadPermission(permission: Permission): boolean;
 // @public
 export function isUpdatePermission(permission: Permission): boolean;
 
+// @public
+export type NonEmptyArray<T> = [T, ...T[]];
```
Comment (Rugvip) [inline plugins/permission-common/api-report.md:79]: Possibly unfortunate to export this. If you mark it with `/** @ignore */` you can avoid exporting it without warnings in the API report. The DX of using the criteria should stay the same afaik, as in you'll see the same editor hints

**Review by Rugvip — APPROVED** [review]
👍 , just a minor nit if you agree with it

File: plugins/permission-common/api-report.md (hunk 4 above)
Comment (joeporpeglia) [reply plugins/permission-common/api-report.md:79]: Ah I tried using `@internal` but that broke the api report. I'll give `@ignore` a try!

Comment (Rugvip) [reply plugins/permission-common/api-report.md]: Yeah `@internal` is for when you want to explicitly say that something should not be part of the external API, and API Extractor will then help you enforce that. `@ignore` is for when you wanna tell API Extractor "i know what I'm doing", it's our own invention though.

Update looks 👌
