### PR TITLE
Ignore .git store on Template uploads for editor and increase payload size to 10MB (fixes #12561)

### LINKED ISSUE #12561: Exclude .git directory when uploading template for scaffolder dry-runs
## Expected Behavior

When uploading content for a scaffolder dry-run, I get `payload too large` errors. The easiest way to fix them is to remove the `.git` folder from my local check-out, but that's also complicating things when you work on the templates.

## Actual Behavior

Exclude the `.git` folder from the content uploaded.

## Steps to Reproduce

1. Use the dry-run templating action, uploading a local directory
2. Fill out the form
3. Dry-run the template

## Context

_Originally posted by @leon-vg in https://github.com/backstage/backstage/issues/12176#issuecomment-1168720597_

## Your Environment

backstage 1.3.0

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 20.6.0 - darwin/x64
node: v16.15.1
yarn: 1.22.19
cli:  0.17.2 (installed)

Dependencies:
  @backstage/app-defaults                         1.0.3
  @backstage/backend-common                       0.14.0
  @backstage/backend-tasks                        0.3.2
  @backstage/catalog-client                       1.0.3
  @backstage/catalog-model                        1.0.3
  @backstage/cli-common                           0.1.9
  @backstage/cli                                  0.17.2
  @backstage/config-loader                        1.1.2
  @backstage/config                               1.0.1
  @backstage/core-app-api                         1.0.3
  @backstage/core-components                      0.9.5
  @backstage/core-plugin-api                      1.0.3
  @backstage/errors                               1.0.0
  @backstage/integration-react                    1.1.1
  @backstage/integration                          1.2.1
  @backstage/plugin-api-docs                      0.8.6
  @backstage/plugin-app-backend                   0.3.33
  @backstage/plugin-auth-backend                  0.14.1
  @backstage/plugin-auth-node                     0.2.2
  @backstage/plugin-catalog-backend-module-github 0.1.4
  @backstage/plugin-catalog-backend               1.2.0
  @backstage/plugin-catalog-common                1.0.3
  @backstage/plugin-catalog-graph                 0.2.18
  @backstage/plugin-catalog-import                0.8.9
  @backstage/plugin-catalog-react                 1.1.1
  @backstage/plugin-catalog                       1.3.0
  @backstage/plugin-github-actions                0.5.6
  @backstage/plugin-org                           0.5.6
  @backstage/plugin-permission-common             0.6.2
  @backstage/plugin-permission-node               0.6.2
  @backstage/plugin-permission-react              0.4.2
  @backstage/plugin-proxy-backend                 0.2.27
  @backstage/plugin-scaffolder-backend            1.3.0
  @backstage/plugin-scaffolder-common             1.1.1
  @backstage/plugin-scaffolder                    1.3.0
  @backstage/plugin-search-backend-node           0.6.2
  @backstage/plugin-search-backend                0.5.3
  @backstage/plugin-search-common                 0.3.5
  @backstage/plugin-search-react                  0.2.1
  @backstage/plugin-search                        0.9.0
  @backstage/plugin-tech-radar                    0.5.13
  @backstage/plugin-techdocs-backend              1.1.2
  @backstage/plugin-techdocs-node                 1.1.2
  @backstage/plugin-techdocs-react                1.0.1
  @backstage/plugin-techdocs                      1.2.0
  @backstage/plugin-user-settings                 0.4.5
  @backstage/release-manifests                    0.0.4
  @backstage/test-utils                           1.1.1
  @backstage/theme                                0.2.15
  @backstage/types                                1.0.0
  @backstage/version-bridge                       1.0.1

```

### PR DESCRIPTION
**Pull request by Pike**
Signed-off-by: Axel Hecht <axel@pike.org>

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/scaffolder-backend/src/service/router.ts [hunk 1]
```diff
@@ -148,7 +148,8 @@ export async function createRouter(
   options: RouterOptions,
 ): Promise<express.Router> {
   const router = Router();
-  router.use(express.json());
+  // Be generous in upload size to support a wide rande of templates in dry-run mode.
```
Comment (Rugvip) [inline plugins/scaffolder-backend/src/service/router.ts:151]:
```suggestion
  // Be generous in upload size to support a wide range of templates in dry-run mode.
```

**Review by Rugvip — APPROVED** [review]
Nice, thank you! 👍
