### PR TITLE
fix: allow reserved characters in all parameters

### LINKED ISSUE #23973: 🐛 Bug Report: Parameter 'term' must be url encoded.
### 📜 Description

When clicking on `Search` and trying to search with a space on the name `text text` (white space between both text strings) getting an error 400 back.

### 👍 Expected behavior

Search is able to be done with space in it

### 👎 Actual Behavior with Screenshots

image

### 👟 Reproduction steps

- Backstage Home Page
- Top left panel click `Search`
- type `text text` into the search 

### 📃 Provide the context for the Bug.

Not able to search with a whitespace in the text.

OS: vf-cep-backstage-597db888f4-8qddm: Linux 5.10.210-201.855.amzn2.x86_64 - linux/x64
Resources: Memory: 4703/31737MB - Load: 2.00/2.10/2.16
node: v18.20.0
backstage: 1.25.1
Dependencies:
    @backstage/backend-app-api: 0.5.10, 0.5.14, 0.5.8, 0.6.2
    @backstage/backend-common: 0.19.10, 0.19.9, 0.20.1, 0.21.3, 0.21.6
    @backstage/backend-dev-utils: 0.1.2, 0.1.3, 0.1.4
    @backstage/backend-openapi-utils: 0.1.0, 0.1.6
    @backstage/backend-plugin-api: 0.6.13, 0.6.16, 0.6.7, 0.6.9
    @backstage/backend-tasks: 0.5.12, 0.5.14, 0.5.18, 0.5.21
    @backstage/catalog-client: 1.4.6, 1.5.2, 1.6.0, 1.6.3
    @backstage/catalog-model: 1.4.3, 1.4.4, 1.4.5
    @backstage/cli-common: 0.1.13
    @backstage/cli-node: 0.1.5, 0.2.0, 0.2.2, 0.2.3, 0.2.4
    @backstage/cli: 0.23.1
    @backstage/config-loader: 1.5.3, 1.6.1, 1.6.2, 1.7.0
    @backstage/config: 1.1.1, 1.2.0
    @backstage/e2e-test-utils: 0.1.0
    @backstage/errors: 1.2.3, 1.2.4
    @backstage/eslint-plugin: 0.1.3
    @backstage/integration-aws-node: 0.1.12, 0.1.8, 0.1.9
    @backstage/integration: 1.7.2, 1.8.0, 1.9.0, 1.9.1
    @backstage/plugin-auth-backend-module-gcp-iap-provider: 0.2.1
    @backstage/plugin-auth-backend-module-github-provider: 0.1.4
    @backstage/plugin-auth-backend-module-gitlab-provider: 0.1.4
    @backstage/plugin-auth-backend-module-google-provider: 0.1.4
    @backstage/plugin-auth-backend-module-oauth2-provider: 0.1.4
    @backstage/plugin-auth-backend: 0.19.4
    @backstage/plugin-auth-node: 0.4.1, 0.4.11, 0.4.3, 0.4.8
    @backstage/plugin-azure-devops-backend: 0.5.1
    @backstage/plugin-azure-devops-common: 0.3.2
    @backstage/plugin-catalog-backend-module-azure: 0.1.26
    @backstage/plugin-catalog-backend-module-github: 0.4.5
    @backstage/plugin-catalog-backend-module-scaffolder-entity-model: 0.1.4
    @backstage/plugin-catalog-backend-module-unprocessed: 0.3.6
    @backstage/plugin-catalog-backend: 1.15.0
    @backstage/plugin-catalog-common: 1.0.18, 1.0.20
    @backstage/plugin-catalog-node: 1.5.0, 1.6.1
    @backstage/plugin-devtools-backend: 0.2.6
    @backstage/plugin-devtools-common: 0.1.8
    @backstage/plugin-events-node: 0.2.16
    @backstage/plugin-linguist-backend: 0.5.4
    @backstage/plugin-linguist-common: 0.1.2
    @backstage/plugin-permission-backend: 0.5.32
    @backstage/plugin-permission-common: 0.7.10, 0.7.12, 0.7.13
    @backstage/plugin-permission-node: 0.7.18, 0.7.20, 0.7.24, 0.7.27
    @backstage/plugin-proxy-backend: 0.4.5
    @backstage/plugin-scaffolder-backend: 1.19.1
    @backstage/plugin-scaffolder-common: 1.4.3
    @backstage/plugin-scaffolder-node: 0.2.8
    @backstage/plugin-search-backend-module-catalog: 0.1.11
    @backstage/plugin-search-backend-module-pg: 0.5.22
    @backstage/plugin-search-backend-module-techdocs: 0.1.11
    @backstage/plugin-search-backend-node: 1.2.11, 1.2.17
    @backstage/plugin-search-backend: 1.4.7
    @backstage/plugin-search-common: 1.2.8, 1.2.10
    @backstage/plugin-tech-insights-backend-module-jsonfc: 0.1.48
    @backstage/plugin-tech-insights-backend: 0.5.30
    @backstage/plugin-tech-insights-common: 0.2.12
    @backstage/plugin-tech-insights-node: 0.4.15, 0.5.2
    @backstage/plugin-techdocs-backend: 1.9.0
    @backstage/plugin-techdocs-node: 1.10.0
    @backstage/plugin-todo-backend: 0.3.5
    @backstage/release-manifests: 0.0.10
    @backstage/repo-tools: 0.6.3
    @backstage/types: 1.1.1

### 🖥️ Your Environment

All pour environments are affected by this issue

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue
Maybe similar to this https://github.com/backstage/backstage/issues/19499 but not the same.

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by aramissennyeydd**
## Hey, I just made a Pull Request!

Fixes #23973 and adds a linting check for this in the future.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: packages/repo-tools/src/lib/runner.ts [hunk 1]
```diff
@@ -37,6 +37,7 @@ export async function runner(
       port: options.startingPort,
       stopPort: options.startingPort + 1_000,
     }));
+  console.log(packages);
```
Comment (tudi2d) [inline packages/repo-tools/src/lib/runner.ts:40]: did you intend to add this here or was it for debugging purposes only?

Comment (aramissennyeydd) [reply packages/repo-tools/src/lib/runner.ts:40]: 😅 , debugging, will remove.

**Comment by aramissennyeydd** [comment]
@tudi2d I don't think so, it's used to skip an additional layer of validation, see https://github.com/cdimascio/express-openapi-validator/issues/300. Some params can contain unencoded values that other params like `+`. This ends up being a breaking change for APIs that move to OpenAPI tooling if they don't explictly set `allowReserved` to true for parameters, which was a miss in my migration work initially, and I'm hoping the lint rule added here helps. I think this is generally restricted to query parameters, but to be safe I'm casting a wider net for all parameters.

File: .changeset/chatty-crabs-tap.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/repo-tools': minor
+---
+
+Adds a lint rule to `repo schema openapi lint` to enforce `allowReserved: true`.
```
Comment (freben) [inline .changeset/chatty-crabs-tap.md:5]: For people who use these repo tools, they'd need an explanation of what the outcome could be in their repos after this and how to go about addressing it, right?

**Review by freben — COMMENTED** [review]
I just gotta double check.

Is this really a symptom of some API callers forgetting to properly URL encode query parameters? It seems odd to me that `+` (being a perfectly valid space marker in query strings) would need `allowReserved` to be set. Unless the user entered an actual plus sign into their search box, at which point it should have been encoded as `%2B` instead right?

**Comment by aramissennyeydd** [comment]
@freben Not really, it's more a reflection of inconsistent URI encodings for different parts of a URI. The [OpenAPI docs](https://swagger.io/docs/specification/describing-parameters/#Reserved%20Characters%20in%20Query%20Parameters) link out to https://datatracker.ietf.org/doc/html/rfc3986#section-2.2. The OpenAPI specification makes no attempt at allowing different sets of URI component delimiters, so it ends up that `+` is not allowed but the encoded version is in a query string. The decoding of that `+` would be different in path params vs query params, so double encoding it is the safest option. In our case, double encoding it is breaking behavior as it requires anyone that single encoded to double encode, removing that restriction requires setting `allowReserved: true`.

File: .changeset/chatty-crabs-tap.md (hunk 2 above)
Comment (aramissennyeydd) [reply .changeset/chatty-crabs-tap.md:5]: Good call, I'll update.

**Comment by joaquin386** [comment]
Hope this PR can be marge soon, as the allowedReserved characters from an AWS API GW is necessary.

File: packages/repo-tools/src/commands/repo/schema/openapi/lint.ts [hunk 3]
```diff
@@ -47,6 +48,16 @@ async function lint(directoryPath: string, config?: { strict: boolean }) {
   const backstageRuleset = new Ruleset(
     {
       extends: [oas, ruleset],
+      rules: {
```
Comment (vinzscam) [inline packages/repo-tools/src/commands/repo/schema/openapi/lint.ts:51]: is the linting necessary? If `allowReserved` is disabled by default maybe we should keep the same behaviour and just fix the plugins which are currently broken? 🤔

Comment (aramissennyeydd) [reply packages/repo-tools/src/commands/repo/schema/openapi/lint.ts:51]: What do you mean? I don't think the right fix here is double encoding client requests.

Comment (vinzscam) [reply packages/repo-tools/src/commands/repo/schema/openapi/lint.ts:51]: usually certain characters are percent encoded to make sure that URLs are correctly interpreted. Otherwise things might go bananas when `/`, `#` or `?` are sent.
I'm worried that setting `allowReserved: true` everywhere might introduce other problems

**Comment by freben** [comment]
Yeah I gotta admit, i am still flabbergasted by this :) I'm probably just dense.

`+` has always as far as i know been meant to be used as the space character replacement in the query part of a URL. Code handles this just fine generally, for example the URL constructor in browsers. But for some reason it was decided that this wasn't safe - maybe people accidentally skipped percent encoding actual pluses? This makes me wonder, ARE we double encoding somewhere "to be safe"? Or are there some other band aids in place, that are actually the source of this being needed at all? Do we need to change those things, rather than making this PR and the large effect it has?

File: packages/repo-tools/src/commands/repo/schema/openapi/lint.ts [hunk 4]
```diff
@@ -47,6 +48,16 @@ async function lint(directoryPath: string, config?: { strict: boolean }) {
...
+        'allow-reserved-in-params': {
+          given: '$.paths..parameters[*]',
+          then: {
+            field: 'allowReserved',
+            function: truthy,
```
Comment (Rugvip) [inline packages/repo-tools/src/commands/repo/schema/openapi/lint.ts:56]: An option here could be to lint for `allowReserved` being set, but allowing it to be `false`? I'd only want to do that if it's still very clear that `true` is the preferred value that should basically always be used though. Just thinking it can be nice to have an escape hatch if absolutely necessary, but kinda low prio tbh

Comment (aramissennyeydd) [reply packages/repo-tools/src/commands/repo/schema/openapi/lint.ts:56]: Hmm, yeah I think that's lower prio. The application can handle rejecting invalid pieces of the URL or incorrectly interpreting them, I don't think having it in the spec adds a bunch of value.

**Comment by Rugvip** [comment]
👍 , gonna :shipit: so that we have these fixes in the release tomorrow
