### PR TITLE
fix: page hader

### LINKED ISSUE #14026: Add/improve labels in banner when viewing an entity from Docs
When viewing an entity from the **Docs** link, the banner may confuse users for the following reasons:

* The "Component" label is misleading; a `kind: Resource` entity can also have documentation
* The `<>` icon may not be intuitive to non-technical users 

image

## Feature Suggestion

* Update the "Component" label to "Entity"
* Add `source` label below the `<>` icon

## Context

As a new Backstage user, I was confused by the some of the labels when viewing an entity from the **Docs** link

### PR DESCRIPTION
**Pull request by ilteoood**
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

image

Closes #14026 
cc: @simoneb

### CODE REVIEW

File: plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx [hunk 1]
```diff
@@ -102,7 +103,7 @@ export const TechDocsReaderPageHeader = (
   const labels = (
     <>
       <HeaderLabel
-        label="Component"
+        label="Entity"
```
Comment (awanlin) [inline plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx:106]: Could we use the Kind name (Component, Resource, API, etc.) instead and fall back to "Entity" if that's not provided? I'm sure this information is already available or easy to get at

**Review by awanlin — CHANGES_REQUESTED** [review]
Hi @ilteoood, thanks for the contribution, this is great. Left one small comment

Also, you'll want to add a changeset, here's the details on how to do that: https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets

File: plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx (hunk 1 above)
Comment (ilteoood) [reply plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx]: I found it and applied your suggestion!

File: .changeset/witty-horses-press.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/plugin-techdocs': minor
+---
+
+feat: tech doc reader page hader now has a explicit label for code icon
```
Comment (awanlin) [inline .changeset/witty-horses-press.md:5]: Sorry, looks like you add this just as I left my note about this. Thanks!

There's a small typo - "hader" should be "header". Keep in mind these will be used a release notes so they should be a descriptive. Something like "Updated TechDocs header to include label for source code icon and updated label to reflect Kind name"

File: plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx (hunk 1 above)
Comment (awanlin) [reply plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx]: Awesome, thanks!

File: .changeset/witty-horses-press.md (hunk 2 above)
Comment (ilteoood) [reply .changeset/witty-horses-press.md]: I've applied your suggestion for the content, may thanks!

Comment (awanlin) [reply .changeset/witty-horses-press.md]: Sweet 👍

**Review by awanlin — APPROVED** [review]
Looks good to me, now you'll just need the Backstage maintainers to do their review

**Review by simoneb — COMMENTED** [review]
Based on the original request in the issue, and for consistency with the existing UI, shouldn't the Source label be below the symbol?

**Comment by ilteoood** [comment]
ping this

File: plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx [hunk 3]
```diff
@@ -102,7 +103,7 @@ export const TechDocsReaderPageHeader = (
   const labels = (
     <>
       <HeaderLabel
-        label="Component"
+        label={entityMetadata?.kind || 'Entity'}
```
Comment (agentbellnorm) [inline plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx:106]: For consistency with the other header labels, we probably want this to be capitalized. For example `component` should be `Component`. And edge case is `api` which should probably be `API`.

Do you have a suggestion for how we could solve this?

File: plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx [hunk 4]
```diff
@@ -131,14 +132,21 @@ export const TechDocsReaderPageHeader = (
         <HeaderLabel
           label=""
           value={
-            <a
-              href={locationMetadata.target}
-              target="_blank"
-              rel="noopener noreferrer"
+            <Grid
+              container
+              direction="row"
```
Comment (agentbellnorm) [inline plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx:137]: Since the other labels are aligned vertically, could we make this one vertical as well by using `direction="column"`?

**Review by agentbellnorm — COMMENTED** [review]
Hi @ilteoood, thanks a lot for taking the time to contribute!

I made two comments based on the linked issue. Let me know what you think!

File: plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx (hunk 3 above)
Comment (teobmg) [reply plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx:106]: Maybe we could define a map of how we want to rename each kind?

File: plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx (hunk 4 above)
Comment (teobmg) [reply plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx:137]: Sure, I could try and let you know the final result

File: plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx (hunk 3 above)
Comment (ilteoood) [reply plugins/techdocs/src/reader/components/TechDocsReaderPageHeader/TechDocsReaderPageHeader.tsx]: For now, I've used the `capitalize` function.

**Comment by ilteoood** [comment]
Hey @agentbellnorm I should have addressed all your comments.
Please let me know if I have to do something else!

**Comment by ilteoood** [comment]
Ping @agentbellnorm

**Review by soapraj — APPROVED** [review]

**Comment by soapraj** [comment]
cc @backstage/reviewers for review/approval

**Review by agentbellnorm — APPROVED** [review]

**Comment by ilteoood** [comment]
Can someone merge this?

**Review by Rugvip — APPROVED** [review]
:shipit: !

**Comment by suuus** [comment]
Thank you for contributing during Hacktoberfest 🍂! You can claim the Backstage Hacktoberfest Holopin at https://bck.st/hacktoberfest-holopin 🙌🏻
