### PR TITLE
[Analytics] Handle gathered mountpoints

### LINKED ISSUE #17998: 🐛 Bug Report: `navigate` events' `pluginId` is always `root` on gathered routes
### 📜 Description

The Analytics API will fire a `navigate` event when react router's location changes.  If there is a routable extension whose mountpoint matches the path that was navigated to, metadata from that extension (including the `pluginId`) will decorate the event.

For example, if the following is wired up in the app `<Route path="/docs" element={<TechDocsIndexPage />} />`, then any navigation to `/docs` will fire a `navigate` event with `context.pluginId` set to `techdocs` (which provided the `<TechDocsIndexPage>` routable extension).

This behavior is not working when a navigation is made to a gathered mountpoint (e.g. anything using `<EntityLayout.Route />`, `<TabbedLayout.Route />`, etc).  In such cases, the `pluginId` will be the default `root`.

### 👍 Expected behavior

The contextual `pluginId` value on the `navigate` event should accurately reflect the plugin associated with the routable extension that was mounted and rendered.

```json
{
  "action": "navigate",
  "subject": "/catalog/default/component/foo/docs",
  "context": {
    "routeRef": "techdocs:catalog-reader-view",
    "pluginId": "techdocs",
    "extension": "App"
  }
}
```

### 👎 Actual Behavior with Screenshots

```json
{
  "action": "navigate",
  "subject": "/catalog/default/component/foo/docs",
  "context": {
    "routeRef": "techdocs:catalog-reader-view",
    "pluginId": "root",
    "extension": "App"
  }
}
```

### 👟 Reproduction steps

Set up an API implementation that `console.log`s the relevant bits of the analytics event, like this:

```diff
diff --git a/packages/app/src/apis.ts b/packages/app/src/apis.ts
index f348d2446612..17898b2afb13 100644
--- a/packages/app/src/apis.ts
+++ b/packages/app/src/apis.ts
@@ -29,6 +29,7 @@ import {
 } from '@backstage/plugin-graphiql';
 import {
   AnyApiFactory,
+  analyticsApiRef,
   configApiRef,
   createApiFactory,
   discoveryApiRef,
@@ -71,4 +72,9 @@ export const apis: AnyApiFactory[] = [
   }),
 
   createApiFactory(costInsightsApiRef, new ExampleCostInsightsClient()),
+  createApiFactory(analyticsApiRef, {
+    captureEvent: e => {
+      console.log({ action: e.action, subject: e.subject, ...e.context });
+    }
+  })
 ];
```

Navigate around various tabs of an entity in the Catalog.

### 📃 Provide the context for the Bug.

There are basically 5 possible cases when a `navigate` event fires.  The two that work as expected today are:

- **No routable extension**: It's possible for adopters to supply a `<Route>` whose element is a custom React component that was not created via `createRoutableExtension()`. In this case, it only makes sense to supply the default contextual info (`root` plugin, `unknown` routeRef)
- **Mounted extension**: In the case where a routable extension is directly mounted to a path, we would expect that the `routeRef` and `plugin` metadata to come from the extension itself.

The following are not functioning as expected:

- **Gathered Mountpoint, Single Extension**: In this case, an adopter has used something like `<EntityLayout.Route>` and placed only a single plugin's routable extension underneath it.  In this case, it makes sense to assume the `pluginId` and `routeRef` correspond to the one extension's.  ...And while we accurately reflect the `routeRef` today, we do not accurately reflect the `pluginId` (which comes through as the default `root`).

- **Gathered Mountpoint, Multiple Extensions, Single Rendered**: This is common when multiple plugins' routable extensions are used conditionally on a single entity tab (e.g. jenkins vs. github actions on the `/ci-cd` tab). In this case, it would make sense to assume the `pluginId` and `routeRef` corresponding to the _rendered_ extension should be reflected on the `navigate` event.

- **Gathered Mountpoint, Multiple Extensions, Multiple Rendered**: There is nothing constraining rendering of multiple routable extensions under a gathered mountpoint.  ...It's not clear what the behavior should be in this case, but it's probably uncommon enough that we can define something arbitrary and document it...

...For the latter two cases, because the metadata needed is ultimately a render-time concern (rather than something declarative that can be introspected from route configuration), a creative solution will be needed...

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by iamEAP**
## What / Why

This PR attempts to address a shortcoming of the current implementation of `navigate` event tracking: capturing accurate plugin and/or route context when routing is built up using, e.g. `<EntityLayout>` or `<TabbedLayout>` components.

There are conceptually two changes to support this:

1. Replaces `plugin` key with `plugins` set to `BackstageRouteObject` (a complement to `routeRefs` as a set), which allows the route tracker to pull the `pluginId` in cases where a gathered mountpoint has only one extension underneath it.
2. Adds logic to the main Analytics API `Tracker` that holds back certain `navigate` events (e.g. those corresponding to `gathered` mountpoints with default `pluginId` metadata).  Such a `navigate` event is held back until the next "real" event is seen, at which point, the `navigate` event is fired, but decorated with contextual metadata from the most recently rendered routable extension.  A `beforeunload` handler is added that fires any un-fired `navigate` events to ensure we don't miss any data.
   
This approach has a couple of less-than-ideal consequences:

- For analytics systems that expose or make use of event timing, the timing of these events would be off (although the order would at least be preserved).  ...Due to the render-time nature of gathered mountpoints, this may be unavoidable (e.g. one CI/CD routable extension may be rendered for one entity, and another for a different entity, based entirely on the annotations set on each entity).
- If multiple routable extensions are rendered under a single gathered mountpoint, the last rendered extension's metadata would be associated with the navigation.  ...Due to the render-time nature of gathered mountpoints, this may be unavoidable.

closes #17998 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: packages/core-app-api/src/routing/types.ts [hunk 1]
```diff
@@ -54,6 +54,7 @@ export interface BackstageRouteObject {
   element: React.ReactNode;
   path: string;
   routeRefs: Set<RouteRef>;
+  plugins: Set<BackstagePlugin>;
   plugin?: BackstagePlugin;
```
Comment (Rugvip) [inline packages/core-app-api/src/routing/types.ts:58]: Thinking it's worth getting rid of `plugin` while we're at it? 😁

File: packages/core-app-api/src/routing/RouteTracker.tsx [hunk 2]
```diff
@@ -68,8 +70,9 @@ const getExtensionContext = (
 
     return {
       extension: 'App',
-      pluginId: routeObject.plugin?.getId() || 'root',
+      pluginId: plugin?.getId() || 'root',
       ...(routeRef ? { routeRef: (routeRef as { id?: string }).id } : {}),
+      _element: routeObject.element as string,
```
Comment (Rugvip) [inline packages/core-app-api/src/routing/RouteTracker.tsx:75]: I think it's best to move over to some other name than `element` here, we just use that name because it's already part of the routing object in react-router. Maybe something like `_routeNodeType`?

File: packages/core-plugin-api/src/analytics/Tracker.ts [hunk 3]
```diff
@@ -21,6 +21,24 @@ import {
...
+  attributes?: AnalyticsEventAttributes;
+  context: AnalyticsContextValue;
+}> = [];
+
+/**
+ * Global storing recent routable extension renders.
+ */
+const routableExtensionRenders: Array<{
+  context: AnalyticsContextValue;
+}> = [];
```
Comment (Rugvip) [inline packages/core-plugin-api/src/analytics/Tracker.ts:40]: Since all we do is push and pop + clear, these can just be single optional values rather than arrays right? Feel that could potentially clean up the logic a bit too

File: packages/core-plugin-api/src/analytics/Tracker.ts [hunk 4]
```diff
@@ -43,13 +61,69 @@ export class Tracker implements AnalyticsTracker {
...
+    }
+
+    // Never directly fire a navigation event on a gathered route with default
+    // contextual details.
+    if (
+      action === 'navigate' &&
+      _element === 'gathered' &&
+      context.pluginId === 'root'
+    ) {
+      // Instead, push it onto the global store.
```
Comment (Rugvip) [inline packages/core-plugin-api/src/analytics/Tracker.ts:109]: Is there a risk that we have hold extension renders laying around at this point that would get incorrectly associated with this gathered navigation? i.e. should we clear `routableExtensionRenders` here?

File: packages/core-plugin-api/src/analytics/Tracker.ts [hunk 5]
```diff
@@ -43,13 +61,69 @@ export class Tracker implements AnalyticsTracker {
...
+      gatheredNavigations.push({
+        action,
+        subject,
+        value,
+        attributes,
+        context,
+      });
```
Comment (Rugvip) [inline packages/core-plugin-api/src/analytics/Tracker.ts:116]: Ah, so as long as the user doesn't close the page at this point, we'll generally always emit a more accurate event later? Regardless of whether the user interacts on the page or navigates away, we'll end up with the gathered navigation being emitted later.

So the tradeoff with this approach is that we might drop some events if the page is closed, and we might have some situations where the next even happens before we're able to capture the rendered extension, so there might be a bit of flakiness in some analytics events wrt their reported plugin ID?

File: packages/core-plugin-api/src/extensions/extensions.tsx [hunk 6]
```diff
@@ -101,6 +103,15 @@ export function createRoutableExtension<
                 }
                 throw error;
               }
+
+              // This event, never exposed to end-users of the analytics API,
+              // helps inform which extension metadata gets associated with a
+              // navigation event when the route navigated to is a gathered
+              // mountpoint.
+              useEffect(() => {
+                analytics.captureEvent('_routable-extension-rendered', '');
```
Comment (Rugvip) [inline packages/core-plugin-api/src/extensions/extensions.tsx:112]: Feeling it's worth defining an internal constant for `'_routable-extension-rendered'`

**Review by Rugvip — CHANGES_REQUESTED** [review]
Interesting 😁

File: packages/core-plugin-api/src/analytics/Tracker.ts (hunk 3 above)
Comment (iamEAP) [reply packages/core-plugin-api/src/analytics/Tracker.ts:40]: Do you think a global singleton from version bridge is warranted, @Rugvip?

File: packages/core-app-api/src/routing/RouteTracker.tsx [hunk 7]
```diff
@@ -51,10 +52,11 @@ const getExtensionContext = (
     }
 
     // If there is a single route ref, return it.
-    // todo: get routeRef of rendered gathered mount point(?)
     let routeRef: RouteRef | undefined;
+    let plugin: BackstagePlugin | undefined;
     if (routeObject.routeRefs.size === 1) {
       routeRef = routeObject.routeRefs.values().next().value;
+      plugin = routeObject.plugins.values().next().value;
```
[the remark this answers is not in the document]
Comment (iamEAP) [reply packages/core-app-api/src/routing/RouteTracker.tsx:63]: I couldn't imagine a scenario where it would be different, but may as well set it in its own block.

File: packages/core-plugin-api/src/analytics/Tracker.ts (hunk 4 above)
Comment (iamEAP) [reply packages/core-plugin-api/src/analytics/Tracker.ts]: Think swapping this from an array to a single optional value clarifies what's going on here a bit. Lemme know if not!

File: packages/core-plugin-api/src/analytics/Tracker.ts (hunk 5 above)
Comment (iamEAP) [reply packages/core-plugin-api/src/analytics/Tracker.ts]: > _Ah, so as long as the user doesn't close the page at this point, we'll generally always emit a more accurate event later? Regardless of whether the user interacts on the page or navigates away, we'll end up with the gathered navigation being emitted later._

Yep.  We could even mitigate for the "close the page" scenario by adding a `beforeunload` event handler?

**Comment by iamEAP** [comment]
Back to you for consideration, @Rugvip

**Comment by iamEAP** [comment]
Un-stale'ing.  @Rugvip, any chance you can take a look before the next release?

**Comment by Rugvip** [comment]
@iamEAP will try :sweat_smile:

**Review by Rugvip — APPROVED** [review]
Solid work! 👍 🎉 

Let's :shipit: 🤞
