### PR TITLE
Remove usages of `srOnly` variant of `Typography`

### LINKED ISSUE #18019: [MUI v5] Typography no longer has srOnly variant
### 📜 Description

When upgrading to MUI v5 there are type errors from using the `srOnly` variant prop with the `Typography` component.

The only usages of this variant are in the `CatalogTable` located here:

- https://github.com/backstage/backstage/blob/36a139d1362f73f2075eb1ba1a928442cfe99a33/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L147
- https://github.com/backstage/backstage/blob/36a139d1362f73f2075eb1ba1a928442cfe99a33/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L166
- https://github.com/backstage/backstage/blob/36a139d1362f73f2075eb1ba1a928442cfe99a33/plugins/catalog/src/components/CatalogTable/CatalogTable.tsx#L186

The error is:

```text
No overload matches this call.
  Overload 1 of 2, '(props: { component: ElementType<any>; } & SystemProps<Theme> & { align?: "left" | "right" | "inherit" | "center" | "justify" | undefined; children?: ReactNode; ... 6 more ...; variantMapping?: Partial<...> | undefined; } & CommonProps & Omit<...>): Element | null', gave the following error.
    Type '"srOnly"' is not assignable to type 'OverridableStringUnion<"inherit" | Variant, TypographyPropsVariantOverrides> | undefined'.
  Overload 2 of 2, '(props: DefaultComponentProps<TypographyTypeMap<{}, "span">>): Element | null', gave the following error.
    Type '"srOnly"' is not assignable to type 'OverridableStringUnion<"inherit" | Variant, TypographyPropsVariantOverrides> | undefined'.
```

### 👍 Expected behavior

There should be no type errors when using the MUI v5 `Typography` component.

### 👎 Actual Behavior with Screenshots

We get this type error:

```text
No overload matches this call.
  Overload 1 of 2, '(props: { component: ElementType<any>; } & SystemProps<Theme> & { align?: "left" | "right" | "inherit" | "center" | "justify" | undefined; children?: ReactNode; ... 6 more ...; variantMapping?: Partial<...> | undefined; } & CommonProps & Omit<...>): Element | null', gave the following error.
    Type '"srOnly"' is not assignable to type 'OverridableStringUnion<"inherit" | Variant, TypographyPropsVariantOverrides> | undefined'.
  Overload 2 of 2, '(props: DefaultComponentProps<TypographyTypeMap<{}, "span">>): Element | null', gave the following error.
    Type '"srOnly"' is not assignable to type 'OverridableStringUnion<"inherit" | Variant, TypographyPropsVariantOverrides> | undefined'.
```

### 👟 Reproduction steps

Sorry, not going to have as much detail here as normal. Basically you need to upgrade to MUI v5 at which point you'll run into this error.

### 📃 Provide the context for the Bug.

The type errors are preventing a clean upgrade to MUI v5

### 🖥️ Your Environment

This really isn't environment specific and more related to the upgrade to MUI v5

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by tudi2d**
Fixes #18019 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [ ] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/catalog/src/components/CatalogTable/CatalogTable.tsx [hunk 1]
```diff
@@ -64,6 +63,26 @@ const YellowStar = withStyles({
...
 })(Star);
 
+/**
+ * MUI v5 removes `srOnly` variant from `Typography` component
+ *
+ * Utility copied from https://github.com/mui/material-ui/blob/master/packages/mui-utils/src/visuallyHidden.ts
+ * as `srOnly` variant was only used in this file.
+ */
+const useStyles = makeStyles({
+  visuallyHidden: {
```
Comment (Rugvip) [inline plugins/catalog/src/components/CatalogTable/CatalogTable.tsx:73]: Tbh I think it would be completely fine to depend on `@mui/utils` directly and import from there instead. We actually already have it installed as a transitive dependency in the repo.

**Review by Rugvip — COMMENTED** [review]
🎉

**Review by Edje-C — APPROVED** [review]

File: plugins/catalog/src/components/CatalogTable/CatalogTable.tsx (hunk 1 above)
Comment (tudi2d) [reply plugins/catalog/src/components/CatalogTable/CatalogTable.tsx:73]: yeah - not sure. Felt a bit uneccessary as this is really the only place `srOnly` is used & I'm not sure if there would be another place this util would be used. Should I change it for this PR or can we just go with this?

Comment (Rugvip) [reply plugins/catalog/src/components/CatalogTable/CatalogTable.tsx:73]: I think it's best to introduce `@mui/utils` already tbh, shouldn't hurt much and we avoid the duplication of this logic.

File: plugins/catalog/src/components/CatalogTable/CatalogTable.tsx [hunk 2]
```diff
@@ -146,7 +147,7 @@ export const CatalogTable = (props: CatalogTableProps) => {
       return {
         icon: () => (
           <>
-            <Typography variant="srOnly">{title}</Typography>
+            <Typography style={visuallyHidden}>{title}</Typography>
```
Comment (Rugvip) [inline plugins/catalog/src/components/CatalogTable/CatalogTable.tsx:150]: Switched these back to use `Typography` rather than `span`, figured it kinda makes sense and we avoid the lint rule skip

**Review by Rugvip — APPROVED** [review]
🎉
