### PR TITLE
fix: duplicate origins with multiple notification processors

### LINKED ISSUE #30464: Duplicate Origin Entries in Notification Settings When Email Extension Is Enabled
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
notification user settings
```

### 🗃️ Project Area

Notifications

### 🔗 External Integration

N/A

### 📝 Description & Context

When using the default Backstage notifications plugin alongside the email extension (@backstage/plugin-notifications-backend-email), the "Origin" entries are rendered twice in the User Settings > Notification Settings UI. This duplication only happens when the email notification channel is enabled.

When using only the default web notification channel, the origin appears correctly just once.

Image

### 👍 Expected Behavior

Each origin (e.g., announcements) should appear only once in the UI, regardless of the number of enabled notification channels (Web, Email, etc.).

### 📦 Reproduction Repo

_No response_

### 🥾 Reproduction steps

1. Set up the default `@backstage/plugin-notifications`.
2. Add and configure `@backstage/plugin-notifications-backend-email`.
3. Start Backstage.
4. Navigate to **User Settings > Notification Settings**.
5. Observe the repeated origin rows for `announcements`

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Undecided

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

this fixes the notification settings panel showing duplicate origins when there is multiple notification processors installed. closes #30464 and replaces #30500 to work with latest changes to master.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/notifications/src/components/UserNotificationSettingsCard/UserNotificationSettingsPanel.tsx [hunk 1]
```diff
@@ -109,6 +112,18 @@ export const UserNotificationSettingsPanel = (props: {
...
   }
 
+  const uniqueOriginsMap = settings.channels
+    .flatMap(channel => channel.origins)
+    .reduce((map, origin) => {
+      if (!map.has(origin.id)) {
+        map.set(origin.id, origin);
+      }
+      return map;
+    }, new Map<string, OriginSetting>())
```
Comment (Rugvip) [inline plugins/notifications/src/components/UserNotificationSettingsCard/UserNotificationSettingsPanel.tsx:122]: Looks like something that could be `new Map((...).map(origin => [origin.id, origin]))`, as in passing an iterable of entries to the map constructor instead of manual reduce. It might not actually be more readable though

**Review by Rugvip — APPROVED** [review]
Nice! 👍 :shipit:

File: plugins/notifications/src/components/UserNotificationSettingsCard/UserNotificationSettingsPanel.tsx (hunk 1 above)
Comment (drodil) [reply plugins/notifications/src/components/UserNotificationSettingsCard/UserNotificationSettingsPanel.tsx:122]: Readability over nice tweaks 🎩

**Comment by drodil** [comment]
@Rugvip any chance to get this merged for 1.42.0?

**Comment by Rugvip** [comment]
Ah, you need to get merge privileges 😏
