### PR TITLE
fix: environment variable substitution in config doesn't work with boolean values

### LINKED ISSUE #15422: 🐛 Bug Report: Environment variable substitution in config doesn't work with boolean values
### 📜 Description

When using [Environment Variable Substitution](https://backstage.io/docs/conf/writing#environment-variable-substitution), there is no way to substitute an env var with boolean values. This is because when env vars are substituted, they are substituted as strings and booleans expect nothing but booleans and thus ends up throwing an error.

### 👍 Expected behavior

When env vars are used for something like `backend.database.ensureExists: ${DB_ENSURE_EXISTS}`, it gets substituted as `backend.database.ensureExists: 'false'`, which gets type checked and rejected. This should be handled how numbers are handled during such substitution.

### 👎 Actual Behavior with Screenshots

NA

### 👟 Reproduction steps

Use the value `backend.database.ensureExists: ${DB_ENSURE_EXISTS}` in the `app-config.yaml` and set the `DB_ENSURE_EXISTS` env var to false in your system. And then run the program.

### 📃 Provide the context for the Bug.

This issue seems to be originated from the `config` package's `getOptionalBoolean` method https://github.com/backstage/backstage/blob/72d4b7061d5f2a1d1d09d77f7aeaf8bd1726e26f/packages/config/src/reader.ts#L282.
Unlike the `getOptionalNumber` which accept a string type, the boolean one only accepts boolean.

### 🖥️ Your Environment

OS: Windows_NT 10.0.22623 - win32/x64
node: v18.12.0
yarn: 1.22.19
cli: 0.21.1 (installed)
backstage: 1.8.0

Dependencies:
@backstage/app-defaults 1.0.8
@backstage/backend-common 0.16.0
@backstage/backend-plugin-api 0.1.4
@backstage/backend-tasks 0.3.7
@backstage/catalog-client 1.1.2
@backstage/catalog-model 1.1.3
@backstage/cli-common 0.1.10
@backstage/cli 0.21.1
@backstage/config-loader 1.1.6
@backstage/config 1.0.4
@backstage/core-app-api 1.2.0
@backstage/core-components 0.12.0
@backstage/core-plugin-api 1.1.0
@backstage/errors 1.1.3
@backstage/integration-react 1.1.6
@backstage/integration 1.4.0
@backstage/plugin-api-docs 0.8.11
@backstage/plugin-app-backend 0.3.38
@backstage/plugin-auth-backend 0.17.1
@backstage/plugin-auth-node 0.2.7
@backstage/plugin-catalog-backend-module-github 0.2.1
@backstage/plugin-catalog-backend 1.5.1
@backstage/plugin-catalog-common 1.0.8
@backstage/plugin-catalog-graph 0.2.23
@backstage/plugin-catalog-import 0.9.1
@backstage/plugin-catalog-node 1.2.1
@backstage/plugin-catalog-react 1.2.1
@backstage/plugin-catalog 1.6.1
@backstage/plugin-github-actions 0.5.11
@backstage/plugin-org 0.6.0
@backstage/plugin-permission-common 0.7.1
@backstage/plugin-permission-node 0.7.1
@backstage/plugin-permission-react 0.4.7
@backstage/plugin-proxy-backend 0.2.32
@backstage/plugin-scaffolder-backend 1.8.0
@backstage/plugin-scaffolder-common 1.2.2
@backstage/plugin-scaffolder 1.8.0
@backstage/plugin-techdocs-backend 1.4.1
@backstage/plugin-techdocs-module-addons-contrib 1.0.6
@backstage/plugin-techdocs-node 1.4.2
@backstage/plugin-techdocs-react 1.0.6
@backstage/plugin-techdocs 1.4.0
@backstage/plugin-user-settings 0.5.1
@backstage/release-manifests 0.0.7
@backstage/test-utils 1.2.2
@backstage/theme 0.2.16
@backstage/types 1.0.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by SayakMukhopadhyay**
## Hey, I just made a Pull Request!
This PR fixes #15422 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by SayakMukhopadhyay** [comment]
I am supplying the test first as mentioned in a previous PR. But the test fails in other files than the one I am working on. So, please check the tests results for `reader.test.ts`. As of now, it fails as intended.

File: packages/config/src/reader.ts [hunk 1]
```diff
@@ -280,10 +280,26 @@ export class ConfigReader implements Config {
...
       key,
-      value => typeof value === 'boolean' || { expected: 'boolean' },
+      val =>
+        typeof val === 'boolean' ||
+        typeof val === 'string' || { expected: 'boolean' },
     );
+    if (typeof value === 'boolean' || value === undefined) {
+      return value;
+    }
+    let boolean;
```
Comment (benjdlambert) [inline packages/config/src/reader.ts:292]: Thinking that we should probably go a little bit further and take some inspiration from the `yn` package and use some regex's like these https://github.com/sindresorhus/yn/blob/main/index.js#L17-L23 to match a few other values and do the coercion to boolean here.

**Review by benjdlambert — CHANGES_REQUESTED** [review]
Hey :wave: Thanks for this.

Just the one comment really, thinking that we should probably use some regex here instead and match some other common values that might be passed in env variables so that we can support other string values.

File: packages/config/src/reader.ts (hunk 1 above)
Comment (benjdlambert) [reply packages/config/src/reader.ts:292]: Probably don't want to bring the whole package in, but thinking we can lift the regex's out of that package into here instead.

Comment (SayakMukhopadhyay) [reply packages/config/src/reader.ts:292]: I don't think that it would be a good idea. People might want to keep `yes/no` as it is. We also don't want to coerce `0` to false as integer likes are already coerced to numbers. The boolean true and false are the only weird edge cases where they are valid tokens in javascript but can't be represented as such in environment variables.

Comment (benjdlambert) [reply packages/config/src/reader.ts:292]: `yes/no` would be kept as is if they're requested with `getString` or `getOptionalString`, but in this case, theres a requirement to coerce the value that is set in config into the type that you're requesting. I think it's pretty reasonable to assume also that if I have in config something like this:

```yaml
enabled: ${IS_ENABLED}
```

With `IS_ENABLED=1` as an Environment Variable, If I'm doing `getBoolean('enabled')` i'd expect it to return `true`, but `getNumber('enabled')` I'd expect 1. The coercion is only happening in the `getOptionalBoolean` part which I think is fine.

Comment (SayakMukhopadhyay) [reply packages/config/src/reader.ts:292]: Alright, I am pushing a commit for the same.

**Comment by SayakMukhopadhyay** [comment]
> Hey 👋 Thanks for this.
> 
> Just the one comment really, thinking that we should probably use some regex here instead and match some other common values that might be passed in env variables so that we can support other string values.

@benjdlambert Thanks for reviewing. I have pushed a new commit which coerces `yes'no`, `y/n`, `zero/on`, `0/1` and `on/off` into booleans as suggested in the review. Let me know what you think.

File: packages/config/src/reader.ts [hunk 2]
```diff
@@ -280,10 +280,27 @@ export class ConfigReader implements Config {
...
+        typeof val === 'boolean' ||
+        typeof val === 'number' ||
+        typeof val === 'string' || { expected: 'boolean' },
     );
+    if (typeof value === 'boolean' || value === undefined) {
+      return value;
+    }
+    let boolean;
+    if (/^(?:y|yes|true|1|on)$/i.test(value as string) || value === 1) {
+      boolean = true;
```
Comment (benjdlambert) [inline packages/config/src/reader.ts:295]:
```suggestion
     return true;
```

File: packages/config/src/reader.ts [hunk 3]
```diff
@@ -280,10 +280,27 @@ export class ConfigReader implements Config {
...
+    } else if (/^(?:n|no|false|0|off)$/i.test(value as string) || value === 0) {
+      boolean = false;
```
Comment (benjdlambert) [inline packages/config/src/reader.ts:297]:
```suggestion
      return false;
```

Comment (benjdlambert) [inline packages/config/src/reader.ts:297]:
```suggestion
      return false;
```

File: packages/config/src/reader.ts [hunk 4]
```diff
@@ -280,10 +280,27 @@ export class ConfigReader implements Config {
...
+    } else {
+      throw new Error(
+        errors.convert(this.fullKey(key), this.context, 'boolean'),
+      );
+    }
+    return boolean;
```
Comment (benjdlambert) [inline packages/config/src/reader.ts:303]:
```suggestion
      throw new Error(
        errors.convert(this.fullKey(key), this.context, 'boolean'),
      );
```

Comment (benjdlambert) [inline packages/config/src/reader.ts:303]:
```suggestion
      throw new Error(
        errors.convert(this.fullKey(key), this.context, 'boolean'),
      );
```

**Review by benjdlambert — CHANGES_REQUESTED** [review]
Thanks for the changes, spotted a bit of refactoring that we could do to clean it up a little bit, and then there's a few tests that are failing too 👍

**Comment by SayakMukhopadhyay** [comment]
@benjdlambert pushed your suggestions. The tests were failing due to a single check. There was a test which was expecting to throw an error if `0` was passed to the boolean. Since we are coercing now, that test had to be removed. I hope this wont cause any regressions lol 😅

File: .changeset/tidy-flies-cheer.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/config': patch
+---
+
+Handle a case when boolean configuration parameters are given a string type of 'true' or 'false'. This happens particularly when such parameters are used with environmental substitution as environment variables are always strings.
```
Comment (benjdlambert) [inline .changeset/tidy-flies-cheer.md:5]: Think this changeset could do with adding a few more of the supported boolean types now as we've added some more, maybe it makes sense to add these to the list too.

```suggestion
Adds the ability to be able to coerce values to their boolean representatives. 
Thinks such as `"true"` `1` `on` and `y` will become `true` when using `getBoolean` and the opposites `false`.
This happens particularly when such parameters are used with environmental substitution as environment variables are always strings.
```

**Review by benjdlambert — CHANGES_REQUESTED** [review]
Thanks for fixing them up @SayakMukhopadhyay, I think I found a simplification for some of the logic too, and then we've also got a small changeset update too to be more representative of the change that's happening now after the comments :)

**Review by benjdlambert — APPROVED** [review]
Nice! Thanks for this 👍
