### PR TITLE
IconLinkVertical component to accept disabled prop

### LINKED ISSUE #2389: [bug] Handle TechDocs missing more gracefully
## Expected Behavior

If TechDocs is missing for a component I expect to get a more helpful error/warning message.

Also, this URL looks really weird to me: `http://localhost:3000/docs/Component::searcher`. Should there really be `::` in the path?

## Current Behavior

Clicking a TechDocs link when About card "crashes" rendering...

Screenshot 2020-09-10 at 08 26 19

...leads to this problem:

Screenshot 2020-09-10 at 08 26 35

If I click the DOCS tab I get a different experience:

Screenshot 2020-09-10 at 08 26 11

### PR DESCRIPTION
**Pull request by emmaindal**
## Hey, I just made a Pull Request!

closes #2389 
Screen Shot 2020-09-10 at 12 42 50 PM
Screen Shot 2020-09-10 at 12 43 03 PM

#### :heavy_check_mark: Checklist

- [ ] All tests are passing `yarn test`
- [ ] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

File: plugins/catalog/src/components/AboutCard/IconLinkVertical/IconLinkVertical.tsx [hunk 1]
```diff
@@ -41,9 +49,20 @@ const useIconStyles = makeStyles({
...
+    return (
+      <Link className={classes.disabled} underline="none" {...props}>
+        {icon}
+        <span className={classes.label}>{props.label}</span>
+      </Link>
+    );
+  }
+
   return (
     <Link className={classes.link} href={href} {...props}>
```
Comment (freben) [inline plugins/catalog/src/components/AboutCard/IconLinkVertical/IconLinkVertical.tsx:67]: no need for the repetition; add ONLY `color: gray` to the `disabled` class, and then something like

```ts
import classnames from 'classnames';
// ...
<Link className={classnames(classes.link, { [classes.disabled]: disabled })} underline="none" {...props}>
```

Comment (emmaindal) [reply plugins/catalog/src/components/AboutCard/IconLinkVertical/IconLinkVertical.tsx:68]: @freben done!

File: plugins/catalog/src/components/AboutCard/IconLinkVertical/IconLinkVertical.tsx [hunk 2]
```diff
@@ -41,9 +46,24 @@ const useIconStyles = makeStyles({
...
+        className={classnames(classes.link, classes.disabled)}
+        underline="none"
+        {...props}
+      >
+        {icon}
+        <span className={classes.label}>{props.label}</span>
+      </Link>
+    );
+  }
+
```
Comment (freben) [inline plugins/catalog/src/components/AboutCard/IconLinkVertical/IconLinkVertical.tsx:66]: Oh I meant to use one single return, where everything is the same except the `disabled` class is added if it's disabled. But, now I realise - you actually do NOT want to have the `<Link>` here at all if it's disabled, right? Isn't the point that it should not be clickable? :)

Comment (emmaindal) [reply plugins/catalog/src/components/AboutCard/IconLinkVertical/IconLinkVertical.tsx:66]: yeah thats why it doesn't have a href, but now when you say it I can actually just make it another element and not a Link

Comment (emmaindal) [reply plugins/catalog/src/components/AboutCard/IconLinkVertical/IconLinkVertical.tsx:66]: what would you prefer. a disabled link as it is now or change it to be a Typography with the link class? (since I want the same styles as the Link when its not disabled)

Comment (freben) [reply plugins/catalog/src/components/AboutCard/IconLinkVertical/IconLinkVertical.tsx:66]: Aha! Ok yeah well then it works anyway to keep using Link even though it's a bit unexpected perhaps.

**Review by freben — APPROVED** [review]
:shipit:
