### PR TITLE
fix related to catalog import accepting invalid component name 

### LINKED ISSUE #18508: 🐛 Bug Report: Catalog import does not validate component name during PR creation
### 📜 Description

Hi! I hope you're all doing really well. I wanted to report a bug we've run into with Catalog Import when you provide a GitHub repository without an existing catalog-info.yaml file. On the second step you can edit the component name from what is set during the analyze step. You can rename the component to something that does not conform to the ADR described [here](https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md) (like "My First Component"). The PR is created successfully and can be merged without issue. However, the component is never imported. If you try to import the component again using the newly created catalog-info.yaml, you get an error that the metadata name does not conform to the expected format, blocking you from importing the component. 

### 👍 Expected behavior

I would expect the UI component to validate the given name, and display an error if it doesn't match the expected scheme.

### 👎 Actual Behavior with Screenshots

Here is a screenshot of clicking into a different field with the name being set to something invalid:
Screen Shot 2023-06-30 at 10 25 38 AM

Here is a screenshot of the error:
Screen Shot 2023-06-30 at 10 24 39 AM

### 👟 Reproduction steps

1. Navigate to the Catalog section of the nav.
2. Click "New".
3. Click "Register new component".
4. Enter GitHub repo URL without a catalog-info.yaml.
5. Alter the component name to something invalid like "My First Component".
6. Merge the created PR.
7. Refresh and verify the component is not registered.
8. Try and reimport the component using the new catalog-info.yaml file (i.e. repoURL/blob/main/catalog-info.yaml).
9. Error should show up.

### 📃 Provide the context for the Bug.

Teams registering components are unaware of the restrictions in place for component names. We've had teams mistakenly register a component, alter the name, but then be unable to find their component in the catalog. This causes confusion, and bug reports on our end, although we are using the out of the box React plugin.

### 🖥️ Your Environment

Our environment is deployed to Kubernetes. I was able to reproduce it using Chrome Version 114.0.5735.198 on a MacBook. We are using Backstage version `1.13.2` and plugin-catalog-import `^0.9.7`. I did some checking and couldn't see a case where this bug was fixed in a new version but I may have missed something so please correct me if I'm wrong! I'm happy to provide any more info that would help. Thanks in advance!

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by npiyush97**
## Hey, I just made a Pull Request!
fix #18508 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

error from validate entity
Screenshot from 2024-02-22 17-12-24

### CODE REVIEW

**Comment by npiyush97** [comment]
feedback on cleanliness

File: plugins/catalog-import/src/components/StepPrepareCreatePullRequest/StepPrepareCreatePullRequest.tsx [hunk 1]
```diff
@@ -143,11 +143,25 @@ export const StepPrepareCreatePullRequest = (
...
   });
 
+  const isValidObjectName = (value: unknown): boolean => {
+    return (
+      typeof value === 'string' &&
+      value.length >= 1 &&
+      value.length <= 63 &&
+      /^([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$/.test(value)
+    );
+  };
```
Comment (Rugvip) [inline plugins/catalog-import/src/components/StepPrepareCreatePullRequest/StepPrepareCreatePullRequest.tsx:153]: This would need to rely on the remote catalog validation in some way. The validation logic that the catalog backend uses can be reconfigured, so we can't hardcode it here.

**Review by Rugvip — CHANGES_REQUESTED** [review]
Thank you! 👍 

Bit of early feedback to avoid this particular trap

File: plugins/catalog-import/src/api/CatalogImportClient.ts [hunk 2]
```diff
@@ -175,7 +176,15 @@ the component will become available.\n\nFor more information, read an \
     body: string;
   }): Promise<{ link: string; location: string }> {
     const { repositoryUrl, fileContent, title, body } = options;
-
+    const parseData = YAML.parse(fileContent);
+    const {
+      metadata: { name },
+    } = parseData;
```
Comment (aramissennyeydd) [inline plugins/catalog-import/src/api/CatalogImportClient.ts:182]: It looks like we have access to the catalog API in this class, can we use the [`validateEntity` method](https://github.com/backstage/backstage/blob/patch/v1.22.0/packages/catalog-client/src/types/api.ts#L632-L642) instead? That will run it against the current catalog instance and ensure it can be imported later. Users may have customized their naming format or other formats and we'll want to check those as well IMO.

Comment (npiyush97) [reply plugins/catalog-import/src/api/CatalogImportClient.ts:182]: did not know about this 
this would be good I'm not sure?
```
async submitPullRequest(options: {
    repositoryUrl: string;
    fileContent: string;
    title: string;
    body: string;
  }): Promise<{ link: string; location: string }> {
    const { repositoryUrl, fileContent, title, body } = options;
    const parseData = YAML.parse(fileContent);
    try {
      const validationResponse = await this.catalogApi.validateEntity(
        parseData,
        `url:${repositoryUrl}`,
      );
      if (!validationResponse.valid) {
        throw new Error(validationResponse.errors[0].message);
      }
      const ghConfig = getGithubIntegrationConfig(
        this.scmIntegrationsApi,
        repositoryUrl,
      );

      if (ghConfig) {
        return await this.submitGitHubPrToRepo({
          ...ghConfig,
          repositoryUrl,
          fileContent,
          title,
          body,
        });
      }
      throw new Error('unimplemented!');
    } catch (err) {
      throw err;
    }
  }
```
having issue with tests.

Comment (aramissennyeydd) [reply plugins/catalog-import/src/api/CatalogImportClient.ts:182]: I believe that looks good, I think for this we can just use `url:http://localhost` or similar non-value for the location. It would need to point at an existing repository and only for `Location` kinds which _shouldn't_ be used here @backstage/scaffolder-maintainers to confirm though?

**Comment by npiyush97** [comment]
@aramissennyeydd another look ?

File: plugins/catalog-import/src/api/CatalogImportClient.ts [hunk 3]
```diff
@@ -175,23 +176,33 @@ the component will become available.\n\nFor more information, read an \
...
+          repositoryUrl,
+          fileContent,
+          title,
+          body,
+        });
+      }
+      throw new Error('unimplemented!');
+    } catch (err) {
+      throw err;
+    }
```
Comment (aramissennyeydd) [inline plugins/catalog-import/src/api/CatalogImportClient.ts:205]: If we're just catching to rethrow, do we need this block at all?

**Review by aramissennyeydd — APPROVED** [review]
Looks good! One small comment.

File: plugins/catalog-import/src/api/CatalogImportClient.ts (hunk 3 above)
Comment (npiyush97) [reply plugins/catalog-import/src/api/CatalogImportClient.ts]: yes both of them throw error no need for a try catch.

**Comment by npiyush97** [comment]
ping @Rugvip

**Comment by npiyush97** [comment]
@freben, is there any specific reason for not merging anything on my side?

**Review by freben — APPROVED** [review]
Not at all - I've been out sick and things have backed up a lot.

Maybe this could be improved in the future to contain all actual errors as extra data on a custom error etc. So that you get all the contextual info in the serialized error in the response etc. But let's go for now

**Comment by npiyush97** [comment]
> Not at all - I've been out sick and things have backed up a lot.
> 
> Maybe this could be improved in the future to contain all actual errors as extra data on a custom error etc. So that you get all the contextual info in the serialized error in the response etc. But let's go for now

GWS 👍
