### PR TITLE
fix(auth): memory leaks

### LINKED ISSUE #33329: OIDC Request failed with status 500: server_error: Key (oidc_client_id)=(https://vscode.dev/oauth/client-metadata.json) is not present in table "oidc_clients"
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
auth mcp oidc
```

### 🗃️ Project Area

Auth

### 🔗 External Integration

N/A

### 📝 Description & Context

During MCP OIDC auth, it seems to throw an exception in some rare cases:

constraint: `offline_sessions_oidc_client_id_foreign`
detail: `Key (oidc_client_id)=(https://vscode.dev/oauth/client-metadata.json) is not present in table "oidc_clients".`
message:
```
OIDC Request failed with status 500: server_error - insert into "offline_sessions" ("created_at", "id", "last_used_at", "oidc_client_id", "token_hash", "user_entity_ref") values (CURRENT_TIMESTAMP, $1, CURRENT_TIMESTAMP, $2, $3, $4) - insert or update on table "offline_sessions" violates foreign key constraint "offline_sessions_oidc_client_id_foreign" insert into "offline_sessions" ("created_at", "id", "last_used_at", "oidc_client_id", "token_hash", "user_entity_ref") values (CURRENT_TIMESTAMP, $1, CURRENT_TIMESTAMP, $2, $3, $4) - insert or update on table "offline_sessions" violates foreign key constraint "offline_sessions_oidc_client_id_foreign"
```
table: `offline_sessions`

This exception happens after the log message:

> Issuing token for user:default/john.doe, with entities undefined

We have enabled the following experimental settings that might cause the issue:

 * `auth.experimentalDynamicClientRegistration.enabled` = true
 * `auth.experimentalRefreshToken.enabled` = true
 * `auth.experimentalClientIdMetadataDocuments.enabled` = true

### 👍 Expected Behavior

It should not throw an exception during authentication process. 

### 📦 Reproduction Repo

_No response_

### 🥾 Reproduction steps

_No response_

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

alb-provider: JWT verification block was wrapped in generic error that turned 401 to 500 causing clients to retry the login

cimd: cimd clients are not registered in oidc_clients table so inserting offline sessions for them violates the foreign key constraint. dropping the fk.

offline: return access token even when refresh token issuing fails. if the refresh token issue fails for some reason, it will return 500 which will then cause client to retry even it can get valid access token without refresh token.

closes #33329

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/auth-backend-module-aws-alb-provider/src/authenticator.ts [hunk 1]
```diff
@@ -98,7 +98,13 @@ export const awsAlbAuthenticator = createProxyAuthenticator({
         },
       };
     } catch (e) {
-      throw new Error(`Exception occurred during JWT processing: ${e}`);
+      if (e instanceof AuthenticationError) {
+        throw e;
+      }
```
Comment (Rugvip) [inline plugins/auth-backend-module-aws-alb-provider/src/authenticator.ts]: e.name === 'AuthenticationError` instead of safety

File: plugins/auth-backend/src/service/OidcService.ts [hunk 2]
```diff
@@ -509,10 +518,18 @@ export class OidcService {
...
+        refreshToken = await this.offlineAccess.issueRefreshToken({
+          userEntityRef: session.userEntityRef,
+          oidcClientId: session.clientId,
+        });
+      } catch (err) {
+        // Don't fail the entire token exchange if refresh token issuance fails.
+        // The access token is still valid and should be returned.
+        this.logger.warn(
+          `Failed to issue refresh token for user ${session.userEntityRef}, offline_access will not be available: ${err}`,
+        );
```
Comment (Rugvip) [inline plugins/auth-backend/src/service/OidcService.ts:531]: Hmm, don't love it but it's a bit safer for sure

Comment (drodil) [reply plugins/auth-backend/src/service/OidcService.ts:531]: Yeah, it would still work but without the refresh token; meaning there is something broken and user just needs to login again once the token expires. And yes, just for safety; logging added to actually catch this if it happens.

File: plugins/auth-backend-module-aws-alb-provider/src/authenticator.ts (hunk 1 above)
Comment (drodil) [reply plugins/auth-backend-module-aws-alb-provider/src/authenticator.ts]: fixed.
