### PR TITLE
cli: fix diff command filepath handling on windows

### LINKED ISSUE #6762: backstage-cli plugin:diff fails with `Error: No template file handler found for dev\index.tsx`
## Expected Behavior

running yarn backstage-cli plugin:diff should make it through the entire plugin files.

## Current Behavior

diff fails on dev/index.tsx file and does not continue.

## Steps to Reproduce

1. clone backstage
2. yarn create-plugin
2. cd to the new plugin folder
3. yarn backstage-cli plugin:diff

## Context

I'm working on keeping our instance of backstage up to date with backstage but verifying plugin changes is not working anymore.

## Your Environment

- NodeJS Version (v12): 14
- Operating System and Version (e.g. Ubuntu 14.04): windows

### PR DESCRIPTION
**Pull request by Rugvip**
Fixes #6762 ._.

### CODE REVIEW

File: packages/cli/src/lib/diff/handlers.ts [hunk 1]
```diff
@@ -281,7 +282,7 @@ export async function handleAllFiles(
   promptFunc: PromptFunc,
 ) {
   for (const file of files) {
-    const { path } = file;
+    const path = file.path.split(sep).join(posix.sep);
```
Comment (freben) [inline packages/cli/src/lib/diff/handlers.ts:285]: Is there a posix.normalize :)

**Review by freben — APPROVED** [review]

**Comment by alzafacon** [comment]
Doesn't fail anymore! here is an example of the output I see:

```
$ C:\Users\work\git\backstage\node_modules\.bin\backstage-cli plugin:diff
Making sure .eslintrc.js exists
Skipping tsconfig.json
Checking package.json
Skipping README.md
Making sure dev\index.tsx exists
Making sure src\plugin.test.ts exists
Making sure src\plugin.ts exists
Skipping src\routes.ts
Making sure src\index.ts exists
Making sure src\setupTests.ts exists
Skipping src\components\ExampleComponent\ExampleComponent.test.tsx
Skipping src\components\ExampleComponent\ExampleComponent.tsx
Skipping src\components\ExampleComponent\index.ts
Skipping src\components\ExampleFetchComponent\ExampleFetchComponent.test.tsx
Skipping src\components\ExampleFetchComponent\index.ts
Skipping src\components\ExampleFetchComponent\ExampleFetchComponent.tsx
Done in 1.22s.
```

File: packages/cli/src/lib/diff/handlers.ts (hunk 1 above)
Comment (Rugvip) [reply packages/cli/src/lib/diff/handlers.ts:285]: Yet but it doesn't do this :p. It's more about converting `a//b` into `a/b` and that kinda stuff
