### PR TITLE
TechDocs: Proper caching with URL Reader, warnings for git/dir preparers and cleanups

### LINKED ISSUE #3548: Cache docs pages built with UrlReader
Currently we cannot detect updates to source files when techdocs are built using the UrlReader. This means we can't do caching of built docs and have to reload on every pageload. We need to find some way of checking the last updated date of files in a repository or subtree of a repository.

This will probably require a solution for each supported VCS. For example in Github we can probably use the api and check when a file or directory was last updated.

Ideas on how to approach this is welcome!

### LINKED ISSUE #4011: Techdocs memory consumption issues
Hi! 

I'm experiencing some memory consumption issues with techdocs. Any time I click and navigate on a documentation component, response is slow (like 5-10 secs to load the page) and memory consumption increases dramatically till the point backstage crashes.

## Expected Behavior

I should be able to navigate the documentation with no memory consumption issues.

## Current Behavior

When navigating documentation, lots of `techdocs-tmp-*`  directories are generated and copied to the generated folder, which increases memory consumption dramatically.

## Steps to Reproduce

Create a documentation project in Gitlab, then, add that component to Backstage and start navigating documentation. I've been using this [example](https://github.com/saltosystems-bot/tech-docs-test) repository for the test.

I only have experienced this behaviour with Gitlab private projects, the same project on Github works as expected; navigation is fast and there isn't any memory issue.

## Context

I was trying to test techdocs with a private documentation repository in the Gitlab instance of my company.

## Your Environment

I've deployed Backstage on Kubernetes. I built Backstage docker image as stated [here](https://github.com/backstage/backstage/tree/master/contrib/docker/kubernetes-example-backend). For reference, the docker image I'm using right now is [this](https://hub.docker.com/layers/saltosystems/backstage/f891a65900192ae969beda8bb21fe59c68245e12/images/sha256-c34e1acd1f6e4aad6701233c03e37191b48b05ab70d8dc2e01cc462ad4d8d73a?context=explore).

- NodeJS Version: v12
- Operating System and Version: docker image based on `node:12-buster`
- `plugin-techdocs-backend` Version: "@backstage/plugin-techdocs-backend": "^0.5.0"

I've been able to inspect the docker container file system using `du` command and these are the [results](https://gist.github.com/amarruedo/bf77b31dee9393fc0fbec1aa0ce5d5b9#file-techdocs_du_result-txt).

With every page click, the size of the folder `/var/lib/docker/overlay2/b4d472adaeb760884411df13e3c508b4bbc3c3deab29a23b009e282759bd5d88/merged/usr/src/app/plugins/techdocs-backend/static/docs/default/Component/tech-docs-test-gitlab` doubles, resulting in an increase of memory consumption and finally, in pod eviction.

/cc @OrkoHunter

### PR DESCRIPTION
**Pull request by OrkoHunter**
Closes #3548 
Closes #4011 (with cleanup of temp dirs)
Address #4409 partially with warnings

This PR accomplishes the following -

1. Previously sites built using URL Reader were cached for 30 minutes. Now, an `etag` will be stored and used for caching. Support for etag based caching was added to URL Reader in https://github.com/backstage/backstage/pull/4120
2. Throw warning when legacy git/dir preparer is used. See https://github.com/backstage/backstage/issues/4409 for reasons of doing so.
3. Clean up prepared and generated temporary directories once they are used. They used to occupy a lot of `/tmp` space over time.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4411-cztsz5zsmz0qoa5u0on8l5eleczbnw5w.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/601e945d353bbb7999a1b3f6

File: packages/techdocs-common/src/stages/prepare/commonGit.ts [hunk 1]
```diff
@@ -31,23 +35,45 @@ export class CommonGitPreparer implements PreparerBase {
...
       const repoPath = await checkoutGitRepository(
         target,
         this.config,
         this.logger,
       );
-      const parsedGitLocation = parseGitUrl(target);
+      // Check if etag has changed for cache invalidation.
+      const etag = await getLastCommitTimestamp(repoPath, this.logger);
+      if (options?.etag === etag.toString()) {
+        throw new NotModifiedError();
```
Comment (emmaindal) [inline packages/techdocs-common/src/stages/prepare/commonGit.ts:63]: Hmm do we want to throw an error when nothing is modified and its still good to use? or do we just want to do nothing? I guess we are mostly interested in an action when its changed.

Comment (emmaindal) [reply packages/techdocs-common/src/stages/prepare/commonGit.ts:63]: continued to review and could see it's mostly for debugging purposes, which I guess make sense

**Review by emmaindal — APPROVED** [review]

File: packages/techdocs-common/src/stages/prepare/commonGit.ts (hunk 1 above)
Comment (OrkoHunter) [reply packages/techdocs-common/src/stages/prepare/commonGit.ts:63]: Yep, this error is not transmitted to the user.

File: plugins/techdocs-backend/src/DocsBuilder/builder.ts [hunk 2]
```diff
@@ -63,22 +60,57 @@ export class DocsBuilder {
...
+    try {
+      const preparerResponse = await this.preparer.prepare(this.entity, {
+        etag: buildMetadataStorage.getEtag(),
+      });
+
+      preparedDir = preparerResponse.preparedDir;
+      etag = preparerResponse.etag;
+    } catch (NotModifiedError) {
+      // No need to prepare anymore since cache is valid.
+      return;
```
Comment (OrkoHunter) [inline plugins/techdocs-backend/src/DocsBuilder/builder.ts:103]: Note to self

```suggestion
    } catch (err) {
      if (err instanceof NotModifiedError) {
	      // No need to prepare anymore since cache is valid.
	      return;
	   } else {
	     throw new Error(err.message)
	   }
```

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4411-cztsz5zsmz0qoa5u0on8l5eleczbnw5w.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/601e945d353bbb7999a1b3f6

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4411-cztsz5zsmz0qoa5u0on8l5eleczbnw5w.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/601e945d353bbb7999a1b3f6

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4411-cztsz5zsmz0qoa5u0on8l5eleczbnw5w.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/601e945d353bbb7999a1b3f6
