### PR TITLE
Bazaar plugin: The project member link will now target the user catalog

### LINKED ISSUE #13190: Bazaar plugin: The member link should target the backstage user catalog entity
## Expected Behavior

The backstage user entity ref should be stored for each member and the member link should open the backstage user entity catalog page (i.e. "/catalog/default/user/username").

## Actual Behavior

The member database contains only the "display" name of an user and the member link goes to "https://github.com/${entity.displayName}"

## Steps to Reproduce

* Go to a Bazaar project that you are not a member of.
* Join the project by clicking the "Join project".
* The url in the "Latest members" points to Github.

## Implementation

* Add a new field to the members table that contains the user entity ref.
* Store the user entity ref when adding a new user.
* Update the url of the member list to link to the catalog page of the user.

I plan to work on this issue.

### PR DESCRIPTION
**Pull request by anicke**
## Hey, I just made a Pull Request!

The url for a project member is currently hard coded as "httpx://github.com/${backstage_display_name}", this PR changes the url to instead target the backstage catalog page of the user. 
Changes:

Backend: Added a migration to add a field ("user_ref") to the member table. This will contain the user entity ref.
Backend: When a user is requested to be added as a member the user ref is looked up using the "IdentityApi".
Front end: If the 'userRef' field is set on a member, the url will link to the catalog page of the user.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [X] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

Closes #13190

### CODE REVIEW

**Comment by anicke** [comment]
@Rugvip I could not manage to reopen my PR so I made a new one. This is basically #13216 but with your comments fixed.

**Comment by Rugvip** [comment]
@anicke yep gotta ask to get it reopened unfortunately. If you close this one I can reopen the other one, if you want to keep the discussions intact. Otherwise it's fine to continue here

**Comment by anicke** [comment]
Let's continue in #13216.

**Comment by anicke** [comment]
Rebased!

File: plugins/bazaar-backend/src/service/standaloneServer.ts [hunk 1]
```diff
@@ -54,6 +55,7 @@ export async function startStandaloneServer(
     logger,
     database: { getClient: async () => db },
     config: config,
+    identity: {} as DefaultIdentityClient,
```
Comment (freben) [inline plugins/bazaar-backend/src/service/standaloneServer.ts:58]: DefaultIdentityClient is an instance - you could change this to `IdentityApi`, or making an actual instance, or making a mock instance like `{ getIdentity: async () => undefined }` or so. I'd actually be surprised if this doesn't crash after running `yarn start` in the plugin folder?

**Review by freben — COMMENTED** [review]
Nice. One small thing to fix!

File: plugins/bazaar-backend/src/service/DatabaseHandler.ts [hunk 2]
```diff
@@ -67,11 +67,17 @@ export class DatabaseHandler {
     return await this.client.select('*').from('members').where({ item_id: id });
   }
 
-  async addMember(id: number, userId: string, picture?: string) {
+  async addMember(
+    id: number,
+    userId: string,
+    userRef?: string,
+    picture?: string,
```
[the remark this answers is not in the document]
Comment (anicke) [reply plugins/bazaar-backend/src/service/DatabaseHandler.ts:74]: Yes, I can do that.

File: plugins/bazaar-backend/src/service/standaloneServer.ts (hunk 1 above)
Comment (anicke) [reply plugins/bazaar-backend/src/service/standaloneServer.ts]: The stand alone server still works. It's just just used a typecast so the typing should not be there at run time?

Comment (freben) [reply plugins/bazaar-backend/src/service/standaloneServer.ts]: Sure it does :) Just a bit unexpected to see a concrete class as the typecast, rather than the interface. No big deal.

**Review by freben — APPROVED** [review]
Let's 🚢

**Comment by suuus** [comment]
Thank you for contributing during Hacktoberfest 🍂! You can claim the Backstage Hacktoberfest Holopin at https://bck.st/hacktoberfest-holopin 🙌🏻
