### PR TITLE
fix: Change the catalog header to a normal header instead of a dropdown

### LINKED ISSUE #14726: 🐛 Bug Report: There are two "kind dropdowns": header and filter box
### 📜 Description

On a freshly created Backstage app, the catalog page has two identical ways of filtering by kind, which may be confusing.

### 👍 Expected behavior

The kind should be filterable by only the header dropdown or the filter box dropdown.

### 👎 Actual Behavior with Screenshots

[double-kind-filter.webm](https://user-images.githubusercontent.com/110673802/203047630-ec9eb3e4-6374-4c37-b700-0ee18301f685.webm)

### 👟 Reproduction steps

1. `npx @backstage/create-app` (`0.4.34`)
2. cd `$name`, `yarn dev`
3. Click on header, filter box on catalog page.

### 📃 Provide the context for the Bug.

Likely related to #9616

### 🖥️ Your Environment

```
$ yarn backstage-cli info          
yarn run v1.22.19
$ /home/mitch/dev/backstage-new/mitch/node_modules/.bin/backstage-cli info
OS:   Linux 6.0.8-300.fc37.x86_64 - linux/x64
node: v16.17.0
yarn: 1.22.19
cli:  0.21.1 (installed)
backstage:  1.8.0

Dependencies:
  @backstage/app-defaults                          1.0.8
  @backstage/backend-common                        0.16.0
  @backstage/backend-plugin-api                    0.1.4
  @backstage/backend-tasks                         0.3.7
  @backstage/catalog-client                        1.1.2
  @backstage/catalog-model                         1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.21.1
  @backstage/config-loader                         1.1.6
  @backstage/config                                1.0.4
  @backstage/core-app-api                          1.2.0
  @backstage/core-components                       0.12.0
  @backstage/core-plugin-api                       1.1.0
  @backstage/errors                                1.1.3
  @backstage/integration-react                     1.1.6
  @backstage/integration                           1.4.0
  @backstage/plugin-api-docs                       0.8.11
  @backstage/plugin-app-backend                    0.3.38
  @backstage/plugin-auth-backend                   0.17.1
  @backstage/plugin-auth-node                      0.2.7
  @backstage/plugin-catalog-backend                1.5.1
  @backstage/plugin-catalog-common                 1.0.8
  @backstage/plugin-catalog-graph                  0.2.23
  @backstage/plugin-catalog-import                 0.9.1
  @backstage/plugin-catalog-node                   1.2.1
  @backstage/plugin-catalog-react                  1.2.1
  @backstage/plugin-catalog                        1.6.1
  @backstage/plugin-github-actions                 0.5.11
  @backstage/plugin-org                            0.6.0
  @backstage/plugin-permission-common              0.7.1
  @backstage/plugin-permission-node                0.7.1
  @backstage/plugin-permission-react               0.4.7
  @backstage/plugin-proxy-backend                  0.2.32
  @backstage/plugin-scaffolder-backend             1.8.0
  @backstage/plugin-scaffolder-common              1.2.2
  @backstage/plugin-scaffolder                     1.8.0
  @backstage/plugin-search-backend-module-pg       0.4.2
  @backstage/plugin-search-backend-node            1.0.4
  @backstage/plugin-search-backend                 1.1.1
  @backstage/plugin-search-common                  1.1.1
  @backstage/plugin-search-react                   1.2.1
  @backstage/plugin-search                         1.0.4
  @backstage/plugin-tech-radar                     0.5.18
  @backstage/plugin-techdocs-backend               1.4.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.6
  @backstage/plugin-techdocs-node                  1.4.2
  @backstage/plugin-techdocs-react                 1.0.6
  @backstage/plugin-techdocs                       1.4.0
  @backstage/plugin-user-settings                  0.5.1
  @backstage/release-manifests                     0.0.7
  @backstage/test-utils                            1.2.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.1
  @backstage/version-bridge                        1.0.2
Done in 0.78s.

```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

### PR DESCRIPTION
**Pull request by lucahuettner**
## Hey, I just made a Pull Request!

This would close #14726 

I have changed the CatalogKindHeader from a select to a normal header as discussed in #14726.

This is my first PR to a open source project so any feedback is appreciated :)

### Screenshot:

image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by pjungermann** [comment]
I wonder whether we even need this as normal header. Removing it entirely might be good, too. At the end, the kind filter also show this.

Or if we really want to keep this redundancy, maybe rather a sub-title at the page header vs consuming the space here? 🤔

**Review by jhaals — CHANGES_REQUESTED** [review]
We are not able to change the behaviour on the `CatalogKindHeader` as that would be a breaking change for anyone using it in their custom catalog pages. We can however not render this component in the [DefaultCatalogPage](https://github.com/backstage/backstage/blob/master/plugins/catalog/src/components/CatalogPage/DefaultCatalogPage.tsx#L79) This is similar to what we do in [docs](https://demo.backstage.io/docs?filters%5Buser%5D=all) and [API](https://demo.backstage.io/api-docs?filters%5Bkind%5D=api&filters%5Buser%5D=all) pages.

**Comment by lucahuettner** [comment]
Okay, so do we want to remove the header completely like in [API](https://demo.backstage.io/api-docs?filters%5Bkind%5D=api&filters%5Buser%5D=all) or still want to keep it in the `DefaultCatalogPage` but not as a select?

If we want to keep it I could add an optional `staticHeader` (or any name recommendations?) prop to `CatalogKindHeader` which returns a normal `<Typography/>` header instead of a select if set to true. I think this shouldn't break any existing implementations that use the `CatalogKindHeader`.

**Comment by jhaals** [comment]
I discussed this briefly with @freben and @Rugvip (please correct me if I interpreted our conclusion incorrectly 😅), we opted for constancy by removing the header from the `DefaultCatalogPage` but still keeping the component around for those that want to use it. Possibly adding a `@deprecated` to it as well which open up for removing it in the next major release

**Review by djamaile — COMMENTED** [review]
@lucahuettner Hi! Don't forget to run api reports command 😄 Example: `yarn run build:api-reports plugin/catalog`

File: plugins/catalog/src/components/CatalogKindHeader/CatalogKindHeader.tsx [hunk 1]
```diff
@@ -59,7 +59,10 @@ export interface CatalogKindHeaderProps {
   initialFilter?: string;
 }
 
-/** @public */
+/**
+ * @public
+ * @deprecated Might be removed in a future release.
```
Comment (djamaile) [inline plugins/catalog/src/components/CatalogKindHeader/CatalogKindHeader.tsx:64]: non-blocking comment, but I wonder if this description is good enough. As from the user standpoint this might be sufficiënt to let me know why this is deprecated and if should (not) use it. I'll leave the final judgement to @jhaals

Comment (jhaals) [reply plugins/catalog/src/components/CatalogKindHeader/CatalogKindHeader.tsx:64]: Good point @djamaile.
As this deprecation might be controversial for users I suggest that we add some more context and also tell users that want this functionality to remain to create an issue.

For example
```suggestion
* @deprecated This component has been deprecated in favour of the EntityKindPicker in the list of filters. If you wish to keep this component long term make sure to raise an issue at github.com/backstage/backstage
```

File: .changeset/modern-camels-cheat.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/plugin-catalog': patch
+---
+
+Remove `CatalogKindHeader` from `DefaultCatalogPage`. Deprecate `CatalogKindHeader`.
```
Comment (jhaals) [inline .changeset/modern-camels-cheat.md:5]:
```suggestion
Removed `CatalogKindHeader` from `DefaultCatalogPage`. Deprecated `CatalogKindHeader` in favour of `EntityKindPicker`.
```

**Review by jhaals — CHANGES_REQUESTED** [review]

**Review by jhaals — CHANGES_REQUESTED** [review]
Thanks for the changes, one very minor thing and then I think we're good to go!

**Review by jhaals — APPROVED** [review]
Thank you!
