### PR TITLE
fix: Prefer accountId for AwsOrganizationCloudAccountProcessor authentication

### LINKED ISSUE #18052: 🐛 Bug Report: `AwsOrganizationCloudAccountProcessor` no longer respects provided `roleArn` in configuration
### 📜 Description

In our Backstage instance, we utilize the `AwsOrganizationCloudAccountProcessor` to consume AWS accounts from our Principal Org (Backstage runs in a different AWS account). To do this, we assume a role outside of the AWS account our Backstage instance runs in order to have access to the `ListAccounts` organization endpoint.

Here is what our configuration looks like for `AwsOrganizationCloudAccountProcessor`
```yaml
catalog:
  processors:
    awsOrganization:
      provider:
        roleArn: 'arn:aws:iam::<other-account-id>:role/<list-organizations-role-name>'
```

After upgrading to `1.14.1`, we noticed that there was now new necessary required configuration to support the new [`DefaultAwsCredentialsManager`](https://github.com/backstage/backstage/blob/v1.14.1/packages/integration-aws-node/src/DefaultAwsCredentialsManager.ts) since the `AwsOrganizationCloudAccountProcessor` uses the credentials manager to find the Credentials to use for the `<other-account-id>` specified in our `roleArn` ([source](https://github.com/backstage/backstage/blob/v1.14.1/plugins/catalog-backend-module-aws/src/processors/AwsOrganizationCloudAccountProcessor.ts#L59-L63))

_However_, the creds determined there **do not** respect the `catalog.processors.awsOrganization.provider.roleArn` configuration since `awsCredentialsManager.getCredentialProvider()` does not use the provided ARN to assume the role _unless_ we use the following full set of configuration

```yaml
catalog:
  processors:
    awsOrganization:
      provider:
        roleArn: 'arn:aws:iam::<other-account-id>:role/<list-organizations-role-name>'

aws:
  accounts:
    - accountId: "<other-account-id>"
      roleName: <list-organizations-role-name>
```

We want to always utilize the default provider credential chain and be able to optionally assume roles for specific processors/providers. This configuration makes it so that is not possible, we will _always_ cache credentials assumed as `<list-organizations-role-name>` anywhere else we want to access the `<other-account-id>` AWS account.

### 👍 Expected behavior

The `AwsOrganizationCloudAccountProcessor` should still properly assume the `catalog.processors.awsOrganization.provider.roleArn` role with the following minimal configuration

```yaml
catalog:
  processors:
    awsOrganization:
      provider:
        roleArn: 'arn:aws:iam::<other-account-id>:role/<list-organizations-role-name>'

aws:
  accounts:
    - accountId: "<other-account-id>"
```

This makes it so that we always use the default credentials chain and are able to assume arbitrary roles for specific purposes

### 👎 Actual Behavior with Screenshots

We must globally configure a specific `roleName` for a specific `accountId`, which prevents us from having dedicated roles for specific providers/processors 

Without specifying `roleName` in the `aws.accounts` configuration, we receive the following error:
```
2023-05-31T20:40:36.328Z catalog warn Processor AwsOrganizationCloudAccountProcessor threw an error while reading aws-cloud-accounts:<ID>; caused by AccessDeniedException: You don't have permissions to access this resource. 
```

### 👟 Reproduction steps

1. create a specific AWS Role that grants `ListAccounts` access that Backstage should assume
2. add the following config
```yaml
catalog:
  processors:
    awsOrganization:
      provider:
        roleArn: 'arn:aws:iam::<other-account-id>:role/<list-organizations-role-name>'

aws:
  accounts:
    - accountId: "<other-account-id>"
```
3. integrate the `AwsOrganizationCloudAccountProcessor` with a location entity for the org to consume accounts from
4. Run backstage with AWS credentials in the environment for a role that can assume `arn:aws:iam::<other-account-id>:role/<list-organizations-role-name>`
5. hit the error

### 📃 Provide the context for the Bug.

Currently, the duplication of specifying the `roleArn` and `roleName` is annoying and not ideal, but moving forward, we would love to be able to not be tied to a specific role for any given AWS account for the `DefaultAwsCredentialsManager`.

We heavily make use of AWS roles to limit exposure and would like to not grant multiple unrelated permissions globally to our application role if not necessary.

### 🖥️ Your Environment

```
OS: Darwin 22.4.0 - darwin/x64
node: v16.14.0
backstage: 1.14.1
Dependencies:
    @backstage/app-defaults: 1.3.1
    @backstage/backend-app-api: 0.4.3
    @backstage/backend-common: 0.18.5
    @backstage/backend-dev-utils: 0.1.1
    @backstage/backend-plugin-api: 0.5.2
    @backstage/backend-tasks: 0.5.2
    @backstage/backend-test-utils: 0.1.37
    @backstage/catalog-client: 1.4.1
    @backstage/catalog-model: 1.2.0, 1.3.0
    @backstage/cli-common: 0.1.12
    @backstage/cli-node: 0.1.0
    @backstage/cli: 0.22.7
    @backstage/config-loader: 1.3.0
    @backstage/config: 1.0.7
    @backstage/core-app-api: 1.8.0
    @backstage/core-components: 0.12.4, 0.12.5, 0.13.1
    @backstage/core-plugin-api: 1.0.6, 1.5.1
    @backstage/dev-utils: 1.0.15
    @backstage/errors: 1.1.5
    @backstage/eslint-plugin: 0.1.3
    @backstage/integration-aws-node: 0.1.3
    @backstage/integration-react: 1.1.13
    @backstage/integration: 1.4.5
    @backstage/plugin-analytics-module-ga: 0.1.29
    @backstage/plugin-api-docs-module-protoc-gen-doc: 0.1.2
    @backstage/plugin-api-docs: 0.9.3
    @backstage/plugin-app-backend: 0.3.45
    @backstage/plugin-auth-backend: 0.18.3
    @backstage/plugin-auth-node: 0.2.14
    @backstage/plugin-catalog-backend-module-aws: 0.2.0
    @backstage/plugin-catalog-backend-module-github: 0.3.0
    @backstage/plugin-catalog-backend: 1.9.1
    @backstage/plugin-catalog-common: 1.0.13
    @backstage/plugin-catalog-graph: 0.2.30
    @backstage/plugin-catalog-node: 1.3.6
    @backstage/plugin-catalog-react: 1.2.1, 1.6.0
    @backstage/plugin-catalog: 1.11.0
    @backstage/plugin-devtools-backend: 0.1.0
    @backstage/plugin-devtools-common: 0.1.0
    @backstage/plugin-devtools: 0.1.0
    @backstage/plugin-events-backend-module-github: 0.1.7
    @backstage/plugin-events-backend-test-utils: 0.1.7
    @backstage/plugin-events-backend: 0.2.6
    @backstage/plugin-events-node: 0.2.6
    @backstage/plugin-explore-backend: 0.0.7
    @backstage/plugin-explore-common: 0.0.1
    @backstage/plugin-explore-react: 0.0.28
    @backstage/plugin-explore: 0.4.3
    @backstage/plugin-github-actions: 0.5.18
    @backstage/plugin-github-pull-requests-board: 0.1.12
    @backstage/plugin-home: 0.5.2
    @backstage/plugin-kubernetes-backend: 0.11.0
    @backstage/plugin-kubernetes-common: 0.6.3
    @backstage/plugin-kubernetes: 0.9.1
    @backstage/plugin-org: 0.6.8
    @backstage/plugin-pagerduty: 0.5.11
    @backstage/plugin-permission-common: 0.7.5
    @backstage/plugin-permission-node: 0.7.8
    @backstage/plugin-permission-react: 0.4.12
    @backstage/plugin-proxy-backend: 0.2.39
    @backstage/plugin-scaffolder-backend: 1.14.0
    @backstage/plugin-scaffolder-common: 1.3.0
    @backstage/plugin-scaffolder-node: 0.1.3
    @backstage/plugin-scaffolder-react: 1.4.0
    @backstage/plugin-scaffolder: 1.13.1
    @backstage/plugin-search-backend-module-catalog: 0.1.1
    @backstage/plugin-search-backend-module-elasticsearch: 1.3.0
    @backstage/plugin-search-backend-module-explore: 0.1.1
    @backstage/plugin-search-backend-module-pg: 0.5.6
    @backstage/plugin-search-backend-node: 1.2.1
    @backstage/plugin-search-backend: 1.3.1
    @backstage/plugin-search-common: 1.2.3
    @backstage/plugin-search-react: 1.6.0
    @backstage/plugin-search: 1.3.0
    @backstage/plugin-shortcuts: 0.3.10
    @backstage/plugin-tech-insights-backend-module-jsonfc: 0.1.29
    @backstage/plugin-tech-insights-backend: 0.5.11
    @backstage/plugin-tech-insights-common: 0.2.10
    @backstage/plugin-tech-insights-node: 0.4.3
    @backstage/plugin-tech-insights: 0.3.10
    @backstage/plugin-user-settings-backend: 0.1.9
    @backstage/plugin-user-settings: 0.7.3
    @backstage/release-manifests: 0.0.9
    @backstage/test-utils: 1.3.1
    @backstage/theme: 0.2.19, 0.3.0
    @backstage/types: 1.0.2
    @backstage/version-bridge: 1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by ooiyeefei**
…tication

## Hey, I just made a Pull Request!

Closes #18052 - update for AwsOrganizationCloudAccountProcessor to use accountId as preferred

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/catalog-backend-module-aws/src/processors/AwsOrganizationCloudAccountProcessor.ts [hunk 1]
```diff
@@ -98,23 +106,27 @@ export class AwsOrganizationCloudAccountProcessor implements CatalogProcessor {
...
-      .forEach(entity => {
-        emit(processingResult.entity(location, entity));
-      });
+          return true;
+        })
+        .forEach(entity => {
+          emit(processingResult.entity(location, entity));
+        });
+    } catch (e) {
+      this.logger?.error(e);
```
Comment (vinzscam) [inline plugins/catalog-backend-module-aws/src/processors/AwsOrganizationCloudAccountProcessor.ts:128]: don't we need to emit the error at this point? cc @freben

**Review by vinzscam — CHANGES_REQUESTED** [review]

File: .changeset/swift-kings-sparkle.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/plugin-catalog-backend-module-aws': patch
+---
+
+AwsOrganizationCloudAccountProcessor configuration field roleArn is deprecated in favor of new field accountId
```
Comment (freben) [inline .changeset/swift-kings-sparkle.md:5]:
```suggestion
`AwsOrganizationCloudAccountProcessor` configuration field `roleArn` is deprecated in favor of new field `accountId`
```

this disabled the spell check for those words since they are treated as code

File: plugins/catalog-backend-module-aws/src/awsOrganization/config.ts [hunk 3]
```diff
@@ -24,6 +24,11 @@ export type AwsOrganizationProviderConfig = {
    * The role to assume for the processor.
    */
   roleArn?: string;
```
Comment (freben) [inline plugins/catalog-backend-module-aws/src/awsOrganization/config.ts:26]: may want to add a `@deprecated` on this one's doc comment as well

File: plugins/catalog-backend-module-aws/src/processors/AwsOrganizationCloudAccountProcessor.ts (hunk 1 above)
Comment (freben) [reply plugins/catalog-backend-module-aws/src/processors/AwsOrganizationCloudAccountProcessor.ts:128]: Yeah. In fact it looks like temporary test code right? Might as well just remove the try/catch and let it bubble out to the caller instead.

Comment (niallthomson) [reply plugins/catalog-backend-module-aws/src/processors/AwsOrganizationCloudAccountProcessor.ts:128]: The reason we included this was we were actually having problems with the code throwing errors and we didn't see any output in the logs. I'll revert this code since it isn't directly related to the PR.

File: plugins/catalog-backend-module-aws/src/awsOrganization/config.ts (hunk 3 above)
Comment (niallthomson) [reply plugins/catalog-backend-module-aws/src/awsOrganization/config.ts:26]: Hey @freben might need more direction on this one. What doc comment needs amended?

File: .changeset/swift-kings-sparkle.md (hunk 2 above)
Comment (niallthomson) [reply .changeset/swift-kings-sparkle.md]: Updated this

**Review by vinzscam — APPROVED** [review]

File: plugins/catalog-backend-module-aws/src/awsOrganization/config.ts (hunk 3 above)
Comment (niallthomson) [reply plugins/catalog-backend-module-aws/src/awsOrganization/config.ts:26]: That should already be there:

https://github.com/backstage/backstage/blob/2b8b4f115a1f3052dc5db9ff14c33b8d0afd8d20/plugins/catalog-backend-module-aws/config.d.ts#L29

File: plugins/catalog-backend-module-aws/src/awsOrganization/config.ts [hunk 4]
```diff
@@ -24,6 +24,11 @@ export type AwsOrganizationProviderConfig = {
    * The role to assume for the processor.
```
Comment (vinzscam) [inline plugins/catalog-backend-module-aws/src/awsOrganization/config.ts:24]:
```suggestion
   * The role to assume for the processor.
   * @deprecated Use `accountId` instead.
```

**Comment by benjdlambert** [comment]
Nice thanks! :pray:
