### PR TITLE
org: Update visual display on User and Group cards

### LINKED ISSUE #4211: org: Visual alignment of data on User Profile Card
Trivial visual bug of aligning text on the User Profile Card in the `org` plugin.

## Expected Behavior

The displayed data for a user lines up in a table-like fashion.

## Current Behavior

The user's e-mail address and the list of their group memberships aren't fully aligned, likely because the e-mail and group icons are slightly different widths.

image

## Possible Solution

Display the data in this section of the card in a table to drive better alignment - icons first row, data second, etc.

Currently, the e-mail icon + e-mail is displayed in one Grid element, and the group icon + group names are displayed in another grid element. So the grid items line up, but the element spacing _in them_ do not. Could set some sort of forced width on the icons, if that's a thing, or refactor the Grid as either fixed width (as you wouldn't want the icons to move away from the text), or refactor as a table.

https://github.com/backstage/backstage/blob/master/plugins/org/src/components/Cards/User/UserProfileCard/UserProfileCard.tsx

## Steps to Reproduce

1. Load user data to the catalog entities
2. At least one user must have an e-mail provided (I used GitHub) and at least one group
3. View the user's card at `/catalog/default/user/<userid>`

## Context

Neither my users nor I will likely think about it again, unless it comes back at me in my dreams  haunting my alignment sensibilities.  😴 👻 :twisted_rightwards_arrows:

But as more and more data is displayed in this card over time, the alignment may become more noticable.

## Your Environment

- NodeJS Version (v12): v12 and v14
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information: Microsoft Edge (Chrome engine)

### PR DESCRIPTION
**Pull request by adamdmharvey**
## Hey, I just made a Pull Request!

Closes #4211.

* Updates the contents of the about cards in both User and Group pages using a `<List>` to fix some minor visual alignment
* Grid/box fixes to improve alignment/reduce complexity. (avatar icons weren't truly 3 spaced and aligned with other content, I've tested varying sizes (sm/md/lg), resizing etc.)
* Makes the user's e-mail clickable (to mailto:, firing up your local e-mail client).
* Replaces the title of the Group about card with the group's description, if it's available. This better lines up with how the user card shows, with the user name (like `adamharvey`) or the group name (like `backend-team`) at the top of the page and the friendly version in the card (e.g., "Adam Harvey" or "Members of the Backend Team").

### User card

image

### Parent team with a child
image

### Child team with a parent

image

### Group with no description; name repeated in about card

image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

File: plugins/org/src/components/Cards/Group/GroupProfile/GroupProfileCard.tsx [hunk 1]
```diff
@@ -76,77 +85,68 @@ export const GroupProfileCard = ({
     ?.map(groupItem => groupItem.target.name)
     .toString();
 
-  const childrens = group?.relations
+  const childRelations = group?.relations
     ?.filter(r => r.type === RELATION_PARENT_OF)
     ?.map(groupItem => groupItem.target.name);
```
Comment (Fox32) [inline plugins/org/src/components/Cards/Group/GroupProfile/GroupProfileCard.tsx:90]: Btw, we now have a helper for this: `getEntityRelations` in `@backstage/plugin-catalog-react`

File: plugins/org/src/components/Cards/Group/GroupProfile/GroupProfileCard.tsx [hunk 2]
```diff
@@ -76,77 +85,68 @@ export const GroupProfileCard = ({
...
   const displayName = profile?.displayName ?? name;
+  const descriptionHeading = description ?? name;
 
   if (!group) return <Alert severity="error">User not found</Alert>;
 
   return (
     <InfoCard
-      title={<CardTitle title={displayName} />}
-      subheader={description}
+      title={<CardTitle title={descriptionHeading} />}
```
Comment (Fox32) [inline plugins/org/src/components/Cards/Group/GroupProfile/GroupProfileCard.tsx:99]: Sure that you want to display the group description as the heading? I would expect `displayName` here? In our data the description contains a description/mission of the group, for example the field of responsibility. I think that would be quite neat as a subheader.
The `UserCard` is also doing it that way.

File: plugins/org/src/components/Cards/User/UserProfileCard/UserProfileCard.tsx [hunk 3]
```diff
@@ -80,40 +89,35 @@ export const UserProfileCard = ({
...
-              <Box ml={1} display="inline">
+        <Grid item md={10} lg={11}>
+          <List>
+            {profile?.email && (
+              <ListItem>
+                <ListItemIcon>
+                  <EmailIcon />
+                </ListItemIcon>
+                <ListItemText>
+                  <Link href={emailHref}>{profile.email}</Link>
```
Comment (Fox32) [inline plugins/org/src/components/Cards/User/UserProfileCard/UserProfileCard.tsx:109]: This code isn't using `Link` from `@backstage/core`, but I'm not sure if that one would support `mailto:`

Comment (freben) [reply plugins/org/src/components/Cards/User/UserProfileCard/UserProfileCard.tsx:109]: If it doesn't we should make it!

File: plugins/org/src/components/Cards/Group/GroupProfile/GroupProfileCard.tsx (hunk 2 above)
Comment (adamdmharvey) [reply plugins/org/src/components/Cards/Group/GroupProfile/GroupProfileCard.tsx:99]: Yes - difference here is the display name for, say a GitHub group called `testing-service`, is `testing-service`. WHile the display name for GitHub user `adamdmharvey` because I have it in my profile is `Adam Harvey`.

So the reason I had changed this was that the header, in most cases, just looked duplicative?

| User | Group |
| --- | --- |
|  image | image |

But fair, if you have very large descriptions that would wildly blow out these headers, I can see that would be problematic. All of the examples I looked at at my firm were about 5-15 words long and fit relatively well. I also checked GItHub's REST API and could not find a max size of description.

So all of that to say, happy to put this back the way it was for group card; appreciate the feedback.

File: plugins/org/src/components/Cards/User/UserProfileCard/UserProfileCard.tsx (hunk 3 above)
Comment (adamdmharvey) [reply plugins/org/src/components/Cards/User/UserProfileCard/UserProfileCard.tsx:109]: * @Fox32 , yes this works.  This is the Material-UI Link, which allows href, and this is just translated back to standard href links via HTML.
* @freben agree.  Fox32 is correct - `@backstage/core` requires the variable `to` and thus always needs a route, and does NOT support providing href's i.e. URLs.

File: plugins/org/src/components/Cards/Group/GroupProfile/GroupProfileCard.tsx (hunk 1 above)
Comment (adamdmharvey) [reply plugins/org/src/components/Cards/Group/GroupProfile/GroupProfileCard.tsx]: Awesome - thanks! I gave it a shot, but could use your review to ensure I used it correctly. 🤜🤛

Comment (Fox32) [reply plugins/org/src/components/Cards/Group/GroupProfile/GroupProfileCard.tsx]: Looks good

**Comment by adamdmharvey** [comment]
Think this one is ready for maintainers review. 🚀 Appreciate the feedback @Fox32. Thx!

File: plugins/org/src/components/Cards/User/UserProfileCard/UserProfileCard.tsx (hunk 3 above)
Comment (andrewthauer) [reply plugins/org/src/components/Cards/User/UserProfileCard/UserProfileCard.tsx:109]: It might be a good idea to check if email is set before displaying the mailto link. I'm pretty sure this is field is optional and in the case of GitHub users there are many times people do not make it public.

Comment (adamdmharvey) [reply plugins/org/src/components/Cards/User/UserProfileCard/UserProfileCard.tsx:109]: @andrewthauer Should already be handled because that entire section is wrapped with a ~{ profile?.email ? }` element. So if there's no e-mail, the list item won't even display. (I checked on a number of my users who I know lacked e-mails also.)

**Review by Rugvip — APPROVED** [review]
Looks good, thanks! 😁  🎉
