### PR TITLE
Added validation for component id in the CRA template, fixed issue when job stages fail

### LINKED ISSUE #3077: Some errors in Run Templater stage are not correctly represented in the JobStatusModal since logger fails to log the error
When creating a new component using the CRA template, if the Run Templater stage throws an error, the modal is not updated accordingly. The Run Templater stage's status gets stuck at "STARTED" (blue color) when it should be "FAILED" (red color).  
Screenshot 2020-10-24 at 11 10 30

When I debugged it, I found that in `processor.ts`, the error is caught as expected in [processor.ts line 119](https://github.com/spotify/backstage/blob/f72b512649f3edc2d62a4207efac7214b8476e7a/plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts#L119). However, logger.error() in that catch-block throws its own exception, namely _"[ERR_STREAM_WRITE_AFTER_END]: write after end"_ which is consequently caught at [line 134](https://github.com/spotify/backstage/blob/f72b512649f3edc2d62a4207efac7214b8476e7a/plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts#L134). Since stage.status is set after the logger throws a new error, it's never reflected in the GUI that the stage failed. 

I've tried to find out where/why the logger is prematurely closed but to no avail. To make matters more complicated, the issue doesn't seem to be consistent for all errors. For example, when I create a component without Docker running (which also breaks the Run Templater stage with _"ECONNREFUSED"_) it doesn't happen. 

## Expected Behavior
- The Run Templater stage should get marked as "FAILED", making the sidebar color red. 
- The logger should not fail to log the error. 

## Current Behavior
- The Run Templater stage gets stuck on "STARTED", making the sidebar color blue, even it it failed. 
- The logger throws _"[ERR_STREAM_WRITE_AFTER_END]: write after end"_.

## Possible Solution
- A quick work-around which doesn't solve the logger-issue is just to set the stage's status before logging the error.
- For the logger ending prematurely, I don't know!

## Steps to Reproduce
1. navigate to `/create/create-react-app-template`
2. For the component-Id field, enter a name with capital letters. 
3. Go through the rest of the form and press "Create".
4. Wait for the Run Templater stage to break.
5. See error. 

My setup: notice the invalid Component ID
Screenshot 2020-10-24 at 11 13 47

## Context
[Error caught in processor.ts line 119: ](https://github.com/spotify/backstage/blob/f72b512649f3edc2d62a4207efac7214b8476e7a/plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts#L119)

Screenshot 2020-10-24 at 16 28 05

[Error caught in processor.ts line 134: ](https://github.com/spotify/backstage/blob/f72b512649f3edc2d62a4207efac7214b8476e7a/plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts#L134)

Screenshot 2020-10-24 at 16 27 34

## Your Environment
NodeJS Version (v12): v12.18.4
Operating System and Version: macOS catalina version 10.15.4
Browser Information: Google Chrome Version 85.0.4183.121 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by erictnilsson**
## Hey, I just made a Pull Request!
Resolves #3077 and #3078 
For #3078, I've added validation to the component id in the CRA template using Json Schema validation's [_pattern_](https://json-schema.org/draft/2019-09/json-schema-validation.html#pattern). Also added a [custom error message](https://react-jsonschema-form.readthedocs.io/en/latest/usage/validation/#custom-error-messages) so it doesn't just say _".component-id does not match pattern "[ugly regex]""_. However, I've kept it fairly general for simplicity's sake. 

The new validation and message:
Screenshot 2020-10-26 at 20 59 47

For #3077, I've just made the it so the stage's status is updated before the error is logged. 

#### :heavy_check_mark: Checklist
- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/spotify/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

File: plugins/scaffolder/src/components/MultistepJsonForm/MultistepJsonForm.tsx [hunk 1]
```diff
@@ -63,6 +63,15 @@ export const MultistepJsonForm = ({
     setActiveStep(Math.min(activeStep + 1, steps.length));
   const handleBack = () => setActiveStep(Math.max(activeStep - 1, 0));
 
+  const transformErrors = (errors: AjvError[]) =>
+    errors.map(error => {
+      if (error.name === 'pattern') {
+        error.message = 'does not match the required pattern';
```
Comment (benjdlambert) [inline plugins/scaffolder/src/components/MultistepJsonForm/MultistepJsonForm.tsx:69]: I wonder do you get the desired pattern here? Would be good to show in the form maybe as the audience should understand the `RegEx` too

**Comment by benjdlambert** [comment]
@erictnilsson nice work! Glad that we can push most of this to the JSONSchema rather than have too much code client side, just one question for you!

File: plugins/scaffolder/src/components/MultistepJsonForm/MultistepJsonForm.tsx (hunk 1 above)
Comment (erictnilsson) [reply plugins/scaffolder/src/components/MultistepJsonForm/MultistepJsonForm.tsx:69]: If we want the error to include the RegEx pattern, I can just remove `transformErrors()` and let react-jsonschema-form do its default behaviour. Then the message shown will be _".component-id does not match pattern "^[a-z0-9]+(-[a-z0-9]+)*$"_. Does that sound good? @benjdlambert

Comment (benjdlambert) [reply plugins/scaffolder/src/components/MultistepJsonForm/MultistepJsonForm.tsx:69]: @spotify/backstage-core thoughts?

Comment (freben) [reply plugins/scaffolder/src/components/MultistepJsonForm/MultistepJsonForm.tsx:69]: Oh tough question. As a dev I like the regex version, but realize that that doesn't apply to everyone. If we can't have per field custom written details, I still think we can keep the original regex version.

Comment (erictnilsson) [reply plugins/scaffolder/src/components/MultistepJsonForm/MultistepJsonForm.tsx:69]: yeah, one idea I had was to add something like an `error_message` key to the property in template.yaml like so: 
Screenshot 2020-10-27 at 14 57 20

We can then use the `error_msg` in `transformErrors()` to display a nicer, per-field details. It's trivial to implement but I'm not sure how good of an idea it is? @freben @benjdlambert

Comment (benjdlambert) [reply plugins/scaffolder/src/components/MultistepJsonForm/MultistepJsonForm.tsx:69]: I thought I actually recalled that this was a feature in json schema forms that you could define the error message in the schema, but a quick google suggests that it might not be available and it was just a dream. I think for now, let's remove the transformErrors part and we can revisit if there's a need in the future

**Review by benjdlambert — APPROVED** [review]
