### PR TITLE
TechDocs: Change breadcrumbs link to be static "/docs"

### LINKED ISSUE #4825: TechDocs breadcrumb: highest level link is broken
## Expected Behavior

After using the TechDocs home page to navigate to a certain documentation page, I should be able to use the breadcrumbs to navigate back to the TechDocs homepage.

## Current Behavior

Clicking on the "root" Breadcrumb element of an individual docs page, takes you to a generic catalog (not documentation) homepage (and that's also due to an invalid entity link).

**TechDocs Homepage**:
image

**Backstage Component docs page**:
image

**Returned to the catalog homepage**:
image

## Possible Solution

* Statically hardcode the main route for the page that draws the documentation as `/docs`?
* Currently, the breadcrumb seems to display "entityname / Mkdocs Site Name" as elements. However, I would have expected the breadcrumbs to be "Docs / Mkdocs Site Name", where "Docs" (or Tech Docs or something that triggers for the user "a list of all available documentation) is what brings me back to the `/docs` route.

## Steps to Reproduce

1. Visit the TechDocs main route of /docs: http://localhost:3000/docs
2. Select a specific piece of documentation, e.g. the sample `backstage` site: http://localhost:3000/docs/default/Component/backstage
3. Along the top, see the Breadcrumbs which should say "backstage > Backstage".
4. Click the left-most home link "backstage" which should take you to this link: http://localhost:3000/catalog/Component/backstage
5. This is the catalog homepage.

The correct entity link in this case could have been http://localhost:3000/catalog/default/component/backstage.

But my expectation would have been getting right back to the main TechDocs homepage instead (back to the /docs route).

## Context

The reason you're brought back to the catalog homepage is in fact the entity link is wrong.  You're taken here:
http://localhost:3000/catalog/Component/backstage

But the correct entity page for that component should be:
http://localhost:3000/catalog/default/component/backstage

However, that's not where I expected to be taken back to.

## Your Environment

- NodeJS Version (v12): v12
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 WSL2 Ubuntu 18.04
- Browser Information: Edge (Chrome engine)

### PR DESCRIPTION
**Pull request by tudi2d**
Change breadcrumbs link to static reference to docs page.

Closes #4825 

image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4894-ezd0p0wxjzgihtcvauanowuqfkx6utxs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604796f4fcb22d13c16c8456

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4894-ezd0p0wxjzgihtcvauanowuqfkx6utxs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604796f4fcb22d13c16c8456

**Comment by OrkoHunter** [comment]
Hey @tudi2d  ! Good to see you around. :) You'll have to sign-off both of your commits for the DCO check to pass. [Detailed instructions here](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin) but I think you need `git rebase --signoff HEAD~2` and `git push -f`. And in future, use `git commit -s`

File: plugins/techdocs/src/reader/components/TechDocsPageHeader.tsx [hunk 1]
```diff
@@ -112,8 +112,8 @@ export const TechDocsPageHeader = ({
       subtitle={
         siteDescription && siteDescription !== 'None' ? siteDescription : ''
       }
-      type={name}
-      typeLink={componentLink(entityId)}
+      type="Docs"
+      typeLink="/docs"
```
Comment (OrkoHunter) [inline plugins/techdocs/src/reader/components/TechDocsPageHeader.tsx:116]: It's highly likely that this will be the correct URL for TechDocs plugin, but we should not assume this.

If you're up for it, the TechDocs API has an instance of something called [`discovery API`](https://github.com/backstage/backstage/blob/e07b41751e18c8f633d5d6430b2619d6e7def05c/plugins/techdocs/src/api.ts#L53) which can give you the base URL with `.getBaseUrl()`.

File: .changeset/fluffy-cooks-smoke.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/plugin-techdocs': patch
+---
+
+Change breadcrumbs link to be static
```
Comment (OrkoHunter) [inline .changeset/fluffy-cooks-smoke.md:5]:
```suggestion
On TechDocs page header, change the breadcrumbs link to be static and point to TechDocs homepage.
```

File: plugins/techdocs/src/reader/components/TechDocsPageHeader.tsx (hunk 1 above)
Comment (OrkoHunter) [reply plugins/techdocs/src/reader/components/TechDocsPageHeader.tsx:116]: We can find out `'/docs'` by `useRouteRef(rootRouteRef)()` where `useRouteRef` comes from `@backstage/core` and `rootRouteRef` is defined inside `plugins/techdocs/plugin.ts`

**Comment by tudi2d** [comment]
Thanks for the review @OrkoHunter - appreciate the instructions - wasn't aware of the route references. Hope everything is good now - have a great weekend! :)

File: plugins/techdocs/src/reader/components/TechDocsPageHeader.tsx [hunk 3]
```diff
@@ -59,6 +60,8 @@ export const TechDocsPageHeader = ({
     ownerEntity = parseEntityName(owner, { defaultKind: 'group' });
   }
 
+  const docsRootLink = useRouteRef(rootRouteRef)();
```
Comment (adamdmharvey) [inline plugins/techdocs/src/reader/components/TechDocsPageHeader.tsx:63]: is this an extra pair of parens?

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4894-ezd0p0wxjzgihtcvauanowuqfkx6utxs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604796f4fcb22d13c16c8456

File: plugins/techdocs/src/reader/components/TechDocsPageHeader.tsx (hunk 3 above)
Comment (tudi2d) [reply plugins/techdocs/src/reader/components/TechDocsPageHeader.tsx:63]: Yes - `useRouteRef` returns a `RouteFunc`

image

Comment (adamdmharvey) [reply plugins/techdocs/src/reader/components/TechDocsPageHeader.tsx:63]: ah I see; learning new things every day, thank you @tudi2d !

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4894-ezd0p0wxjzgihtcvauanowuqfkx6utxs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/604796f4fcb22d13c16c8456

**Review by freben — APPROVED** [review]

**Review by OrkoHunter — APPROVED** [review]
Sweet! 🎉
