### PR TITLE
auth-node: Refresh handler not returning persisted scope in response

### LINKED ISSUE #20322: 🐛 Bug Report: auth.getAccessToken doesn't survive page reloads anymore
### 📜 Description

When calling auth.getAccesToken for the GitHub provider, it forces the user to login even if they're already logged in. This session can withstand route changes and subsequent calls, but not a page reload. The user will see a login popup again.

### 👍 Expected behavior

It should work as it used to where if the provider has already been authorized, a token should be returned.

### 👎 Actual Behavior with Screenshots

It actually props the user to login on every page load.

Screenshot 2023-10-02 at 12 34 20

### 👟 Reproduction steps

Using backstage 1.18.3 try something like the PR plugin (https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/frontend/backstage-plugin-github-pull-requests)

I'm experiencing the same behavior on an internal techdocs addon that calls the GH api.

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

Chrome Version 117.0.5938.132 (Official Build) (arm64)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kunickiaj**
## Fix OAuth refresh handler in auth-node prompting for re-login on page reload.

The refresh handler is returning an empty scope if scope was previously saved in a cookie. The session is successfully refreshed but the client receives a response without the scope it requested, prompting a new login.

This should also be backported to 1.18.x

Resolves #20322

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by Rugvip** [comment]
Patch release in #20367

**Comment by xyzmurali** [comment]
Hi, We are seeing a similar issue where this issue does not happen during first login to github using authenticator app, but happens during subsequent login after logging out of github and logging in again. 

This issue can be reproduced with below steps.

1. Go to page where Github authenticator sign in present
2. Login to github using Github authenticator
3. Go to page where 'backstage-plugin-github-pull-requests' results should be displayed. The results are displayed
4. Go to page where Github authenticator sign in present
5. Log out of gihub 
6. login to github again
7.  Go to page where 'backstage-plugin-github-pull-requests' results should be displayed. The results are not displayed and asks for github login again.

I see that the fix for "scope: result.session.scope," was made only to one location in file plugins/auth-node/src/oauth/createOAuthRouteHandlers.ts but it is present at two locations. Can this be an issue?

File: plugins/auth-node/src/oauth/createOAuthRouteHandlers.ts [hunk 1]
```diff
@@ -320,7 +320,9 @@ export function createOAuthRouteHandlers<TProfile>(
           providerInfo: {
             idToken: result.session.idToken,
             accessToken: result.session.accessToken,
-            scope: result.session.scope,
```
Comment (xyzmurali) [inline plugins/auth-node/src/oauth/createOAuthRouteHandlers.ts:323]: Hi, We are seeing a similar issue where this issue does not happen during first login to github using authenticator app, but happens during subsequent login after logging out of github and logging in again.

This issue can be reproduced with below steps.

Go to page where Github authenticator sign in present
Login to github using Github authenticator
Go to page where 'backstage-plugin-github-pull-requests' results should be displayed. The results are displayed
Go to page where Github authenticator sign in present
Log out of gihub
login to github again
Go to page where 'backstage-plugin-github-pull-requests' results should be displayed. The results are not displayed and asks for github login again.
I see that the fix for "scope: result.session.scope," was made only to one location in file plugins/auth-node/src/oauth/createOAuthRouteHandlers.ts but it is present at two locations. Can this be an issue?

**Comment by awanlin** [comment]
@xyzmurali it would be best to log this as an issue as it's not going to be followed up easily here 👍

**Comment by xyzmurali** [comment]
Thank you, i submitted issue https://github.com/backstage/backstage/issues/24652
