### PR TITLE
fix(PermissionClient): fix rules schema to handle optional params

### LINKED ISSUE #14228: Playlist plugin-playlist-backend throws internal error when using DefaultPlaylistPermissionPolicy provided with plugin
## Expected Behavior

When an authenticated user navigates to the Playlists page via the sidebar link, the Playlists front-end should display correctly.

## Actual Behavior

When an authenticated user navigates to the Playlists page via the sidebar link, the Playlists playlists front-end displays with the following warning message:
Warning: Oops! something went wrong loading playlists
Request failed with 500 ZodError
Also, while the flow to create a Playlist is accessible in the front-end, the Playlist does not save and an error is being thrown by the backend plugin.

## Steps to Reproduce

Testing with this project's example-app using the commit for version 1.7.0 24e54dda874e42713304246dbf92c9b45ec3e00d
1. Start the application using yarn dev
2. Sign in using a Github account via the 'Sign In using GitHub option'
3. Select the Playlists option in the side bar, user is presented with the warning message.
4. Create a playlist, playlist does not save.

## Context

Cannot use default permissions provided with the playlist plugin. The plugin appears to be incompatible with latest changes to the permissions plugins
This issue is present in the backstage source same app
https://github.com/backstage/backstage
## Your Environment

- Browser Information: Google Chrome Version 106.0.5249.119 (Official Build) (x86_64)

- Output of `yarn backstage-cli info`: 

```text
yarn backstage-cli info
OS:   Darwin 21.6.0 - darwin/x64
node: v16.15.1
yarn: 3.2.3
cli:  0.20.0 (local)
backstage:  N/A

Dependencies:
  @backstage/app-defaults                                   0.0.0-use.local
  @backstage/backend-app-api                                0.0.0-use.local
  @backstage/backend-common                                 0.0.0-use.local
  @backstage/backend-defaults                               0.0.0-use.local
  @backstage/backend-plugin-api                             0.0.0-use.local
  @backstage/backend-tasks                                  0.0.0-use.local
  @backstage/backend-test-utils                             0.0.0-use.local
  @backstage/catalog-client                                 0.0.0-use.local
  @backstage/catalog-model                                  0.0.0-use.local
  @backstage/cli-common                                     0.0.0-use.local
  @backstage/cli                                            0.0.0-use.local
  @backstage/codemods                                       0.0.0-use.local
  @backstage/config-loader                                  0.0.0-use.local
  @backstage/config                                         0.0.0-use.local
  @backstage/core-app-api                                   0.0.0-use.local
  @backstage/core-components                                0.0.0-use.local
  @backstage/core-plugin-api                                0.0.0-use.local
  @backstage/create-app                                     0.0.0-use.local
  @backstage/dev-utils                                      0.0.0-use.local
  @backstage/errors                                         0.0.0-use.local
  @backstage/integration-react                              0.0.0-use.local
  @backstage/integration                                    0.0.0-use.local
  @backstage/plugin-adr-backend                             0.0.0-use.local
  @backstage/plugin-adr-common                              0.0.0-use.local
  @backstage/plugin-adr                                     0.0.0-use.local
  @backstage/plugin-airbrake-backend                        0.0.0-use.local
  @backstage/plugin-airbrake                                0.0.0-use.local
  @backstage/plugin-allure                                  0.0.0-use.local
  @backstage/plugin-analytics-module-ga                     0.0.0-use.local
  @backstage/plugin-apache-airflow                          0.0.0-use.local
  @backstage/plugin-api-docs-module-protoc-gen-doc          0.0.0-use.local
  @backstage/plugin-api-docs                                0.0.0-use.local
  @backstage/plugin-apollo-explorer                         0.0.0-use.local
  @backstage/plugin-app-backend                             0.0.0-use.local
  @backstage/plugin-auth-backend                            0.0.0-use.local
  @backstage/plugin-auth-node                               0.0.0-use.local
  @backstage/plugin-azure-devops-backend                    0.0.0-use.local
  @backstage/plugin-azure-devops-common                     0.0.0-use.local
  @backstage/plugin-azure-devops                            0.0.0-use.local
  @backstage/plugin-badges-backend                          0.0.0-use.local
  @backstage/plugin-badges                                  0.0.0-use.local
  @backstage/plugin-bazaar-backend                          0.0.0-use.local
  @backstage/plugin-bazaar                                  0.0.0-use.local
  @backstage/plugin-bitbucket-cloud-common                  0.0.0-use.local
  @backstage/plugin-bitrise                                 0.0.0-use.local
  @backstage/plugin-catalog-backend-module-aws              0.0.0-use.local
  @backstage/plugin-catalog-backend-module-azure            0.0.0-use.local
  @backstage/plugin-catalog-backend-module-bitbucket-cloud  0.0.0-use.local
  @backstage/plugin-catalog-backend-module-bitbucket-server 0.0.0-use.local
  @backstage/plugin-catalog-backend-module-bitbucket        0.0.0-use.local
  @backstage/plugin-catalog-backend-module-gerrit           0.0.0-use.local
  @backstage/plugin-catalog-backend-module-github           0.0.0-use.local
  @backstage/plugin-catalog-backend-module-gitlab           0.0.0-use.local
  @backstage/plugin-catalog-backend-module-ldap             0.0.0-use.local
  @backstage/plugin-catalog-backend-module-msgraph          0.0.0-use.local
  @backstage/plugin-catalog-backend-module-openapi          0.0.0-use.local
  @backstage/plugin-catalog-backend                         0.0.0-use.local
  @backstage/plugin-catalog-common                          0.0.0-use.local
  @backstage/plugin-catalog-graph                           0.0.0-use.local
  @backstage/plugin-catalog-graphql                         0.0.0-use.local
  @backstage/plugin-catalog-import                          0.0.0-use.local
  @backstage/plugin-catalog-node                            0.0.0-use.local
  @backstage/plugin-catalog-react                           0.0.0-use.local
  @backstage/plugin-catalog                                 0.0.0-use.local
  @backstage/plugin-cicd-statistics-module-gitlab           0.0.0-use.local
  @backstage/plugin-cicd-statistics                         0.0.0-use.local
  @backstage/plugin-circleci                                0.0.0-use.local
  @backstage/plugin-cloudbuild                              0.0.0-use.local
  @backstage/plugin-code-climate                            0.0.0-use.local
  @backstage/plugin-code-coverage-backend                   0.0.0-use.local
  @backstage/plugin-code-coverage                           0.0.0-use.local
  @backstage/plugin-codescene                               0.0.0-use.local
  @backstage/plugin-config-schema                           0.0.0-use.local
  @backstage/plugin-cost-insights-common                    0.0.0-use.local
  @backstage/plugin-cost-insights                           0.0.0-use.local
  @backstage/plugin-dynatrace                               0.0.0-use.local
  @backstage/plugin-explore-react                           0.0.0-use.local
  @backstage/plugin-explore                                 0.0.0-use.local
  @backstage/plugin-firehydrant                             0.0.0-use.local
  @backstage/plugin-fossa                                   0.0.0-use.local
  @backstage/plugin-gcalendar                               0.0.0-use.local
  @backstage/plugin-gcp-projects                            0.0.0-use.local
  @backstage/plugin-git-release-manager                     0.0.0-use.local
  @backstage/plugin-github-actions                          0.0.0-use.local
  @backstage/plugin-github-deployments                      0.0.0-use.local
  @backstage/plugin-github-issues                           0.0.0-use.local
  @backstage/plugin-github-pull-requests-board              0.0.0-use.local
  @backstage/plugin-gitops-profiles                         0.0.0-use.local
  @backstage/plugin-gocd                                    0.0.0-use.local
  @backstage/plugin-graphiql                                0.0.0-use.local
  @backstage/plugin-graphql-backend                         0.0.0-use.local
  @backstage/plugin-home                                    0.0.0-use.local
  @backstage/plugin-ilert                                   0.0.0-use.local
  @backstage/plugin-jenkins-backend                         0.0.0-use.local
  @backstage/plugin-jenkins-common                          0.0.0-use.local
  @backstage/plugin-jenkins                                 0.0.0-use.local
  @backstage/plugin-kafka-backend                           0.0.0-use.local
  @backstage/plugin-kafka                                   0.0.0-use.local
  @backstage/plugin-kubernetes-backend                      0.0.0-use.local
  @backstage/plugin-kubernetes-common                       0.0.0-use.local
  @backstage/plugin-kubernetes                              0.0.0-use.local
  @backstage/plugin-lighthouse                              0.0.0-use.local
  @backstage/plugin-newrelic-dashboard                      0.0.0-use.local
  @backstage/plugin-newrelic                                0.0.0-use.local
  @backstage/plugin-org                                     0.0.0-use.local
  @backstage/plugin-pagerduty                               0.0.0-use.local
  @backstage/plugin-periskop-backend                        0.0.0-use.local
  @backstage/plugin-periskop                                0.0.0-use.local
  @backstage/plugin-permission-backend                      0.0.0-use.local
  @backstage/plugin-permission-common                       0.0.0-use.local
  @backstage/plugin-permission-node                         0.0.0-use.local
  @backstage/plugin-permission-react                        0.0.0-use.local
  @backstage/plugin-playlist-backend                        0.0.0-use.local
  @backstage/plugin-playlist-common                         0.0.0-use.local
  @backstage/plugin-playlist                                0.0.0-use.local
  @backstage/plugin-proxy-backend                           0.0.0-use.local
  @backstage/plugin-rollbar-backend                         0.0.0-use.local
  @backstage/plugin-rollbar                                 0.0.0-use.local
  @backstage/plugin-scaffolder-backend-module-cookiecutter  0.0.0-use.local
  @backstage/plugin-scaffolder-backend-module-rails         0.0.0-use.local
  @backstage/plugin-scaffolder-backend-module-yeoman        0.0.0-use.local
  @backstage/plugin-scaffolder-backend                      0.0.0-use.local
  @backstage/plugin-scaffolder-common                       0.0.0-use.local
  @backstage/plugin-scaffolder                              0.0.0-use.local
  @backstage/plugin-search-backend-module-elasticsearch     0.0.0-use.local
  @backstage/plugin-search-backend-module-pg                0.0.0-use.local
  @backstage/plugin-search-backend-node                     0.0.0-use.local
  @backstage/plugin-search-backend                          0.0.0-use.local
  @backstage/plugin-search-common                           0.0.0-use.local
  @backstage/plugin-search-react                            0.0.0-use.local
  @backstage/plugin-search                                  0.0.0-use.local
  @backstage/plugin-sentry                                  0.0.0-use.local
  @backstage/plugin-shortcuts                               0.0.0-use.local
  @backstage/plugin-sonarqube-backend                       0.0.0-use.local
  @backstage/plugin-sonarqube                               0.0.0-use.local
  @backstage/plugin-splunk-on-call                          0.0.0-use.local
  @backstage/plugin-stack-overflow-backend                  0.0.0-use.local
  @backstage/plugin-stack-overflow                          0.0.0-use.local
  @backstage/plugin-tech-insights-backend-module-jsonfc     0.0.0-use.local
  @backstage/plugin-tech-insights-backend                   0.0.0-use.local
  @backstage/plugin-tech-insights-common                    0.0.0-use.local
  @backstage/plugin-tech-insights-node                      0.0.0-use.local
  @backstage/plugin-tech-insights                           0.0.0-use.local
  @backstage/plugin-tech-radar                              0.0.0-use.local
  @backstage/plugin-techdocs-addons-test-utils              0.0.0-use.local
  @backstage/plugin-techdocs-backend                        0.0.0-use.local
  @backstage/plugin-techdocs-module-addons-contrib          0.0.0-use.local
  @backstage/plugin-techdocs-node                           0.0.0-use.local
  @backstage/plugin-techdocs-react                          0.0.0-use.local
  @backstage/plugin-techdocs                                0.0.0-use.local
  @backstage/plugin-todo-backend                            0.0.0-use.local
  @backstage/plugin-todo                                    0.0.0-use.local
  @backstage/plugin-user-settings-backend                   0.0.0-use.local
  @backstage/plugin-user-settings                           0.0.0-use.local
  @backstage/plugin-vault-backend                           0.0.0-use.local
  @backstage/plugin-vault                                   0.0.0-use.local
  @backstage/plugin-xcmetrics                               0.0.0-use.local
  @backstage/release-manifests                              0.0.0-use.local
  @backstage/test-utils                                     0.0.0-use.local
  @backstage/theme                                          0.0.0-use.local
  @backstage/types                                          0.0.0-use.local
  @backstage/version-bridge                                 0.0.0-use.local
```

### PR DESCRIPTION
**Pull request by kuangp**
Signed-off-by: Phil Kuang <pkuang@factset.com>

## Hey, I just made a Pull Request!

Fixes #14228 

This fixes the schema validation to handle scenarios where a rule has no params such as:
https://github.com/backstage/backstage/blob/8db366cc4ceb0fe6e10de81b8ba2277a350a3729/plugins/playlist-backend/src/permissions/rules.ts#L46-L52 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by kuangp** [comment]
cc: @HHogg as it looks like this was introduced in https://github.com/backstage/backstage/pull/13905

File: plugins/permission-common/src/PermissionClient.ts [hunk 1]
```diff
@@ -41,7 +41,7 @@ const permissionCriteriaSchema: z.ZodSchema<
     .object({
       rule: z.string(),
       resourceType: z.string(),
-      params: z.record(z.any()),
+      params: z.record(z.any()).optional(),
```
Comment (HHogg) [inline plugins/permission-common/src/PermissionClient.ts:44]: @kuangp I'm not sure this is a bug linked (or a bug at all). Going back to before these changes the original line was ...

```ts
params: z.array(z.unknown()),
```

... without optional. And checking out a previous commit, the same test added above fails. Are you seeing a change in functionality somewhere, because if you are, and I'm correct with the above, it might be the bug exists elsewhere.

Comment (kuangp) [reply plugins/permission-common/src/PermissionClient.ts:44]: @HHogg digging into this, here's what I suspect caused the bug here:

[Originally](https://github.com/backstage/backstage/pull/13905/files#diff-86bf8b2c2693596aa362974dcec18329152d803e6ec1b2ab8cbb8caf2c29c616L40) `createConditionFactory` was grabbing `params` via  [rest parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters). For rules that did not receive any params, this will always still result in an empty array due to the semantics of rest params.  This allowed the schema validation of `z.array(z.unknown())` to always pass before since the `params` field was always defined even if empty. This is also why the newly added test fails in the previous implementation since that is not a scenario that could actually arise so that test is not applicable before. This was not technically a bug before but is a new bug that came out of the recent changes because of changed behavior.

With the change from your PR, `params` became potentially `undefined` for rules that don't take any params and results in the schema validation `ZodError` reported in #14228 not matching `z.record(z.any())`. 

I think this change was just mistakenly left out from your PR since I see a similar schema update in [createPermissionIntegrationRouter](https://github.com/backstage/backstage/pull/13905/files#diff-7a65a8dbe156fbea873fa051cedb9605c5eb98bb19965b6d11acf04e5ba5fd31R50)

Let me know if I misunderstood anything here!

**Review by HHogg — APPROVED** [review]

**Review by Rugvip — APPROVED** [review]
Nice, thank you! 👍 

Let's :shipit:

**Comment by oconnormj** [comment]
@kuangp, @HHogg, @Rugvip,

thanks to all of you guys for turning this around so quickly. I'm very eager to get a hold of this update.

Maybe you can help me out with a query. I'm unable to import the new version into my project because we use a number of artifactory proxies. Pardon my ignorance but should the version of https://www.npmjs.com/package/@backstage/plugin-permission-common be updated to 0.7.1 so that the new version will be referenced instead of a cached version of the prior build?
Regards,
