### PR TITLE
Make `WebStorage`  notify its subscribers when `localStorage` values change in other tabs/windows

### LINKED ISSUE #14729: 🐛 Bug Report: Starred entities are overwritten from different tabs/windows
### 📜 Description

Starred entities are overwritten if modified in different tabs/windows.

### 👍 Expected behavior

When two entities are open on separate tabs and both are starred from their respective tabs, they both should be present in the starred entities.

### 👎 Actual Behavior with Screenshots

Only the last starred entity is present in the starred entities.

### 👟 Reproduction steps

1. Go to https://demo.backstage.io/catalog/default/component/playback-order
2. In a separate tab, go to https://demo.backstage.io/catalog/default/component/searcher
3. Star `playback-order` in the first tab
4. Star `searcher` in the second tab
5. Go to https://demo.backstage.io/catalog
6. Only `searcher` is starred

### 📃 Provide the context for the Bug.

It seems like each page retrieves the starred entity list. When we star/unstar an entity, it makes its update to its own starred entity list and saves the whole list. This process overwrites changes in other tabs. It behaves the same way with `storageApi` for logged-in users.

### 🖥️ Your Environment

OS:   Linux 5.10.16.3-microsoft-standard-WSL2 - linux/x64
node: v16.16.0
yarn: 1.22.19
cli:  0.20.0 (installed)
backstage:  1.7.1

Dependencies:
  @backstage/app-defaults                            1.0.7
  @backstage/backend-common                          0.15.2
  @backstage/backend-plugin-api                      0.1.3
  @backstage/backend-tasks                           0.3.6
  @backstage/catalog-client                          1.1.1
  @backstage/catalog-model                           1.1.2
  @backstage/cli-common                              0.1.10
  @backstage/cli                                     0.20.0
  @backstage/config-loader                           1.1.5
  @backstage/config                                  1.0.3
  @backstage/core-app-api                            1.1.1
  @backstage/core-components                         0.11.2
  @backstage/core-plugin-api                         1.0.7
  @backstage/dev-utils                               1.0.7
  @backstage/errors                                  1.1.2
  @backstage/integration-react                       1.1.5
  @backstage/integration                             1.3.2
  @backstage/plugin-api-docs                         0.8.10
  @backstage/plugin-app-backend                      0.3.37
  @backstage/plugin-auth-backend                     0.17.0
  @backstage/plugin-auth-node                        0.2.6
  @backstage/plugin-bitbucket-cloud-common           0.2.0
  @backstage/plugin-catalog-backend-module-bitbucket 0.2.4
  @backstage/plugin-catalog-backend                  1.5.0
  @backstage/plugin-catalog-common                   1.0.7
  @backstage/plugin-catalog-graph                    0.2.22
  @backstage/plugin-catalog-import                   0.9.0
  @backstage/plugin-catalog-node                     1.2.0
  @backstage/plugin-catalog-react                    1.2.0
  @backstage/plugin-catalog                          1.6.0
  @backstage/plugin-github-actions                   0.5.10
  @backstage/plugin-home                             0.4.26
  @backstage/plugin-jenkins-backend                  0.1.27
  @backstage/plugin-jenkins-common                   0.1.9
  @backstage/plugin-jenkins                          0.7.9
  @backstage/plugin-org                              0.5.10
  @backstage/plugin-permission-common                0.7.0
  @backstage/plugin-permission-node                  0.7.0
  @backstage/plugin-permission-react                 0.4.6
  @backstage/plugin-proxy-backend                    0.2.31
  @backstage/plugin-scaffolder-backend               1.7.0
  @backstage/plugin-scaffolder-common                1.2.1
  @backstage/plugin-scaffolder                       1.7.0
  @backstage/plugin-search-backend-module-pg         0.4.1
  @backstage/plugin-search-backend-node              1.0.3
  @backstage/plugin-search-backend                   1.1.0
  @backstage/plugin-search-common                    1.1.0
  @backstage/plugin-search-react                     1.2.0
  @backstage/plugin-search                           1.0.3
  @backstage/plugin-sonarqube-backend                0.1.2
  @backstage/plugin-sonarqube                        0.4.2
  @backstage/plugin-stack-overflow                   0.1.6
  @backstage/plugin-tech-radar                       0.5.17
  @backstage/plugin-techdocs-backend                 1.4.0
  @backstage/plugin-techdocs-module-addons-contrib   1.0.5
  @backstage/plugin-techdocs-node                    1.4.1
  @backstage/plugin-techdocs-react                   1.0.5
  @backstage/plugin-techdocs                         1.3.3
  @backstage/plugin-user-settings-backend            0.1.1
  @backstage/plugin-user-settings                    0.5.0
  @backstage/release-manifests                       0.0.6
  @backstage/test-utils                              1.2.1
  @backstage/theme                                   0.2.16
  @backstage/types                                   1.0.0
  @backstage/version-bridge                          1.0.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by dawitam11**
## Hey, I just made a Pull Request!

Currently, browser tabs and windows aren't being properly informed about `localStorage` value changes in other tabs/windows. That causes issues like overwriting data and unsynchronized tabs or windows.
This PR fixes these issues by making `StorageApi` notify all its subscribers when `localStorage` values change in other tabs/windows.

Closes #14729 

This video shows synchronized windows after the changes in this PR.

[backstage-storage-event.webm](https://user-images.githubusercontent.com/72073614/205857004-059ac768-1fb7-47db-9568-7a15de31839d.webm)

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts [hunk 1]
```diff
@@ -89,9 +89,19 @@ export class WebStorage implements StorageApi {
   observe$<T extends JsonValue>(
     key: string,
   ): Observable<StorageValueSnapshot<T>> {
+    this.addStorageEventListener();
```
Comment (freben) [inline packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts:92]: So this will add a new subscription every single time that anybody observes for changes, which probably is excessive.

We could reduce it to happening at most once per WebStorage instance, or even better ... exactly once ever, globally, and then iterating through the buckets collection to learn which one(s) to notify when events come in.

File: packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts [hunk 2]
```diff
@@ -89,9 +89,19 @@ export class WebStorage implements StorageApi {
...
     return this.observable.filter(({ key: messageKey }) => messageKey === key);
   }
 
+  private addStorageEventListener() {
+    window.addEventListener('storage', event => {
+      if (event.key?.includes(this.namespace)) {
```
Comment (freben) [inline packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts:98]: This check is probably a bit too liberal, would be best to check for ```namespace === event.key || namespace.startsWith(`${event.key}/`)``` and then looking at what that means for the replacement below (when there's an exact match with no slash)

**Review by freben — COMMENTED** [review]
Thanks! Cool stuff

File: packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts (hunk 1 above)
Comment (dawitam11) [reply packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts]: @freben 

> So this will add a new subscription every single time that anybody observes for changes, which probably is excessive.

I checked the number of storage events listeners inside browser Dev Tools and there were 2 (since there are 2 `WebStorage` observers) and I thought that wouldn't be a big deal.  But I agree with that there should be only one listener as the number of observers will probably increase over time.

> We could reduce it to happening at most once per WebStorage instance, or even better ... exactly once ever, globally, and then iterating through the buckets collection to learn which one(s) to notify when events come in.

I've updated it to be exactly one global event listener for all storage buckets as you suggested.

Thank you for your great suggestion!

File: packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts (hunk 2 above)
Comment (dawitam11) [reply packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts]: @freben Thanks, `startsWith` is a better check for this than `includes` .

> namespace.startsWith(`${event.key}/`)

I think that will never be `true` since `event.key` contains `namespace + key`. You mean `event.key.startsWith(namespace)`?

File: packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts (hunk 1 above)
Comment (dawitam11) [reply packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts]: `@backstage/cli  packages/cli/src/commands/versions/bump.test.ts` test is failing after I

File: packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts (hunk 2 above)
Comment (freben) [reply packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts]: Not sure what I meant :D Just in such a way that it works, and never gets false positives by finding matches higher up in the string instead of at the start

File: packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts (hunk 1 above)
Comment (dawitam11) [reply packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts]: > You should just hold a state flag (either in the root, or better, as a private static initialized = false in the class)

That's great, thanks!

Check this out https://github.com/backstage/backstage/pull/15040/commits/5aa0dc604f772d3b825d057b3917f498b6965405

- There's still only one listener.
- Listener will be added only if there's at least one `WebStorage` API subscriber as there's no point in adding a listener if there're no subscribers.

File: packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts [hunk 3]
```diff
@@ -35,13 +35,25 @@ export class WebStorage implements StorageApi {
     private readonly errorApi: ErrorApi,
   ) {}
 
+  private static hasSubscribers = false;
```
Comment (freben) [inline packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts:38]: `hasSubscribed`?

File: packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts [hunk 4]
```diff
@@ -89,9 +101,19 @@ export class WebStorage implements StorageApi {
...
     key: string,
   ): Observable<StorageValueSnapshot<T>> {
+    if (!WebStorage.hasSubscribers) {
+      WebStorage.addStorageEventListener();
+      WebStorage.hasSubscribers = true;
+    }
     return this.observable.filter(({ key: messageKey }) => messageKey === key);
   }
 
+  handleStorageChange(eventKey: StorageEvent['key']) {
```
Comment (freben) [inline packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts:111]: This should still be private (making it go away from the api-report file). `addStorageEventListener` can still access the private method right, since it's inside the class itself? Otherwise do `(webStorage as any). handleStorageChange `

**Review by freben — COMMENTED** [review]
Aaaaalmost there! :D

File: packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts (hunk 4 above)
Comment (dawitam11) [reply packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts:111]: > addStorageEventListener can still access the private method right, since it's inside the class itself? 

Yes, you are right. I just left it public since I also defined it in `StorageApi` interface, in case other classes implement it in the future. 

Making it private ...

Comment (dawitam11) [reply packages/core-app-api/src/apis/implementations/StorageApi/WebStorage.ts]: Done https://github.com/backstage/backstage/pull/15040/commits/1dec14de936bf550d5252b34055f5020c500fb29
