### PR TITLE
Deprecate Scaffolder config, prefer integrations config instead

### LINKED ISSUE #4133: GitLab integration does not work for the prepare and publish stages.
When you want to publish a component to GitLab from a template hosted in GitLab, it fails on both stages.

In the prepare stage, the template cloning returns 404 Not Found.

If you fix the prepare stage, the publish stage fails at the end because it does not return the `catalogInfoUrl`.

## Expected Behavior

The component should be published in a GitLab repository when the template is hosted in GitLab. 

## Current Behavior

It fails at the beginning of the prepare stage with a 404 Not Found message.

## Possible Solution

In the prepare stage the template is cloned, backstage uses the [isomorphic-git](https://github.com/isomorphic-git) library which has issues related to Github and GitLab URLs, if it does not finish on `.git` it breaks, and this is how the template repository URLs are handled by backstage (no `.git` at the end) because this is the default behavior of the library used to parse git URLs ([git-url-parse](https://github.com/IonicaBizau/git-url-parse)).

For Github, it can be fixed with a proper user-agent header, already implemented by backstage. See [here](https://github.com/isomorphic-git/isomorphic-git/issues/1145#issuecomment-653819147) and [here](https://github.com/backstage/backstage/blob/master/packages/backend-common/src/scm/git.ts#L100).

For GitLab, if you don't append the `.git` at the end, GitLab responds 301 Redirect with the proper URL but isomorphic-git does not follow redirects. This is an open [issue](https://github.com/isomorphic-git/isomorphic-git/issues/671).

A possible solution would be to add the `.git` in the repository URL.

The publish stage can be solved by adding the code related to the `catalogInfoUrl` variable, just like in the Github integration.

## Steps to Reproduce

1. Create a Location yaml in GitLab with templates hosted in GitLab as well, like https://gitlab.com/ruloweb/backstage/-/blob/master/plugins/scaffolder-backend/sample-templates/all-templates2.yaml
2. Add this Location template to your backstage instance and start/restart it.
3. Try to create a component, using one of the templates defined in the Location yaml you just added.
4. It will throw a 404 Not Found error in the Prepare stage.

## Context

I'm not able to create components hosted in GitLab.

## Your Environment

- NodeJS Version (v12): 14.15.4
- Operating System and Version (e.g. Ubuntu 14.04): macOS Catalina 10.15.7
- Browser Information: Google Chrome 87.0.4280.141 (Official Build) (x86_64)

### PR DESCRIPTION
**Pull request by benjdlambert**
## Hey, I just made a Pull Request!
- Before the upcoming work for scaffolder v2, we want to deprecate some parts to make things easier to upgrade to the newer scaffolder.
- There's duplicated config and keys everywhere for integrations config, which powers the catalog reading, and the scaffolder project generation.
- Ideally we'd just have one config section, in which you can specify different keys for different hosts etc, which would open up support for cross preparing and publishing from different provider hosts.

- Fixes #4133 
- Allow for cross provider templating

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

File: packages/integration/src/gitlab/config.ts [hunk 1]
```diff
@@ -31,7 +31,7 @@ export type GitLabIntegrationConfig = {
 
   /**
    * The base URL of the API of this provider, e.g. "https://gitlab.com/api/v4",
-   * with no trailing slash.
+   * with no trailing slash.s
```
Comment (OrkoHunter) [inline packages/integration/src/gitlab/config.ts:34]: Accidental? :)
```suggestion
   * with no trailing slash.
```

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/github.ts [hunk 2]
```diff
@@ -20,22 +20,46 @@ import { TemplateEntityV1alpha1 } from '@backstage/catalog-model';
...
-    this.token = params.token;
+  constructor(config: Config, { logger }: { logger: Logger }) {
+    this.logger = logger;
+    this.integrations = readGitHubIntegrationConfigs(
+      config.getOptionalConfigArray('integrations.github') ?? [],
+    );
+
+    if (!this.integrations.length) {
+      this.logger.warn(
+        'Integrations for Github in Scaffolder are not set. This will cause errors in a future release. Please migrate to using integrations config and specifying tokens under hostnames',
```
Comment (OrkoHunter) [inline plugins/scaffolder-backend/src/scaffolder/stages/prepare/github.ts:44]: > Please migrate to using integrations config and specifying tokens under hostnames

Is it possible to improve this message by giving out an example? Either print in the console
```
integrations:
  github:
...
```

or a permalink to a few lines of an example config file? That would help the migrations a bit.

**Review by OrkoHunter — APPROVED** [review]

**Comment by OrkoHunter** [comment]
Oops, approved the wrong PR. My bad 🤦

File: plugins/scaffolder-backend/package.json [hunk 3]
```diff
@@ -32,10 +32,10 @@
     "@backstage/backend-common": "^0.4.3",
     "@backstage/catalog-model": "^0.6.1",
     "@backstage/config": "^0.1.2",
-    "@backstage/integration": "^0.2.0",
+    "@backstage/integration": "^0.1.5",
```
Comment (Rugvip) [inline plugins/scaffolder-backend/package.json]: Should still be `0.2.0`? O_o

Same below

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/github.ts (hunk 2 above)
Comment (freben) [reply plugins/scaffolder-backend/src/scaffolder/stages/prepare/github.ts:42]: Use GitHub with that capitalization in all "regular" text

File: plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts [hunk 4]
```diff
@@ -120,6 +120,7 @@ export class JobProcessor implements Processor {
           // Log to the current stage the error that occurred and fail the stage.
           stage.status = 'FAILED';
           logger.error(`Stage failed with error: ${error.message}`);
+          logger.error(error.stack);
```
Comment (Rugvip) [inline plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts]: Prolly lock the stack as part of the previous message, or just remove?

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts [hunk 5]
```diff
@@ -22,24 +22,47 @@ import { InputError, Git } from '@backstage/backend-common';
...
-    this.privateToken =
-      config.getOptionalString('scaffolder.azure.api.token') ?? '';
+  constructor(config: Config, { logger }: { logger: Logger }) {
+    this.integrations = readAzureIntegrationConfigs(
+      config.getOptionalConfigArray('integrations.azure') ?? [],
+    );
+
+    if (!this.integrations.length) {
+      logger.warn(
+        'Integrations for Azure in Scaffolder are not set. This will cause errors in a future release. Please migrate to using integrations config and specifying tokens under hostnames',
```
Comment (Rugvip) [inline plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts:42]: This would spam ppl quite a bit won't it? It would be completely valid to not have an azure config. But then again this never actually happens either right, since `readAzureIntegrationConfigs` always returns at least one entry.

Same with the other cases below

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts [hunk 6]
```diff
@@ -22,24 +22,47 @@ import { InputError, Git } from '@backstage/backend-common';
...
 
 export class AzurePreparer implements PreparerBase {
-  private readonly privateToken: string;
+  private readonly integrations: AzureIntegrationConfig[];
+  private readonly scaffolderToken: string | undefined;
 
-  constructor(config: Config) {
-    this.privateToken =
-      config.getOptionalString('scaffolder.azure.api.token') ?? '';
+  constructor(config: Config, { logger }: { logger: Logger }) {
```
Comment (Rugvip) [inline plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts:35]: Think it would be a bit nicer to have a `AzurePreparer.fromConfig` rather than doing all of this work in the constructor.

File: plugins/scaffolder-backend/package.json (hunk 3 above)
Comment (jhaals) [reply plugins/scaffolder-backend/package.json]: Fixed, thanks!

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts (hunk 6 above)
Comment (freben) [reply plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts:35]: i've been liking the pattern of `constructor(private readonly opts: { x: string; y: integer... }) {}` so you get all of your settings in one go :) no need to line by line copy the N constructor arguments to fields

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts [hunk 7]
```diff
@@ -22,24 +22,47 @@ import { InputError, Git } from '@backstage/backend-common';
...
     opts: PreparerOptions,
   ): Promise<string> {
     const { protocol, location } = parseLocationAnnotation(template);
-    const workingDirectory = opts?.workingDirectory ?? os.tmpdir();
-    const { logger } = opts;
+    const workingDirectory = opts.workingDirectory ?? os.tmpdir();
+    const logger = opts.logger;
 
-    if (!['azure/api', 'url'].includes(protocol)) {
+    if (!['azure', 'url'].includes(protocol)) {
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts:65]: so this breaks for those that happen to have `azure/api` locations stored in their actual databases, right?

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts [hunk 8]
```diff
@@ -74,4 +99,11 @@ export class AzurePreparer implements PreparerBase {
 
     return path.resolve(tempDir, templateDirectory);
   }
+
+  private getToken(host: string): string | undefined {
+    return (
+      this.scaffolderToken ||
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts:105]: should we keep prioritising this one when present? or should we prioritise the other one

honest question :)

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts [hunk 9]
```diff
@@ -22,24 +22,47 @@ import { InputError, Git } from '@backstage/backend-common';
...
+  private readonly integrations: AzureIntegrationConfig[];
+  private readonly scaffolderToken: string | undefined;
 
-  constructor(config: Config) {
-    this.privateToken =
-      config.getOptionalString('scaffolder.azure.api.token') ?? '';
+  constructor(config: Config, { logger }: { logger: Logger }) {
+    this.integrations = readAzureIntegrationConfigs(
+      config.getOptionalConfigArray('integrations.azure') ?? [],
+    );
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts:38]: i will want to expose this type instead soon https://github.com/backstage/backstage/blob/master/packages/integration/src/types.ts#L42

so instead of dealing with the configs directly you would be able to do like `const integrations = readAzureIntegration(config)` and then `integrations.byHost(hostname).config.token` or whatever, so you don't have to do the lookups manually and knowing the config format for that part

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/gitlab.test.ts [hunk 10]
```diff
@@ -70,16 +70,17 @@ describe('GitLabPreparer', () => {
...
+  const logger = getVoidLogger();
 
   jest.spyOn(Git, 'fromAuth').mockReturnValue(mockGitClient as any);
 
   beforeEach(() => {
     jest.clearAllMocks();
   });
 
-  ['gitlab', 'gitlab/api'].forEach(protocol => {
+  ['gitlab'].forEach(protocol => {
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/prepare/gitlab.test.ts:81]: so we remove that type as well, as mentioned above

also maybe skip the iteration now :)

**Review by freben — APPROVED** [review]
got about half way, gotta prep now :)

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts (hunk 7 above)
Comment (benjdlambert) [reply plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts:65]: Hmm maybe yes. But we should prefer `url` now anyway. this is an old way of doing this. They would just have to remove the location and re register it. How should we communicate this?

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts (hunk 9 above)
Comment (benjdlambert) [reply plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts:38]: The idea (not this PR as it's huge) is that we will iterate through each of the integrations and create a new Publisher or Preparer for each host with the integration config so the preparers interface will go back to having a more simple interface injecting the client + tokens needed but we can't do that until everyone is off the scaffolder config hence this interim PR. 👍

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts (hunk 8 above)
Comment (benjdlambert) [reply plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts:105]: I think this is fine, I'd rather that we keep to as close existinging functionality right now, so that we don't use the integration config key if it doesn't have write permissions etc.

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts (hunk 9 above)
Comment (freben) [reply plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts]: Ya what you are doing is fine, I'm just mentioning that in the near future i may make this even easier to consume. :)

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts (hunk 8 above)
Comment (freben) [reply plugins/scaffolder-backend/src/scaffolder/stages/prepare/azure.ts:104]: Makes sense!

File: plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts [hunk 11]
```diff
@@ -120,7 +120,7 @@ export class JobProcessor implements Processor {
           // Log to the current stage the error that occurred and fail the stage.
           stage.status = 'FAILED';
           logger.error(`Stage failed with error: ${error.message}`);
-
+          logger.debug(error.stack);
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts:123]: I'm a bit torn on this one. If it's at debug level, we just have to make sure to return the corresponding information (or at least rich enough information) in the logs instead, so that it's clearly visible where and how the error happened.

File: packages/integration/src/gitlab/config.ts [hunk 12]
```diff
@@ -68,8 +67,6 @@ export function readGitLabIntegrationConfig(
 
   if (apiBaseUrl) {
     apiBaseUrl = apiBaseUrl.replace(/\/+$/, '');
-  } else if (host === GITLAB_HOST) {
-    apiBaseUrl = GITLAB_API_BASE_URL;
```
Comment (freben) [inline packages/integration/src/gitlab/config.ts:72]: I think this should not be removed (but you do need to add `https://` to the constant, that is a bug). The point here is that you will be able to add just a token for public gitlab if you wanted to, without having to figure out and fill in their public API base URL.

```
integrations:
  gitlab:
    host: gitlab.com
    token: blah
```

see the documented behavior here https://github.com/backstage/backstage/blob/master/packages/integration/src/gitlab/config.ts#L36

File: plugins/scaffolder-backend/src/scaffolder/stages/helpers.ts [hunk 13]
```diff
@@ -40,7 +38,7 @@ export const parseLocationAnnotation = (
   // split on the first colon for the protocol and the rest after the first split
   // is the location.
   const [protocol, location] = annotation.split(/:(.+)/) as [
-    RemoteProtocol?,
+    ('file' | 'url')?,
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/helpers.ts:41]: If you are strict about this type (not just making it `string`) for some reason, you should really have a check and throw an error if it turned out to not be one of those two values. Or just make it `string`

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/bitbucket.ts [hunk 14]
```diff
@@ -18,35 +18,33 @@ import fs from 'fs-extra';
...
+      config.username,
+      config.token,
+      config.appPassword,
+    );
   }
 
+  constructor(
+    private readonly username?: string,
+    private readonly token?: string,
+    private readonly appPassword?: string,
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/prepare/bitbucket.ts:38]: this is one place where it's generally proven neat to just do `constructor(private readonly auth: { username?: string; ... }) {}`

File: plugins/scaffolder-backend/src/scaffolder/stages/prepare/gitlab.test.ts [hunk 15]
```diff
@@ -24,15 +24,15 @@ import {
...
 
-const mockEntityWithProtocol = (protocol: string): TemplateEntityV1alpha1 => ({
+const mockTemplate = (): TemplateEntityV1alpha1 => ({
   apiVersion: 'backstage.io/v1alpha1',
   kind: 'Template',
   metadata: {
     annotations: {
-      [LOCATION_ANNOTATION]: `${protocol}:https://gitlab.com/benjdlambert/backstage-graphql-template/-/blob/master/template.yaml`,
+      [LOCATION_ANNOTATION]:
+        'gitlab:https://gitlab.com/benjdlambert/backstage-graphql-template/-/blob/master/template.yaml',
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/prepare/gitlab.test.ts:35]: are you explicitly testing the `gitlab` type? otherwise make this `url:`

File: plugins/scaffolder-backend/src/scaffolder/stages/publish/azure.ts [hunk 16]
```diff
@@ -15,27 +15,41 @@
...
 
 export class AzurePublisher implements PublisherBase {
-  private readonly client: GitApi;
-  private readonly token: string;
-
-  constructor(client: GitApi, token: string) {
-    this.client = client;
-    this.token = token;
+  static async fromConfig(config: AzureIntegrationConfig) {
+    if (!config.token) {
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/publish/azure.ts:27]: hm maybe filter on this on the caller side instead and log a warning that publishing won't work to that host because there was no token set - and then throw in here if there's no token

File: plugins/scaffolder-backend/src/scaffolder/stages/publish/azure.ts [hunk 17]
```diff
@@ -15,27 +15,41 @@
...
 
 import { PublisherBase, PublisherOptions, PublisherResult } from './types';
-import { GitApi } from 'azure-devops-node-api/GitApi';
+import { IGitApi } from 'azure-devops-node-api/GitApi';
 import { GitRepositoryCreateOptions } from 'azure-devops-node-api/interfaces/GitInterfaces';
-import { JsonValue } from '@backstage/config';
-import { RequiredTemplateValues } from '../templater';
 import { initRepoAndPush } from './helpers';
+import { AzureIntegrationConfig } from '@backstage/integration';
+import gitUrlParse from 'git-url-parse';
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/publish/azure.ts:22]: look, I just made a big PR to unify this to `parseGitUrl` ;)

File: plugins/scaffolder-backend/src/scaffolder/stages/publish/bitbucket.ts [hunk 18]
```diff
@@ -16,62 +16,83 @@
 
 import { PublisherBase, PublisherOptions, PublisherResult } from './types';
 import { initRepoAndPush } from './helpers';
-import { RequiredTemplateValues } from '../templater';
-import { JsonValue } from '../../../../../../packages/config/src';
 import fetch from 'cross-fetch';
+import { BitbucketIntegrationConfig } from '@backstage/integration';
+import gitUrlParse from 'git-url-parse';
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/publish/bitbucket.ts:21]: same

File: plugins/scaffolder-backend/src/scaffolder/stages/publish/bitbucket.ts [hunk 19]
```diff
@@ -16,62 +16,83 @@
...
+      config.appPassword,
+      config.username,
+    );
   }
 
+  constructor(
+    private readonly host: string,
+    private readonly token?: string,
+    private readonly appPassword?: string,
+    private readonly username?: string,
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/publish/bitbucket.ts:41]: maybe an object here too

File: plugins/scaffolder-backend/src/scaffolder/stages/publish/github.ts [hunk 20]
```diff
@@ -15,40 +15,49 @@
...
-  private client: Octokit;
-  private token: string;
-  private repoVisibility: RepoVisibilityOptions;
+  static async fromConfig(
+    config: GitHubIntegrationConfig,
+    { repoVisibility }: { repoVisibility: RepoVisibilityOptions },
+  ) {
+    if (!config.token) {
+      return undefined;
+    }
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/publish/github.ts:31]: same here, filter on the utside and throw here?

File: plugins/scaffolder-backend/src/scaffolder/stages/publish/github.ts [hunk 21]
```diff
@@ -15,40 +15,49 @@
...
-  }: GithubPublisherParams) {
-    this.client = client;
-    this.token = token;
-    this.repoVisibility = repoVisibility;
+    return new GithubPublisher(config.token, githubClient, repoVisibility);
   }
+  constructor(
+    private readonly token: string,
+    private readonly client: Octokit,
+    private readonly repoVisibility: RepoVisibilityOptions,
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/publish/github.ts:43]: object?

File: plugins/scaffolder-backend/src/scaffolder/stages/publish/gitlab.ts [hunk 22]
```diff
@@ -15,26 +15,39 @@
  */
 
 import { PublisherBase, PublisherOptions, PublisherResult } from './types';
-import { Gitlab } from '@gitbeaker/core';
-import { JsonValue } from '@backstage/config';
+import { Gitlab } from '@gitbeaker/node';
+import { Gitlab as GitlabClient } from '@gitbeaker/core';
 import { initRepoAndPush } from './helpers';
-import { RequiredTemplateValues } from '../templater';
+import gitUrlParse from 'git-url-parse';
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/publish/gitlab.ts:21]: same

File: plugins/scaffolder-backend/src/scaffolder/stages/publish/gitlab.ts [hunk 23]
```diff
@@ -15,26 +15,39 @@
...
+
+import { GitLabIntegrationConfig } from '@backstage/integration';
 
 export class GitlabPublisher implements PublisherBase {
-  private readonly client: Gitlab;
-  private readonly token: string;
+  static async fromConfig(config: GitLabIntegrationConfig) {
+    if (!config.token) {
+      return undefined;
+    }
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/publish/gitlab.ts:29]: same

File: plugins/scaffolder-backend/src/scaffolder/stages/publish/gitlab.ts [hunk 24]
```diff
@@ -15,26 +15,39 @@
...
-  constructor(client: Gitlab, token: string) {
-    this.client = client;
-    this.token = token;
+    const client = new Gitlab({ host: config.apiBaseUrl, token: config.token });
+    return new GitlabPublisher(config.token, client);
   }
 
+  constructor(
+    private readonly token: string,
+    private readonly client: GitlabClient,
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/publish/gitlab.ts:37]: same?

File: plugins/scaffolder-backend/src/scaffolder/stages/publish/publishers.ts [hunk 25]
```diff
@@ -14,184 +14,130 @@
...
 
 export class Publishers implements PublisherBuilder {
-  private publisherMap = new Map<RemoteProtocol, PublisherBase>();
-
-  constructor(private readonly typeDetector?: DeprecatedLocationTypeDetector) {}
+  private publisherMap = new Map<string, PublisherBase | undefined>();
 
-  register(protocol: RemoteProtocol, publisher: PublisherBase) {
-    this.publisherMap.set(protocol, publisher);
+  register(host: string, preparer: PublisherBase | undefined) {
```
Comment (freben) [inline plugins/scaffolder-backend/src/scaffolder/stages/publish/publishers.ts:29]: yeah avoiding the undefined here is desirable...

File: plugins/scaffolder-backend/src/service/router.test.ts [hunk 26]
```diff
@@ -65,7 +65,7 @@ describe('createRouter - working directory', () => {
     kind: 'Template',
     metadata: {
       annotations: {
-        'backstage.io/managed-by-location': 'azure/api:dev.azure.com',
+        'backstage.io/managed-by-location': 'azure:https://dev.azure.com',
```
Comment (freben) [inline plugins/scaffolder-backend/src/service/router.test.ts:68]: url:

File: plugins/scaffolder/src/components/TemplatePage/TemplatePage.tsx [hunk 27]
```diff
@@ -39,6 +39,7 @@ import { rootRoute } from '../../routes';
 import { JobStatusModal } from '../JobStatusModal';
 import { MultistepJsonForm } from '../MultistepJsonForm';
 import { useJobPolling } from '../hooks/useJobPolling';
+import gitParse from 'git-url-parse';
```
Comment (freben) [inline plugins/scaffolder/src/components/TemplatePage/TemplatePage.tsx:42]: same

File: packages/integration/src/gitlab/config.ts (hunk 12 above)
Comment (jhaals) [reply packages/integration/src/gitlab/config.ts:72]: It's the case that you can just insert the token. The constant is incorrect.

File: plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts (hunk 11 above)
Comment (jhaals) [reply plugins/scaffolder-backend/src/scaffolder/jobs/processor.ts:123]: We'll address this in a future PR, but for now people would have to run in debug mode to troubleshoot an issue.

File: plugins/scaffolder-backend/src/scaffolder/stages/publish/publishers.ts (hunk 25 above)
Comment (Rugvip) [reply plugins/scaffolder-backend/src/scaffolder/stages/publish/publishers.ts:29]: Yeah would be nicer to not register if it's undefined ^_>

**Review by Rugvip — APPROVED** [review]
:shipit: ? 😏

**Comment by freben** [comment]
Yeah totally

**Comment by n2ygk** [comment]
@jhaals This is after-the fact but suggest you update the documentation to match the code at https://github.com/backstage/backstage/blame/master/docs/features/software-templates/index.md#L43-L45

**Comment by benjdlambert** [comment]
@n2ygk indeed - incoming PR!
