### PR TITLE
fix(user-settings): use non-deprecated IdentityApi methods

### LINKED ISSUE #8520: Undefined identity throwing an error on UserSettingsProfileCard
## Expected Behavior

When navigating to `/settings`, where `<Route path="/settings" element={<UserSettingsPage />} />` is mounted, I expect the user's settings page to be rendered.

## Current Behavior

An error is thrown:

Screenshot from 2021-12-16 13-36-32

## Possible Solution

Use the non-deprecated `IdentityApi` methods `getBackendUserIdentity()` and `getProfileInfo()` instead of `getUserId()` and `getProfile()`.

## Steps to Reproduce

1. Clone backstage/backstage `gh repo clone backstage/backstage && cd backstage`
2. Install dependencies and start server `yarn install && yarn dev`
3. Navigate to `http://localhost:3000/settings`

## Context

I used `yarn backstage-cli versions:bump` on a Backstage app that was at version `0.4.4` of the create-app and noticed that the settings page was not working anymore.

## Your Environment

This is the output of `yarn backstage-cli info` after doing a fresh clone of the repo and reproducing the issue.

```shell
OS:   Linux 5.11.0-41-generic - linux/x64
node: v16.13.1
yarn: 1.22.1
cli:  0.10.2 (local)

Dependencies:
  @backstage/catalog-client       0.3.19
  @backstage/core-app-api         0.1.24
  @backstage/core-components      0.3.3, 0.4.2, 0.5.0, 0.6.1, 0.7.6
  @backstage/core-plugin-api      0.1.13, 0.2.2
  @backstage/plugin-catalog-react 0.4.6, 0.5.2

```

### PR DESCRIPTION
**Pull request by reinoudk**
This fixes the undefined identity error that is being thrown on the user-settings page.

Signed-off-by: Reinoud Kruithof <2184455+reinoudk@users.noreply.github.com>

## Hey, I just made a Pull Request!

I've updated the `useUserProfile` hook in `plugin-user-settings` so it uses the recommended API methods of `IdentityApi`.
These new methods are asynchronous, so I added the `useState` and `useEffect` hooks. I'm not a React developer at heart, so I'm not a 100% sure this is the way to go. It **does** fix #8520, but I don't know if I can write a regression test for it.

Sidenote: I'm not really sure the linter made the code in line 28 more readable...

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/user-settings/src/components/useUserProfileInfo.ts [hunk 1]
```diff
@@ -14,13 +14,36 @@
...
+
+    setDisplayName(name);
+    setProfile(profileInfo);
+  };
+
+  useEffect(() => {
+    if (!displayName) {
+      getUserProfile();
+    }
+  });
```
Comment (freben) [inline plugins/user-settings/src/components/useUserProfileInfo.ts:46]: Hm this all turns out a bit awkward.

May I suggest using useAsync instead?

```ts
const alertApi = useApi(alertApiRef);

const { value, loading, error } = useAsync(async () => {
 return {
   profile: await identityApi.getProfileInfo();
   identity: await identityApi.getBackstageIdentity();
 };
}, []);

useEffect(() => {
  if (error) {
    alertApi.post({ message: `Failed to load user identity: ${error}` });
  }
}, [error]);
```

Now the question is what to do with the `value`. We could choose to return some empty placeholder values as you do now,

```ts
if (loading) {
  return ...
}
```

And maybe that's a good first stab at it. However, I would like to _also_ return the `loading` flag.

```ts
return {
  profile: loading ? {} : value.profile,
  displayName: loading ? '' : value.profile?.displayName ?? value.identity.userEntityRef,
  loading,
};
```

that way, callers can choose to show a loading progress bar or similar while waiting for data to arrive.

You'll have to run `yarn build:api-reports` and commit the results after, then, because this amends the contract a bit.

**Review by freben — COMMENTED** [review]
Thanks! I wanted to propose a slightly different fix - let me know what you think.

File: plugins/user-settings/src/components/useUserProfileInfo.ts (hunk 1 above)
Comment (reinoudk) [reply plugins/user-settings/src/components/useUserProfileInfo.ts]: Thanks for the pointers! That looks a lot better: I've applied the changes almost verbatim. I've used non-null assertion operators on the `value`s, as I think think they are always non-null when loading is null, right?

File: plugins/user-settings/src/components/useUserProfileInfo.ts [hunk 2]
```diff
@@ -14,13 +14,39 @@
...
+    if (error) {
+      alertApi.post({
+        message: `Failed to load user identity: ${error}`,
+        severity: "error",
+      });
+    }
+  }, [error, alertApi]);
+
+  return {
+    profile: loading ? {} : value!.profile,
```
Comment (freben) [inline plugins/user-settings/src/components/useUserProfileInfo.ts:46]: Oh this was actually a nice catch of yours - the typescript is actually right here, we can't be sure at this point that it has a value - because we aren't exiting when `error` is true. We have to address that.

maybe something like

```ts
if (loading || error) {
  return {
    profile: {},
    displayName: '',
    loading,
  };
};

return {
  profile: value.profile, // at this point tsc will know that it actually isn't undefined!
  displayName: value.profile.displayName ?? value.identity.userEntityRef,
  loading: false,
};
```

that actually even turned out to be cleaner.

Comment (reinoudk) [reply plugins/user-settings/src/components/useUserProfileInfo.ts]: Ah of course. I added the check and reutrn on `loading || error` but tsc was still complaining about using `value` :disappointed:. But now it should actually be safe to use `!`.

**Review by freben — APPROVED** [review]
