### PR TITLE
fix: Omit collecting `backend-common` `config.d.ts` if `backend-defaults` is detected

### LINKED ISSUE #28170: 🐛 Bug Report: Database connection objects no longer pass schema validation
### 📜 Description

Looks like this was caused by https://github.com/backstage/backstage/pull/27901

```

Error: Configuration does not match schema
--
  |  
  | Config must have required property 'instance' { missingProperty=instance } at /backend/database/connection
  | Config must have required property 'type' { missingProperty=type } at /backend/database/connection
  | Config must NOT have additional properties { additionalProperty=host } at /backend/database/connection
  | Config must NOT have additional properties { additionalProperty=port } at /backend/database/connection
  | Config must NOT have additional properties { additionalProperty=user } at /backend/database/connection
  | Config must NOT have additional properties { additionalProperty=host } at /backend/database/connection
  | Config must NOT have additional properties { additionalProperty=port } at /backend/database/connection
  | Config must NOT have additional properties { additionalProperty=user } at /backend/database/connection
  | Config must be string { type=string } at /backend/database/connection
  | Config must match a schema in anyOf {  } at /backend/database/connection


```

My config looks like this:

```
  database:
    client: pg
    connection:
      host: ${DB_HOST}
      port: ${DB_PORT}
      user: ${DB_USERNAME}
      password: ${DB_PASSWORD}
```
It's trying to validate it against the new CloudSQL schema:

```
          {
            /**
             * The specific config for cloudsql connections
             */
            type: 'cloudsql';
            /**
             * The instance connection name for the cloudsql instance, e.g. `project:region:instance`
             */
            instance: string;
          }
```

instead of the more flexible type:
```
          {
            /**
             * Password that belongs to the client User
             * @visibility secret
             */
            password?: string;
            /**
             * Other connection settings
             */
            [key: string]: unknown;
          }
```

### 👍 Expected behavior

`yarn backstage-cli config:check --strict` should pass. This was not listed as a breaking change so I'm assuming I shouldn't need to change my config at all. I'm happy to do so if it was simply mislabeled though.

### 👎 Actual Behavior with Screenshots

`yarn backstage-cli config:check --strict` fails with above description

### 👟 Reproduction steps

I assume: create a new backstage app and setup postgres then run `yarn backstage-cli config:check --strict`

### 📃 Provide the context for the Bug.

This is new in 1.34.0

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by benjdlambert**
Fixes #28170

### CODE REVIEW

**Review by camilaibs — APPROVED** [review]

File: packages/config-loader/src/schema/collect.ts [hunk 1]
```diff
@@ -151,14 +154,26 @@ export async function collectConfigSchemas(
...
-  return schemas.concat(tsSchemas);
+  return schemas
+    .concat(tsSchemas)
+    .filter(
+      ({ packageName }, _, original) =>
+        !(
+          packageName === '@backstage/backend-common' &&
+          original.some(
+            ({ packageName: p }) => p === '@backstage/backend-defaults',
+          )
```
Comment (Rugvip) [inline packages/config-loader/src/schema/collect.ts:165]: Bit cleaner to extract this into an earlier `hasBackendDefaults` I think

File: packages/config-loader/src/schema/collect.ts [hunk 2]
```diff
@@ -45,7 +45,7 @@ export async function collectConfigSchemas(
   packagePaths: string[],
 ): Promise<ConfigSchemaPackageEntry[]> {
   const schemas = new Array<ConfigSchemaPackageEntry>();
```
Comment (Rugvip) [inline packages/config-loader/src/schema/collect.ts:47]: Thinking `& { packageName: string }` here instead to avoid the public API change

File: packages/config-loader/src/schema/collect.ts [hunk 3]
```diff
@@ -150,15 +153,26 @@ export async function collectConfigSchemas(
...
+  const isMissingBackendDefaults = !allSchemas.some(
+    ({ packageName }) => packageName === '@backstage/backend-defaults',
+  );
 
-  return schemas.concat(tsSchemas);
+  // Filter out the backend-common schema unless the backend-defaults schema is missing
+  return allSchemas.filter(
+    ({ packageName }) =>
+      packageName !== '@backstage/backend-common' || isMissingBackendDefaults,
+  );
```
Comment (Rugvip) [inline packages/config-loader/src/schema/collect.ts:166]:
```
if (hasBackendDefaults) {
  return allSchemas.filter(...)
}
return allSchemas
```

thinking that's the most clear way

**Review by Rugvip — APPROVED** [review]
