### PR TITLE
[TechDocs] Set entity filters as they change in TechDocsSearchBar

### LINKED ISSUE #9769: Techdocs search is broken when navigating from other techdocs
## Expected Behavior
We should see search results of current techdocs we are in 

## Actual Behavior
You should be observe search results still referring to documented-component page instead of techdocs-e2e-fixture

## Steps to Reproduce

1. Add link `[Link for e2e-fixture ](http://localhost:3000/docs/default/component/techdocs-e2e-fixture)` in plugins\techdocs-backend\examples\documented-component\docs\index.md file.
2. Now, go ahead and open tech docs of documented-component and search something in the page
3. Click the link add on step-1 and search for the content techdocs-e2e-fixture. You should be observe search results still referring to documented-component page.

P.S: Running techdocs locally

## Context
Search is showing wrong results
image

## Your Environment
Locally

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

### PR DESCRIPTION
**Pull request by iamEAP**
## Hey, I just made a Pull Request!

Closes #9769

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/techdocs/src/reader/components/TechDocsSearch.tsx [hunk 1]
```diff
@@ -87,6 +88,17 @@ const TechDocsSearchBar = ({
...
+  // Update the filter context when the entityId changes, e.g. when the search
+  // bar continues to be rendered, navigating between different TechDocs sites.
+  useEffect(() => {
+    setFilters(prevFilters => {
+      return {
+        ...prevFilters,
+        ...entityId,
+      };
+    });
+  }, [entityId, setFilters]);
```
Comment (freben) [inline plugins/techdocs/src/reader/components/TechDocsSearch.tsx:100]: Is it safe to compare the entity id by reference? As opposed to e.g. its stringifyEntityRef version

**Review by freben — APPROVED** [review]

File: plugins/techdocs/src/reader/components/TechDocsSearch.tsx (hunk 1 above)
Comment (iamEAP) [reply plugins/techdocs/src/reader/components/TechDocsSearch.tsx:100]: Yeah, I wonder if it actually makes the effect more readable to destruct the bits we use from it and merge those into the filter manually anyway.

**Review by soapraj — APPROVED** [review]

File: plugins/techdocs/src/reader/components/TechDocsSearch.tsx (hunk 1 above)
Comment (freben) [reply plugins/techdocs/src/reader/components/TechDocsSearch.tsx]: I like it!
