### PR TITLE
[tech-insights] Fix maxItems lifecycle condition

### LINKED ISSUE #11595: [TECH INSIGHTS] Time To Live Configuration not working as intended.
## Expected Behavior

Should clear the facts data in the database based on the configuration set using `lifecycle`

## Actual Behavior

Not clearing the facts

## Steps to Reproduce

I am trying to set lifecycle maxItems  to be kept in the database for each fact retriever/entity pair like below
createFactRetrieverRegistration({
        cadence: * * * * *,
        factRetriever: entityOwnershipFactRetriever,
        lifecycle: { maxItems: 1 },
      })

But this is not clearing the data as intended.

### PR DESCRIPTION
**Pull request by Xantier**
Modify facts database table to have a more restricted timestamp precision for cases where the postgres server isn't configured to contain such value. This fixes the issue where in some cases `maxItems` lifecycle condition didn't work as expected.

Introduce additional JsonValue types to be storable as facts. This enables the possibility to store more complex objects for fact checking purposes. The rules engine supports walking keyed object values directly to create rules and checks

resolves #11595

Signed-off-by: Jussi Hallila <jussi@hallila.com>

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [n/a] Added or updated documentation
- [n/a] Tests for new functionality and regression tests for bug fixes
- [n/a] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/tech-insights-backend/migrations/2022060100821_facts_timestamp_precision.js [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+ * @param {import('knex').Knex} knex
+ */
+exports.up = async function up(knex) {
+  await knex.schema.alterTable('facts', table => {
+    table
+      .dateTime('timestamp', { precision: 0 })
+      .defaultTo(knex.fn.now())
+      .notNullable()
+      .comment('The timestamp when this entry was created')
+      .alter();
```
Comment (freben) [inline plugins/tech-insights-backend/migrations/2022060100821_facts_timestamp_precision.js:29]: Hmm. I think this is one of those times when knex wants a `.alter({ alterType: true })` here 🤔

Comment (Xantier) [reply plugins/tech-insights-backend/migrations/2022060100821_facts_timestamp_precision.js:29]: AFAIK that should be the default value for this method call: https://github.com/knex/knex/blob/a4df3e35403756615f297ef75ac1d998035d65e6/lib/schema/columnbuilder.js#L127

Confirmed that the modification gets applied correcly on my pg 12.5
