### PR TITLE
Fix 18778 : template editor fails with multiple templates per file

### LINKED ISSUE #18778: 🐛 Bug Report: template editor fails with multiple templates per file
### 📜 Description

The scaffolder template editor shows an error when you load a file with multiple templates in a single file.

### 👍 Expected behavior

It should work somehow, maybe it could show tabs, one for each template.

### 👎 Actual Behavior with Screenshots

It shows the following error

```
Source contains multiple documents; please use YAML.parseAllDocuments() at line 210, column 1: # message: 'Hello, ${{ parameters.person }}!' --- ^
```

### 👟 Reproduction steps

Create a file locally with two templates in a single catalog file.
Go to the template editor and load the directory that contains the file.
Click to load in the templates.

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

### PR DESCRIPTION
**Pull request by npiyush97**
## Hey, I just made a Pull Request!
fix #18778 

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by npiyush97** [comment]
@freben i don't know about next/ 
also, require this change ?

https://github.com/backstage/backstage/blob/53b7c7668d0f783e50359e091d63ddc429aee05b/plugins/scaffolder/src/next/TemplateEditorPage/TemplateEditorForm.tsx#L116

File: plugins/tech-radar/src/components/RadarTimeline/RadarTimeline.tsx [hunk 1]
```diff
@@ -76,10 +76,10 @@ const RadarTimeline = (props: Props): JSX.Element => {
                     ''
                   )}
                 </TableCell>
-                <TableCell align="left">
+                <TableCell align="left" style={{ whiteSpace: 'nowrap' }}>
```
Comment (freben) [inline plugins/tech-radar/src/components/RadarTimeline/RadarTimeline.tsx:79]: should undo these unrelated changes

File: plugins/scaffolder/src/components/TemplateEditorPage/TemplateEditorForm.tsx [hunk 2]
```diff
@@ -123,7 +123,9 @@ export function TemplateEditorForm(props: TemplateEditorFormProps) {
           setSteps(undefined);
           return;
         }
-        const parsed: JsonValue = yaml.parse(content);
+        const parsed: JsonValue = yaml
+          .parseAllDocuments(content)
```
Comment (freben) [inline plugins/scaffolder/src/components/TemplateEditorPage/TemplateEditorForm.tsx:127]: you also should add a `.filter(c => c)` to get rid of spurious null documents. Like we do for example [here](https://github.com/backstage/backstage/blob/abdece5ae0ed71516a905caff935153d180e6acb/plugins/catalog-backend/src/modules/core/PlaceholderProcessor.ts#L177).

Comment (npiyush97) [reply plugins/scaffolder/src/components/TemplateEditorPage/TemplateEditorForm.tsx:127]: okay but same is required in src/next/ ?

Comment (freben) [reply plugins/scaffolder/src/components/TemplateEditorPage/TemplateEditorForm.tsx:127]: Anything that calls `parseAllDocuments` should have that check.

You also moved the `.filter` AFTER `.toJSON`; at that point it's already too late; you want to filter directly after `parseAllDocuments` because that's the one that may have nulls in its response array entries

Comment (npiyush97) [reply plugins/scaffolder/src/components/TemplateEditorPage/TemplateEditorForm.tsx:127]: brilliant

**Review by freben — APPROVED** [review]
