### PR TITLE
Show a Not Found message when navigating to a nonexistent entity

### LINKED ISSUE #4766: Clicking owner link on an entity with an invalid group results in an empty group page
## Expected Behavior

One of three,
* The group page should display when an an invalid group has been provided or does not exist in the catalog.
* I should not be able to register an entity with an invalid group?
* An entity with an invalid group as owner should not be clickable, possibly with a tool tip indicating it's not a valid user and maybe a little red X next to it (or a visual indicator of it being invalid in the instance).

## Current Behavior

If I register an entity with a `spec.owner` of `group:fake-group`, this becomes a link on the entity's main page in both the About card as well as the header. Clicking either of those links, takes me to the group page which is entirely blank: http://localhost:3000/catalog/default/group/fake-group

image

Clicking either link results in:

image

And an HTTP 404 Not Found in my backend:

```
2021-03-03T02:40:29.837Z backstage info ::1 - - [03/Mar/2021:02:40:29 +0000] "GET /api/catalog/entities/by-name/group/default/fake-group HTTP/1.1" 404 239 "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88 blah blah blah" type=incomingRequest
```

## Possible Solution

The easiest is likely to trap empty/invalid groups and display as such in the org plugin, which likely covers this case but also any URL hacking someone might do or just bad copy/pastes say if someone IM'd a group link to someone else. So the empty group should likely print something more friendly.

However, there may be a higher-level method to address such as any time we ingest an entity, maybe it should validate the `spec.owner` before allowing it to be written? Or should we have an owner wrapper component which creates a link to the entity only if it's invalid, and if it's not then putting like a red X next to it with a tool tip saying it's not a valid user. This would help elevate this info into the UI. But open to other opinions on it?

## Steps to Reproduce

1. Register an entity and specify a group that does not exist in your instance, for example,
    ```yaml
    spec:
      owner: group:fake-group
    ```
2. Register the entity in your instance
3. View it's main page
4. Click the owner link in the About card
5. See empty group page

## Context

I have a feeling there's some sort of challenge with passing in the entity as context to the group overview card here:

https://github.com/backstage/backstage/blob/1b8b40cfeeb5c7dfd60cdb36807ba1fa09c092a4/packages/app/src/components/catalog/EntityPage.tsx#L429-L437

There is not actually an entity, so there's no object to pass in.  And not to make this too broad, but this seems to happen for all of the entities, likely again because of needing to pass the context in?  So the solution to this may be some sort of higher wrapper that errors if the entity is not valid.  I see the same if I put in a fake component name as well:

image

## Your Environment

- NodeJS Version (v12): v12
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 WSL2 Ubuntu 18.04
- Browser Information: Microsoft Edge (Chrome engine)

### PR DESCRIPTION
**Pull request by freben**
Fixes #4766

### CODE REVIEW

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4837-nqb5xn08bybd80pkvnnxtjstm2krrlls.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60423ce7fcb22d5b686979ba

File: plugins/catalog/src/components/EntityPageLayout/EntityPageLayout.tsx [hunk 1]
```diff
@@ -134,6 +146,19 @@ export const EntityPageLayout = ({ children }: PropsWithChildren<{}>) => {
           <Alert severity="error">{error.toString()}</Alert>
         </Content>
       )}
+
+      {!loading && !error && !entity && (
+        <Content>
+          <WarningPanel title="Entity not found">
+            There was no entity with a matching{' '}
```
Comment (adamdmharvey) [inline plugins/catalog/src/components/EntityPageLayout/EntityPageLayout.tsx:153]:
```suggestion
            There is no entity with a matching{' '}
```

total nitpick: but maybe IS makes more sense since right now as they click the link it can't be found? (not in the past)

**Review by adamdmharvey — APPROVED** [review]
Love it as an incremental update!

I'd throw in, from an end-user's perspective, I think the word "entity" isn't as obvious. We (project team, integrators) throw it around a lot, but even with the early project discussions about software vs. service vs. component vs. entity, etc, it took us time to get there.

I'm Jane Doe, I clicked the owner link at the top of my documentation site, and the error is "There is no entity with a matching"?  what does that mean? i don't want an entity, I want a user's info.

So not sure if this is possible, but would be great if the hook knew you say tried to get a kind:API and this error message (dug out of the URL I suppose) and could more specifically say something like,

> There is no group with that matching....

or something to avoid the word entity.  e.g., on my use case here of missing group specifically.

But as an improvement over what we have this is an amazingly fast fix so thanks Fredrik!! 👏🏻

**Comment by freben** [comment]
@adamdmharvey The kind was there just waiting to be rendered, so let's use it! Tried a slight rewording too, let me know what you think.

**Comment by backstage-service** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr4837-nqb5xn08bybd80pkvnnxtjstm2krrlls.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/60423ce7fcb22d5b686979ba

**Review by adamdmharvey — APPROVED** [review]
Like it 😁

**Review by jhaals — APPROVED** [review]

**Review by benjdlambert — APPROVED** [review]
