### PR TITLE
backend-defaults: log low severity audit events as debug

### LINKED ISSUE #28905: 🐛 Bug Report: 1.36.0 Auditor logging `[object Object]` and is way too verbose
### 📜 Description

The new auditor service in 1.36.0 has issue with logging like follows:

```
[0] 2025-02-19T07:03:34.790Z catalog info catalog.entity-facets isAuditEvent=true eventId=entity-facets severityLevel=low actor=[object Object] request=[object Object] meta=undefined status=initiated
```
Additionally the auditor service is way too verbose; for example fetching entity facets log each request. 

### 👍 Expected behavior

The audit log should contain proper information about the event. Having `[object Object]` brings no value.

IMHO the audit log should only contain actions done by the user tor example registering/deleting entity, starting scaffolder task and so on - not every data fetch.

### 👎 Actual Behavior with Screenshots

See above.

### 👟 Reproduction steps

1. Update to backstage 1.36.0
2. Go to catalog page
3. Check auditor logs

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by Rugvip**
## Hey, I just made a Pull Request!

Fixes #28905

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by freben — APPROVED** [review]

File: packages/backend-defaults/src/entrypoints/auditor/auditorServiceFactory.ts [hunk 1]
```diff
@@ -40,7 +40,14 @@ export const auditorServiceFactory = createServiceFactory({
   factory({ logger, plugin, auth, httpAuth }) {
     const auditLogger = logger.child({ isAuditEvent: true });
     return DefaultAuditorService.create(
-      event => auditLogger.info(`${event.plugin}.${event.eventId}`, event),
+      event => {
+        const message = `${event.plugin}.${event.eventId}`;
+        if (event.severityLevel === 'low') {
+          auditLogger.debug(message, event);
```
Comment (benjdlambert) [inline packages/backend-defaults/src/entrypoints/auditor/auditorServiceFactory.ts:46]: should it be `verbose` instead? `debug` feels a little too low?
