### PR TITLE
Pass configs from build:backend to app builds. Fixes #15274

### LINKED ISSUE #15274: 🐛 Bug Report: `yarn backend:build` doesn't forward config options on to app build
### 📜 Description

When running `yarn backend:build --config foo.yaml` when teh app is being bundled into the backend, the backend ignores the `--config` option provided and continues to use the default config file

### 👍 Expected behavior

The `--config` arguments should be passed on to the app build. 

### 👎 Actual Behavior with Screenshots

The app build continues to just use `app-config.yaml`

```
yarn build:backend --config foo.yaml
yarn run v1.22.19
$ yarn workspace backend build --config foo.yaml
$ backstage-cli package build --config foo.yaml
Building app separately because it is a bundled package

app:  
app:  $ backstage-cli package build
app:  
app:  Loaded config from app-config.yaml
app:  
```

### 👟 Reproduction steps

1. Run `yarn backend:build --config foo.yaml`

### 📃 Provide the context for the Bug.

I am upgrading from 1.7.0 to 1.8.3 and in the process migrating from `yarn build` to `yarn build:backend`.

I'm able to work around this by updating the build script in `packages/app/package.json` (As suggested at https://discord.com/channels/687207715902193673/1026835211285184593 )
```json
    "build": "backstage-cli package build --config ../../app-config.yaml --config ../../app-config.production.yaml",
```

### 🖥️ Your Environment

OS:   Linux 5.15.79.1-microsoft-standard-WSL2 - linux/x64
node: v16.14.0
yarn: 1.22.19
cli:  0.21.1 (installed)
backstage:  1.8.3

Dependencies:
  @backstage/app-defaults                          1.0.8
  @backstage/backend-common                        0.16.0
  @backstage/backend-plugin-api                    0.1.4
  @backstage/backend-tasks                         0.3.7
  @backstage/catalog-client                        1.1.2
  @backstage/catalog-model                         1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.21.1
  @backstage/config-loader                         1.1.6
  @backstage/config                                1.0.4
  @backstage/core-app-api                          1.2.0
  @backstage/core-components                       0.12.0
  @backstage/core-plugin-api                       1.1.0
  @backstage/dev-utils                             1.0.8
  @backstage/errors                                1.1.3
  @backstage/integration-react                     1.1.6
  @backstage/integration                           1.4.0
  @backstage/plugin-api-docs                       0.8.11
  @backstage/plugin-app-backend                    0.3.38
  @backstage/plugin-auth-backend                   0.17.1
  @backstage/plugin-auth-node                      0.2.7
  @backstage/plugin-azure-devops-backend           0.3.17
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.2.2
  @backstage/plugin-catalog-backend-module-azure   0.1.9
  @backstage/plugin-catalog-backend-module-github  0.2.1
  @backstage/plugin-catalog-backend-module-msgraph 0.4.4
  @backstage/plugin-catalog-backend                1.5.1
  @backstage/plugin-catalog-common                 1.0.8
  @backstage/plugin-catalog-graph                  0.2.23
  @backstage/plugin-catalog-import                 0.9.1
  @backstage/plugin-catalog-node                   1.2.1
  @backstage/plugin-catalog-react                  1.2.1
  @backstage/plugin-catalog                        1.6.1
  @backstage/plugin-explore-react                  0.0.23
  @backstage/plugin-explore                        0.3.42
  @backstage/plugin-github-actions                 0.5.11
  @backstage/plugin-github-pull-requests-board     0.1.5
  @backstage/plugin-home                           0.4.27
  @backstage/plugin-org                            0.6.1
  @backstage/plugin-permission-common              0.7.1
  @backstage/plugin-permission-node                0.7.1
  @backstage/plugin-permission-react               0.4.7
  @backstage/plugin-proxy-backend                  0.2.32
  @backstage/plugin-scaffolder-backend             1.8.0
  @backstage/plugin-scaffolder-common              1.2.2
  @backstage/plugin-scaffolder                     1.8.0
  @backstage/plugin-search-backend-module-pg       0.4.2
  @backstage/plugin-search-backend-node            1.0.4
  @backstage/plugin-search-backend                 1.1.1
  @backstage/plugin-search-common                  1.1.1
  @backstage/plugin-search-react                   1.2.1
  @backstage/plugin-search                         1.0.4
  @backstage/plugin-stack-overflow                 0.1.7
  @backstage/plugin-tech-radar                     0.5.18
  @backstage/plugin-techdocs-backend               1.4.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.6
  @backstage/plugin-techdocs-node                  1.4.2
  @backstage/plugin-techdocs-react                 1.0.6
  @backstage/plugin-techdocs                       1.4.0
  @backstage/plugin-user-settings                  0.5.1
  @backstage/release-manifests                     0.0.7
  @backstage/test-utils                            1.2.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.1
  @backstage/version-bridge                        1.0.2
Done in 0.60s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by Pike**
When using `build:backend` with `--config` options, they're not passed down to the packaging of the FE app.
Thus, that's picking up the default configs, which includes the `app-config.local.yaml`, but it's also missing the production yaml, if requested.

Pass the given `configPaths` around for the backend build like the frontend build already does.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: packages/cli/src/lib/packager/createDistWorkspace.ts [hunk 1]
```diff
@@ -166,7 +176,10 @@ export async function createDistWorkspace(
         console.warn(
           `Building ${pkg.packageJson.name} separately because it is a bundled package`,
         );
-        customBuild.push({ dir: pkg.dir, name: pkg.packageJson.name });
+        const args = buildScript.includes('--config')
```
Comment (Rugvip) [inline packages/cli/src/lib/packager/createDistWorkspace.ts:179]: This wouldn't work with just a simple `backstage-cli package build` right? I think in general we'll need a check with a bit more confidence. I'm thinking we could at least check if the build script starts with `backstage-cli package build`, and that `backstage.role` is `frontend`?

**Review by Rugvip — CHANGES_REQUESTED** [review]
Thank you! 👍

File: packages/cli/src/lib/packager/createDistWorkspace.ts (hunk 1 above)
Comment (Pike) [reply packages/cli/src/lib/packager/createDistWorkspace.ts:179]: The beef is a bit outside of the default context here. In line 167, handle all build scripts that are not `backstage-cli package build`, so here we know that we're `package build` and a `bundle` role. I'd not further restrict to `frontend`, we'd want to the top-level options for some backend role thing, too. Not sure how we'd get there, though :-) 

Then this check finds if `package.json` already specifies configs, and if not, passes the one from the cli.

I tested locally with different app names to see what makes it into `index.html`'s title tag.

Comment (Rugvip) [reply packages/cli/src/lib/packager/createDistWorkspace.ts:179]: Ah derp, I totally read this the wrong way around 😅. Yep makes sense! 👍  Realized it also makes sense to forward the config flags even if it's a bundled backend package that we're building, as that may in turn have frontends that need config.

File: packages/cli/src/lib/config.ts [hunk 2]
```diff
@@ -38,7 +38,7 @@ export async function loadCliConfig(options: Options) {
   const configTargets: ConfigTarget[] = [];
   options.args.forEach(arg => {
     if (!isValidUrl(arg)) {
-      configTargets.push({ path: paths.resolveTarget(arg) });
+      configTargets.push({ path: paths.resolveTargetRoot(arg) });
```
Comment (Rugvip) [inline packages/cli/src/lib/config.ts:41]: Sup with this change?

File: .changeset/clever-lizards-whisper.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/cli': patch
+---
+
+Support building the frontend with the same set of configs as the backend.
```
Comment (Rugvip) [inline .changeset/clever-lizards-whisper.md:5]:
```suggestion
When building a backend package with dependencies any `--config <path>` options will now be forwarded to any dependent app package builds, unless the build script in the app package already contains a `--config` option.
```

Figured we can explain a bit more 😁

**Review by Rugvip — COMMENTED** [review]
Nice, think it's pretty much good to go! 👍

File: packages/cli/src/lib/config.ts (hunk 2 above)
Comment (Pike) [reply packages/cli/src/lib/config.ts:41]: `paths.resolveTarget` resolves against cwd, `paths.resolveTargetRoot` against the root of the mono-repo, just so that you don't need to reverse-engineer the code itself. And `cwd` is the package directory. If you'd run from the top-level, you'd have to pass relative paths with `../../` like we do for catalog entries in `app-config.yaml` ;-)

Comment (Rugvip) [reply packages/cli/src/lib/config.ts:41]: Yep, I know how it works ;) To be clear I'm not really opposed to this change as such, it makes sense, it's just that it's very much a breaking change. There are a lot of `--config ../../app-config.production.yaml` etc. out there. We'd need to ship this in a more backwards compatible way I'd say.

For now I think it's best if we simply resolve the config paths upfront and pass resolved paths to the upstream builds, either as absolute paths, or relative. If you want to spend some time finding a nice way to ship this change than that's alright too, but that is likely fairly tricky.

Comment (Pike) [reply packages/cli/src/lib/config.ts:41]: I was wondering about this, too. What do you think about doing

```typescript
    if (!isValidUrl(arg)) {
      let path = paths.resolveTarget(arg);
      if (!pathExistsSync(path)) {
        path = paths.resolveOwnRoot(arg);
      }
      configTargets.push({ path });
    }
```

That way, paths local to app and to the root would work?

Comment (Pike) [reply packages/cli/src/lib/config.ts]: Figured I can also just push it if I have it written already. It's easy to undo if that's not the right way.

Comment (Rugvip) [reply packages/cli/src/lib/config.ts]: Hmm, tbh I think it would be best to just forward the resolved config path for now, and not include this change. The change actually has fairly high impact and I wouldn't want to ship it strait into mainline on Tuesday. We'd also need to look over all other places that config is loaded to make sure it all behaves the same way.

Ok with skipping this for now and leaving it for a potential future change?

Comment (Pike) [reply packages/cli/src/lib/config.ts]: Yeah, that's OK, but I won't get to it this week.

Comment (Pike) [reply packages/cli/src/lib/config.ts]: Like so?

File: packages/cli/src/commands/build/command.ts [hunk 4]
```diff
@@ -20,22 +20,32 @@ import { findRoleFromCommand, getRoleInfo } from '../../lib/role';
...
-  if (role === 'backend') {
-    return buildBackend({
-      targetDir: paths.targetDir,
-      skipBuildDependencies: Boolean(opts.skipBuildDependencies),
+  if (role === 'frontend' || role === 'backend') {
+    const configPaths = (opts.config as string[]).map(arg => {
+      if (isValidUrl(arg)) {
+        return arg;
+      }
+      return paths.resolveTarget(arg);
```
Comment (Rugvip) [inline packages/cli/src/commands/build/command.ts:33]: This is what I had in mind

**Review by Rugvip — APPROVED** [review]
Throw in the final tweak, since we're eager to get this into today's release

Thank you! 👍
