### PR TITLE
TechDocs: Tell users when index.md is missing (better error message)

### LINKED ISSUE #3303: TechDocs: tell users when source of docs is missing index.md/html
This is a follow up to #3290 to help users better understand why their docs are not loading when an `index.md` file is missing from the source code.

## Feature Suggestion

There are many static generators that automatically generate index.html files. This could lead creators of docs to assume that they do not need to create index files. `mkdocs` uses `index.md` file to generate `index.html` which TechDocs UI loads by default when navigating to the root of the docs. The absence of this file produces a 404 which can lead down a rabbit hole of debugging. Instead, it would be helpful to explain that to the user why they TechDocs fails to load that page.

## Possible Implementation

Provide an error message that reads something like this: `We could not load index.html because it doesn't exist. Consider adding an index.md file to the docs directory so this file will be generated`.

## Context

Spent a lot of time debugging TechDocs in the process of preparing a POC of Backstage. It took about a day to figure out why TechDocs was giving me this error.

### PR DESCRIPTION
**Pull request by OrkoHunter**
Closes #3303

cc @taras 

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Review by taras — APPROVED** [review]
👍 

image

File: plugins/techdocs-backend/src/techdocs/stages/publish/local.ts [hunk 1]
```diff
@@ -53,17 +53,15 @@ export class LocalPublish implements PublisherBase {
     );
 
     if (!fs.existsSync(publishDir)) {
-      this.logger.info(
-        `[TechDocs]: Could not find ${publishDir}, creates the directory.`,
-      );
+      this.logger.info(`Could not find ${publishDir}, creates the directory.`);
```
Comment (freben) [inline plugins/techdocs-backend/src/techdocs/stages/publish/local.ts:56]:
```suggestion
      this.logger.info(`Could not find ${publishDir}, creating the directory.`);
```

File: plugins/techdocs/src/api.ts [hunk 2]
```diff
@@ -95,7 +95,13 @@ export class TechDocsStorageApi implements TechDocsStorage {
     );
 
     if (request.status === 404) {
-      throw new Error('Page not found');
+      let errorMessage = 'Page not found. ';
+      // path is empty for the home page of an entity's docs site
+      if (!path) {
+        errorMessage +=
+          'This could because there is no index.md file in the root of docs directory of this repository.';
```
Comment (freben) [inline plugins/techdocs/src/api.ts:102]:
```suggestion
          'This could be because there is no index.md file in the root of the docs directory of this repository.';
```

**Review by iamEAP — APPROVED** [review]

**Review by hooloovooo — APPROVED** [review]
