### PR TITLE
fix(backend): URL Reader readTree gets rid of archive directory name dependency

### LINKED ISSUE #4230: bug: URL Reader's readTree is not working with github.com targets (affects TechDocs)
In #4169, URL Reader's readTree started using the archive API's response header to get the name of the file being downloaded.

https://github.com/backstage/backstage/blob/c3ea694e8400a35e2dfe4cf577c0fa66c66a8570/packages/backend-common/src/reading/GithubUrlReader.ts#L169-L193

This approach works fine for GHE, GitLab, etc. but for github.com the name of the tarball can be different from the name of the directory the tarball is extracted to.

Example:
The URL (Clicking on it will download a ~50MB file)
https://api.github.com/repos/backstage/backstage/tarball/c3ea694e8400a35e2dfe4cf577c0fa66c66a8570 downloads a file named `backstage-backstage-release-2021-01-21.1-21-gc3ea694.tar.gz` but when extracted, the root directory is named `backstage-backstage-c3ea694/`.

The `fromZip` and `fromTar` methods rely on the directory name to extract the files from the archive.

# Possible Solution

1. Use the tar library to get the name of the directory.

2. (Cleaner) Do not rely on the name of the directory.

### PR DESCRIPTION
**Pull request by OrkoHunter**
Closes #4230

This PR updates the URL Reader's `readTree` behavior to NOT expect the name of the top level directory contained inside the Tarball/Zip. `readTree` should work without it. The motivation of this change is to get rid of GitHub/GitLab/etc.-specific URL readers having to guess the name of the directory, thus leading to bugs in different scenarios.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

File: packages/backend-common/src/reading/tree/TarArchiveResponse.ts [hunk 1]
```diff
@@ -30,6 +30,10 @@ import {
 const TarParseStream = (Parse as unknown) as { new (): ParseStream };
 
 const pipeline = promisify(pipelineCb);
+// Matches a directory name + one `/` at the start of any string,
+// containing any character except `/` one or more times, and ending with a `/`
+// e.g. Will match `dirA/` in `dirA/dirB/file.ext`
+const directoryNameRegex = /^[^\/]+\//;
```
Comment (freben) [inline packages/backend-common/src/reading/tree/TarArchiveResponse.ts:36]: Is this backslash on a win system?

Comment (freben) [reply packages/backend-common/src/reading/tree/TarArchiveResponse.ts:36]: Hm ok i see the rest of the code uses forward slashes as well

Comment (OrkoHunter) [reply packages/backend-common/src/reading/tree/TarArchiveResponse.ts:36]: Yeah that's why I spared no precaution myself in this PR. Since the Tarball is downloaded from GitHub, kept in memory for all of this, I am assuming `/` separator won't change due to the machine being Windows. But I could totally be wrong.

**Comment by OrkoHunter** [comment]
@Rugvip Would love your 👀 on this! 🙏

File: packages/backend-common/src/reading/tree/ReadTreeResponseFactory.ts [hunk 2]
```diff
@@ -24,8 +24,9 @@ import { ZipArchiveResponse } from './ZipArchiveResponse';
 type FromArchiveOptions = {
   // A binary stream of a tar archive.
   stream: Readable;
-  // If set, the root of the tree will be set to the given directory path.
-  path?: string;
+  // If unset, the files at the root of the tree will be read.
+  // subpath must not contain the name of the top level directory.
```
[the remark this answers is not in the document]
Comment (OrkoHunter) [reply packages/backend-common/src/reading/tree/ReadTreeResponseFactory.ts:28]: > So this is single-dir-at-root is true for all of the readTree sources?

Yeah I think so. We are downloading a zip/tarball of the repository regardless of the path requested by the user. So,
`reader.readTree("https://github.com/backstage/backstage")`
and
`reader.readTree("https://github.com/backstage/backstage/tree/master/docs")`

will download the same `something-master.tar.gz` which will have the single dir at the root. It's kept in memory and not extract to filesystem.

When `response.dir()` or `response.files()` is called, it will output files and their paths relative to the subpath provided - `/` or `/docs`.

So, 

```
const response = await reader.readTree("https://github.com/backstage/backstage/tree/master/docs/conf")
const dir = await response.dir()

// ls dir ->
// defining.md
// index.md
// reading.md
// writing.md
```

```
const response = await reader.readTree("https://github.com/backstage/backstage")
const dir = await response.dir()

// ls dir ->
// .changeset
// .github
// ...
```

**Comment by OrkoHunter** [comment]
@backstage/maintainers Another gentle ping that we should have this before tomorrow's release. 🙏

File: packages/backend-common/src/reading/AzureUrlReader.test.ts [hunk 3]
```diff
@@ -139,6 +140,16 @@ describe('AzureUrlReader', () => {
   });
 
   describe('readTree', () => {
+    beforeEach(() => {
+      mockFs({
+        '/tmp': mockFs.directory(),
```
Comment (OrkoHunter) [inline packages/backend-common/src/reading/AzureUrlReader.test.ts:145]: Oooh, I think this will fail on Windows master build. 😅

**Review by freben — APPROVED** [review]
LGTM! Hold off on merging until we've finished running a couple of practical tests though

**Comment by OrkoHunter** [comment]
Thanks! Yeah, will wait.

**Review by Rugvip — APPROVED** [review]
Verified with the tests in #4282 👌
