### PR TITLE
Fix #16288: add styling to handle overflow text on ownership and members card

### LINKED ISSUE #16288: 🐛 Bug Report: `EntityOwnershipCard` shows overlapped text for long Component type
### 📜 Description

It seems `EntityOwnershipCard` doesn't take care of long strings like `documentation` for Component's `spec.type`.

### 👍 Expected behavior

Either of the following:

- Long strings are properly shown
- Part of a long string is folded
- Part of a long string is trimmed

### 👎 Actual Behavior with Screenshots

Screen Shot 2023-02-10 at 12 09 32

### 👟 Reproduction steps

Register a Component like the below:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docs
spec:
  type: documentation
  owner: foo
  lifecycle: experimental
```

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

<details>
<summary><code>yarn backstage-cli info</code></summary>

```console
OS:   Darwin 21.3.0 - darwin/arm64
node: v18.12.1
yarn: 1.22.19
cli:  0.22.1 (installed)
backstage:  1.10.1

Dependencies:
  @backstage/app-defaults                          1.1.0
  @backstage/backend-app-api                       0.3.1
  @backstage/backend-common                        0.18.1
  @backstage/backend-plugin-api                    0.3.1
  @backstage/backend-tasks                         0.4.2
  @backstage/catalog-client                        1.3.0
  @backstage/catalog-model                         1.1.5
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.1
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.4.0
  @backstage/core-components                       0.12.3
  @backstage/core-plugin-api                       1.3.0
  @backstage/errors                                1.1.4
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.9
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.8.14
  @backstage/plugin-app-backend                    0.3.41
  @backstage/plugin-auth-backend                   0.17.4
  @backstage/plugin-auth-node                      0.2.10
  @backstage/plugin-catalog-backend-module-github  0.2.4
  @backstage/plugin-catalog-backend                1.7.1
  @backstage/plugin-catalog-common                 1.0.10
  @backstage/plugin-catalog-graph                  0.2.26
  @backstage/plugin-catalog-import                 0.9.4
  @backstage/plugin-catalog-node                   1.3.2
  @backstage/plugin-catalog-react                  1.2.4
  @backstage/plugin-catalog                        1.7.2
  @backstage/plugin-events-node                    0.2.2
  @backstage/plugin-github-actions                 0.5.14
  @backstage/plugin-home                           0.4.30
  @backstage/plugin-org                            0.6.4
  @backstage/plugin-permission-backend             0.5.16
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.4
  @backstage/plugin-permission-react               0.4.9
  @backstage/plugin-proxy-backend                  0.2.35
  @backstage/plugin-scaffolder-backend             1.10.1
  @backstage/plugin-scaffolder-common              1.2.4
  @backstage/plugin-scaffolder-react               1.0.1
  @backstage/plugin-scaffolder                     1.10.1
  @backstage/plugin-search-backend-module-pg       0.5.2
  @backstage/plugin-search-backend-node            1.1.2
  @backstage/plugin-search-backend                 1.2.2
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.4.0
  @backstage/plugin-search                         1.0.7
  @backstage/plugin-shortcuts                      0.3.6
  @backstage/plugin-stack-overflow                 0.1.10
  @backstage/plugin-techdocs-backend               1.5.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.9
  @backstage/plugin-techdocs-node                  1.4.5
  @backstage/plugin-techdocs-react                 1.1.2
  @backstage/plugin-techdocs                       1.4.3
  @backstage/plugin-user-settings                  0.6.2
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.4
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
```

</details>

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by clairelcasey**
## Hey, I just made a Pull Request!

Closes https://github.com/backstage/backstage/issues/16288

Adds styling to `MembersListCard` and `ComponentsGrid` to hide overlapping text and show it on hover. 

This is my first-ever Backstage PR so lmk if I missed something!! 

Styling decision:
* I decided to go with hiding full text with elipses because this was consistent with emails in the `MembersListCard`. 
* An alternate approach would be to decrease the font size to fit the text or show all the wrapped text. Very open if there are other design standards for Backstage too to consider here! 

**New design:**
image
on hover:
image
image
on hover:
image

**Current design:**
image
image

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/org/src/components/Cards/OwnershipCard/ComponentsGrid.tsx [hunk 1]
```diff
@@ -44,8 +44,16 @@ const useStyles = makeStyles((theme: BackstageTheme) =>
...
+    title: {
       fontWeight: theme.typography.fontWeightBold,
+      textAlign: 'center',
+      overflow: 'hidden',
+      textOverflow: 'ellipsis',
+      maxWidth: '100%',
+      '&:hover': {
+        overflow: 'visible',
+        wordBreak: 'break-word',
+      },
```
Comment (Rugvip) [inline plugins/org/src/components/Cards/OwnershipCard/ComponentsGrid.tsx:56]: Another option for the hover reveal is to use the [`OverflowTooltip`](https://backstage.io/storybook/?path=/story/data-display-overflowtooltip--default) component from `@backstage/core-components`. Not sure which one will provide the best UX in this case but could be worth trying it out.

File: plugins/org/src/components/Cards/OwnershipCard/ComponentsGrid.tsx [hunk 2]
```diff
@@ -44,8 +44,16 @@ const useStyles = makeStyles((theme: BackstageTheme) =>
       },
       height: '100%',
     },
-    bold: {
+    title: {
       fontWeight: theme.typography.fontWeightBold,
+      textAlign: 'center',
+      overflow: 'hidden',
+      textOverflow: 'ellipsis',
```
Comment (Rugvip) [inline plugins/org/src/components/Cards/OwnershipCard/ComponentsGrid.tsx:51]: Honestly it would be pretty cool to try out shrinking the font size to fit, but doing it properly essentially requires reimplementing `react-test-truncate` which the `OverflowTooltip` uses as far as I can tell 😅. Wonder if there's some super simple version that could be used that is just a simple best effort text length check between two different font sizes or something like that, still keeping the truncation.

File: .changeset/selfish-hats-wait.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/plugin-org': patch
+---
+
+Add styling to the MembersListCard and ComponentsGrid to handle overflow text.
```
Comment (Rugvip) [inline .changeset/selfish-hats-wait.md:5]:
```suggestion
Add styling to the `MembersListCard` and `ComponentsGrid` to handle overflow text.
```

Always nice to wrap code symbols up in code blocks to highlight what they are 😁

**Review by Rugvip — CHANGES_REQUESTED** [review]
Sweet, thank you! 😁 👍 

Kind of optional nits, but I especially think it's worth exploring using `OverflowTooltip`. Might be that it doesn't work well and we merge as is though 😅

File: plugins/org/src/components/Cards/OwnershipCard/ComponentsGrid.tsx (hunk 1 above)
Comment (clairelcasey) [reply plugins/org/src/components/Cards/OwnershipCard/ComponentsGrid.tsx]: Awesome, I didn't know about `OverflowTooltip` this is great!! I refactored to use that component instead, and also added in a few comments to the PR. I think this looks better, but not 100% confident from a UX standpoint.

File: plugins/org/src/components/Cards/OwnershipCard/ComponentsGrid.tsx (hunk 2 above)
Comment (clairelcasey) [reply plugins/org/src/components/Cards/OwnershipCard/ComponentsGrid.tsx]: Yes, I also played around with [react-scale-text](https://www.npmjs.com/package/react-scale-text?activeTab=explore), but this didn't work super smoothly/ bring a lot of value in my opinion. I added in a really simple fontSize change to the `ComponentsGrid` but not to the `MembershipListCard` because I thought this didn't look as clean (screenshot below), but could easily add it in to that component as well! 
Screenshot 2023-02-16 at 3 24 28 PM

File: plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx [hunk 4]
```diff
@@ -106,14 +107,14 @@ const MemberComponent = (props: { member: UserEntity }) => {
             }}
             textAlign="center"
           >
-            <Typography variant="h5">
+            <Typography variant="h6">
```
Comment (clairelcasey) [inline plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx:110]: I changed this to an h6 because of the implementation of `OverflowTooltip`. The component uses [TextTruncate](https://github.com/backstage/backstage/blob/master/packages/core-components/src/components/OverflowTooltip/OverflowTooltip.tsx#L59) from `react-text-truncate`, which truncates based on the last line specified. In other words, if you add in `line={2}` this will then truncate the second line, and if you leave it blank it'll truncate the first line. So, the current implementation means all names will now be on a single line and I reduced the fontSize to have it fit better. If we do want names to be continued to have 2 lines, we'd have to modify this implementation because otherwise you get some funky results when it's one long name or the first name is longer than the last name, see below. I can look into this more if we're worried about names being limited to one line! 

image

File: plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx [hunk 5]
```diff
@@ -106,14 +107,14 @@ const MemberComponent = (props: { member: UserEntity }) => {
...
                 to={generatePath(
                   `/catalog/:namespace/user/${metaName}`,
                   entityRouteParams(props.member),
                 )}
               >
-                {displayName}
+                <OverflowTooltip text={displayName} />
               </Link>
             </Typography>
             {profile?.email && (
```
Comment (clairelcasey) [inline plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx:120]: curious if you think we should change the email to use `OverflowTooltip` for consistency, or keep it where it shows the entire email on hover?

**Comment by clairelcasey** [comment]
Updated to use `OverflowTooltip`. Current implementation looks like:

image
image

**Comment by clairelcasey** [comment]
I see that some tests are failing, will look into this tomorrow! Having some difficulty getting tests to run locally :(

File: plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx (hunk 5 above)
Comment (Rugvip) [reply plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx:120]: Oh hmm, I guess the entire email is always accessible via the link either way, so could probably switch it over to use `OverflowTooltip` as well? I think that'd make sense

**Review by Rugvip — APPROVED** [review]
Sweet, thank you! 😁 

Let me know if you wanna ship it as is or do the email tweak as well

File: plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx (hunk 5 above)
Comment (clairelcasey) [reply plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx:109]: I agree! Also allows us to remove some custom CSS for it. Just changed it

**Comment by clairelcasey** [comment]
@Rugvip added in that email change - should be ready for a re-review :) thanks!!

**Review by Rugvip — APPROVED** [review]
Nice! 👍 

Let's :shipit:
