### PR TITLE
gitlab discovery ignore projects without default_branch

### LINKED ISSUE #8623: can filter out more projects in gitlab discovery
this is a very minor potential improvement to gitlab discovery, but i noticed when running gitlab discovery that backstage filters out "archived" projects but not "empty repo" projects (see: https://gitlab.com/gitlab-org/gitlab/-/issues/3800). these projects don't have a repository and thus don't have a default branch, though discovery assumes `project.default_branch` to exist and attempts to fetch a catalog file, erroring with:

```
catalog warn Unable to read url, Error: https://[gitlab-host]/[group]/[project]/-/blob/undefined/catalog-info.yaml could not be read as https://[gitlab-host]/api/v4/projects/[project-id]/repository/files/catalog-info.yaml/raw?ref=undefined, 403 Forbidden
```

not a huge deal but the warn logs are confusing: "why are we trying to discover from `?ref=undefined`?" on a gitlab instance with a lot of empty repo projects, discovery could save some time by filtering these out up front.

it seems a decent way to do this is filter out `project.empty_repo === true`, though this [isn't yet documented in their API](https://gitlab.com/gitlab-org/gitlab/-/issues/32694). we could also filter where `project.default_branch === undefined`.

https://github.com/backstage/backstage/blob/5284458e18f7da3bc0ba5eb8043e902108518726/plugins/catalog-backend/src/ingestion/processors/GitLabDiscoveryProcessor.ts#L97-L99

just wanted to flag! happy to put up a PR if desired.

### PR DESCRIPTION
**Pull request by zhammer**
## Hey, I just made a Pull Request!

fixes #8623 

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [X] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/catalog-backend/src/ingestion/processors/GitLabDiscoveryProcessor.ts [hunk 1]
```diff
@@ -94,7 +94,7 @@ export class GitLabDiscoveryProcessor implements CatalogProcessor {
     };
     for await (const project of projects) {
       result.scanned++;
-      if (!project.archived) {
+      if (!(project.archived || project.default_branch === undefined)) {
```
Comment (zhammer) [inline plugins/catalog-backend/src/ingestion/processors/GitLabDiscoveryProcessor.ts:97]: we discussed in #8662 two ways to filter out "empty repo" projects, a) filter where `project.empty_repo === true`, b) filter where `project.default_branch === undefined`. as per @Rugvip's [suggestion](https://github.com/backstage/backstage/issues/8623#issuecomment-1001619984) we went with option b, as `project.empty_repo` isn't documented.

my followup here is: do we want to update this to `|| (branch === '*' && project.default_branch === undefined)`, so we only filter repos where default_branch is missing if a gitlab discovery is configured to scan projects for default branch? I just don't know enough about the gitlab api to know if there's a case where a repo has no default branch but _does_ have a branch you can manually read from. I doubt it but wanted to raise here just to flag

Comment (Rugvip) [reply plugins/catalog-backend/src/ingestion/processors/GitLabDiscoveryProcessor.ts:97]: Yep I think that extended check makes sense 👍

File: plugins/catalog-backend/src/ingestion/processors/GitLabDiscoveryProcessor.ts [hunk 2]
```diff
@@ -94,7 +94,12 @@ export class GitLabDiscoveryProcessor implements CatalogProcessor {
     };
     for await (const project of projects) {
       result.scanned++;
-      if (!project.archived) {
+      if (
```
Comment (Rugvip) [inline plugins/catalog-backend/src/ingestion/processors/GitLabDiscoveryProcessor.ts:97]: This got pretty large, perhaps we could flip it around so that it skips the excluded ones instead?

```
if (project.archived) {
  continue
}
...etc
```

Think that should be a bit easier to read

Comment (zhammer) [reply plugins/catalog-backend/src/ingestion/processors/GitLabDiscoveryProcessor.ts:97]: yep, I prefer that as well!

**Review by Rugvip — APPROVED** [review]
Nice, thank you! 👍
