### PR TITLE
catalog-backend: refactor deferral of entites + fix dissapearing ref bug

### LINKED ISSUE #6826: Items falsely marked as isOrphan when using GitHub location discovery and default branch is main
If users are running backstage and using GitHub location discovery like so in their `app-config.yaml`

**Note**: We have to use `master` to find repositories that use `main` as well, as that is the only way to get this to work for projects that use either `master` or `main` without getting duplicate errors during locations refresh.

```
  locations:
    - type: github-discovery
      target: https://github.com/example-organization/*/blob/master/catalog-info.yaml
```
The latest `isOrphan` and `EntityOrphanWarning` logic fires, even though the repository is correctly configured with a `catalog-info.yaml` at root, as is in fact not orphaned. The logic below will trigger if any entity exists in github on a branch that is not `master` (e.g. the new default branch of `main`).

```
// packages/app/src/components/catalog/EntityPage.tsx

    {/* <EntitySwitch>
      <EntitySwitch.Case if={isOrphan}>
        <Grid item xs={12}>
          <EntityOrphanWarning />
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch> */}
```

## Expected Behavior

The `isOrphan` logic should not fire when the item being indexed by GitHub location discovery exists on a branch that is not explicitly named `master`.

## Current Behavior

The `isOrphan` logic fires when an entity is being discovered (github location discovery) and the default branch != `master`

Screen Shot 2021-08-13 at 9 23 58 AM

## Steps to Reproduce

1. Configure github location discovery to find a `catalog-info.yaml` for a component upstream in a github.com repository
2. Configure the default branch of the component's github.com repository to != `master` (e.g. set it to use `main`)
3. Watch backstage mark the item as isOrphan = true

## Context

This is troublesome because we use github discovery to find all catalog-info.yaml files that exist across all repositories, regardless of the set default master branch. However, if we use the newish `isOrphan` logic, we get many items in the catalog that are _falsely_ marked as orphaned if they use `main` as their default branch.

## Your Environment

Backstage Version: [release-2021-08-12](https://github.com/backstage/backstage/releases/tag/release-2021-08-12)

### PR DESCRIPTION
**Pull request by Rugvip**
The catalog currently has a bug where adding new locations to the catalog will cause the root references to all the old ones to disappear. The impact of this has been mitigated by the fact that we don't properly surface errors and orphan status from locations yet (#6973).

This fixes #6826, and also a more recent issue where refreshes would fail for most entities in the catalog.

### CODE REVIEW

**Comment by Rugvip** [comment]
Still a bit WIP as I wanna add some regression tests and make sure the bad state that this bug caused is self-healing

**Comment by Rugvip** [comment]
Alright ready for review, added a regression test. It's also self-healing due to the full sync being used by both the location and config providers, along with the delta calculation being done based on the existing references rather than refresh state.

File: plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts [hunk 1]
```diff
@@ -332,143 +274,38 @@ export class DefaultProcessingDatabase implements ProcessingDatabase {
...
+          if (!ok) {
+            ok = await this.updateUnprocessedEntity(tx, entity, locationKey);
           }
 
-          const result: { /* postgres */ rowCount?: number } = await query;
-          if (result.rowCount === 0) {
-            throw new ConflictError(
-              'Insert failed due to conflicting entity_ref',
+          if (ok) {
+            await tx('refresh_state_references').insert<any>({
```
Comment (freben) [inline plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts:287]:
```suggestion
            await tx<DbRefreshStateReferencesRow>('refresh_state_references').insert({
```

File: plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts [hunk 2]
```diff
@@ -599,4 +436,246 @@ export class DefaultProcessingDatabase implements ProcessingDatabase {
       throw rethrowError(e);
     }
   }
+
+  /**
+   * Attempts to update an existing refresh state row, returning true if it was
+   * updated and false if there was no with a matching entity ref and location key.
+   *
+   * Updating the entity will also caused it to be scheduled for immediate processing.
```
Comment (freben) [inline plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts:444]:
```suggestion
   * Attempts to update an existing refresh state row, returning true if it was
   * updated and false if there was no entity with a matching ref and location key.
   *
   * Updating the entity will also cause it to be scheduled for immediate processing.
```

File: plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts [hunk 3]
```diff
@@ -599,4 +436,246 @@ export class DefaultProcessingDatabase implements ProcessingDatabase {
...
+  private async updateUnprocessedEntity(
+    tx: Knex.Transaction,
+    entity: Entity,
+    locationKey?: string,
+  ): Promise<boolean> {
+    const entityRef = stringifyEntityRef(entity);
+    const serializedEntity = JSON.stringify(entity);
+
+    // We optimistically try to update any existing refresh state first, as this is by far
+    // the most common case.
```
Comment (freben) [inline plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts:455]: can probably remove this comment now that this is the exact intent of the code

File: plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts [hunk 4]
```diff
@@ -599,4 +436,246 @@ export class DefaultProcessingDatabase implements ProcessingDatabase {
...
+   */
+  private async insertUnprocessedEntity(
+    tx: Knex.Transaction,
+    entity: Entity,
+    locationKey?: string,
+  ): Promise<boolean> {
+    const entityRef = stringifyEntityRef(entity);
+    const serializedEntity = JSON.stringify(entity);
+
+    // In the event that we can't update an existing refresh state, we first try to insert a new row
```
Comment (freben) [inline plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts:491]: probably remove this comment as well now

File: plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts [hunk 5]
```diff
@@ -599,4 +436,246 @@ export class DefaultProcessingDatabase implements ProcessingDatabase {
...
+    try {
+      let query = tx('refresh_state').insert<any>({
```
Comment (freben) [inline plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts:493]:
```suggestion
      let query = tx<DbRefreshStateReferencesRow>('refresh_state').insert({
```

**Review by freben — APPROVED** [review]
Pre-approve to unblock, some small things only, this is looking really good and is easier to understand than what was there before.

**Review by benjdlambert — APPROVED** [review]

File: plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts [hunk 6]
```diff
@@ -332,143 +274,40 @@ export class DefaultProcessingDatabase implements ProcessingDatabase {
...
-            last_discovery_at: tx.fn.now(),
-          });
-
-          // TODO(Rugvip): only tested towards Postgres and SQLite
-          // We have to do this because the only way to detect if there was a conflict with
-          // SQLite is to catch the error, while Postgres needs to ignore the conflict to not
-          // break the ongoing transaction.
-          if (tx.client.config.client !== 'sqlite3') {
-            query = query.onConflict('entity_ref').ignore();
+          let ok = await this.insertUnprocessedEntity(tx, entity, locationKey);
```
Comment (freben) [inline plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts:281]: Not to be fixed in this PR, but it is probably unfortunate that we try insert first and update after. Large refreshes of mostly pre-existing things will have a large amount of data in toAdd, and this code kinda assumes that add means add, not upsert.

It could be that we want to add a toUpdate array in the delta output. It could even check content hashes if we wanted to.

Comment (Rugvip) [reply plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts:281]: I flipped them around here for the opposite reason. We compute the delta first so the by far most common case is that it doesn't already exist

Comment (freben) [reply plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts:281]: So when I issue a 'full' sync, what happens to all the ones that exist and have changes?

Comment (Rugvip) [reply plugins/catalog-backend/src/next/database/DefaultProcessingDatabase.ts:281]: Nothing, right now the full sync is only concerned with making sure the entities are(n't) in the catalog, it doesn't trigger refreshes other than by "accident" when an entity is already provided from another source
