### PR TITLE
Fix hitbox of sidebar search input

### LINKED ISSUE #6529: SidebarSearch input smaller than surrounding anchor tag
The input of the SidebarSearch component of the search plugin (`@backstage/plugin-search`) is smaller than the parent anchor tag, resulting in unexpected behaviour when clicking slightly next to it.

Screenshot 2021-07-19 at 09 33 29 Screenshot 2021-07-19 at 09 33 42

https://user-images.githubusercontent.com/24435169/126126316-9c6eef5d-79d4-43bc-93f7-4869cf719b18.mp4

## Expected Behavior

When clicking slightly under or above the input field, the user focuses on the input element.

## Current Behavior

When clicking slightly under or above the input field, the user navigates to the search page.

## Possible Solution

Increase the padding of the input element from `6px 0 7px` to `16px 0px`.

## Steps to Reproduce

1. Run Backstage version `release-2021-07-16` (or navigate to demo.backstage.io)
2. Hover over and around the sidebar search.
3. Observe how the cursor changes.

## Your Environment

- NodeJS Version: v14.17.0
- Operating System and Version: macOS Catalina (version 10.15.7)
- Browser Information: Chrome (version 90.0.4430.85)

### PR DESCRIPTION
**Pull request by gnarlex**
## Hey, I just made a Pull Request!

     
Increase the vertical padding of the sidebar search input field to match the height of the parent anchor tag. This prevents users from accidentally navigating to the search page when they actually wanted to use the search input directly.

Fixes #6529

Before:

https://user-images.githubusercontent.com/24435169/126139192-23bea8a5-f33d-46d3-8cbc-dbc771bcbca8.mp4

After:

https://user-images.githubusercontent.com/24435169/126139223-24ba8fba-2f09-4e04-92b9-1536bdeb4af6.mp4

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: packages/core-components/src/layout/Sidebar/Items.tsx [hunk 1]
```diff
@@ -97,6 +97,9 @@ const useStyles = makeStyles<BackstageTheme>(theme => {
       fontWeight: 'bold',
       fontSize: theme.typography.fontSize,
     },
+    searchFieldHTMLInput: {
+      padding: '15px 0 17px',
```
Comment (benjdlambert) [inline packages/core-components/src/layout/Sidebar/Items.tsx:101]: I wonder if it makes sense to to use `theme.spacing(x)` here instead?

**Comment by OrkoHunter** [comment]
cc @backstage/techdocs-core

**Review by benjdlambert — APPROVED** [review]

**Review by iamEAP — APPROVED** [review]
