### PR TITLE
Permission: improve request batching

### LINKED ISSUE #23303: 🐛 Bug Report: AuthorizedSearchEngine fails with Payload too Large
### 📜 Description

When searching with a bigger `pageLimit` than 25, the AuthorizedSearchEngine fails to call apply conditions for all entities.

### 👍 Expected behavior

The permission evaluation should not fail even with a bigger `pageLimit`

### 👎 Actual Behavior with Screenshots

Response from `/api/catalog/.well-known/backstage/permissions/apply-conditions`

```
Request failed with status 500 Unexpected response from plugin upstream when applying conditions. Expected 200 but got 400 - Bad Request
Request failed with status 500 There was a problem performing the search query: Request failed with 500 Error
```

Client side failure reason: `HTTP response 400 - Bad Request`
Server side failure reason: `Exception PayloadTooLargeError`

### 👟 Reproduction steps

1. Enable permissions
2. Modify the `pageLimit` for search queries to `100`
3. Try to search for catalog items

### 📃 Provide the context for the Bug.

This fix changed the behavior so that the `pageLimit` can be defined from the query (like with default search engine): https://github.com/backstage/backstage/commit/3ed0eac5b4fc6e48f50395d61adc4a6a88423f21

### 🖥️ Your Environment

OS:   Darwin 23.3.0 - darwin/arm64
node: v18.15.0
yarn: 1.22.19
cli:  0.25.2 (installed)
backstage:  1.23.3

Dependencies:
  @backstage/app-defaults                                            1.5.0
  @backstage/backend-app-api                                         0.5.13
  @backstage/backend-common                                          0.17.0, 0.19.9, 0.20.1, 0.21.2
  @backstage/backend-dev-utils                                       0.1.4
  @backstage/backend-openapi-utils                                   0.1.5
  @backstage/backend-plugin-api                                      0.6.12
  @backstage/backend-tasks                                           0.5.17
  @backstage/backend-test-utils                                      0.3.2
  @backstage/catalog-client                                          1.6.0
  @backstage/catalog-model                                           1.4.4
  @backstage/cli-common                                              0.1.13
  @backstage/cli-node                                                0.2.3
  @backstage/cli                                                     0.25.2
  @backstage/config-loader                                           1.6.2
  @backstage/config                                                  1.1.1
  @backstage/core-app-api                                            1.12.0
  @backstage/core-compat-api                                         0.2.0
  @backstage/core-components                                         0.12.5, 0.13.10, 0.14.0
  @backstage/core-plugin-api                                         1.9.0
  @backstage/dev-utils                                               1.0.27
  @backstage/errors                                                  1.2.3
  @backstage/eslint-plugin                                           0.1.5
  @backstage/frontend-plugin-api                                     0.6.0
  @backstage/integration-aws-node                                    0.1.9
  @backstage/integration-react                                       1.1.24
  @backstage/integration                                             1.9.0
  @backstage/plugin-api-docs                                         0.11.0
  @backstage/plugin-app-backend                                      0.3.60
  @backstage/plugin-app-node                                         0.1.12
  @backstage/plugin-auth-backend-module-atlassian-provider           0.1.4
  @backstage/plugin-auth-backend-module-aws-alb-provider             0.1.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider             0.2.7
  @backstage/plugin-auth-backend-module-github-provider              0.1.9
  @backstage/plugin-auth-backend-module-gitlab-provider              0.1.9
  @backstage/plugin-auth-backend-module-google-provider              0.1.9
  @backstage/plugin-auth-backend-module-microsoft-provider           0.1.7
  @backstage/plugin-auth-backend-module-oauth2-provider              0.1.9
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider        0.1.5
  @backstage/plugin-auth-backend-module-oidc-provider                0.1.2
  @backstage/plugin-auth-backend-module-okta-provider                0.0.5
  @backstage/plugin-auth-backend                                     0.21.2
  @backstage/plugin-auth-node                                        0.4.7
  @backstage/plugin-catalog-backend-module-aws                       0.3.6
  @backstage/plugin-catalog-backend-module-msgraph                   0.5.19
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model   0.1.9
  @backstage/plugin-catalog-backend-module-unprocessed               0.3.9
  @backstage/plugin-catalog-backend                                  1.17.2
  @backstage/plugin-catalog-common                                   1.0.21
  @backstage/plugin-catalog-graph                                    0.4.0
  @backstage/plugin-catalog-node                                     1.7.2
  @backstage/plugin-catalog-react                                    1.10.0
  @backstage/plugin-catalog-unprocessed-entities                     0.1.8
  @backstage/plugin-catalog                                          1.17.0
  @backstage/plugin-devtools-backend                                 0.2.9
  @backstage/plugin-devtools-common                                  0.1.8
  @backstage/plugin-devtools                                         0.1.9
  @backstage/plugin-events-backend                                   0.2.21
  @backstage/plugin-events-node                                      0.2.21
  @backstage/plugin-github-actions                                   0.6.11
  @backstage/plugin-home-react                                       0.1.8
  @backstage/plugin-home                                             0.6.2
  @backstage/plugin-jenkins-backend                                  0.3.6
  @backstage/plugin-jenkins-common                                   0.1.24
  @backstage/plugin-jenkins                                          0.9.5
  @backstage/plugin-kubernetes-common                                0.7.4
  @backstage/plugin-org                                              0.6.20
  @backstage/plugin-permission-backend                               0.5.35
  @backstage/plugin-permission-common                                0.7.12
  @backstage/plugin-permission-node                                  0.7.23
  @backstage/plugin-permission-react                                 0.4.20
  @backstage/plugin-proxy-backend                                    0.4.10
  @backstage/plugin-scaffolder-backend-module-azure                  0.1.4
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud        0.1.2
  @backstage/plugin-scaffolder-backend-module-bitbucket-server       0.1.2
  @backstage/plugin-scaffolder-backend-module-bitbucket              0.2.2
  @backstage/plugin-scaffolder-backend-module-confluence-to-markdown 0.2.13
  @backstage/plugin-scaffolder-backend-module-cookiecutter           0.2.36
  @backstage/plugin-scaffolder-backend-module-gerrit                 0.1.4
  @backstage/plugin-scaffolder-backend-module-gitea                  0.1.2
  @backstage/plugin-scaffolder-backend-module-github                 0.2.2
  @backstage/plugin-scaffolder-backend-module-gitlab                 0.2.15
  @backstage/plugin-scaffolder-backend                               1.21.2
  @backstage/plugin-scaffolder-common                                1.5.0
  @backstage/plugin-scaffolder-node                                  0.2.10, 0.3.2
  @backstage/plugin-scaffolder-react                                 1.8.0
  @backstage/plugin-scaffolder                                       1.18.0
  @backstage/plugin-search-backend-module-catalog                    0.1.16
  @backstage/plugin-search-backend-module-elasticsearch              1.3.15
  @backstage/plugin-search-backend-module-techdocs                   0.1.16
  @backstage/plugin-search-backend-node                              1.2.16
  @backstage/plugin-search-backend                                   1.5.2
  @backstage/plugin-search-common                                    1.2.10
  @backstage/plugin-search-react                                     1.7.6
  @backstage/plugin-search                                           1.4.6
  @backstage/plugin-signals-node                                     0.0.1, 0.0.3
  @backstage/plugin-signals-react                                    0.0.1
  @backstage/plugin-signals                                          0.0.1
  @backstage/plugin-sonarqube-backend                                0.2.14
  @backstage/plugin-sonarqube-react                                  0.1.13
  @backstage/plugin-sonarqube                                        0.7.12
  @backstage/plugin-techdocs-backend                                 1.9.5
  @backstage/plugin-techdocs-node                                    1.11.4
  @backstage/plugin-techdocs-react                                   1.1.16
  @backstage/plugin-techdocs                                         1.10.0
  @backstage/plugin-user-settings-backend                            0.2.11
  @backstage/plugin-user-settings                                    0.8.1
  @backstage/release-manifests                                       0.0.11
  @backstage/repo-tools                                              0.6.2
  @backstage/test-utils                                              1.5.0
  @backstage/theme                                                   0.2.19, 0.4.4, 0.5.1
  @backstage/types                                                   1.1.1
  @backstage/version-bridge                                          1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by vinzscam**
## Hey, I just made a Pull Request!

This PR optimizes the permission framework requests flow by batching requests. This fixes #23303, as the search plugin currently performs result-by-result authorization. When attempting to authorize the catalog search results, search sends: 

```json
[
  {
    "items": [
      {
        "id": "b8c3abdf-2f8a-44ff-ab52-5af9671a92bf",
        "resourceRef": "user:default/sarah.gilroy",
        "permission": {
          "type": "resource",
          "name": "catalog.entity.read",
          "attributes": {
            "action": "read"
          },
          "resourceType": "catalog-entity"
        }
      },
      {
        "id": "6a38049d-de04-46fa-84cf-9861aaebba0f",
        "resourceRef": "group:default/team-c",
        "permission": {
          "type": "resource",
          "name": "catalog.entity.read",
          "attributes": {
            "action": "read"
          },
          "resourceType": "catalog-entity"
        }
      },
      ... // x times depending on the set limit
]
```

if you have a permission policy returning a conditional result, for example containing the following conditional decision:

```js
  if (
    isPermission(request.permission, catalogEntityReadPermission)
  ) {
    return createCatalogConditionalDecision(request.permission, {
      not: catalogConditions.hasMetadata({ key: 'something' }),
    });
  }
```

the permission-backend sends to catalog the resolved value of the permission policy:

```json
  {
    "items": [
      {
        "id": "f2e0b4a1-79ee-41c4-8dcb-9187286d3e74",
        "resourceRef": "location:default/example-systems",
        "resourceType": "catalog-entity",
        "conditions": {
          "not": {
            "rule": "HAS_METADATA",
            "resourceType": "catalog-entity",
            "params": {
              "key": "something"
            }
          }
        }
      },
      {
        "id": "cdef0c2e-2ec3-4284-8204-251b54483f35",
        "resourceRef": "user:default/lucy.sheehan",
        "resourceType": "catalog-entity",
        "conditions": {
          "not": {
            "rule": "HAS_METADATA",
            "resourceType": "catalog-entity",
            "params": {
              "key": "something"
            }
          }
        }
      },
      // ... x times depending on the set limit
]
```

Note that in the request above the resolved value of the permission policy is repeated x times. So if your permission policy is more complex than the one above, the payload limit is exhausted faster.

With the new approach the first request becomes:

```json
  {
    "items": [
      {
        "id": "f9c5bd93-9bc9-455b-89f8-c918e15121e3",
        "resourceRefs": [
          "user:default/colette.brock",
          "user:default/nigel.manning",
          // ...x times depending on the set limit
        ],
        "permission": {
          "type": "resource",
          "name": "catalog.entity.read",
          "attributes": {
            "action": "read"
          },
          "resourceType": "catalog-entity"
        }
      }
    ]
  }
```

The second request:

```json
  {
    "items": [
      {
        "id": "beebd90b-3445-482f-82c4-98220be83d09",
        "resourceRefs": [
          "user:default/colette.brock",
          "user:default/nigel.manning",
          // ...x times depending on the set limit
        ],
        "resourceType": "catalog-entity",
        "conditions": {
          "not": {
            "rule": "HAS_METADATA",
            "resourceType": "catalog-entity",
            "params": {
              "key": "something"
            }
          }
        }
      }
    ]
  }
```

This should avoid exhausting the request body size limit too quickly.
Note that the new batching of requests happens internally within the `PermissionClient`, so no changes are needed to the plugins authorizing the permissions. However, since the new version of `@backstage/plugin-permission-common` needs to be in sync with the new version of `@backstage/plugin-permission-backend`, I have introduced a new `permission.EXPERIMENTAL_enableBatchedRequests` configuration to enable the new batching mode. Eventually, we can enable this feature by default in the future.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/permission-common/src/PermissionClient.ts [hunk 1]
```diff
@@ -144,17 +177,75 @@ export class PermissionClient implements PermissionEvaluator {
...
+          id: uuid.v4(),
+        };
+      } else {
+        request[permission.name] ||= {
+          permission,
+          id: uuid.v4(),
+        };
+      }
+
+      if (resourceRef) {
```
[the remark this answers is not in the document]
Comment (vinzscam) [reply plugins/permission-common/src/PermissionClient.ts:223]: it definitely does! 🙏

File: plugins/permission-common/src/PermissionClient.test.ts [hunk 2]
```diff
@@ -211,7 +218,284 @@ describe('PermissionClient', () => {
...
+            enabled: true,
+            EXPERIMENTAL_enableBatchedRequests: true,
+          },
+        }),
+      });
+    });
+
+    const mockAuthorizeConditional = {
+      permission: mockPermission,
+      resourceRef: 'foo:bar',
```
Comment (freben) [inline plugins/permission-common/src/PermissionClient.test.ts:236]: maybe doesn't matter for the test but these (here and elsewhere) really should always be full refs

File: plugins/permission-common/src/PermissionClient.ts [hunk 3]
```diff
@@ -144,17 +177,75 @@ export class PermissionClient implements PermissionEvaluator {
...
+    const parsedResponse = await this.makeRawRequest(
+      { items: Object.values(request) },
+      authorizePermissionResponseBatchSchema,
+      options,
+    );
+
+    return queries.map(query => {
+      const { id } = request[query.permission.name];
+
+      const item = parsedResponse.items.find(i => i.id === id)!;
```
Comment (freben) [inline plugins/permission-common/src/PermissionClient.ts:237]: Just noting that this is N^2 (iterates through the items for every query)

File: plugins/permission-node/report.api.md [hunk 4]
```diff
@@ -37,20 +38,33 @@ export type ApplyConditionsRequest = {
...
-}>;
+export type ApplyConditionsRequestEntry = IdentifiedPermissionMessage<
+  | {
+      resourceRef: string;
+      resourceRefs?: undefined;
+      resourceType: string;
+      conditions: PermissionCriteria<PermissionCondition>;
+    }
+  | {
+      resourceRef?: undefined;
```
Comment (freben) [inline plugins/permission-node/report.api.md:49]: would it just have been enough to make this a single `resourceRef: string | string[]`? Seems simpler at least to a casual observer. But maybe you wanted to deprecate the non-array one later down the line

**Review by freben — APPROVED** [review]
Approve but just with some open optional questions

File: plugins/permission-node/report.api.md (hunk 4 above)
Comment (vinzscam) [reply plugins/permission-node/report.api.md:49]: yeah that was my intention, but happy to change it to using only `resourceRef`

Comment (vinzscam) [reply plugins/permission-node/report.api.md:49]: I've pivoted to keeping just `resourceRef`

File: plugins/permission-common/src/PermissionClient.ts (hunk 3 above)
Comment (vinzscam) [reply plugins/permission-common/src/PermissionClient.ts:237]: it should have any impact given the limited set of items, but I've pushed a fix 👍
