### PR TITLE
fix banner position and color

### LINKED ISSUE #2245: Fix banner component
## 🗒 General

Hi! Would love if someone could help us update our DismissableBanners component. Currently, the banner appears at the top, and the colors don't pass accessibility standards. We'd love for the banner to show at the bottom (20px above the bottom). 
Banners

Example 1

Example 2

## 📐 Specs
You can access specs by duplicating our [Figma UI Kit](https://www.figma.com/community/file/850673348101741100). Click on the "Dismissable Banner" page on the left. 
Screenshot 2020-09-02 at 3 46 46 PM

### PR DESCRIPTION
**Pull request by samiramkr**
#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

This PR closes: https://github.com/spotify/backstage/issues/2245

The "fixed" props added to control the position of the banner. When it is set to true the banner will be shown in bottom of tha page and the width will be based on the content of the message.

Screenshot 2020-09-21 at 13 45 25
Screenshot 2020-09-21 at 13 45 03

### CODE REVIEW

File: packages/core/src/components/DismissableBanner/DismissableBanner.tsx [hunk 1]
```diff
@@ -27,12 +27,19 @@ import Close from '@material-ui/icons/Close';
 
 const useStyles = makeStyles((theme: BackstageTheme) => ({
   root: {
-    position: 'relative',
+    // position: 'relative',
```
Comment (stefanalund) [inline packages/core/src/components/DismissableBanner/DismissableBanner.tsx:30]: Please remove commented out code.

File: packages/core/src/components/DismissableBanner/DismissableBanner.tsx [hunk 2]
```diff
@@ -27,12 +27,19 @@ import Close from '@material-ui/icons/Close';
...
     padding: theme.spacing(0),
-    marginBottom: theme.spacing(6),
-    marginTop: -theme.spacing(3),
+    marginBottom: theme.spacing(0),
+    marginTop: theme.spacing(0),
     display: 'flex',
     flexFlow: 'row nowrap',
+    // zIndex: 'unset'
```
Comment (stefanalund) [inline packages/core/src/components/DismissableBanner/DismissableBanner.tsx:36]: Same as above.

File: packages/theme/src/types.ts [hunk 3]
```diff
@@ -64,6 +64,8 @@ type PaletteAdditions = {
   banner: {
     info: string;
     error: string;
+    textColor: string;
```
Comment (Rugvip) [inline packages/theme/src/types.ts:67]: The context here is already a palette of colors, so no need to suffix with `Color`, `text` is enough imo

**Review by Rugvip — COMMENTED** [review]
Nice! 🎉

File: packages/core/src/components/DismissableBanner/DismissableBanner.stories.tsx [hunk 4]
```diff
@@ -100,3 +100,15 @@ export const WithLink = () => (
     </ApiProvider>
   </div>
 );
+export const Fixed = () => (
+  <div style={containerStyle}>
+    <ApiProvider apis={apis}>
+      <DismissableBanner
+        message="This is a dismissable banner with a fixed position fixed at the bottom of the page"
+        variant="info"
+        id="fixed_dismissable"
```
Comment (shmidt-i) [inline packages/core/src/components/DismissableBanner/DismissableBanner.stories.tsx:109]: Can we drop the id here?

**Review by shmidt-i — COMMENTED** [review]
Congratz on the first PR! 🎉

File: packages/core/src/components/DismissableBanner/DismissableBanner.stories.tsx (hunk 4 above)
Comment (freben) [reply packages/core/src/components/DismissableBanner/DismissableBanner.stories.tsx:109]: hm they all have one, i wonder why

File: packages/core/src/components/DismissableBanner/DismissableBanner.tsx [hunk 5]
```diff
@@ -58,9 +67,15 @@ type Props = {
   variant: 'info' | 'error';
   message: ReactNode;
   id: string;
+  fixed?: boolean;
 };
 
-export const DismissableBanner: FC<Props> = ({ variant, message, id }) => {
+export const DismissableBanner: FC<Props> = ({
```
Comment (freben) [inline packages/core/src/components/DismissableBanner/DismissableBanner.tsx:73]: Just a side note since it's not part of your changes, but we [avoid FC](https://github.com/spotify/backstage/blob/master/docs/architecture-decisions/adr006-avoid-react-fc.md). You don't need to change anything here, only informational :)

File: packages/core/src/components/DismissableBanner/DismissableBanner.tsx [hunk 6]
```diff
@@ -88,9 +103,17 @@ export const DismissableBanner: FC<Props> = ({ variant, message, id }) => {
...
+          ? { vertical: 'bottom', horizontal: 'center' }
+          : { vertical: 'top', horizontal: 'center' }
+      }
       open={!dismissedBanners.has(id)}
-      classes={{ root: classes.root }}
+      classes={
+        fixed
+          ? { root: classes.root }
+          : { root: classNames(classes.topPosition, classes.root) }
+      }
```
Comment (freben) [inline packages/core/src/components/DismissableBanner/DismissableBanner.tsx:116]: This could be shortened to `classes={{ root: classNames(classes.root, fixed && classes.topPosition) }}` if you want, since `classNames` skips over anything that's falsy. But it's a matter of taste, yours is arguably clearer to read.

File: packages/core/src/components/DismissableBanner/DismissableBanner.stories.tsx (hunk 4 above)
Comment (samiramkr) [reply packages/core/src/components/DismissableBanner/DismissableBanner.stories.tsx:109]: So you mean I remove the id?

File: packages/core/src/components/DismissableBanner/DismissableBanner.tsx [hunk 7]
```diff
@@ -58,9 +67,15 @@ type Props = {
...
   message: ReactNode;
   id: string;
+  fixed?: boolean;
 };
 
-export const DismissableBanner: FC<Props> = ({ variant, message, id }) => {
+export const DismissableBanner: FC<Props> = ({
+  variant,
+  message,
+  id,
```
[the remark this answers is not in the document]
Comment (samiramkr) [reply packages/core/src/components/DismissableBanner/DismissableBanner.tsx:76]: it was there and it has been used in the body of the component

File: packages/core/src/components/DismissableBanner/DismissableBanner.stories.tsx (hunk 4 above)
Comment (shmidt-i) [reply packages/core/src/components/DismissableBanner/DismissableBanner.stories.tsx:109]: Yeah, that's what I meant, but saw your comment above, let's leave it intact then!

**Comment by benjdlambert** [comment]
@samiramkr it looks like this has some failing tests, could you take a look? :)

**Review by benjdlambert — APPROVED** [review]
Hey @samiramkr - nice job! I approved the stories, so you should be able to go ahead and merge this now
