### PR TITLE
auth-backend: UTF decode the auth response message

### LINKED ISSUE #3275: Character encoding seems off in welcoming banner
The welcome banner at the top does not seem to display ÅÄÖ in usernames correctly. In this case the username comes from a GitHub Enterprise installation through the OAuth2 auth plugin. 

image

It should show those letters with the correct encoding even if the underlying. 

## Current Behavior

Currently it displays my last name as **Ã**

## Possible Solution

Find and use the correct encoding for the welcome plugin. I'm not entirely sure where that would be. 

## Steps to Reproduce

1. Use an OAuth app from GitHub to authenticate
2. Have an Ö in the username 
3. Open the first page of backstage

## Context

It's a mildly annoying error at best, not particularly premium when doing demoes when i cannot change my name in either the github enterprise installation nor backstage. 

## Your Environment

- NodeJS Version (v12): Node v12.19.0
- Operating System and Version (e.g. Ubuntu 14.04): Windows and WSL1 with ubuntu 18.04
- Browser Information: Chrome

### PR DESCRIPTION
**Pull request by freben**
Fixes #3275

### CODE REVIEW

**Comment by O5ten** [comment]
LGTM!

File: plugins/auth-backend/src/lib/flow/authFlowHelpers.ts [hunk 1]
```diff
@@ -31,8 +31,15 @@ export const postMessageResponse = (
 
   // TODO: Make target app origin configurable globally
   const script = `
-    (window.opener || window.parent).postMessage(JSON.parse(atob('${base64Data}')), '${appOrigin}')
-    window.close()
+    var json = atob('${base64Data}');
+    var origin = '${appOrigin}';
+    try {
+      var encoded = Uint8Array.from(json, c => c.codePointAt(0));
```
Comment (Fox32) [inline plugins/auth-backend/src/lib/flow/authFlowHelpers.ts:37]: Another option would be to pass a base64 encoded data: uri to a Blob, but that code is much longer and has the same IE problems... If the current solution works I would stay with it.

But should we add a comment that says why we have this trick in place?

**Review by Fox32 — APPROVED** [review]
👍

File: plugins/auth-backend/src/lib/flow/authFlowHelpers.ts (hunk 1 above)
Comment (freben) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts:37]: Sure, maybe above then, on like 32. Don't have to send it over the wire :) I'll fix

Comment (freben) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: @Fox32 @Rugvip Uh this made me wonder - why don't we just use encode/decodeURIComponent instead that are perfectly aware of non-7-bit chars and are extremely widely supported? Updated the PR accordingly

Comment (Rugvip) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: @freben Because injecting user controlled content into html on a secure domain is super scary and I want to be really far away from any possibilities of injection rather than treading the line. The current implementation with `encodeURIComponent` is broken and imo it's too easy to revert to the mistake even if we fix it. I'd prefer sticking to base64 and decoding though an `UInt8Array` and `TextDecoder`.

Comment (freben) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: In what way is it broken? I didn't get that part.

Comment (freben) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: In terms of

- how could `encodeURIComponent` result in any character that isn't safe to put in the document as we do
- how could `decodeURIComponent` result in a string that somehow breaks `JSON.parse` in a dangerous way
- how could UTF characters be misrepresented in `decodeURIComponent(encodeURIComponent(x))`

Comment (freben) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: Ah haha, I forgot about it not encoding `'` but encoding `"`. So I would still like to use this method but doing `var data = "${data}"`

Comment (Rugvip) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: Yup, but let's not. With that you gonna slap a big comment above it explaining why it is the way it is and why nobody should change it back to `'`. And even with that there's plenty of occasions of comments not being read :grin:. Better just stick to a safer encoding.

Comment (Rugvip) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: This gives you some decent browser support without being very verbose:

```
new TextDecoder().decode(Uint8Array.from(Array.from(atob('8J+Ukg'), c => c.charCodeAt(0))))
```

Comment (freben) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: Yeah that's what the code used to do right before you reviewed, it's updated now with a wall of text accompanying it

File: plugins/auth-backend/src/lib/flow/authFlowHelpers.ts [hunk 2]
```diff
@@ -25,16 +25,43 @@ export const postMessageResponse = (
 ) => {
   const jsonData = JSON.stringify(response);
   const base64Data = Buffer.from(jsonData, 'utf8').toString('base64');
+  const base64Origin = Buffer.from(appOrigin, 'utf8').toString('base64');
```
Comment (freben) [inline plugins/auth-backend/src/lib/flow/authFlowHelpers.ts:28]: SHOULD not be necessary, but you know - it's ultimately user controllable in a way and it doesn't hurt to be thorough

File: plugins/auth-backend/src/lib/flow/authFlowHelpers.ts (hunk 1 above)
Comment (Rugvip) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: I avoided `Uint8Array.from` because it doesn't have as broad support as `Array.from`

File: plugins/auth-backend/src/lib/flow/authFlowHelpers.ts (hunk 2 above)
Comment (Rugvip) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts:28]: Sure xP, It's not user controllable though, only controllable by whoever has access to config, and with that usually the code itself anyway :p

Doesn't hurt though

File: plugins/auth-backend/src/lib/flow/authFlowHelpers.ts (hunk 1 above)
Comment (Rugvip) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: Uh derp, except that I didn't, this would be the correct one:

```
new TextDecoder().decode(new Uint8Array(Array.from(atob('8J+Ukg'), c => c.charCodeAt(0))))
```

Comment (freben) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: Ah I didn't know about the `from` support - updated to use `Array.from`

Comment (freben) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: Still kinda wondering if `encodeURIComponent(x).replace(/'/g, '%27')` wouldn't have been way better and easier and well supported and ... :)

File: plugins/auth-backend/src/lib/flow/authFlowHelpers.ts [hunk 3]
```diff
@@ -25,16 +25,43 @@ export const postMessageResponse = (
...
+      json = new TextDecoder().decode(encoded);
+    } catch (e) {
+    }
+    (window.opener || window.parent).postMessage(JSON.parse(json), origin);
+    window.close();
   `;
   const hash = crypto.createHash('sha256').update(script).digest('base64');
+
+  res.setHeader('Content-Type', 'text/html');
+  res.setHeader('X-Frame-Options', 'sameorigin');
```
Comment (Rugvip) [inline plugins/auth-backend/src/lib/flow/authFlowHelpers.ts:64]: Setting this to `sameorigin` kinda defeats the purpose of being able to use this in an iframe if desired :p. Any particular reason you wanted to do it?

Comment (freben) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts:64]: I don't, this is just moved code from above (to keep all the `res.X` methods together)

Comment (freben) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts:64]: Shall I remove it as part of this PR? I assumed it was added for good reason

File: plugins/auth-backend/src/lib/flow/authFlowHelpers.ts (hunk 1 above)
Comment (Rugvip) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: ... scarier, but do it if you want to. I can't think of anything that could go wrong with it right now

File: plugins/auth-backend/src/lib/flow/authFlowHelpers.ts (hunk 3 above)
Comment (Rugvip) [reply plugins/auth-backend/src/lib/flow/authFlowHelpers.ts]: Ah alright, nah keep it and we can see if we wanna change the behaviour in the future. I think the proper way to do it would be to explicitly allow the app origin but no other origins.

**Comment by freben** [comment]
Umkay, all fixed!

**Review by Rugvip — APPROVED** [review]
