### PR TITLE
Fix Sequence component not switching background on dark mode

### LINKED ISSUE #650: Sequence component does not work in dark mode
## Expected Behavior

All components should work in dark mode. 

## Current Behavior

9F09BA34-5AD5-4293-B910-58F8C7DCDFC1

## Steps to Reproduce

1. Step 1
2. Step 2
3. ...

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:

### PR DESCRIPTION
**Pull request by elchocarrero**
## Hey, I just made a Pull Request!

Fixes sequence dark mode having a white background. I also took the liberty to add some vertical padding to the content. I think it looks a bit less crowded.

Fixes #650 :D
#### :heavy_check_mark: Checklist

- [X] All tests are passing `yarn test`
- [X] Screenshots attached (for UI changes)

Screenshot from 2020-04-26 00-40-16

Screenshot from 2020-04-26 00-41-03

- [ ] Relevant documentation updated
- [ ] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

### CODE REVIEW

File: packages/core/src/components/Sequence/Sequence.tsx [hunk 1]
```diff
@@ -26,8 +26,7 @@ import SequenceFooter from './SequenceFooter';
 
 const useStyles = makeStyles((theme: any) => ({
   content: {
-    padding: theme.spacing(0, 4, 4, 4),
-    backgroundColor: 'white',
```
Comment (OrkoHunter) [inline packages/core/src/components/Sequence/Sequence.tsx:30]: 👍👍👍

**Review by stefanalund — APPROVED** [review]

**Comment by wesleyyee** [comment]
The reason i didn't remove this is that it looks broken on light mode.
