### PR TITLE
cli: add versions:check and versions:bump

### LINKED ISSUE #3185: Mismatched Backstage versions cause missing API context
The `@backstage/core-api` package creates a React Context for the `ApiHolder` used to retrieve registered APIs.

If a Backstage installation uses mismatched plugin versions - e.g. `0.1.1-alpha.24` in the app package, and `0.1.1-alpha.25` in an internal plugin - calling `useApi` throws an error:

```
index.esm.js?143a:44 Uncaught Error: No ApiProvider available in react context
    at useApiHolder (index.esm.js?143a:44)
    at useApi (index.esm.js?143a:49)
    at ConfigProvider (index.esm.js?be0f:278)
    at renderWithHooks (react-dom.development.js?f354:14826)
    at mountIndeterminateComponent (react-dom.development.js?f354:17506)
    at beginWork (react-dom.development.js?f354:18630)
    at HTMLUnknownElement.callCallback (react-dom.development.js?f354:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?f354:238)
    at invokeGuardedCallback (react-dom.development.js?f354:293)
    at beginWork$1 (react-dom.development.js?f354:23235)
```

I suspect this is due to how mismatched dependencies are handled by yarn workspaces in a monorepo. If dependency versions match, the dependency is hoisted to the root `node_modules` folder and can be referenced by all sub-packages. If there is a discrepancy between dependency versions from different sub-packages, the appropriate version is installed in a `node_modules` folder for each sub-package and not in the root `node_modules` folder.

The effect is that the `ApiHolder` React Context is created separately in each sub-package, and the plugin attempting to load an API registered in the `app` package does not find the referentially-equivalent ApiHolder context it's looking for, as it's referencing the context from the plugin's `node_modules` copy.

## Expected Behavior

The internal plugin can successfully call `useApi` to find an API registered in the `app` package.

## Current Behavior

Error above.

## Possible Solution

@Rugvip points out that this is a potential problem for any monorepo, e.g. react-router. So there may be prior art in dealing with this situation. Perhaps a central configuration for @backstage package versions that enforces bumping all packages at the same time.

## Steps to Reproduce

1. npx @backstage/create-app
2. Create a new plugin package that has @backstage/core 0.1.1-alpha.{current-1} as a dependency
3. Call useApi from this plugin package

## Context

Companies (including Spotify) that create internal Backstage plugins may inadvertently have mismatched @backstage package versions that cause confusing ApiHolder errors. This means that updating a @backstage package in one part of the app will most likely necessitate updating the package versions everywhere in the app. This is brittle and easy to break accidentally.

### PR DESCRIPTION
**Pull request by Rugvip**
## Hey, I just made a Pull Request!

Adds `backstage-cli versions:bump` and `backstage-cli versions:check`, which allow users to bump `@backstage` packages to the latest versions, and remove duplicates.

The bump commands will pull down the latest version of each `@backstage` package and then run a deduplication. The idea is that this command can be used to easily stay on top of the latest releases without having to manually sift though `package.json`s. There's currently no way to select which weekly release of the packages to use, it will always use the latest release. The metadata returned from npm contains enough information about the releases that it should be possible to add that if we want to.

The check command will detect duplicates of the `@backstage` packages and warn the user. If the `--fix` flag is provided, it will act like `yarn-deduplicate` and get rid of any duplicates that can be removed while staying within the requested version range. It will also warn about packages that can't be deduplicated automatically, and exit with an error if any of those packages are known to not function if there are duplicates, such as `@backstage/core`.

Fixes #3185, although will likely leave this undocumented until after the next release. I did some local verification but want to make sure this works properly with a released version too.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by freben** [comment]
Amaze!

File: packages/cli/src/commands/versions/lint.ts [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+    'The following packages can be deduplicated by updating dependencies in package.json',
+    e => `  ${e.name} @ ${e.oldRange} should be changed to ${e.newRange}`,
+  );
+
+  if (!success) {
+    throw new Error('Failed versioning check');
+  }
+};
+
+function logArray<T>(arr: T[], header: string, each: (item: T) => void) {
```
Comment (freben) [inline packages/cli/src/commands/versions/lint.ts:100]: `=> string`

File: packages/cli/src/lib/versioning/Lockfile.ts [hunk 2]
```diff
@@ -0,0 +1,253 @@
...
+
+/** Entries that can be deduplicated by bumping to an existing higher version */
+type AnalyzeResultNewVersion = {
+  name: string;
+  range: string;
+  oldVersion: string;
+  newVersion: string;
+};
+
+/** Entries that {would need a dependency update in package.json to be deduplicated */
```
Comment (freben) [inline packages/cli/src/lib/versioning/Lockfile.ts:54]: Extra curly brace

File: packages/cli/src/lib/versioning/Lockfile.ts [hunk 3]
```diff
@@ -0,0 +1,253 @@
...
+type AnalyzeResultNewRange = {
```
Comment (freben) [inline packages/cli/src/lib/versioning/Lockfile.ts:55]: I guess this was the name i had the hardest to understand intuitively what it meant

File: packages/cli/src/lib/versioning/Lockfile.ts [hunk 4]
```diff
@@ -0,0 +1,253 @@
...
+    const lockfile = parseLockfile(lockfileContents);
+    if (lockfile.type !== 'success') {
+      throw new Error(`Failed yarn.lock parse with ${lockfile.type}`);
+    }
+
+    const data = lockfile.object as LockfileData;
+    const packages = new Map<string, LockfileQueryEntry[]>();
+
+    for (const [key, value] of Object.entries(data)) {
+      const [, name, range] = ENTRY_PATTERN.exec(key) ?? [];
```
Comment (freben) [inline packages/cli/src/lib/versioning/Lockfile.ts:81]: This could be several comma separated entries right?

Doesn't the library export a function to parse these?

File: packages/cli/src/lib/versioning/Lockfile.ts [hunk 5]
```diff
@@ -0,0 +1,253 @@
...
+      newVersions: [],
+      newRanges: [],
+    };
+
+    for (const [name, allEntries] of this.packages) {
+      if (filter && !filter(name)) {
+        continue;
+      }
+
+      // Get rid of an signal any invalid ranges upfront
```
Comment (freben) [inline packages/cli/src/lib/versioning/Lockfile.ts:121]:
```suggestion
      // Get rid of and signal any invalid ranges upfront
```

File: packages/cli/src/lib/versioning/Lockfile.ts [hunk 6]
```diff
@@ -0,0 +1,253 @@
...
+      const invalid = allEntries.filter(e => !semver.validRange(e.range));
+      result.invalidRanges.push(
+        ...invalid.map(({ range }) => ({ name, range })),
+      );
+
+      // Grab all valid entries, if there isn't at least 2 different valid ones we're done
```
Comment (freben) [inline packages/cli/src/lib/versioning/Lockfile.ts:127]:
```suggestion
      // Grab all valid entries, if there aren't at least 2 different valid ones we're done
```

File: packages/cli/src/lib/versioning/Lockfile.ts [hunk 7]
```diff
@@ -0,0 +1,253 @@
...
+            range,
+            newVersion: acceptedVersion,
+            oldVersion: version,
+          });
+        }
+
+        acceptedVersions.add(acceptedVersion);
+      }
+
+      // If all ranges where able to accept the same version, we're done
```
Comment (freben) [inline packages/cli/src/lib/versioning/Lockfile.ts:166]:
```suggestion
      // If all ranges were able to accept the same version, we're done
```

File: packages/cli/src/lib/versioning/Lockfile.ts [hunk 8]
```diff
@@ -0,0 +1,253 @@
...
+        ([q, e]) => q.startsWith(`${name}@`) && e.version === newVersion,
+      );
+      if (!matchingEntry) {
+        throw new Error(
+          `No matching entry found for ${name} at version ${newVersion}`,
+        );
+      }
+      this.data[query] = matchingEntry[1];
+
+      // Update out internal data structure
```
Comment (freben) [inline packages/cli/src/lib/versioning/Lockfile.ts:232]:
```suggestion
      // Update our internal data structure
```

File: packages/cli/src/lib/versioning/packages.test.ts [hunk 9]
```diff
@@ -0,0 +1,109 @@
...
+  });
+});
+
+describe('mapDependencies', () => {
+  afterEach(() => {
+    mockFs.restore();
+    jest.resetAllMocks();
+  });
+
+  it('should derp', async () => {
```
Comment (freben) [inline packages/cli/src/lib/versioning/packages.test.ts:50]:
```suggestion
  it('should herpaderp', async () => {
```

File: packages/cli/src/lib/versioning/packages.ts [hunk 10]
```diff
@@ -0,0 +1,90 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+import { runPlain } from '../../lib/run';
+import { paths } from '../../lib/paths';
+
+const PREFIX = '@backstage';
+
+const DEP_TYPES = [
```
Comment (freben) [inline packages/cli/src/lib/versioning/packages.ts:22]: Repeated. But that's OK I guess

**Review by freben — APPROVED** [review]
Cool stuff 👌

File: packages/cli/src/lib/versioning/Lockfile.ts (hunk 4 above)
Comment (Rugvip) [reply packages/cli/src/lib/versioning/Lockfile.ts:81]: It splits the comma separated entries for you, but the key you get is still of the form `<name>@<range>`

File: packages/cli/src/lib/versioning/packages.ts (hunk 10 above)
Comment (Rugvip) [reply packages/cli/src/lib/versioning/packages.ts:22]: Yeah attempted a refactor to split out the other usage of this too, but wasn't worth it

File: packages/cli/src/commands/versions/bump.ts [hunk 11]
```diff
@@ -0,0 +1,162 @@
...
+  }
+
+  if (result.newRanges.length > 0) {
+    throw new Error(
+      `Version bump failed for ${result.newRanges.map(i => i.name).join(', ')}`,
+    );
+  }
+};
+
+async function workerThreads<T>(
```
[the remark this answers is not in the document]
Comment (Rugvip) [reply packages/cli/src/commands/versions/bump.ts:140]: Eh, code with p-limit ends up being a lot uglier, and it's another dep :p

File: packages/cli/src/lib/versioning/Lockfile.ts (hunk 3 above)
Comment (Rugvip) [reply packages/cli/src/lib/versioning/Lockfile.ts:55]: Any clear replacement? ^_> In general I'm using `range` to refer to various version ranges, so new range would mean that the dependency version range has to be replaced rather than the version in the lockfile. Could be something like `newDependencyVersions`

Comment (freben) [reply packages/cli/src/lib/versioning/Lockfile.ts:55]: Nah. It's just that as in this instance it's used for actual "failures", I was looking for some expression of "needs package json update" or so - but the analysis is general and not just for this context so

**Comment by dtuite** [comment]
I can't remember if the CLI works outside the monorepo or not but, if it does, this is going to help us A LOT.

**Comment by benjdlambert** [comment]
> I can't remember if the CLI works outside the monorepo or not but, if it does, this is going to help us A LOT.

Yeah it should work in any package I think? @Rugvip

**Comment by Rugvip** [comment]
Yep!

**Review by benjdlambert — APPROVED** [review]

**Comment by dtuite** [comment]
We tried this out on a few plugins and found it worked well. 👍

**Comment by ahrberg** [comment]
@Rugvip how about private backstage plugins not published to npm (or other artifactory) just stored in the monorepo `/plugins/`? Our private plugins use the same naming convention `@backstage/my-plugin` as other backstage plugins. This seams to break the `version:bump` since the plugin is not published and the `yarn info` fails. Any thoughts if private plugins should be named something else than `@backstage/*` or if this could be fixed?

**Comment by Rugvip** [comment]
@ahrberg Ah alright so couple things to unpack there. We generally recommend `@internal` as the scope for internal packages. Those internal packages ofc won't need a bump from `version:bump` though as they're part of the monorepo.

Regarding handling of internal `@backstage` packages and `yarn info` failing, I think we can safely silently ignore any package that isn't available on NPM. Alright with creating a PR/issue for that?

**Comment by ahrberg** [comment]
@Rugvip I made a [PR](https://github.com/backstage/backstage/pull/4027), please check if the solution is of interest. I guess you can solve this in many ways.
