### PR TITLE
packages/cli: target modern browsers and switch output to module + dynamic graphiql import

### LINKED ISSUE #630: Dynamic imports don't work
## Expected Behavior

It should be possible to use dynamic imports, i.e. `import('my-module').then(module => ...)`

## Current Behavior

Rollup doesn't seem to generate correct output for import statements. It ends up removing the import function with this:

```
() => new Promise(function (resolve) { resolve(_interopNamespace(require('my-module'))); })
```

## Possible Solution

Changing the rollup output format to 'module' seems to produce correct code. We might want to switch to that and make sure it works with the rest of the build.

## Steps to Reproduce

Try to use a dynamic import in a plugin.

## Context

Dynamic imports is a huge part of keeping initial page load fast, it's best to have it working early on so that all plugins can use it.

### PR DESCRIPTION
**Pull request by Rugvip**
Fixes #630 and hopefully speeds up builds and execution a bit 🎉

As far as I can tell it doesn't break anything x)

ES2019 syntax has full support in latest versions of Chrome, Firefox and Safari, so should target that in the final bundle too imo.

ES2020 isn't supported by rollup yet, so can't use that

### CODE REVIEW

File: plugins/graphiql/src/components/GraphiQLBrowser/GraphiQLBrowser.tsx [hunk 1]
```diff
@@ -14,14 +14,16 @@
  * limitations under the License.
  */
 
-import React, { FC, useState } from 'react';
+import React, { FC, useState, Suspense } from 'react';
```
Comment (freben) [inline plugins/graphiql/src/components/GraphiQLBrowser/GraphiQLBrowser.tsx:17]: Whoa! 🎉 the future is here

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
And the es2019 syntax works on latest mobile browsers too?

**Comment by Rugvip** [comment]
@freben yeah support is pretty much the same up until es2020, I think iOS Safari is just behind in releases. For CSS and APIs I think it can differ from Desktop Safari, but afaik ES support is the same.

**Comment by Rugvip** [comment]
❤️ create-app e2e tests

Build issue was that jest couldn't load the es6 modules from node_modules
