### PR TITLE
fix: elastic search for missing or no indexes

### LINKED ISSUE #16423: 🐛 Bug Report: search collator run should result an index to ElasticSearch even if no documents are emitted
### 📜 Description

When you have a search collator that does not emit documents at all then [search-backend-module-elasticsearch](https://github.com/backstage/backstage/tree/master/plugins/search-backend-module-elasticsearch) does not produce index and alias for it.

Normally this is not an issue but if you select specific type with give Type filter given in the advanced search view:

image

[https://demo.backstage.io/search?query=&types%5B%5D=techdocs](https://demo.backstage.io/search?query=&types%5B%5D=techdocs)

_Or if you have permissions enabled that causes all aliases/indexes to be expanded in search query which in turn causes "All" filter to fail._

Then you run into an error that is cause by the fact that there is no index created.

### 👍 Expected behavior

There should be a empty index created and related alias for it.

### 👎 Actual Behavior with Screenshots

Search API returns:

```
Request failed with status 500 Missing index for software-catalog__search. This means there are no documents to search through.
```

### 👟 Reproduction steps

Sorry, I didn't have time to prepare ready-to-use repository with all the details filled in but you could end up into such situation by:

1. Enable QETA plugin (https://github.com/drodil/backstage-plugin-qeta)
3. Enable Elastic Search plugin
4. (Enable permissions for search if you want to have an error with "All" filter too!)
5. See how search query catastrophically fails due to missing index  

### 📃 Provide the context for the Bug.

I think Q&A plugin (https://github.com/drodil/backstage-plugin-qeta) is perfect example of a search collator that does not emit any documents and it's still valid run. How networks issues & other errors are communicated via collator API is different thing, but maybe, just maybe, this is related to another issue that was causing orphan indexes: https://github.com/backstage/backstage/issues/14810

### 🖥️ Your Environment

Backend issue, so my browser does not matter. Node 16 in use.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

this occurs when the index is missing during the search for example the TechDocs provider creates the index when initiating, but if there's no docs to index, it removes the index but still tries to search from it.

fixes #16423

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by drodil** [comment]
Not stale, waiting for review

File: plugins/search-backend-module-elasticsearch/src/engines/ElasticSearchClientWrapper.ts [hunk 1]
```diff
@@ -91,12 +91,23 @@ export class ElasticSearchClientWrapper {
...
+    const searchOptions = {
+      ignore_unavailable: true,
+      allow_no_indices: true,
+    };
+
     if (this.openSearchClient) {
-      return this.openSearchClient.search(options);
+      return this.openSearchClient.search({
+        ...options,
+        ...searchOptions,
```
Comment (aitherios) [inline plugins/search-backend-module-elasticsearch/src/engines/ElasticSearchClientWrapper.ts:102]: Hi @drodil ! Thank you for this PR.
It first glance, I would argue that `options` should override `searchOptions`:
```
this.openSearchClient.search({
        ...searchOptions,
        ...options,
})
```

Did you had some use case in mind when you wrote it the other way?

**Review by aitherios — APPROVED** [review]
