### PR TITLE
Fix settings page not displaying sing in properly

### LINKED ISSUE #13091: Losing Sign-in on every refresh
We are using two sign in providers - Microsoft & Github ; Microsoft is our primary where we validate users and github  sign for working with templates where  we have git based scaffolder actions .  On every refresh - we are loosing github sign in - here is my auth.ts.   All preloaded groups  are populated with the microsoft sign in name, so we decided add github name as new entity to the user 

```
providerFactories: {
      ...defaultAuthProviderFactories,
      microsoft: providers.microsoft.create({
        signIn: {
          resolver: async ({ profile }, ctx) => {
            if (!profile.email) {
              throw new Error(
                'Login failed, user profile does not contain an email',
              );
            }
            const [name, domain] = profile.email.split('@');
            if (domain !== '*****************') {
              throw new Error(
                `Login failed, this email ${profile.email} does not belong to the expected domain`,
              );
            }
            return ctx.signInWithCatalogUser({
              entityRef: { name },
            });
          },
        },
      }),
      github: providers.github.create({
        signIn: {
          resolver: async ({ profile }, ctx) => {
            if (!profile.email) {
              throw new Error(
                'Login failed, user profile does not contain an email',
              );
            }
            const [localPart] = profile.email.split('@');
            const userEntity = stringifyEntityRef({
              kind: 'User',
              name: localPart,
              namespace: DEFAULT_NAMESPACE,
            });
            return ctx.issueToken({
              claims: {
                sub: userEntity,
                ent: [userEntity],
              },
            });
          },
        },
      }),
    },
  });

```

github-sign-in-issue

<hr>

Backend  Package.json : 

    "@backstage/plugin-app-backend": "^0.3.33",
    "@backstage/plugin-auth-backend": "^0.14.1",
    "@backstage/plugin-auth-node": "^0.2.2",

### PR DESCRIPTION
**Pull request by VladMasarik**
Resolves #13091
When the user has two providers, the settings page checks only for one, and the others are considered signed out, although the user is signed in properly.

This fix uses `getProfile` to check on whether the user is signed in, instead of the session information, as per what was suggested in the issue.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by VladMasarik** [comment]
This is only the most bare bones fix I could find. Let me know your thoughts, especially whether I am going some way we don't want to. I have not tested yet how the logic would behave with two providers yet, which is kind of the main thing. But hey, it didn't crash yet!
image

File: plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx [hunk 1]
```diff
@@ -45,17 +46,21 @@ export const ProviderSettingsItem = ({
...
-      .sessionState$()
-      .subscribe((sessionState: SessionState) => {
-        if (!didCancel) {
-          setSignedIn(sessionState === SessionState.SignedIn);
-        }
-      });
+    const subscription = api.sessionState$().subscribe(() => {
+      if (!didCancel) {
+        api
+          .getProfile({ optional: false })
```
Comment (freben) [inline plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx:57]: This was meant to be true as per the issue.

File: plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx [hunk 2]
```diff
@@ -45,17 +46,21 @@ export const ProviderSettingsItem = ({
...
+          .then((profile: ProfileInfo | undefined) => {
+            setSignedIn(profile !== undefined);
```
Comment (freben) [inline plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx:59]: You should probably still check the sessionState out of the observable for this. If that's signed in, we should probably set this state to true no matter what.

File: plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx [hunk 3]
```diff
@@ -72,7 +77,9 @@ export const ProviderSettingsItem = ({
         primary={title}
         secondary={
           <Tooltip placement="top" arrow title={description}>
-            <span>{description}</span>
+            <span>
+              {description}. Signed in as {profileEmail}
```
Comment (freben) [inline plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx:81]: I'd prefer if the profile info was on a row of its own, perhaps standing out a little using colour or boldness or something. Could also have more than just the email (do some smart string building based on what the provided parts of the profile actually were, perhaps in a helper function).

Maybe this could be something like

```tsx
<Grid container spacing={3} alignItems="stretch">
  <Grid item xs={12} md={6}>
    {description}
  </Grid>

  <Grid item xs={12} md={6}>
    {profileInfo)
  </Grid>
</Grid>
```

or something like that. Completely untested, just an idea :) Then the profile info would be between the description and the button, and could even contain a div with several lines of stuff in it if you wanted

**Review by freben — COMMENTED** [review]
Remember that whenever you make a change, you must make a changeset that describes the update, otherwise the changes won't be released.

File: plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx (hunk 3 above)
Comment (Rugvip) [reply plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx:81]: Would say that we want to display all the information as well if it's available. Display name, email, and avatar. I think it would be fine to leave that for a later PR too though

File: plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx (hunk 1 above)
Comment (VladMasarik) [reply plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx:57]: yeah, not sure why I did that

File: plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx (hunk 2 above)
Comment (VladMasarik) [reply plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx:59]: okay, is there any reason that makes it a good thing? purely from personal interest of why it would be better

**Comment by VladMasarik** [comment]
I also tested two providers logged in, and only one.

File: plugins/user-settings/src/components/AuthProviders/ProviderSettingsAvatar.tsx [hunk 4]
```diff
@@ -0,0 +1,38 @@
+/*
```
[the remark this answers is not in the document]
Comment (freben) [reply plugins/user-settings/src/components/AuthProviders/ProviderSettingsAvatar.tsx:1]: This is required by the linter; it's part of the license of the repository and is not possible to remove. You usually have the year set to the current year for new files and then just leave it after that.

[the remark this answers is not in the document]
Comment (VladMasarik) [reply plugins/user-settings/src/components/AuthProviders/ProviderSettingsAvatar.tsx:1]: ah thanks

File: .changeset/soft-falcons-love.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+'@backstage/plugin-user-settings': patch
```
Comment (freben) [inline .changeset/soft-falcons-love.md:2]: This actually constitutes a breaking change to the API surface. You will want to set this to `minor`, and running `yarn build:api-reports` to get an updated api report to add to the pull request (see the failing build log)

File: plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx [hunk 6]
```diff
@@ -50,7 +57,16 @@ export const ProviderSettingsItem = (props: {
...
-          setSignedIn(sessionState === SessionState.SignedIn);
+          api
+            .getProfile({ optional: true })
+            .then((profileResponse: ProfileInfo | undefined) => {
+              if (sessionState === SessionState.SignedIn) {
+                setSignedIn(true);
+              } else {
+                setSignedIn(profileResponse !== undefined);
+              }
+              setProfile(profileResponse ?? {});
```
Comment (freben) [inline plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx:68]: this should probably be

```ts
if (sessionState === SessionState.SignedIn) {
  setSignedIn(true);
}
if (profileResponse) {
    setProfile(profileResponse);
}
```

no need to re-set the profile if nothing was given, and I'm not sure that ONLY getting a profile response should constitute being signed in.

File: plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx [hunk 7]
```diff
@@ -69,7 +85,32 @@ export const ProviderSettingsItem = (props: {
...
+                        color="textPrimary"
+                        gutterBottom
+                      >
+                        {profile.displayName}
+                      </Typography>
+                      <Typography variant="body2" color="textSecondary">
+                        {profile.email}
+                      </Typography>
+                      <Typography variant="body2" color="textSecondary">
+                        {description}
```
Comment (freben) [inline plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx:107]: Maybe the description could be in a row of its own (`<Grid item xs={12}>`) and then the whole avatar and stuff on the row below?

File: plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx (hunk 6 above)
Comment (VladMasarik) [reply plugins/user-settings/src/components/AuthProviders/ProviderSettingsItem.tsx:68]: ahh good suggestion, I completely missed that

> I'm not sure that ONLY getting a profile response should constitute being signed in.

Is this just a thought, or is that a request for change? I would agree, and my assumption would be that there would be a `isSignedIn()` function, but I believe that is the current shortcoming that we are trying to solve, ie. we can check whether the user is signed in, only on one provider. I checked whether there would be some other ways to check whether user is logged in, but all of them create a pop-up for the user to log in if they are not, which I guess would be annoying.

File: .changeset/soft-falcons-love.md (hunk 5 above)
Comment (VladMasarik) [reply .changeset/soft-falcons-love.md:2]: I changed it to minor, but I dont know how to handle the changeset description. 

AFAIK there is no "breaking" change that has to be fixed. I added the `ProfileInfoApi` into `apiRef: ApiRef<ProfileInfoApi & SessionApi>;`, but I have no idea whether the users have to pass something extra into the `apiRef` or whether anyone who creates a signin provider has to implement the `ProfileInfoApi`. So I am not sure what I should write into the description, and how to explain what needs to be changed.

**Review by freben — APPROVED** [review]
Alright, pushed a small tweak mainly to the changeset. Let's ship it once it goes green!
