### PR TITLE
Conditionally add Sentry widget to component page

### LINKED ISSUE #2257: [Service catalogue] Sentry integration showing no issues or only mock data
## Expected Behavior

When using the Sentry plugin, I expect to see the issues related to the selected component in the service catalogue.
In the case that we don't know the Sentry project key for the component, I expect the Sentry widget to not show.

## Current Behavior

Currently, with the Sentry plugin installed, we always show the widget. If the plugin isn't configured, it shows mock data for all components. If it is configured, it always tries to load data for a dummy project named `sample-sentry-project-id`, which means the list of issues is empty. 
image

This seems to have changed with #2246 in which the widget was removed altogether.

## Possible Solution

Allow components or, more generally, items in the service catalogue to specify their corresponding Sentry project ID through an annotation. Following the style of other plugins, I'd suggest using `backstage.io/sentry-project-id` as the key.

## Steps to Reproduce

0. Follow the steps to [run Backstage locally](https://backstage.io/docs/getting-started/)
1. Configure the Sentry plugin with an API key by setting the `SENTRY_TOKEN` environment variable
2. Navigate to any component in the service catalogue
3. Observe the empty list of Sentry issues and a request to http://localhost:7000/sentry/api/0/projects//spotify/sample-sentry-project-id/issues/?statsFor=24h 

## Context

The sentry project ID was hard-coded in the EntityPageOverview and eventually removed altogether in #2246. We should add it back if the component supports it. I'm happy to submit a PR to add 

## Your Environment

- NodeJS Version (v12): 12.18.2
- Operating System and Version (e.g. Ubuntu 14.04): Mac OS 10.15.6
- Browser Information: Firefox 80.0.1

### PR DESCRIPTION
**Pull request by muffix**
## Hey, I just made a Pull Request!

This adds the Sentry widget back to the component page (from which it
was removed in #2246) if the component declares its own Sentry project
ID in the annotation named backstage.io/sentry-project-id. The widget
is hidden otherwise.

Previous to #2246, the widget was just displaying an empty list because
it was trying to load data for a hardcoded project name of
sample-sentry-project-id.

Fixes #2257

#### :heavy_check_mark: Checklist

- [x] All tests are passing `yarn test`
- [x] Screenshots attached (for UI changes)
- [ ] Relevant documentation updated
- [x] Prettier run on changed files
- [ ] Tests added for new functionality
- [ ] Regression tests added for bug fixes

## EDIT
After some discussion, this now adds a new Sentry tab instead of a widget to the component page.

image

### CODE REVIEW

File: plugins/catalog/src/components/EntityPageOverview/EntityPageOverview.tsx [hunk 1]
```diff
@@ -51,6 +52,16 @@ export const EntityPageOverview: FC<{ entity: Entity }> = ({ entity }) => {
             <GithubActionsWidget entity={entity} branch="master" />
           </Grid>
         )}
+        {entity.metadata?.annotations?.['backstage.io/sentry-project-id'] && (
```
Comment (muffix) [inline plugins/catalog/src/components/EntityPageOverview/EntityPageOverview.tsx:55]: Happy to change the naming of the annotation to something more suitable if required. Is there a good place to document the annotations?

**Review by Rugvip — APPROVED** [review]
Sure, thanks!

Noting that this is gonna need more changes to apps created with `create-app` if they want to use sentry, as that part was removed in https://github.com/spotify/backstage/pull/2239. We're not looking to revert that right now though.

Overall we're about to flip around the responsibility for populating the catalog pages with plugins, see https://github.com/spotify/backstage/pull/2076

**Comment by muffix** [comment]
#2076 looks great, thanks. Happy to submit an update again then. 👍

**Comment by muffix** [comment]
Resolved the merge conflicts. Is there anything else you'd like me to do @Rugvip?

File: plugins/catalog/src/components/EntityPageOverview/EntityPageOverview.tsx (hunk 1 above)
Comment (andrewthauer) [reply plugins/catalog/src/components/EntityPageOverview/EntityPageOverview.tsx:56]: I was under the impression this might be 'sentry.com/project-id'? I recall seeing the usage of 'github.com/project-slug' elsewhere.

**Comment by shmidt-i** [comment]
@muffix since #2076 was merged the EntityPageOverview in plugin-catalog's src doesn't really shows up anymore, would be awesome if you can move the code into `packages/app/src/components/catalog/EntityPage.tsx`😉

File: plugins/catalog/src/components/EntityPageOverview/EntityPageOverview.tsx (hunk 1 above)
Comment (Rugvip) [reply plugins/catalog/src/components/EntityPageOverview/EntityPageOverview.tsx:56]: Maybe not exactly that though https://www.sentry.com/ 😅 

`sentry.io/project-id`, sentry.io

Comment (freben) [reply plugins/catalog/src/components/EntityPageOverview/EntityPageOverview.tsx:56]: @muffix are you up to changing it to that? ^ also below. Or to break it out into a separate variable `const sentryProjectId = entity.metadata?.annotations?.['sentry.io/project-id']` that may or may not be undefined, to avoid the repetition

Comment (freben) [reply plugins/catalog/src/components/EntityPageOverview/EntityPageOverview.tsx:56]: Hang on, just checking - the API lists this parameter as project slug, not id `https://docs.sentry.io/api/projects/get-project-details/`, should it really be named `sentry.io/project-slug` instead?

Comment (freben) [reply plugins/catalog/src/components/EntityPageOverview/EntityPageOverview.tsx:56]: Uh but then in other places they do use the opaque ID instead https://docs.sentry.io/api/pagination/ - are both supported?

Comment (freben) [reply plugins/catalog/src/components/EntityPageOverview/EntityPageOverview.tsx:56]: But I'm going to go with the hypothesis that slug is the better name, and even if both id and slug can be passed there, users will prefer to put the more usable/understandable slug in there anyway.

**Comment by muffix** [comment]
Thanks for the feedback @shmidt-i, @andrewthauer, @freben. I created a router for the Sentry plugin and added it to the entity page. 

Is there a better way to hide the tab entirely if Sentry isn't configured at all? It only makes sense if Sentry is generally functional (i.e. has an API key and an organisation defined).

I can see two options: 
We could either have a Sentry config check in `packages/app/src/components/catalog/EntityPage.tsx` and leave the warning on the tab in case the annotation is missing.
Alternatively, we could hide the tab on a per-entity basis if the annotation isn't defined (e.g. by exporting `isPluginApplicableToEntity()` from the plugin). With this option, it'd be less obvious to the user what went wrong, though.

Happy to add hiding the tab in a different PR/issue, though, if we don't want this one to grow arms and legs. What do you think?

**Comment by freben** [comment]
Yep, leave that for the future.

Internally, we have often made tabs semantic rather than named after a plugin. You would have a tab named "Monitoring" rather than "Grafana", "CI/CD" rather than "GitHub Actions". So hiding tabs hasn't really been as common as you would think. Plus, if the tab is hidden, you lose the possibility of having an informative empty-state, which tells the user "You seem to not have configured this yet, go here for documentation on how to get started" or similar. So from a UX perspective, it's often desirable to not entirely hide things - it generally just surprises the user and offers no guidance. Sometimes it is appropriate, for sure - but we may want to solve it differently for this particular case.

File: plugins/sentry/src/components/Router.tsx [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+import { Entity } from '@backstage/catalog-model';
+import { Routes, Route } from 'react-router';
+import { WarningPanel } from '@backstage/core';
+import { SentryPluginWidget } from './SentryPluginWidget/SentryPluginWidget';
+
+const SENTRY_ANNOTATION = 'sentry.io/project-id';
+
+const isPluginApplicableToEntity = (entity: Entity) =>
+  Boolean(entity.metadata.annotations?.[SENTRY_ANNOTATION]) &&
+  entity.metadata.annotations?.[SENTRY_ANNOTATION] !== '';
```
Comment (freben) [inline plugins/sentry/src/components/Router.tsx:26]: The Boolean actually covers the empty string (an empty string is falsy) - you should skip everything after `&&`

File: plugins/sentry/src/components/Router.tsx [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+import React from 'react';
+import { Entity } from '@backstage/catalog-model';
+import { Routes, Route } from 'react-router';
+import { WarningPanel } from '@backstage/core';
+import { SentryPluginWidget } from './SentryPluginWidget/SentryPluginWidget';
+
+const SENTRY_ANNOTATION = 'sentry.io/project-id';
```
Comment (freben) [inline plugins/sentry/src/components/Router.tsx:22]: so final thing - do name it `slug` instead of `id`. After that, I am more than happy to merge!

File: plugins/sentry/src/components/Router.tsx [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+
+const isPluginApplicableToEntity = (entity: Entity) =>
+  Boolean(entity.metadata.annotations?.[SENTRY_ANNOTATION]) &&
+  entity.metadata.annotations?.[SENTRY_ANNOTATION] !== '';
+
+export const Router = ({ entity }: { entity: Entity }) =>
+  !isPluginApplicableToEntity(entity) ? (
+    <WarningPanel title="Sentry plugin:">
+      `entity.metadata.annotations['
+      {SENTRY_ANNOTATION}']` key is missing on the entity.{' '}
```
Comment (freben) [inline plugins/sentry/src/components/Router.tsx:32]: The backticks won't be rendered helpfully here :) maybe just pre will work

```ts
<WarningPanel title="Sentry plugin:">
  <pre>{SENTRY_ANNOTATION}</pre> annotation is missing on the entity.
</WarningPanel>
```

not sure if we have distinct styling for that actually, but won't hurt :)

File: plugins/sentry/src/components/Router.tsx (hunk 2 above)
Comment (freben) [reply plugins/sentry/src/components/Router.tsx:26]: however, at the first line of the router, you could just do

```ts
const projectId = entity.metadata.annotations?.[SENTRY_ANNOTATION]);
if (!projectId) { return the warning panel }
// here we know that a project ID was given and was non-empty
// so continue just rendering
...
<SentryPluginWidget sentryProjectId={projectId} statsFor="24h" />
```

Comment (muffix) [reply plugins/sentry/src/components/Router.tsx]: Addressed this and the other comments. Thanks for your time. 🙌

**Review by freben — APPROVED** [review]
Love it! Thank YOU!
