### PR TITLE
config-loader: refactor transform logic and add support for env var substitutions

### LINKED ISSUE #3528: Support string interpolation in config files
_This is based on a recent discussion in Discord: https://discord.com/channels/687207715902193673/687207715902193679/771756713337946162_

We often use the proxy backend with authorization headers:

```yaml
proxy:
  '/target':
    target: ...
    headers:
      Authorization:
        $env: TOKEN # with TOKEN="Bearer asdf…"
```

Plugins often add additional documentation to tell the users what the variables must include (ex: https://github.com/backstage/backstage/tree/master/plugins/sonarqube#getting-started).

It would be easier to have some kind of string interpolation functions that could work like this:

```yaml
proxy:
  '/target':
    target: ...
    headers:
      Authorization: "Bearer ${env:TOKEN}" # with TOKEN="asdf…"
```

## Possible Implementation

One suggestion for a possible syntax was this:
> [**freben** 30.10.2020](https://discord.com/channels/687207715902193673/687207715902193679/771758353181179944)
> `"${env:THE_TOKEN}"`
> `"${file:./data.pem}"`

I'm not aware of other tools or existing syntax for this behavior so I'm not sure if there is an approach that can be borrowed.

It would also be cool to do more complex things such as `Authorization: 'Basic "${BASE64("${env:USERNAME}:${env:PASSWORD}")"}'`, but I doubt that we want to support that.

## Context

Make it more fail-safe to configure a new plugin.

### LINKED ISSUE #3922: Config file validation should consider dynamic data for required fields
> “On the hunt for edge-cases...”

Given the following config schema:

```ts
// config.d.ts
{
  /**
   * some random required property
   */
  myProperty: string
}
```

If one uses the following `app-config.yaml`'s, it works as expected:
```yaml
# app-config.correct.yaml
myProperty: anything

# -> Result: valid
```
```yaml
# app-config.invalid.yaml
myPropertyyyyy: anything

# -> Result: Config should have required property 'myProperty' { missingProperty=myProperty }
```

But if one uses the [Secrets and Dynamic data](https://backstage.io/docs/conf/writing#secrets-and-dynamic-data) functionality, it breaks:
```yaml
# app-config.env.yaml
myProperty:
  $env: FILLED_AT_DEPLOYMENT_NOT_AT_BUILD

# -> Result: Config should have required property 'myProperty' { missingProperty=myProperty }
```

## Expected Behavior

The value of `$env` / `$data` / `$include` might only be available at deployment time, so the config validator should interpret them as "valid value".

## Current Behavior

The value is indeed empty, so it complains about it correctly. But since we expect it to be filled _after_ then build, it should somehow work.

## Context

#3739 and #3776 (correctly) introduced the config schemas for the catalog. But with the following in our app-config:

```yaml
#...

catalog:
  # ...
  processors:
    microsoftGraphOrg:
      providers:
        - target: https://graph.microsoft.com/v1.0/
          tenantId: ***
          clientId:
            $env: AUTH_MICROSOFT_CLIENT_ID
          clientSecret:
            $env: AUTH_MICROSOFT_CLIENT_SECRET
```

we get:

```sh
$ yarn backstage-cli config:check
Loaded config from app-config.yaml, app-config.local.yaml

Error: Configuration does not match schema

  Config should have required property 'clientId' { missingProperty=clientId } at .catalog.processors.microsoftGraphOrg.providers[0]
  Config should have required property 'clientSecret' { missingProperty=clientSecret } at .catalog.processors.microsoftGraphOrg.providers[0]

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
---
I would be happy to contribute the solution, but would need some initial guidance on how this could be solved.

### PR DESCRIPTION
**Pull request by Rugvip**
## Hey, I just made a Pull Request!

Ended up in a bit of a rerwite of config-loader 😅
Rather than having one config transform function that knows about all different syntaxes, I switched to one function that applies a list of transforms. The logic is pretty much the same though, except for the things that were added/removed.

Considered breaking this up into multiple PRs, but feel that it's all a bit too related for it to be worth it

* Fixes #3528, by adding support for `${MY_VAR}`
* Fixes #3922, by adding a `--lax` option to the CLI config commands
* Removes deprecated `$data` secrets.
* Renamed the concept of "secrets" to "includes" or "placeholders", as "secrets" no longer matches up with how it interacts with the config schema.
* Apply transforms to files included with `$include`

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

File: packages/config-loader/src/lib/transform/include.ts [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+      throw new Error(`${secretKey} include value is not a string`);
+    }
+
+    switch (secretKey) {
+      case '$file':
+        try {
+          const value = await readFile(resolvePath(baseDir, secretValue));
+          return { applied: true, value };
+        } catch (error) {
+          throw new Error(`failed to read file ${secretValue}, ${error}`);
```
Comment (freben) [inline packages/config-loader/src/lib/transform/include.ts:67]: just randomly noting here - all these have a lowercase initial character

File: packages/config-loader/src/lib/transform/include.ts [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+        }
+      case '$env':
+        try {
+          return { applied: true, value: await env(secretValue) };
+        } catch (error) {
+          throw new Error(`failed to read env ${secretValue}, ${error}`);
+        }
+
+      case '$include': {
+        const [filePath, dataPath] = secretValue.split(/#(.*)/);
```
Comment (freben) [inline packages/config-loader/src/lib/transform/include.ts:77]: just `.split('#')` would do, right?

File: packages/config-loader/src/lib/transform/include.ts [hunk 3]
```diff
@@ -0,0 +1,124 @@
...
+
+        const ext = extname(filePath);
+        const parser = includeFileParser[ext];
+        if (!parser) {
+          throw new Error(
+            `no configuration parser available for extension ${ext}`,
```
Comment (freben) [inline packages/config-loader/src/lib/transform/include.ts:83]: minor thing but, i guess if there's no extension ... could just make the message `for file x` instead

File: packages/config-loader/src/lib/transform/include.ts [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+
+        return {
+          applied: true,
+          value,
+          newBaseDir: newBaseDir !== baseDir ? newBaseDir : undefined,
+        };
+      }
+
+      default:
+        throw new Error(`unknown secret ${secretKey}`);
```
Comment (freben) [inline packages/config-loader/src/lib/transform/include.ts:121]: about this file, still referring to them as secrets throughout rather than includes or placeholders

**Review by freben — APPROVED** [review]
Nice! Little nits

File: docs/conf/writing.md [hunk 5]
```diff
@@ -114,39 +114,37 @@ backend:
...
 ### Including Files
 
-The `$include` keyword can be used to load in JSON data from an external file.
-It's able to load and parse data from `.json`, `.yml`, and `.yaml` files. It's
-also possible to include a url fragment (`#`) to point to a value at the given
-path in the file.
+The `$include` keyword can be used to load configuration values from an external
+file. It's able to load and parse data from `.json`, `.yml`, and `.yaml` files.
+It's also possible to include a url fragment (`#`) to point to a value at the
+given path in the file.
```
[the remark this answers is not in the document]
Comment (Rugvip) [reply docs/conf/writing.md]: Example below has it, but added a bit of clarification too

File: packages/config-loader/src/lib/transform/apply.ts [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+    for (const tf of transforms) {
+      try {
+        const result = await tf(inputObj, baseDir);
+        if (result.applied) {
+          if (result.value === undefined) {
+            return undefined;
+          }
+          obj = result.value;
+          dir = result.newBaseDir ?? dir;
+          break;
```
[the remark this answers is not in the document]
Comment (Rugvip) [reply packages/config-loader/src/lib/transform/apply.ts:47]: Yeah not too keen on allowing substitutions of included files, there are some potential security issues there if used in a bad way, and not too useful either. Really the only thing that you'd want to do that doesn't work without re-applying the transforms is substitutions in included config. I don't think we want to support that for text files, but for included config files it could be a bit more expected to work. It's pretty easy to work around though and a bit of a weird usage, so I'm thinking we leave it like this and if it ends up being a problem we go for some kind of workaround.

File: packages/config-loader/src/lib/transform/include.ts (hunk 1 above)
Comment (Rugvip) [reply packages/config-loader/src/lib/transform/include.ts:67]: Yeah went for structuring the error messages with `error.message` here as they're all just regular `Error` instances and meant for direct display to users.

File: packages/config-loader/src/lib/transform/include.ts (hunk 2 above)
Comment (Rugvip) [reply packages/config-loader/src/lib/transform/include.ts:77]: Just wanna split on the first `#` and put the rest in `dataPath` here

File: packages/config-loader/src/loader.ts [hunk 7]
```diff
@@ -26,39 +33,22 @@ export type LoadConfigOptions = {
...
-    private readonly options: {
-      env: { [name in string]?: string };
-      rootPath: string;
-    },
-  ) {}
-
-  get env() {
-    return this.options.env;
-  }
+  /** @deprecated This option has been removed */
```
Comment (adamdmharvey) [inline packages/config-loader/src/loader.ts:36]: Being deprecated, it hasn't technically been removed yet, is that right? should this @tag also point the user say to the doco that's been updated via this PR to guide devs to what to replace it with? (e.g., the new section on the `${VAR}` including from env)

**Review by adamdmharvey — COMMENTED** [review]
looks great!  i enjoy seeing the techniques you introduce to drive refactoring and enhancement.

File: packages/config-loader/src/lib/transform/include.ts (hunk 1 above)
Comment (freben) [reply packages/config-loader/src/lib/transform/include.ts]: Sure, I just was under the impression that this would be `Failed` elsewhere.

File: packages/config-loader/src/loader.test.ts [hunk 8]
```diff
@@ -29,8 +31,20 @@ describe('loadConfig', () => {
...
+          $include: secrets/included.yaml
       `,
       '/root/secrets/session-key.txt': 'abc123',
+      '/root/secrets/included.yaml': `
+        secret:
+          $file: session-key.txt
+      `,
+      '/root/included.yaml': `
+        foo:
+          bar: token \${MY_SECRET}
```
[the remark this answers is not in the document]
Comment (freben) [reply packages/config-loader/src/loader.test.ts:46]: Since it's a backtick string (starting on line 44) - ts also uses `${`, hence it needs to be escaped so the compiler doesn't see it and try to find a variable named MY_SECRET :)

File: packages/config-loader/src/loader.ts (hunk 7 above)
Comment (Rugvip) [reply packages/config-loader/src/loader.ts:36]: This is for the old APP_ENV-based config selection, which has been deprecated for a long time and was mostly removed in this PR. This option wasn't properly deprecated back then though, which was an oversight, and so we can't remove it now, just deprecate it. All docs etc are long gone tho (I think 😅)

**Review by dhenneke — APPROVED** [review]
Great work! Thanks for fixing this 👍

File: packages/config-loader/src/lib/transform/include.ts (hunk 1 above)
Comment (Rugvip) [reply packages/config-loader/src/lib/transform/include.ts]: Yeah elsewhere I would've gone for `Failed`, but doing some very controlled throwing here, trying to construct actual sentences rather than just patch all errors together :p
