### PR TITLE
scaffolder: fix NFS custom field explorer wiring

### LINKED ISSUE #33101: Scaffolder: custom field explorer is broken (no options, no preview) in NFS
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
scaffolder NFS custom field
```

### 🗃️ Project Area

Software Templates

### 🔗 External Integration

N/A

### 📝 Description & Context

When you go to http://localhost:3000/create/custom-fields using the new frontend system, none of the fields show their field options. Also, the preview doesn't work:

Image

### 👍 Expected Behavior

I expect the options to be shown and the preview to work.

### 📦 Reproduction Repo

https://github.com/dotboris/backstage-bug-custom-fields-no-options

### 🥾 Reproduction steps

1. `yarn start`
2. Go to http://localhost:3000/create/custom-fields
3. Pick a field

You'll that the field options are empty and that the preview doesn't work.

I've tested this in the new frontend system and creating a fresh app and by updating to v1.48.3.

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

### PR DESCRIPTION
**Pull request by kunickiaj**
## Hey, I just made a Pull Request!

Fixes #33101

Fixes regressions in the NFS custom field explorer where the editor routes did not load field extensions consistently and loaded form fields did not expose the schema shape expected by the explorer. This caused empty field options, broken previews, and crashes when the field list was empty.

https://demo.backstage.io/create/edit/custom-fields shows no fields in the dropdown (fixed by this pr)
https://demo.backstage.io/create/edit/template-form fixes the error when clicking puzzle icon, exactly (fixed by this pr).

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/scaffolder/src/alpha/components/EditorSubPage.tsx [hunk 1]
```diff
@@ -107,14 +145,40 @@ function CustomFieldsContent() {
...
+  );
+
+  useEffect(() => {
+    execute();
+  }, [execute]);
+
+  const fieldExtensions = useMemo(
+    () => buildEditorFieldExtensions(customFieldExtensions),
+    [customFieldExtensions],
+  );
```
[the remark this answers is not in the document]
Comment (kunickiaj) [reply plugins/scaffolder/src/alpha/components/EditorSubPage.tsx:161]: out of scope of this change.

**Comment by kunickiaj** [comment]
bump on this

**Comment by awanlin** [comment]
Hi @kunickiaj, can you share some steps to reproduce this? The demo site is on NFS right now so using that would be fine. Pretty sure this page should load things - https://demo.backstage.io/create/edit/custom-fields - but it's not. I'm not sure if that's what this PR fixes. From here - https://demo.backstage.io/create/edit - and then clicking on the puzzle icon gets me an "Cannot read properties of undefined (reading 'name')" error. Is that also fixed by this?

**Comment by kunickiaj** [comment]
Yes, it fixes both of these:

https://demo.backstage.io/create/edit/custom-fields shows no fields in the dropdown (fixed by this pr)
https://demo.backstage.io/create/edit/template-form fixes the error when clicking puzzle icon, exactly (fixed by this pr).

**Comment by awanlin** [comment]
Hi @benjdlambert, could use your eyes on this one and likely want a patch for it. 🙏

File: plugins/scaffolder/src/alpha/components/EditorSubPage.tsx [hunk 2]
```diff
@@ -68,16 +77,40 @@ function EditorIntroContent() {
...
+}
+
+export function toFieldExtensionOptions(
+  formField: FormField,
+): FieldExtensionOptions {
+  const internal = OpaqueFormField.toInternal(formField);
+
+  return {
+    ...internal,
+    schema: internal.schema?.schema ?? internal.schema,
```
Comment (benjdlambert) [inline plugins/scaffolder/src/alpha/components/EditorSubPage.tsx:98]: Hmm this smells a bit weird. I think this might need a cleanup in the API, but not for now.

File: plugins/scaffolder/src/alpha/components/EditorSubPage.tsx [hunk 3]
```diff
@@ -107,14 +145,40 @@ function CustomFieldsContent() {
  * @internal
  */
 export function EditorSubPage() {
+  const formFieldsApi = useApi(formFieldsApiRef);
+  const [{ result: customFieldExtensions = [] }, { execute }] = useAsync(
```
Comment (benjdlambert) [inline plugins/scaffolder/src/alpha/components/EditorSubPage.tsx:149]: This `useAsync` hook API is pretty unorthodox.

I wanna move all the the `useAsync` calls to just use `react-query` instead, as it's much cleaner and more powerful, but again, not for now.

But I think we should do https://github.com/backstage/backstage/pull/33599/changes#r3078356231

File: plugins/scaffolder/src/alpha/components/EditorSubPage.tsx [hunk 4]
```diff
@@ -107,14 +145,40 @@ function CustomFieldsContent() {
...
+    async () => {
+      const formFields = await formFieldsApi.loadFormFields();
+      return formFields.map(toFieldExtensionOptions);
+    },
+  );
+
+  useEffect(() => {
+    execute();
+  }, [execute]);
```
Comment (benjdlambert) [inline plugins/scaffolder/src/alpha/components/EditorSubPage.tsx]:
```suggestion
useMountEffect(execute);
```
