### PR TITLE
fix: allow unauthenticated signals connection to fix 401

### LINKED ISSUE #23927: 🐛 Bug Report: signals-backend fails ws upgrade with new default auth policy
### 📜 Description

You're running backstage with the default auth policy enabled in 1.24.0

### 👍 Expected behavior

Be able to perform the websocket upgrade

### 👎 Actual Behavior with Screenshots

It actually fails with a 401 unauthorized error because the `/api/signals` endpoint is being authenticated but has no credentials in the standard `Authorization` header *i think*.

Adding ```ts
httpRouter.addAuthPolicy({
          path: '/',
          allow: 'unauthenticated',
        });
        ``` to the `plugin.ts` of the `signals-backend` plugin works around the issue, though I'm not sure if its the correct fix. The websocket upgrade code still performs token checks, so maybe its ok.

### 👟 Reproduction steps

Run backstage with the default auth policy enabled and the signals plugins

### 📃 Provide the context for the Bug.

```log
[1] 2024-04-01T22:12:45.589Z rootHttpRouter error Request failed with status 401 Missing credentials type=errorHandler cause=undefined name=AuthenticationError stack=AuthenticationError: Missing credentials
[1]     at DefaultHttpAuthService.credentials (/srv/backstage/node_modules/@backstage/backend-app-api/src/services/implementations/httpAuth/httpAuthServiceFactory.ts:150:13)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1] 2024-04-01T22:12:45.592Z rootHttpRouter info GET /api/signals 401 8.739 ms - 455 type=incomingRequest
```

### 🖥️ Your Environment

Backstage 1.25.0, signals plugins, notifications plugins.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by drodil**
## Hey, I just made a Pull Request!

the signals handles authentication itself in the middleware thus we should allow unauthenticated requests to pass through

closes #23927 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by mareklibra — APPROVED** [review]

File: plugins/signals-backend/src/plugin.ts [hunk 1]
```diff
@@ -58,7 +58,7 @@ export const signalsPlugin = createBackendPlugin({
           }),
         );
         httpRouter.addAuthPolicy({
-          path: '/health',
+          path: '*',
```
Comment (Rugvip) [inline plugins/signals-backend/src/plugin.ts:61]:
```suggestion
          path: '/',
```

Just because this is what we usually do, it's the same thing

**Review by Rugvip — APPROVED** [review]
:shipit:

What do you think about moving the endpoint to something like `/connect`? Just keeping it a bit more sectioned off from the rest and allowing us to only remove auth from that bit. Right now we don't have any other APIs or other connections, but thinking that could become a thing in the future?
