### PR TITLE
Move the `Link` component to `RoutedTabs` instead of `HeaderTabs`

### LINKED ISSUE #25007: 🐛 Backstage HeaderTabs with v1.26.0 cause breaking changes
### 📜 Description

I can see that Backstage has introduced tabs as Links in v1.26.0, with the href attribute. But with the change, you are removing leading slashes (/), and making paths relative which is breaking the navigation.

There are 2 issues,
1. If we had absolute paths before, eg. /team/members, introducing the following code change makes this path relative and so it gets appended to the URL and doesn't redirects to the correct page.
    ```
    // HeaderTabs.tsx

    function removeLeadingSlash(path: string) {
        return path.replace(/^\//, '');
      }
    ...
    component={Link}
    to={removeLeadingSlash(tab.id)}
    ...
    ```
2. If I change it to relative path, if it is outside of nested Routes, it works fine. But if it is in a route element component, the redirection doesn't work anymore. Though if we use the absolute path, and the leading slash is not removed, it works.

### 👍 Expected behavior

I wanted to understand the reason of introducing the method to remove leading slashes and make the path relative on purpose. Ideally, it should redirect to the correct path no matter if we pass absolute or relative path.

### 👎 Actual Behavior with Screenshots

It appends the path in the URL,

Screenshot 2024-05-31 at 16 22 50

### 👟 Reproduction steps

For any HeaderTab implementation,

1. When I pass absolute path,

    ```
    const tabs = [
      { label: 'Tab 1', path: '/plugin-name' },
      { label: 'Tab 2', path: '/plugin-name/coverage' },
      { label: 'Tab 3', path: '/plugin-name/tab-3' },
    ];
    ...
    <HeaderTabs
          selectedIndex={selectedIndex}
           tabs={tabs.map(({ label, path, tabProps }) => ({
            id: path,
            label,
            tabProps,
          }))}
    />
    ```

2. The issue remains the same even when I have relative paths,

    ```
    const tabs = [
      { label: 'Tab 1', path: '' },
      { label: 'Tab 2', path: 'coverage' },
      { label: 'Tab 3', path: 'tab-3' },
    ];
    ...
    <HeaderTabs
          selectedIndex={selectedIndex}
           tabs={tabs.map(({ label, path, tabProps }) => ({
            id: path,
            label,
            tabProps,
          }))}
    />
    ```
    
For 2, the issue occurs when I use the above code inside `Content.tsx` from below (because Content gets re-rendered on click of tab and it updates the href),
    
    ```
    <Routes>
      <Route path="/" element={<DashboardContent />} />
      <Route
        path="/content"
        element={<Content />}
      />
    </Routes>
    ```

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

OS:   Darwin 23.4.0 - darwin/arm64
node: v18.18.0
yarn: 1.22.19
cli:  0.26.6 (installed)
backstage:  1.27.5

@backstage/core-components: 0.14.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by benjdlambert**
- chore: wip
- chore: attempt to fix the tabs
- chore: added changeset Signed-off-by: blam <ben@blam.sh>

## Hey, I just made a Pull Request!

Fixes #25007

### CODE REVIEW

**Comment by benjdlambert** [comment]
@rugvip wanna go through with you these test failures, as I just want to make sure that the `href` links are correct.

File: packages/core-components/src/components/TabbedLayout/RoutedTabs.tsx [hunk 1]
```diff
@@ -68,35 +64,33 @@ export function useSelectedSubRoute(subRoutes: SubRoute[]): {
...
+        const { path, title, tabProps } = t;
+        let to = path;
+        // Remove trailing /*
+        to = to.replace(/\/\*$/, '');
+        // And remove leading / for relative navigation
+        to = to.replace(/^\//, '');
+        return {
+          id: path,
+          label: title,
+          tabProps: {
```
Comment (malhotraashna) [inline packages/core-components/src/components/TabbedLayout/RoutedTabs.tsx:81]: Is it possible to spread tabProps at the end, so that the value for `to`/`component` can be overridden?

```
tabProps: {
            component: Link,
            to,
            ...tabProps,
},
```

**Review by Rugvip — APPROVED** [review]
Nice, that should do it! 👍 

:shipit:
