### PR TITLE
fix(search): return EmptyState/Progress bar/Alert depending on result of api call

### LINKED ISSUE #3342: [Search] Display empty state if no search results can be displayed
We currently are using the catalogAPI to get all entities to search across, If no results are returned from the request we are currently just returning `null`. We would like to return a EmptyState component here instead. 

[Storybook]( https://backstage.io/storybook/?path=/story/feedback-emptystate--data)

### PR DESCRIPTION
**Pull request by magneticz**
## Hey, I just made a Pull Request! 

Fixes #3342 

On Search Result page, depending on the result of the api call display different component.

When `loading`, `Progress` component is shown
Screenshot 2020-11-19 at 13 03 06

When call to api fails with an error, `Alert` component is shown
Screenshot 2020-11-19 at 13 04 17

When call is finished with empty result, `EmptyState` component is shown
Screenshot 2020-11-19 at 13 04 46

#### :heavy_check_mark: Checklist

- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

File: plugins/search/src/components/SearchResult/SearchResult.tsx [hunk 1]
```diff
@@ -159,8 +166,25 @@ export const SearchResult = ({ searchQuery }: SearchResultProps) => {
...
+        Error encountered while fetching search results. {error.toString()}
+      </Alert>
+    );
+  }
+  if (!results || results.length === 0) {
+    return (
+      <EmptyState
+        missing="info"
+        title="No information to display"
+        description="Sorry, no results were found"
```
Comment (emmaindal) [inline plugins/search/src/components/SearchResult/SearchResult.tsx:184]: Wohoo this is great!! 🎉  Just one comment - can we switch the title to be "Sorry, no results were found" and take away the description prop.

Comment (emmaindal) [reply plugins/search/src/components/SearchResult/SearchResult.tsx:184]: and also change to `missing="data"`

File: plugins/search/src/components/SearchResult/SearchResult.tsx [hunk 2]
```diff
@@ -159,8 +166,19 @@ export const SearchResult = ({ searchQuery }: SearchResultProps) => {
...
+  }
+  if (error) {
+    return (
+      <Alert severity="error">
+        Error encountered while fetching search results. {error.toString()}
+      </Alert>
+    );
+  }
+  if (!results || results.length === 0) {
+    return <EmptyState missing="info" title="Sorry, no results were found" />;
```
Comment (magneticz) [inline plugins/search/src/components/SearchResult/SearchResult.tsx:180]: @emmaindal, I amended changes, so the history changed. But, here is fix

Comment (emmaindal) [inline plugins/search/src/components/SearchResult/SearchResult.tsx:180]:
```suggestion
    return <EmptyState missing="data" title="Sorry, no results were found" />;
```

Comment (emmaindal) [reply plugins/search/src/components/SearchResult/SearchResult.tsx:180]: Great! I added a commit suggestion of just changing the type of the empty state component below

Comment (emmaindal) [reply plugins/search/src/components/SearchResult/SearchResult.tsx:180]: so that we get this storybook component https://backstage.io/storybook/?path=/story/feedback-emptystate--data

Comment (magneticz) [reply plugins/search/src/components/SearchResult/SearchResult.tsx]: sorry, i missed your second comment. Just accepted your suggestion

**Comment by emmaindal** [comment]
@magneticz LGTM, will merge when the checks pass! Thank you so much for the contribution 🎉 💯

**Review by emmaindal — APPROVED** [review]
