### PR TITLE
Fix :: Prevent Entity Providers from eliminating Users and Groups if synchronisation fails

### LINKED ISSUE #22222: 🐛 Bug Report: Users and Groups being wiped if synchronisation fails
### 📜 Description

When the synchronisation of Users and Groups starts, in our case utilising `GithubMultiOrgEntityProvider`, if for some reason the request to Github's API fails the existing Users and Groups on the DB get removed. 

### 👍 Expected behavior

If the request should fail no mutation should be applied to the DB.

### 👎 Actual Behavior with Screenshots

When the requests fail for any reason, the Users and Groups present on the DB get eliminated.

### 👟 Reproduction steps

Start the synchronisation process locally while being disconnected from the internet. This will cause the sync to fail which in turn will wipe whatever Users and Groups you currently have in your local DB. 

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

OS:   Darwin 23.2.0 - darwin/arm64
node: v20.11.0
yarn: 1.22.19
cli:  0.24.0 (installed)
backstage:  1.21.1

Dependencies:
  @backstage/app-defaults                                          1.4.6
  @backstage/backend-app-api                                       0.5.9
  @backstage/backend-common                                        0.19.9, 0.20.0
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.1
  @backstage/backend-plugin-api                                    0.6.8
  @backstage/backend-tasks                                         0.5.13
  @backstage/catalog-client                                        1.5.1
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.1
  @backstage/cli                                                   0.25.0
  @backstage/config-loader                                         1.6.0
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.2
  @backstage/core-compat-api                                       0.1.0
  @backstage/core-components                                       0.13.9
  @backstage/core-plugin-api                                       1.8.1
  @backstage/dev-utils                                             1.0.25
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.4.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.22
  @backstage/integration                                           1.8.0
  @backstage/plugin-api-docs                                       0.10.2
  @backstage/plugin-app-backend                                    0.3.56
  @backstage/plugin-app-node                                       0.1.8
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.2
  @backstage/plugin-auth-backend-module-github-provider            0.1.5
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.5
  @backstage/plugin-auth-backend-module-google-provider            0.1.5
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.5
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.0
  @backstage/plugin-auth-backend-module-okta-provider              0.0.1
  @backstage/plugin-auth-backend                                   0.20.2
  @backstage/plugin-auth-node                                      0.4.2
  @backstage/plugin-catalog-backend-module-github                  0.4.6
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.5
  @backstage/plugin-catalog-backend                                1.16.0
  @backstage/plugin-catalog-common                                 1.0.19
  @backstage/plugin-catalog-graph                                  0.3.2
  @backstage/plugin-catalog-import                                 0.10.4
  @backstage/plugin-catalog-node                                   1.6.0
  @backstage/plugin-catalog-react                                  1.9.2
  @backstage/plugin-catalog                                        1.16.0
  @backstage/plugin-cost-insights-common                           0.1.2
  @backstage/plugin-cost-insights                                  0.12.17
  @backstage/plugin-entity-feedback-backend                        0.2.5
  @backstage/plugin-entity-feedback-common                         0.1.3
  @backstage/plugin-entity-feedback                                0.2.11
  @backstage/plugin-events-node                                    0.2.17
  @backstage/plugin-git-release-manager                            0.3.40
  @backstage/plugin-github-actions                                 0.6.9
  @backstage/plugin-home-react                                     0.1.6
  @backstage/plugin-home                                           0.6.0
  @backstage/plugin-org                                            0.6.18
  @backstage/plugin-permission-backend                             0.5.31
  @backstage/plugin-permission-common                              0.7.11
  @backstage/plugin-permission-node                                0.7.19
  @backstage/plugin-permission-react                               0.4.18
  @backstage/plugin-proxy-backend                                  0.4.6
  @backstage/plugin-scaffolder-backend-module-azure                0.1.0
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.0
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.0
  @backstage/plugin-scaffolder-backend-module-github               0.1.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.11
  @backstage/plugin-scaffolder-backend                             1.19.2
  @backstage/plugin-scaffolder-common                              1.4.4
  @backstage/plugin-scaffolder-node                                0.2.9
  @backstage/plugin-scaffolder-react                               1.7.0
  @backstage/plugin-scaffolder                                     1.17.0
  @backstage/plugin-search-backend-module-catalog                  0.1.12
  @backstage/plugin-search-backend-module-pg                       0.5.17
  @backstage/plugin-search-backend-module-stack-overflow-collator  0.1.1
  @backstage/plugin-search-backend-module-techdocs                 0.1.12
  @backstage/plugin-search-backend-node                            1.2.12
  @backstage/plugin-search-backend                                 1.4.8
  @backstage/plugin-search-common                                  1.2.9
  @backstage/plugin-search-react                                   1.7.4
  @backstage/plugin-search                                         1.4.4
  @backstage/plugin-shortcuts                                      0.3.17
  @backstage/plugin-sonarqube-backend                              0.2.10
  @backstage/plugin-sonarqube-react                                0.1.11
  @backstage/plugin-sonarqube                                      0.7.10
  @backstage/plugin-stack-overflow-backend                         0.2.12
  @backstage/plugin-stack-overflow                                 0.1.23
  @backstage/plugin-tech-radar                                     0.6.11
  @backstage/plugin-techdocs-addons-test-utils                     1.0.25
  @backstage/plugin-techdocs-backend                               1.9.1
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.3
  @backstage/plugin-techdocs-node                                  1.11.0
  @backstage/plugin-techdocs-react                                 1.1.14
  @backstage/plugin-techdocs                                       1.9.2
  @backstage/plugin-user-settings                                  0.7.14
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.6
  @backstage/theme                                                 0.4.4, 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by josecosta-shell**
## Hey, I just made a Pull Request!

Fixes #22222

If the API used for user and group synchronisation is down or the requests to it fail for whatever reason when the catalog sync happens Backstage will clear the database of the previously synchronised entities. This PR attempts to fix this by only applying the mutation if there are users or groups present.

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Review by shell-eduardo — APPROVED** [review]
LGTM

File: plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts [hunk 1]
```diff
@@ -299,20 +299,24 @@ export class GithubMultiOrgEntityProvider implements EntityProvider {
...
-      type: 'full',
-      entities: [...allUsers, ...allTeams].map(entity => ({
-        locationKey: `github-multi-org-provider:${this.options.id}`,
-        entity: withLocations(
-          `https://${this.options.gitHubConfig.host}`,
-          entity,
-        ),
-      })),
-    });
+    if (allUsers.length > 0 || allTeams.length > 0) {
```
Comment (awanlin) [inline plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts:302]: I think we should perhaps not just log the error on line 296 but throw as well? Feel like this is the root cause of the issue you described with GitHub being down.

This makes sense as a safety net, I'm not super familiar with this provider but the one thought I had was: is it possible for either of these to be empty and that's valid? Or do we always pull all the data each run? This would also be something to consider for the other providers being changed here

**Review by awanlin — CHANGES_REQUESTED** [review]
Thanks for the contribution @josecosta-shell, just left a single comment

File: plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts (hunk 1 above)
Comment (sennyeya) [reply plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts:302]: Piggybacking off of this, I agree the error should be checked instead. I _think_ this change would stop a very very small case where you emptied out your Github organization completely and Backstage would be unable to overwrite the existing list of entities.

**Comment by freben** [comment]
Agreed with the above; better to throw eagerly and give up, rather than trying to check anything after the fact.

Also remember to DCO sign all of your commits - there are instructions in the build check and the bot comment above.

**Comment by josecosta-shell** [comment]
> Agreed with the above; better to throw eagerly and give up, rather than trying to check anything after the fact.
> 
> Also remember to DCO sign all of your commits - there are instructions in the build check and the bot comment above.

Looking at the code I would think if there was an error in the API it would stop the execution as I cannot see anything catching any errors from this API call. `queryWithPaging` is what actually triggers the request, as far as I can tell, and there is no catch there. Wouldn't the error propagate upward and stop `applyMutation` from happening with the code being as it is?

**Comment by awanlin** [comment]
Am I mistaken thinking this would swallow any errors and cause the issue you experienced during the GitHub instability?

https://github.com/backstage/backstage/blob/ba1ae038f06e3a3ff2a21a0a6497f15af713fe58/plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts#L295-L297

All this does is log an error, the mutation happens after this and would be working with an empty array/object

**Comment by josecosta-shell** [comment]
> backstage/plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts

Indeed it would! I was looking at the `GithubOrgEntityProvider` where there is no need for such a loop! So this issue must be specific to the multi-org setups, like our own. Could the fix be as simple as getting rid of that try catch?

**Comment by awanlin** [comment]
Yes, I think removing the try/catch would be a good idea 👍

File: plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts [hunk 2]
```diff
@@ -248,53 +248,49 @@ export class GithubMultiOrgEntityProvider implements EntityProvider {
...
     for (const org of orgsToProcess) {
-      try {
-        const { headers, type: tokenType } =
-          await this.options.githubCredentialsProvider.getCredentials({
-            url: `${this.options.githubUrl}/${org}`,
-          });
-        const client = graphql.defaults({
-          baseUrl: this.options.gitHubConfig.apiBaseUrl,
-          headers,
+      const { headers, type: tokenType } =
```
Comment (awanlin) [inline plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts:251]: Can we add a test around this change, please?

**Review by awanlin — CHANGES_REQUESTED** [review]
Glad we narrowed this down, I think this is the right direction. I do think we should also add a test for this 👍

File: plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts (hunk 2 above)
Comment (josecosta-shell) [reply plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts:251]: Just to clarify, the test you refer to is to validate that the mutation does not in fact get triggered if a request fails, right?

Comment (josecosta-shell) [reply plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts:251]: In any case such a test would make sense so I have added it

File: plugins/catalog-backend-module-github/src/providers/GithubOrgEntityProvider.test.ts
[the remark this answers is not in the document]
Comment (josecosta-shell) [reply plugins/catalog-backend-module-github/src/providers/GithubOrgEntityProvider.test.ts:1]: Thank you for catching this! I have added the test to the right place this time

File: plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts (hunk 2 above)
Comment (awanlin) [reply plugins/catalog-backend-module-github/src/providers/GithubMultiOrgEntityProvider.ts:251]: Yes, thanks for adding this 👍

**Review by awanlin — APPROVED** [review]
Awesome work @josecosta-shell, thanks for this! 🚀

**Review by freben — APPROVED** [review]

**Comment by freben** [comment]
Oh sorry, I was too fast with the approve - typescript is unhappy due to the usages of `any`.

**Comment by josecosta-shell** [comment]
It doesn't look like I introduced any anys 😆

**Comment by josecosta-shell** [comment]
> Oh sorry, I was too fast with the approve - typescript is unhappy due to the usages of `any`.

Fixed! There were some TS definitions missing for the mock data of the tests.

**Review by shell-eduardo — APPROVED** [review]
LGTM

**Review by nuritizra — APPROVED** [review]

**Review by freben — APPROVED** [review]
