### PR TITLE
cli: reintroduce node polyfills that were removed in webpack 5 migration

### LINKED ISSUE #6824: Unable to run backstage with the snyk plugin using the latest cli (webpack 5)
I'm getting errors like the following when I try to run backstage with the snyk plugin:

```
[0] ERROR in ../../node_modules/@snyk/dep-graph/dist/legacy/index.js 4:15-32
[0] Module not found: Error: Can't resolve 'crypto' in '/Users/iainbillett/code/backstage/node_modules/@snyk/dep-graph/dist/legacy'
[0] 
[0] BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
[0] This is no longer the case. Verify if you need this module and configure a polyfill for it.
[0] 
[0] If you want to include a polyfill, you need to:
[0]     - add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
[0]     - install 'crypto-browserify'
[0] If you don't want to include a polyfill, you can use an empty module like this:
[0]     resolve.fallback: { "crypto": false }
```

## Expected Behavior

I can use the snyk plugin ([backstage-plugin-snyk](https://github.com/snyk-tech-services/backstage-plugin-snyk))

## Current Behavior

When I start the app (e.g. `yarn dev`) webpack fails with the error above. 

## Possible Solution

I've tested setting resolve.fallback.crypto = false in packages/cli/src/lib/bundler/config.ts but presumably this could cause a runtime issue. It does compile though. 

## Steps to Reproduce

* Create a backstage instance (or upgrade an existing one) e.g. npx @backstage/create-app
* Follow instructions to install the Snyk plugin
* run yarn dev

## Context

I've made an [issue](https://github.com/snyk-tech-services/backstage-plugin-snyk/issues/29) with snyk also.

### PR DESCRIPTION
**Pull request by Rugvip**
The Webpack 5 migration in #5292 is supposed to be a non-breaking change. Since webpack 5 removed the default Node.js polyfills and we only reintroduced some of them, it lead to issues like #6824. This reintroduces all of the polyfills that we didn't already explicitly disable, and we'll leave the deprecation of those to a future breaking update.

Fixes #6824

### CODE REVIEW

**Review by joeporpeglia — APPROVED** [review]

File: packages/cli/src/lib/bundler/config.ts [hunk 1]
```diff
@@ -177,6 +178,7 @@ export async function createConfig(
       extensions: ['.ts', '.tsx', '.mjs', '.js', '.jsx'],
       mainFields: ['browser', 'module', 'main'],
       fallback: {
+        ...pickBy(require('node-libs-browser')),
```
Comment (freben) [inline packages/cli/src/lib/bundler/config.ts:181]: This is not very clear :)

**Review by freben — APPROVED** [review]

File: packages/cli/src/lib/bundler/config.ts (hunk 1 above)
Comment (Rugvip) [reply packages/cli/src/lib/bundler/config.ts:181]: BUT THE PERF!1

I blame lodash for providing that silly default, can't bear to provide an arg that is identical to the default x)

Comment (freben) [reply packages/cli/src/lib/bundler/config.ts:181]: sure but, `const cloneWithoutFalsyFields = x` or whatnot :)

Comment (freben) [reply packages/cli/src/lib/bundler/config.ts:181]: just didn't understand the underlying purpose of it at first glance

**Comment by caponetto** [comment]
Hi there! Not sure if this is the best place to ask this but is there any reason to disable the polyfill for `path`?
