### PR TITLE
Fixed WelcomeTitle regression

### LINKED ISSUE #16040: 🐛 Bug Report: `WelcomeTitle` doesn't inherit `Header`'s font size
### 📜 Description

When upgraded to `v1.10.0`, the `WelcomeTitle` component has become unable to inherit the font size of the `Header` component.

### 👍 Expected behavior

I could see it in `v1.9.0` as below:

Screen Shot 2023-01-30 at 19 53 28

### 👎 Actual Behavior with Screenshots

Screen Shot 2023-01-30 at 19 53 57

### 👟 Reproduction steps

Adds a component as below:

```tsx
<Page themeId="home">
  <Header title={<WelcomeTitle />} pageTitleOverride="Home">
     ...
  </Header>
</Page>
```

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

<details>
<summary><code>yarn backstage-cli info</code></summary>

```
OS:   Darwin 21.3.0 - darwin/arm64
node: v18.12.1
yarn: 1.22.19
cli:  0.22.1 (installed)
backstage:  1.10.1

Dependencies:
  @backstage/app-defaults                          1.1.0
  @backstage/backend-app-api                       0.3.1
  @backstage/backend-common                        0.18.1
  @backstage/backend-plugin-api                    0.3.1
  @backstage/backend-tasks                         0.4.2
  @backstage/catalog-client                        1.3.0
  @backstage/catalog-model                         1.1.5
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.1
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.4.0
  @backstage/core-components                       0.12.3
  @backstage/core-plugin-api                       1.3.0
  @backstage/errors                                1.1.4
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.9
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.8.14
  @backstage/plugin-app-backend                    0.3.41
  @backstage/plugin-auth-backend                   0.17.4
  @backstage/plugin-auth-node                      0.2.10
  @backstage/plugin-catalog-backend-module-github  0.2.4
  @backstage/plugin-catalog-backend                1.7.1
  @backstage/plugin-catalog-common                 1.0.10
  @backstage/plugin-catalog-graph                  0.2.26
  @backstage/plugin-catalog-import                 0.9.4
  @backstage/plugin-catalog-node                   1.3.2
  @backstage/plugin-catalog-react                  1.2.4
  @backstage/plugin-catalog                        1.7.2
  @backstage/plugin-events-node                    0.2.2
  @backstage/plugin-github-actions                 0.5.14
  @backstage/plugin-home                           0.4.30
  @backstage/plugin-org                            0.6.4
  @backstage/plugin-permission-backend             0.5.16
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.4
  @backstage/plugin-permission-react               0.4.9
  @backstage/plugin-proxy-backend                  0.2.35
  @backstage/plugin-scaffolder-backend             1.10.1
  @backstage/plugin-scaffolder-common              1.2.4
  @backstage/plugin-scaffolder-react               1.0.1
  @backstage/plugin-scaffolder                     1.10.1
  @backstage/plugin-search-backend-module-pg       0.5.2
  @backstage/plugin-search-backend-node            1.1.2
  @backstage/plugin-search-backend                 1.2.2
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.4.0
  @backstage/plugin-search                         1.0.7
  @backstage/plugin-shortcuts                      0.3.6
  @backstage/plugin-stack-overflow                 0.1.10
  @backstage/plugin-techdocs-backend               1.5.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.9
  @backstage/plugin-techdocs-node                  1.4.5
  @backstage/plugin-techdocs-react                 1.1.2
  @backstage/plugin-techdocs                       1.4.3
  @backstage/plugin-user-settings                  0.6.2
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.4
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
```

</details>

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by awanlin**
Signed-off-by: Andre Wanlin <67169551+awanlin@users.noreply.github.com>

## Hey, I just made a Pull Request!

Fixed regression that caused the `WelcomeTitle` to not be the right size when passed to the `title` property of the `<Header>` component. Also added a Storybook entry. Closes #16040

Before:

Screenshot 2023-01-25 at 12 30 38 PM

After:

Screenshot 2023-01-25 at 12 31 35 PM

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

**Comment by awanlin** [comment]
Hi @luchillo17, could you do a quick review of this when you have time? I know you put in the work to fix all the `span` uses and I'm not sure if my "fix" here is the best way so open to suggestions. Thanks in advance!

**Comment by luchillo17** [comment]
Have you tried the title variants? like ` <Typography variant="h1"></Typography>`, the change was made to ensure we're using theme-related font sizes instead of custom ones, however at that time I replaced every span component with its equivalent Typography one, what's the original font size (the big one in your image)?

**Comment by awanlin** [comment]
I had not tried variants. When I use `<Typography variant="h1"></Typography>` instead the font-size ends up being `54px` which is really big. It also then doesn't match any of the other pages; if you look at any of the other headers they are `32px`. The `WelcomeTitle` gets used a little differently as it gets passed into the `title` property of a `<Header>` component so it's expecting to inherit the styles for a title. Here's an example: https://github.com/backstage/backstage/blob/76b838a85493d210d51817f3776117989f1dced5/packages/app/src/components/home/HomePage.tsx#L60

Here's what it looks like using the H1 variant:

Screenshot 2023-01-26 at 8 16 53 AM

Here's what I currently have just to make comparing a little easier:

Screenshot 2023-01-25 at 12 31 35 PM

**Comment by luchillo17** [comment]
You can try one of the other variants, for `32px` I think `h4` is the closest: https://v4.mui.com/components/typography/#component

**Comment by awanlin** [comment]
@luchillo17 that worked, `H3` ended up being the one that was `32px` 🚀

**Comment by awanlin** [comment]
Hi @backstage/reviewers @backstage/techdocs-core, this PR is ready for review. 

FYI @Rugvip I'm noticing that the home plugin isn't getting anyone assigned to it automatically. Not sure why though.

File: plugins/home/src/homePageComponents/WelcomeTitle/WelcomeTitle.tsx [hunk 1]
```diff
@@ -44,7 +43,7 @@ export const WelcomeTitle = () => {
 
   return (
     <Tooltip title={greeting.language}>
-      <Typography component="span">{`${greeting.greeting}${
+      <Typography variant="h3">{`${greeting.greeting}${
```
Comment (luchillo17) [inline plugins/home/src/homePageComponents/WelcomeTitle/WelcomeTitle.tsx:46]: Hmm? is it not a span anymore? well, I see no reason to keep the span either way.

**Comment by Rugvip** [comment]
@awanlin the home plugin is owned by @backstage/techdocs-core, so they are assigned as reviewers. They don't use the same kind of randomized assignment though, so no direct user assignment

File: plugins/home/src/homePageComponents/WelcomeTitle/WelcomeTitle.tsx (hunk 1 above)
Comment (awanlin) [reply plugins/home/src/homePageComponents/WelcomeTitle/WelcomeTitle.tsx:46]: Yeah, it doesn't make sense to me to put it back now that we've settled on using an `H3`.

Comment (micnncim) [reply plugins/home/src/homePageComponents/WelcomeTitle/WelcomeTitle.tsx:46]: `<Typography component="span" variant="inherit">` works without having a fixed variant.

Comment (awanlin) [reply plugins/home/src/homePageComponents/WelcomeTitle/WelcomeTitle.tsx:46]: Oh, interesting @micnncim! I'll give that a try, feel like that's a bit more clear as to what the intent is.

**Review by iamEAP — APPROVED** [review]
Thanks @awanlin and all for the reviews & recommendations.  This looks good to me.

**Review by benjdlambert — APPROVED** [review]

**Comment by benjdlambert** [comment]
Nice! thanks all!
