### PR TITLE
feat(config-loader): Fix handling of keys with backslashes.

### LINKED ISSUE #17855: 🐛 Bug Report: Proxy authorization header can't be defined as secret
### 📜 Description

I started to test https://github.com/backstage/backstage/tree/master/plugins/devtools. This plugin will expose a UI & endpoint which exposes the whole configuration.
There I saw that some sensible data is not defined as secrets. Therefor I opened some PR's to handle this

- https://github.com/backstage/backstage/pull/17852
- https://github.com/backstage/backstage/pull/17850
- https://github.com/RoadieHQ/roadie-backstage-plugins/pull/990

There could be more, these are only the ones I use and had an issue with.

The last issue was that I use a configuration like https://github.com/backstage/backstage/blob/master/app-config.yaml#L59-L62 with the proxy-backend:

To fix this I changed https://github.com/backstage/backstage/blob/master/plugins/proxy-backend/config.d.ts#L34 to something like
```
headers?: {
  /**
     * @visibility secret
     */
  Authorization?: string;
  [key: string]: string;
};

OR

headers?: {
  /**
     * @visibility secret
     */
  Authorization?: string;
};
```

### 👍 Expected behavior

The header value is treated as secret and will be replaced by https://github.com/backstage/backstage/blob/master/plugins/devtools-backend/src/api/DevToolsBackendApi.ts#L175

### 👎 Actual Behavior with Screenshots

The header is not treated as secret.

### 👟 Reproduction steps

1. Change the config.d.ts for the proxy backend as shown in the description
2. Go to the devtools page an check the output for the proxies

### 📃 Provide the context for the Bug.

I found that the reason for this behaviour are the slashes in the proxy configuration.
Doesn't work
```
'/jenkins/api': <========
    target: http://localhost:8080
    headers:
      Authorization: ${JENKINS_BASIC_AUTH_HEADER}
```
Works
```
'jenkins-api': <========
    target: http://localhost:8080
    headers:
      Authorization: ${JENKINS_BASIC_AUTH_HEADER}
```

As there are a lot of plugins using the authorization header in the proxy backend, this should probably be fixed. Or at least if not fixed a disclaimer should be added to the devtools plugin about this.
What do you think?

FYI @awanlin 

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

### PR DESCRIPTION
**Pull request by sennyeya**
## Hey, I just made a Pull Request!

_should_ close #17855. AJV instance paths are escaped, so `/` characters like those in `/proxy` are converted to `~1`. See this on the [AJV side](https://github.com/ajv-validator/ajv/blob/master/lib/compile/util.ts#L69). 

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: packages/config-loader/src/schema/compile.ts [hunk 1]
```diff
@@ -66,10 +77,9 @@ export function compileConfigSchemas(
             return false;
           }
           if (visibility && visibility !== 'backend') {
-            const normalizedPath = context.instancePath.replace(
-              /\['?(.*?)'?\]/g,
-              (_, segment) => `/${segment}`,
-            );
+            const normalizedPath = normalizeInstancePath(
+              context.instancePath,
+            ).replace(/\['?(.*?)'?\]/g, (_, segment) => `/${segment}`);
```
Comment (Rugvip) [inline packages/config-loader/src/schema/compile.ts:82]: I think we can bring the second replace into `normalizeInstancePath` too, feels like that's part of it

**Review by Rugvip — COMMENTED** [review]
Good catch! 👍

File: packages/config-loader/src/schema/compile.ts (hunk 1 above)
Comment (sennyeya) [reply packages/config-loader/src/schema/compile.ts]: Yup, makes sense. I also adjusted where we're using this to include error messages.
