### PR TITLE
EntityOwnerPicker infinite scrolling

### LINKED ISSUE #17499: 🐛 Bug Report: Owner picker breaks with large catalog
### 📜 Description

The owner picker in `/catalog` page doesn't work anymore if the catalog contains > 4k users/groups.
The issue was introduced in https://github.com/backstage/backstage/pull/16320 where the `catalogApi.getEntitiesByRefs` method is invoked with the entity refs of all users and groups. Since the payload is too big the request fails with the error below.

### 👍 Expected behavior

I should be able to use the owner filter regardless of how many entities my catalog contains.

### 👎 Actual Behavior with Screenshots

Screenshot 2023-04-25 at 10 47 16

### 👟 Reproduction steps

1. Ingest between 4k-5k users or groups in your catalog
2. Load the `/catalog` page.
3. An error `EntityOwnerPicker failed to initialize: Request failed with 413 PayloadTooLargeError` is thrown and the Owner picker will disappear

### 📃 Provide the context for the Bug.

The owner picker has never been optimized for catalog containing a large number of users and groups, so it has always been slow.
The feature introduced in #16320 complicates things, because of the overhead added by the new api request.

The rollback of #16320 can be seen as a quick for to the issue, however it can't be seen as a long term fix to the usability of the owner picker. ideally the entire component needs to be refactored, moving to a infinite scrolling approach and server side filtering of the entities.

### 🖥️ Your Environment

_No response_

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by vinzscam**
## Hey, I just made a Pull Request!

Alò,
The `EntityOwnerPicker` component has been notoriously slow in case of large catalog, due to the fact that the entities aren't virtualized or paginated.
Lately a new feature has been merged which caused #17499.

This PR changes how users and groups are displayed in `EntityOwnerPicker`. Instead of relying on the entities stored in `EntityListContext` and on the `kind` filter applied in `EntityListContext`, all the users and groups available in the catalog are now displayed. Users and groups are now filtered server side and loaded in batches using an infinite scrolling approach.

This new approach fixes the issue with large catalog, closes #17499 and makes another step toward #12247.
 
https://user-images.githubusercontent.com/8433119/234408465-b8fe9337-0f6c-4c5e-8fcc-c267de07237c.mov
 
#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)
- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx [hunk 1]
```diff
@@ -170,38 +135,80 @@ export const EntityOwnerPicker = () => {
           multiple
           disableCloseOnSelect
           loading={loading}
-          options={ownerEntities || []}
-          value={
-            ownerEntities?.filter(e =>
```
Comment (sennyeya) [inline plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx:175]: Is it possible to keep the existing code around rendering the selected options (and using humanizeEntity)? Looks like this is just using the entity refs. Would make sense that it's not possible if we don't have the full list of read entities at load time.

**Review by sennyeya — CHANGES_REQUESTED** [review]
Looks good, thanks for the quick work on this! Couple of comments on the updated UI.

Also, this is keeping selected user state when other filters (like Kind) change, which differs from the existing implementation, is that expected?

File: plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx [hunk 2]
```diff
@@ -35,111 +29,79 @@ import { Autocomplete } from '@material-ui/lab';
...
+        };
+      }
+
+      return catalogApi.queryEntities({
+        fullTextFilter: {
+          term: initialRequest.text || '',
+          fields: [
+            'metadata.name',
+            'kind',
+            'spec.profile.displayname',
```
[the remark this answers is not in the document]
Comment (vinzscam) [reply plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx:80]: yeah in the search table the field are converted to lowercase, so `displayName` won't work. Probably the `queryEntities` endpoint should have handled this internally

File: plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx (hunk 1 above)
Comment (vinzscam) [reply plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx:175]: the entities are always humanized as before. The only case where aren't humanized is when they are selected (displayed as chips), to make it more explicit about which entity is selected (in case multiple ones have the same name)

**Comment by vinzscam** [comment]
> Looks good, thanks for the quick work on this! Couple of comments on the updated UI.
> 
> Also, this is keeping selected user state when other filters (like Kind) change, which differs from the existing implementation, is that expected?

yes, I mention this in the description. That's why I marked this as BREAKING (not sure if it should be marked as breaking btw 🤔)

File: plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (sennyeya) [reply plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx:80]: Ah, gotcha, I misread where this was coming from, assumed it was the top level `fields` and not `fullTextFilter.fields`. Ideally, the backend would handle the casing transformation. 

Also, do we want to use a `fields` filter as well? We're returning the full entities here.

File: plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx (hunk 1 above)
Comment (sennyeya) [reply plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx:175]: It might just be that I'm on a small screen but the chips just show the kind and namespace in the default view. The name is cutoff.

Screenshot 2023-04-26 at 9 36 41 AM

Can we add an override of the `renderTags` option as well? Something like
```
renderTags={(tagValue, getTagProps) => {
            return tagValue.map((option, index) => {
              const isGroup =
                (typeof option === 'string'
                  ? parseEntityRef(option).kind
                  : option.kind
                ).toLocaleLowerCase('en-US') === 'group';
              return (
                <Chip
                  {...getTagProps({ index })}
                  icon={
                    isGroup ? (
                      <GroupIcon fontSize="small" />
                    ) : (
                      <PersonIcon fontSize="small" />
                    )
                  }
                  variant="outlined"
                  label={option?.metadata?.name || parseEntityRef(option).name}
                />
              );
            });
          }}
```

**Comment by sennyeya** [comment]
> That's why I marked this as BREAKING (not sure if it should be marked as breaking btw 🤔) I feel like the improvements we get here are way better than what we loose

Definitely agree, the improvements are really nice. I read the notes you added as the list of users/groups won't be adjusted to the context of other filters on the page, it will just show all users and you're expected to find the ones relevant to you. Suggested a small update there. Since the autocomplete has the ability to delete all selected entries with a single click, I don't think it's a big change, but worth noting as BREAKING still.

File: plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (vinzscam) [reply plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx:80]: it should be fine to return the full entity in this case since we are returning a batch of 20 entities per request. I don't think it will improve anything

File: plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx (hunk 1 above)
Comment (vinzscam) [reply plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx:175]: it feels a bit weird to be to display the humanize entity instead of the entityRef here, since the intent is to filter by owner. Same in the dropdown. If it was me I would keep entityRef for everything, otherwise it might be problematic in case multiple entities have the same display name, or for adopters using namespaces

Comment (sennyeya) [reply plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx:175]: It seems odd to me to have a different user experience for both though. 
The primary thing I was trying to solve with the original PR was that my org's team identifiers were all basically GUIDs and you couldn't easily search or filter them without knowing the exact value. Having the chips use the entity refs leaves the problem of how do I remove an item I selected if I know the display name but not the entity name.

File: plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (sennyeya) [reply plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx:80]: Agree it won't be noticeable, but might still be worth restricting as adopters could have larger than expected User/Group entities and we only need a subset of fields.

File: .changeset/little-boats-think.md [hunk 3]
```diff
@@ -0,0 +1,9 @@
+---
+'@backstage/plugin-catalog-react': minor
+---
+
+`EntityOwnerPicker` now loads entities asynchronously
+
+**BREAKING**: In order to improve the performance of the component, the users and groups displayed by `EntityOwnerPicker` aren't inferred
```
Comment (Rugvip) [inline .changeset/little-boats-think.md:7]: Can't really both label this as breaking and also just do a minor bump 😅. Tbh I think it is alright to call this a non-breaking behavior change, since the user experience is similar and there's no API change.

File: plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx [hunk 4]
```diff
@@ -170,38 +135,80 @@ export const EntityOwnerPicker = () => {
...
+                  </Box>
+                }
+              />
+            );
+          }}
           size="small"
           popupIcon={<ExpandMoreIcon data-testid="owner-picker-expand" />}
           renderInput={params => (
             <TextField
               {...params}
```
Comment (Rugvip) [inline plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx:186]: How come you removed the `input` styling here? Could we keep that in place?

File: plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx (hunk 1 above)
Comment (Rugvip) [reply plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx:175]: I'm feeling it would be best if the selected items look the same as the items that you select tbh, essentially keeping it as it is. It would be sweet to add the user/group icon to the chip though I think.

**Review by Rugvip — CHANGES_REQUESTED** [review]
Nice 😁 just some small bits

File: plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx (hunk 1 above)
Comment (sennyeya) [reply plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx:175]: Also, I've opened #17600 if we want to group by namespace in the results as part of this work or an additional PR afterwards.

Comment (vinzscam) [reply plugins/catalog-react/src/components/EntityOwnerPicker/EntityOwnerPicker.tsx:175]: Fixed in https://github.com/backstage/backstage/pull/17514/commits/999fb3543325a0be6dee48c3ebe31b193bea65bb

File: .changeset/little-boats-think.md [hunk 5]
```diff
@@ -0,0 +1,8 @@
+---
+'@backstage/plugin-catalog-react': patch
```
Comment (Rugvip) [inline .changeset/little-boats-think.md:2]:
```suggestion
'@backstage/plugin-catalog-react': minor
```

Bumping up to minor since we're on 1.0 and this adds new capabilities

**Review by Rugvip — APPROVED** [review]
Sweet 😁 Let's :shipit:

**Review by sennyeya — APPROVED** [review]
Whoops, didn't realize I was a blocker here. Let's :shipit:
