### PR TITLE
core-api: add BackstageRoutes

### LINKED ISSUE #3793: Route order in App.tsx may cause catalog-import to fail
In `App.tsx`, if you put the `/catalog/*` route before the `/catalog-import/*` route, attempting to visit `/catalog-import` will yield a blank page.

## Expected Behavior

The page should show the catalog-import page.

## Current Behavior

A blank page is displayed. Seems the `/catalog/*` route is matched, but that component does not show anything since the URL is not as expected.

## Possible Solution

Is this a bug in React Router? Or how backstage uses it? If not easily fixable, maybe a warning somewhere to avoid adopters accidentally arranging Routes in an order that causes this behaviour.

## Steps to Reproduce

1. `git clone git@github.com:backstage/backstage.git`
2. In App.tsx, move the `/catalog-import/*` route below the `/catalog/*` route.
3. `yarn dev`
4. Visit http://localhost:3000/catalog-import

## Context

Stumbled on this while bumping versions to use the new catalog-import. Cost me a few hours of troubleshooting. Might give others the same.

## Your Environment

- NodeJS Version (v12): v12.19.0
- Operating System and Version (e.g. Ubuntu 14.04): OSX 10.15.7 (same issue when running Docker, node:12-buster image)
- Browser Information: Chrome latest

### PR DESCRIPTION
**Pull request by Rugvip**
Co-authored-by: blam <ben@blam.sh>

## Hey, I just made a Pull Request!

Adds a `BackstageRoutes` component that is similar to the `Routes` component from react-router, but tailored for top-level extension routes by only collecting routes from the immediate children. It also adds `/*` at the end of paths as well as sorts them, so that you don't need to do that manually in the app.

The main reason for the introduction of this is to be able to do the following:

```tsx
<Route path="/catalog/:namespace/:kind/:name" element={<CatalogEntityPage />} >
  <EntityLayout>
    ...
  </EntityLayout>
</Route>
```

instead of

```tsx
<Route path="/catalog/:namespace/:kind/:name/*" element={<CatalogEntityPage />} >
  <Route path="/*" element={
    <EntityLayout>
      ...
    </EntityLayout>
  }/>
</Route>
```

Fixes #3793

#### :heavy_check_mark: Checklist

- [x] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)

### CODE REVIEW

File: packages/core-api/src/routing/BackstageRoutes.tsx [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+              path: '/*',
+              element: children,
+            },
+          ],
+        },
+      ];
+    })
+    .sort((a, b) => b.path.localeCompare(a.path))
+    .map(obj => {
+      obj.path = obj.path === '/' ? '/' : `${obj.path}/*`;
```
Comment (freben) [inline packages/core-api/src/routing/BackstageRoutes.tsx:64]: Hm I'm wondering if we need to explicitly delete (or forbid) trailing slashes in path props so we don't get double slashes here?

File: packages/core-api/src/routing/BackstageRoutes.tsx [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+    .flatMap(child => {
+      if (!isValidElement(child)) {
+        return [];
+      }
+
+      if (child.type === Fragment) {
+        return createRoutesFromChildren(child.props.children);
+      }
+
+      const { children } = child.props;
```
Comment (freben) [inline packages/core-api/src/routing/BackstageRoutes.tsx:39]: Could move above previous block and use

**Review by freben — APPROVED** [review]

File: packages/core-api/src/routing/BackstageRoutes.tsx (hunk 1 above)
Comment (Rugvip) [reply packages/core-api/src/routing/BackstageRoutes.tsx:64]: `/*` suffixes are trimmed above, and react-router trims duplicate slashes

**Review by benjdlambert — APPROVED** [review]
