### PR TITLE
Fix for plugin entity validation: using stated location for the value rather then default

### LINKED ISSUE #16406: 🐛 Bug Report: entity-validation: file location is immutable
### 📜 Description

In the [entity-validation plugin](https://github.com/backstage/backstage/tree/master/plugins/entity-validation), the `File Location` input is immutable.

The issue is likely caused by `value={defaultLocation}`. Maybe it should be `value={locationUrl}`.
https://github.com/backstage/backstage/blob/b25b4bda4e8af306732bba92ec22e986b28aad27/plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx#L71-L81

### 👍 Expected behavior

The `File Location` input should be mutable.

### 👎 Actual Behavior with Screenshots

image

### 👟 Reproduction steps

Run the frontend. Navigate to the UI for the plugin. Try to change the `File Location`

### 📃 Provide the context for the Bug.

_No response_

### 🖥️ Your Environment

`@backstage/plugin-entity-validation@0.1.0`

Bug exists on multiple browsers.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by webark**
Fixes #16406

## Hey, I just made a Pull Request!

Using the locationUrl from the set state.

Also added some basic style updates and fixed the button deprecation.

#### :heavy_check_mark: Checklist

- [X] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes
- [ ] Screenshots attached (for UI changes)
- [X] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))

### CODE REVIEW

File: plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx [hunk 1]
```diff
@@ -83,12 +83,7 @@ export const EntityValidationPage = (props: {
           <Grid item md={3} xs={12}>
             <Grid container alignItems="center" style={{ height: '100%' }}>
               <Grid item>
-                <Button
-                  style={{ textDecoration: 'none' }}
-                  variant="outlined"
-                  to="#"
-                  onClick={parseYaml}
-                >
+                <Button size="large" onClick={parseYaml}>
```
Comment (ivangonzalezacuna) [inline plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx:86]: I wouldn't switch to the "material-ui/core" `Button`. The desired is using the internal backstage Buttons and Links, as they can be used for metrics and other stuff. Also, note that now `Button` is deprecated, `LinkButton` should be used instead.

File: plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx [hunk 2]
```diff
@@ -66,15 +66,15 @@ export const EntityValidationPage = (props: {
...
           <Grid item md={9} xs={12}>
             <TextField
-              style={{ width: '100%' }}
+              fullWidth
               label="File Location"
               margin="normal"
               variant="outlined"
               required
-              value={defaultLocation}
+              value={locationUrl}
```
Comment (ivangonzalezacuna) [inline plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx:77]: The idea behind setting the defaultLocation as a value was to have something filled in. However, I made a mistake when changing this.

I would do it this way:

* Set the state of `locationUrl` with the value of `defaultLocation` instead of an empty string
* In the TextField, set `defaultValue={defaultLocation}` and `value={locationUrl}`. This fixes the issue

File: plugins/entity-validation/dev/index.tsx [hunk 3]
```diff
@@ -16,9 +16,18 @@
...
 createDevApp()
   .registerPlugin(entityValidationPlugin)
+  .registerApi({
+    api: catalogApiRef,
+    deps: {},
+    factory: () =>
+      ({
+        getEntities: () => ({}),
+      } as CatalogApi),
+  })
```
Comment (ivangonzalezacuna) [inline plugins/entity-validation/dev/index.tsx:30]: Is there a reason to add this? I haven't tried the dev mode to be honest, do we need to register the api to make it work?

**Review by ivangonzalezacuna — CHANGES_REQUESTED** [review]
Left a couple comments

File: plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx (hunk 1 above)
Comment (webark) [reply plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx:86]: I was going to switch it to a LinkButton, but since it didn't have a "to" and wasn't really a link, thought about going this direction.. but stuff about the metrics and things is a fair statement. I can make that change back.

File: plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx (hunk 2 above)
Comment (webark) [reply plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx:77]: This was what I had originally, but wasn't sure as to the desired functionality. I can make that change.

File: plugins/entity-validation/dev/index.tsx (hunk 3 above)
Comment (webark) [reply plugins/entity-validation/dev/index.tsx:30]: You do. This just made it easier to iterate quickly on loading it up and inspecting some of the functionality. It's kind of handy, and could be extended in the future if desired.

Comment (ivangonzalezacuna) [reply plugins/entity-validation/dev/index.tsx:30]: Good to know! So let's keep it then

File: plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx (hunk 2 above)
Comment (GoFightNguyen) [reply plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx:77]: I agree with @ivangonzalezacuna; this aligns to what I was going to do when I got around to making the PR. Thanks @webark for beating me to it

File: plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx (hunk 1 above)
Comment (webark) [reply plugins/entity-validation/src/components/EntityValidationPage/EntityValidationPage.tsx]: updated to use LinkButton

**Review by ivangonzalezacuna — APPROVED** [review]
LGTM. Let's wait for approval from someone from Backstage

**Review by freben — APPROVED** [review]
Alright!
